/********************************************************************************************************************************************
****   Projeto: Implementação Satélites Corporativos                                                                     				 ****
****   Autor: BS & Neyond                                                                                                                ****
****   Data: 17/06/2025                                                                                                                  ****
****   SQL Script Descrição: Geração do Satélite 93  																					 **93
********************************************************************************************************************************************/

/*=========================================================================================================================================*/
/*  1. Tabela granular: Obtenção do universo a reportar no âmbito do Satélite 93 + Marcação de metricas relevantes         			       */
/*=========================================================================================================================================*/


-- INSERT OVERWRITE TABLE BU_ESG_WORK.AG093_GHGE_CTO_GRA PARTITION (ID_CORRIDA,REF_DATE)


SELECT
	IDCOMB_SATELITE,
	SOCIEDADE_CONTRAPARTE,
	UNI.CEMPRESA_CT,
	UNI.CBALCAO_CT,
	UNI.CNUMECTA_CT,
	UNI.ZDEPOSIT_CT,
	EMISS.CHAVE_BEM,
	CASE
	    WHEN IDCOMB_SATELITE LIKE '%MC08%' THEN 'INVS5'
	ELSE ''
	END INVESTMENT_SECTOR,
	
	CASE WHEN 
	    UNI.cbalcao_ct = 'CMAH' THEN -SUM(SALDO_CT)
	ELSE -SUM(EMISS.amount)
	END AS ASCI,

	SUM(CAST(EMISS.SCP1_EMSS_FNCD AS DECIMAL (38,16))) AS GESI,
	
	CASE WHEN 
	   UNI.cbalcao_ct = 'CMAH' THEN -SUM(SALDO_CT) 
	ELSE -SUM(EMISS.amount) 
	END AS ASC2,
	
	SUM(CAST(EMISS.SCP2_EMSS_FNCD AS DECIMAL (38,16))) AS GESII,
	
	CASE WHEN 
	    UNI.cbalcao_ct = 'CMAH' THEN -SUM(SALDO_CT) 
	ELSE -SUM(EMISS.amount) 
	END AS ASCIII,
	
	SUM(CAST(EMISS.SCP3_EMSS_FNCD AS DECIMAL (38,16))) AS GESIII,
    
	CASE
        WHEN TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' AND NACE_LEVEL4 IS NOT NULL THEN ID
        WHEN TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' THEN 'NACE19010303' --NACE DEFAULT DISPONIBILIZADO PELA CORPORAÇÃO            
        WHEN TRIM(CT003.CONTRAPARTE) IN ('', 'resto setores / clientes') AND IDCOMB_SATELITE LIKE '%SC0303%' AND NACE_LEVEL4 IS NOT NULL THEN ID	
        WHEN TRIM(CT003.CONTRAPARTE) IN ('', 'resto setores / clientes') AND IDCOMB_SATELITE LIKE '%SC0303%' THEN 'NACE19010303' --NACE DEFAULT DISPONIBILIZADO PELA CORPORAÇÃO
        
        WHEN IDCOMB_SATELITE LIKE '%MC08%' AND NACE_LEVEL4 IS NOT NULL THEN ID           
        WHEN IDCOMB_SATELITE LIKE '%MC08%' THEN 'NACE19010303' -- NACE DEFAULT DISPONIBILIZADO PELA CORPORAÇÃO
        
        WHEN IDCOMB_SATELITE LIKE '%SC0303%' AND EMISS.ZCLIENTE = '0000000000' THEN 'NACE19010303' --INDICAÇÃO DA CONTABILIDADE DEVIDO A ASSIGNAÇÃO ERRADA DE CONTRATO SEM CONTA PCSB
        ELSE ''									
    END AS NACE_ESG,	
	CASE 
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'A' AND TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' THEN 'CNAEL1'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'B' AND TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' THEN 'CNAEL2'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'D' AND TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' THEN 'CNAEL4'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'C' AND TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' THEN 'CNAEL3'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'E' AND TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' THEN 'CNAEL5'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'F' AND TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' THEN 'CNAEL6'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'G' AND TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' THEN 'CNAEL7'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'H' AND TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' THEN 'CNAEL8'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'I' AND TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' THEN 'CNAEL9'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'J' AND TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' THEN 'CNAEL10'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'L' AND TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' THEN 'CNAEL11'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'M' AND TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' THEN 'CNAEL12'  
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'N' AND TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' THEN 'CNAEL13'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'O' AND TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' THEN 'CNAEL14'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'P' AND TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' THEN 'CNAEL15'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'Q' AND TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' THEN 'CNAEL16'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'R' AND TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' THEN 'CNAEL17'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'S' AND TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' THEN 'CNAEL18'
		WHEN TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' THEN 'CNAEL18'
		WHEN IDCOMB_SATELITE LIKE '%SC0303%' AND EMISS.ZCLIENTE = '0000000000' THEN 'CNAEL18' --INDICAÇÃO DA CONTABILIDADE DEVIDO A ASSIGNAÇÃO ERRADA DE CONTRATO SEM CONTA PCSB

		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'A' AND IDCOMB_SATELITE LIKE '%MC08%' THEN 'CNAEL1'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'B' AND IDCOMB_SATELITE LIKE '%MC08%' THEN 'CNAEL2'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'D' AND IDCOMB_SATELITE LIKE '%MC08%' THEN 'CNAEL4'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'C' AND IDCOMB_SATELITE LIKE '%MC08%' THEN 'CNAEL3'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'E' AND IDCOMB_SATELITE LIKE '%MC08%' THEN 'CNAEL5'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'F' AND IDCOMB_SATELITE LIKE '%MC08%' THEN 'CNAEL6'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'G' AND IDCOMB_SATELITE LIKE '%MC08%' THEN 'CNAEL7'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'H' AND IDCOMB_SATELITE LIKE '%MC08%' THEN 'CNAEL8'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'I' AND IDCOMB_SATELITE LIKE '%MC08%' THEN 'CNAEL9'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'J' AND IDCOMB_SATELITE LIKE '%MC08%' THEN 'CNAEL10'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'L' AND IDCOMB_SATELITE LIKE '%MC08%' THEN 'CNAEL11'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'M' AND IDCOMB_SATELITE LIKE '%MC08%' THEN 'CNAEL12'  
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'N' AND IDCOMB_SATELITE LIKE '%MC08%' THEN 'CNAEL13'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'O' AND IDCOMB_SATELITE LIKE '%MC08%' THEN 'CNAEL14'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'P' AND IDCOMB_SATELITE LIKE '%MC08%' THEN 'CNAEL15'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'Q' AND IDCOMB_SATELITE LIKE '%MC08%' THEN 'CNAEL16'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'R' AND IDCOMB_SATELITE LIKE '%MC08%' THEN 'CNAEL17'
		WHEN SUBSTR(NFIN.COD_NACE_ESG,1,1) = 'S' AND IDCOMB_SATELITE LIKE '%MC08%' THEN 'CNAEL18'
		WHEN TRIM(CT003.CONTRAPARTE) = 'outras empresas nao financeiras' THEN 'CNAEL18'
		WHEN TRIM(CT003.CONTRAPARTE) = '' AND IDCOMB_SATELITE LIKE '%SC0303%' THEN 'CNAEL18'		--ADICIONADA NOVA LINHA DE CÓDIGO. VALIDADO COM CONTABILIDADE

		ELSE ''
	END AS CNAEL,

	CASE													
		WHEN COUNTRY_CODE IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428') 
			THEN 'EU1'--- alterar
		WHEN COUNTRY_CODE NOT IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428', '')
			THEN 'EU2'
		WHEN CT003.CPAIS_RESIDENCIA IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428')
			THEN 'EU1'
		WHEN CT003.CPAIS_RESIDENCIA	NOT IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428','')
				THEN 'EU2'
		WHEN EMISS.ZCLIENTE='0000000000' THEN 'EU1' -- ZCLIENTE '0000000000' É PROVENIENTE DE AJUSTE LANÇADO PELA CONTABILIDADE E, COMO TAL, DVEERÁ SER CONSIDERADO EU1
	ELSE '' END AS EUROPEAN_UNION,

	CASE 
	    WHEN EMISS.ORIGEM_SCP1_EMSS LIKE '%SCIB%' THEN 'CLIEA1'
	ELSE 'CLIEA2'
	END AS CLIENT_EMISSION_AREA,

	CASE 
        WHEN EMISS.ORIGEM_SCP1_EMSS LIKE '%BCL%' THEN 'CAAP1'
        WHEN EMISS.ORIGEM_SCP1_EMSS LIKE '%PF%' THEN 'CAAP2'
        WHEN EMISS.ORIGEM_SCP1_EMSS LIKE '%RE%' THEN 'CAAP3'
        WHEN EMISS.ORIGEM_SCP1_EMSS LIKE '%MVL%' THEN 'CAAP4'
    END AS CALCULATION_APPROACH,
    CASE 
        WHEN EMISS.ORIGEM_SCP1_EMSS IN ('MISS','Nao Aplicavel') THEN 'SOUR3'
        WHEN EMISS.ORIGEM_SCP1_EMSS LIKE '%DQS1%' OR EMISS.ORIGEM_SCP1_EMSS LIKE '%DQS2%' THEN 'SOUR1'
    ELSE 'SOUR2'
    END AS SOURCE_EMISSION,
    CASE 
        WHEN EMISS.ORIGEM_SCP1_EMSS LIKE '%DQS1%' THEN 'DQS1'
        WHEN EMISS.ORIGEM_SCP1_EMSS LIKE '%DQS2%' THEN 'DQS2'
        WHEN EMISS.ORIGEM_SCP1_EMSS LIKE '%DQS3%' THEN 'DQS3'
        WHEN EMISS.ORIGEM_SCP1_EMSS LIKE '%DQS4%' THEN 'DQS4'
        WHEN EMISS.ORIGEM_SCP1_EMSS LIKE '%DQS5%' THEN 'DQS5'
    END AS DATA_QUALITY_SCORE,
    CASE WHEN  
        IDCOMB_SATELITE LIKE '%MC08%' AND COALESCE(TRIM(CT003.CONTRAPARTE),'') <> 'outras empresas nao financeiras' THEN 1
    ELSE 0
    END AS FG_EXCL,

	RT.NEW_ID_CORRIDA AS ID_CORRIDA, 
	'${REF_DATE}' AS REF_DATE

FROM
-- TABELA DE UNIVERSO
(
	SELECT
		IDCOMB_SATELITE,
		CEMPRESA_CT,
		CBALCAO_CT,
		CNUMECTA_CT,
		ZDEPOSIT_CT,
		SUM(SALDO_CT) AS SALDO_CT,
		SOCIEDADE_CONTRAPARTE
	FROM bu_esg_work.RF_PILAR3_UNIVERSO_FULL
    WHERE DT_RFRNC = '${REF_DATE}' 
    AND ID_CORRIDA IN ( SELECT 
    					MAX(ID_CORRIDA) 
    					FROM BU_ESG_WORK.RF_PILAR3_UNIVERSO_FULL 
    					WHERE DT_RFRNC = '${REF_DATE}'
    				) 
	AND CSATELITE IN (93) 
    GROUP BY 1,2,3,4,5,7
) UNI

LEFT JOIN

(
SELECT
	CEMPRESA, 
	CBALCAO, 
	CNUMECTA, 
	ZDEPOSIT, 
	concat(CEMPBEM, CKBALBEM, CKCTABEM, CKREFBEM) AS CHAVE_BEM,    
    -- CHAVE_BEM, 
	ZCLIENTE,
	ORIGEM_SCP1_EMSS,
	SUM(SCP1_EMSS_FNCD) AS SCP1_EMSS_FNCD, 
	SUM(SCP2_EMSS_FNCD) AS SCP2_EMSS_FNCD, 
	SUM(SCP3_EMSS_FNCD) AS SCP3_EMSS_FNCD, 
	SUM(AMOUNT) AS AMOUNT
FROM BU_ESG_WORK.MODESG_OUT_EMSS_FNCD 
                WHERE REF_DATE='${REF_DATE}'
                AND NOME_PERIMETRO LIKE '%Individual Idcomb%'
GROUP BY 1,2,3,4,5,6,7
) EMISS

ON  UNI.CEMPRESA_CT = EMISS.CEMPRESA
AND UNI.CBALCAO_CT  = EMISS.CBALCAO
AND UNI.CNUMECTA_CT = EMISS.CNUMECTA
AND UNI.ZDEPOSIT_CT = EMISS.ZDEPOSIT

LEFT JOIN

(
SELECT
	ZCLIENTE, 
	CPAIS_RESIDENCIA, 
	CONTRAPARTE
FROM CD_CAPTOOLS.CT003_UNIV_CLI
WHERE REF_DATE='${REF_DATE}'
) CT003

ON EMISS.ZCLIENTE=CT003.ZCLIENTE

LEFT JOIN

(
SELECT * 
FROM BU_ESG_WORK.MODESG_OUT_EMPR_INFO_NFIN 
WHERE REF_DATE='${REF_DATE}'
) NFIN

ON EMISS.ZCLIENTE = NFIN.ZCLIENTE 

LEFT JOIN BU_ESG_WORK.NACE_ESG_PILLAR3 AS NACE_ESG		--CRIAR TABELA DE EXCEL A IMPORTAR COM BASE NA NOVA MARCAÇÃO DO EXCEL SAT 79 CASO MUDEM OS NACE QUE A CORPORAÇÃO ENVIA
ON CONCAT(SPLIT_PART(NFIN.COD_NACE_ESG,".",1),SPLIT_PART(NFIN.COD_NACE_ESG,".",2),SPLIT_PART(NFIN.COD_NACE_ESG,".",3)) = TRIM(SPLIT_PART(NACE_ESG.NACE_LEVEL4, "-",1))

-- LIGAÇÃO COM A TABELA PROPERTY PARA OBTENÇÃO DE CAMPOS CARACTERIZADORES DO BEM
LEFT JOIN
(
SELECT DISTINCT
    property_bank_id,
	PROPERTY_BRANCH_CODE, 
	PROPERTY_CONTRACT_ID, 
	PROPERTY_REFERENCE_CODE,
	COUNTRY_CODE
FROM BU_ESG_WORK.PROPERTY
WHERE DATA_DATE_PART = '${REF_DATE}'
) PROPERTY


ON EMISS.CHAVE_BEM=concat(property_bank_id, PROPERTY_BRANCH_CODE, PROPERTY_CONTRACT_ID, PROPERTY_REFERENCE_CODE)

LEFT JOIN

(
SELECT
	NVL(MAX(ID_CORRIDA),0)+1 AS NEW_ID_CORRIDA
FROM BU_ESG_WORK.AG093_GHGE_CTO_GRA
WHERE REF_DATE = '${REF_DATE}'
) RT

ON 1=1


GROUP BY 1,2,3,4,5,6,7,8,15,16,17,18,19,20,21,22,23

HAVING FG_EXCL=0
;