
/*===================================================================================================================================================
                                                      
												  SIMULAÇÃO LT004 PROTECTION PILAR 3 & ESG
										                    NEYOND 2024 - V0.03 
															    
 ===================================================================================================================================================*/
 
--------------------------------------------------------------------------------------------------------------------------------------------------
-- 1. Criação da tabela com a simulação da LT004 Pilar 3 para testes 
--------------------------------------------------------------------------------------------------------------------------------------------------

	-- DEZ24: Inserted 446539 row(s) 

DROP TABLE IF EXISTS bu_loantape_work.LT004_PROTECTION_DEZ24;
CREATE TABLE bu_loantape_work.LT004_PROTECTION_DEZ24 AS

SELECT 
	BASE.CHAVE_BEM_PRE AS PRTCTN_ID
	,BASE.ORIGEM
	,CASE
		WHEN BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-P' OR BASE.ORIGEM = 'PM-F' OR BASE.ORIGEM = 'PM-M' THEN 'N/A'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND MBI.EP_SCORE IS NOT NULL AND MBI.EP_SCORE > 0.00 AND MBI.EP_SCORE <= 100 THEN 'EPSC1'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND MBI.EP_SCORE IS NOT NULL AND MBI.EP_SCORE > 100 AND MBI.EP_SCORE <= 200  THEN 'EPSC2'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND MBI.EP_SCORE IS NOT NULL AND MBI.EP_SCORE > 200 AND MBI.EP_SCORE <= 300 THEN 'EPSC3'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND MBI.EP_SCORE IS NOT NULL AND MBI.EP_SCORE > 300 AND MBI.EP_SCORE <= 400 THEN 'EPSC4'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND MBI.EP_SCORE IS NOT NULL AND MBI.EP_SCORE > 400 AND MBI.EP_SCORE <= 500 THEN 'EPSC5'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND MBI.EP_SCORE IS NOT NULL AND MBI.EP_SCORE > 500 THEN 'EPSC6'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND TRIM(PROPERTY.PROPERTY_CODE) IN ('5000','5213','5201','5101','5211','5215','5301','5302','5303','5203','5205','5207','5217') THEN 'MISS'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND PROPERTY.PROPERTY_CODE IS NULL THEN 'MISS'
		ELSE 'EPSC7'
    END AS EP_SCR
	,CASE
		WHEN BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-P' OR BASE.ORIGEM = 'PM-F' OR BASE.ORIGEM = 'PM-M' THEN 'N/A'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND MBI.EP_SCORE IS NOT NULL AND TRIM(UPPER(MBI.SOURCE_CODE)) IN ('OCR','ADENE') THEN 'EPSD1'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND MBI.EP_SCORE IS NOT NULL AND TRIM(UPPER(MBI.SOURCE_CODE)) IN ('GLOVAL') THEN 'EPSD2'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND TRIM(PROPERTY.PROPERTY_CODE) IN ('5000','5213','5201','5101','5211','5215','5301','5302','5303','5203','5205','5207','5217') THEN 'MISS'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND PROPERTY.PROPERTY_CODE IS NULL THEN 'MISS'
		ELSE 'N/A'
    END AS TYP_EP_SCR
	,CASE 
		WHEN BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-P' OR BASE.ORIGEM = 'PM-F' OR BASE.ORIGEM = 'PM-M' THEN 'N/A'
	 	WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND substr(BASE.CHAVE_BEM_PRE,1,1) <> 'I' THEN 'N/A'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND TRIM(MBI.QUALITY_SCORE) = '1-REAL' THEN 'EPCD1'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND TRIM(MBI.QUALITY_SCORE)= 'SANTANDER' THEN 'EPCD1'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND TRIM(MBI.QUALITY_SCORE) = '' THEN 'MISS'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND TRIM(MBI.QUALITY_SCORE) IS NULL THEN 'MISS'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND TRIM(MBI.QUALITY_SCORE) = '2-MUY ALTA' THEN 'EPCD2'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND TRIM(MBI.QUALITY_SCORE) = '3-ALTA' THEN 'EPCD2'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND TRIM(MBI.QUALITY_SCORE) = '4-MEDIA' THEN 'EPCD2'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND TRIM(MBI.QUALITY_SCORE) = '5-MEDIA BAJA' THEN 'EPCD2'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND TRIM(MBI.QUALITY_SCORE) = '6-BAJA' THEN 'EPCD2'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND TRIM(MBI.QUALITY_SCORE) = '7-SIN DATO' THEN 'MISS'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NULL THEN 'MISS'
		ELSE 'NOK'
	END AS TYP_EPC_LBL
	,CASE
		WHEN BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-P' OR BASE.ORIGEM = 'PM-F' OR BASE.ORIGEM = 'PM-M' THEN 'N/A'
	    WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND substr(BASE.CHAVE_BEM_PRE,1,1) <> 'I' THEN 'N/A'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND MBI.EPC = 'A+' THEN 'EPCL1'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND MBI.EPC = 'A' THEN 'EPCL1'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND MBI.EPC = 'B' THEN 'EPCL2' 
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND MBI.EPC = 'B-' THEN 'EPCL2'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND MBI.EPC = 'C' THEN 'EPCL3'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND MBI.EPC = 'D' THEN 'EPCL4'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND MBI.EPC = 'E' THEN 'EPCL5'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND MBI.EPC = 'F' THEN 'EPCL6'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND MBI.EPC = 'G' THEN 'EPCL7'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND (MBI.EPC = '' or MBI.EPC IS NULL) and TRIM(PROPERTY.property_code) IN ('5000','5213','5201','5101','5211','5215','5301','5302','5303','5203','5205','5207','5217') THEN 'MISS'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND (MBI.EPC = '' or MBI.EPC IS NULL) and TRIM(PROPERTY.property_code) IS NULL THEN 'MISS'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MBI.CHAVE_BEM IS NOT NULL AND (MBI.EPC = '' or MBI.EPC IS NULL) and TRIM(PROPERTY.property_code) NOT IN ('5000','5213','5201','5101','5211','5215','5301','5302','5303','5203','5205','5207','5217') THEN 'EPCL8'
		ELSE 'NOK'
	END AS EPC_LBL
	,CASE
        WHEN BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-P' OR BASE.ORIGEM = 'PM-F' OR BASE.ORIGEM = 'PM-M' THEN 'N/A'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND SUBSTR(prtctn_id,1,1) <> 'I' THEN 'N/A'
		WHEN BASE.ORIGEM = 'PM-I' AND LT_ESTRUT.PRTCTN_ID IS NOT NULL THEN LT_ESTRUT.RL_ESTT_CLLTRL_LCTN
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.DISTRICT_MUNICIP_PARISH_CODE IS NOT NULL THEN 'PT'
-- 		WHEN BASE.ORIGEM = 'MBI' AND GT009.CHAVE_BEM IS NOT NULL THEN 'MISS' Comentário: Porquê a gto09?
	  ELSE 'NOK'
	END AS RL_ESTT_CLLTRL_LCTN 
	,CASE
    	WHEN BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-P' OR BASE.ORIGEM = 'PM-F' THEN 'N/A'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND SUBSTR(BASE.CHAVE_BEM_PRE,1,1) <> 'I' THEN 'N/A' 
		WHEN BASE.ORIGEM = 'PM-I' AND LT_ESTRUT.PRTCTN_ID IS NOT NULL THEN RL_ESTT_PST_CD
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND PROPERTY.POSTAL_CODE IS NULL THEN 'MISS'
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND TRIM(PROPERTY.POSTAL_CODE) = '' THEN 'MISS'
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL THEN PROPERTY.POSTAL_CODE --CPOST
--		WHEN BASE.ORIGEM = 'MBI' AND GT009.CHAVE_BEM IS NOT NULL AND LENGTH(GT009.CPOST)=4 THEN CONCAT(GT009.CPOST,'-000')
--		WHEN BASE.ORIGEM = 'MBI' AND GT009.CHAVE_BEM IS NOT NULL THEN GT009.CPOST 
		ELSE 'NOK'
	END AS RL_ESTT_PST_CD 
	,CASE
	    WHEN BASE.ORIGEM = 'PM-P' OR BASE.ORIGEM = 'PM-F' THEN 11111111111
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.SCP1_EMSS IS NOT NULL THEN MV_OUT_VCLS.SCP1_EMSS
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND  MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.SCP1_EMSS IS NULL THEN 99999999999
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND  MV_OUT_VCLS.CHAVE_BEM IS NULL THEN 99999999999
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM_2 IS NOT NULL AND MV_OUT_BI.SCP1_EMSS IS NOT NULL THEN MV_OUT_BI.SCP1_EMSS
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM_2 IS NOT NULL AND MV_OUT_BI.SCP1_EMSS IS NULL AND MV_OUT_BI.SCP2_EMSS IS NULL AND MV_OUT_BI.SCP3_EMSS IS NULL THEN 11111111111
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND  MV_OUT_BI.CHAVE_BEM_2 IS NOT NULL AND MV_OUT_BI.SCP1_EMSS IS NULL THEN 11111111111
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND  MV_OUT_BI.CHAVE_BEM_2 IS NULL THEN 99999999999
    END AS EMSSNS_SCP1_PRTCTN
	,CASE
	    WHEN BASE.ORIGEM = 'PM-P' OR BASE.ORIGEM = 'PM-F' THEN 11111111111
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.SCP2_EMSS IS NOT NULL THEN MV_OUT_VCLS.SCP2_EMSS
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND  MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.SCP2_EMSS IS NULL THEN 99999999999
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND  MV_OUT_VCLS.CHAVE_BEM IS NULL THEN 99999999999
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM_2 IS NOT NULL AND MV_OUT_BI.SCP2_EMSS IS NOT NULL THEN MV_OUT_BI.SCP2_EMSS
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM_2 IS NOT NULL AND MV_OUT_BI.SCP1_EMSS IS NULL AND MV_OUT_BI.SCP2_EMSS IS NULL AND MV_OUT_BI.SCP3_EMSS IS NULL THEN 11111111111
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND  MV_OUT_BI.CHAVE_BEM_2 IS NOT NULL AND MV_OUT_BI.SCP2_EMSS IS NULL THEN 11111111111
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND  MV_OUT_BI.CHAVE_BEM_2 IS NULL THEN 99999999999
    END AS EMSSNS_SCP2_PRTCTN
	,CASE
		WHEN BASE.ORIGEM = 'PM-P' OR BASE.ORIGEM = 'PM-F' THEN 11111111111
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.SCP3_EMSS IS NOT NULL THEN MV_OUT_VCLS.SCP3_EMSS
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.SCP3_EMSS IS NULL THEN 99999999999
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NULL THEN 99999999999
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM_2 IS NOT NULL AND MV_OUT_BI.SCP3_EMSS IS NOT NULL THEN MV_OUT_BI.SCP3_EMSS
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM_2 IS NOT NULL AND MV_OUT_BI.SCP1_EMSS IS NULL AND MV_OUT_BI.SCP2_EMSS IS NULL AND MV_OUT_BI.SCP3_EMSS IS NULL THEN 11111111111
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM_2 IS NOT NULL AND MV_OUT_BI.SCP1_EMSS IS NOT NULL AND MV_OUT_BI.SCP2_EMSS IS NOT NULL AND MV_OUT_BI.SCP3_EMSS IS NULL THEN 99999999999
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM_2 IS NULL THEN 99999999999
	END AS EMSSNS_SCP3_PRTCTN 
 	,CASE
		WHEN BASE.ORIGEM = 'PM-P' OR BASE.ORIGEM = 'PM-F' THEN 'N/A'
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND SUBSTR(BASE.CHAVE_BEM_PRE,1,1) <> 'M' THEN 'N/A' --é para colocar?
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND SUBSTR(BASE.CHAVE_BEM_PRE,1,1) <> 'I' THEN 'N/A' --é para colocar?
 	    WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP1_EMSS = 'MVL_DQS1_1A' THEN 'PM01'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP1_EMSS = 'MVL_DQS1_1A' THEN 'PM01'
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP1_EMSS = 'MVL_DQS1_1B' THEN 'PM02'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP1_EMSS = 'MVL_DQS1_1B' THEN 'PM02'
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP1_EMSS = 'MVL_DQS2_2A' THEN 'PM03'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP1_EMSS = 'MVL_DQS2_2A' THEN 'PM03'
 		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP1_EMSS = 'MVL_DQS3_2B' THEN 'PM04'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP1_EMSS = 'MVL_DQS3_2B' THEN 'PM04'
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP1_EMSS = 'MVL_DQS4_3A' THEN 'PM05'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP1_EMSS = 'MVL_DQS4_3A' THEN 'PM05'
 		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP1_EMSS = 'MVL_DQS5_3B' THEN 'PM06'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP1_EMSS = 'MVL_DQS5_3B' THEN 'PM06'
 		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP1_EMSS = 'RE_DQS1_1A' THEN 'PM07'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP1_EMSS = 'RE_DQS1_1A' THEN 'PM07'
 		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP1_EMSS = 'RE_DQS2_1B' THEN 'PM08'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP1_EMSS = 'RE_DQS2_1B' THEN 'PM08'
 		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP1_EMSS = 'RE_DQS3_2A' THEN 'PM09'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP1_EMSS = 'RE_DQS3_2A' THEN 'PM09'		
 		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP1_EMSS = 'RE_DQS4_2B' THEN 'PM10'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP1_EMSS = 'RE_DQS4_2B' THEN 'PM10' 
 		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP1_EMSS = 'RE_DQS5_3' THEN 'PM11'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP1_EMSS = 'RE_DQS5_3' THEN 'PM11'
		--WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP1_EMSS IS NULL AND MV_OUT_VCLS.ORIGEM_SCP2_EMSS IS NULL AND MV_OUT_VCLS.ORIGEM_SCP3_EMSS IS NULL THEN 'N/A'  THEN 'MISS' 
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP1_EMSS IS NULL THEN 'MISS'
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NULL THEN 'MISS'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP1_EMSS IS NULL THEN 'N/A'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NULL THEN 'MISS'
	END AS MTHD_USD_PRTCTN_SCP_1
	,CASE
		WHEN BASE.ORIGEM = 'PM-P' OR BASE.ORIGEM = 'PM-F' THEN 'N/A'
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND SUBSTR(BASE.CHAVE_BEM_PRE,1,1) <> 'M' THEN 'N/A'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND SUBSTR(BASE.CHAVE_BEM_PRE,1,1) <> 'I' THEN 'N/A' 
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP2_EMSS = 'MVL_DQS1_1A' THEN 'PM01'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP2_EMSS = 'MVL_DQS1_1A' THEN 'PM01'
 		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP2_EMSS = 'MVL_DQS1_1B' THEN 'PM02'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP2_EMSS = 'MVL_DQS1_1B' THEN 'PM02'
 		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP2_EMSS = 'MVL_DQS2_2A' THEN 'PM03'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP2_EMSS = 'MVL_DQS2_2A' THEN 'PM03'
 		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP2_EMSS = 'MVL_DQS3_2B' THEN 'PM04'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP2_EMSS = 'MVL_DQS3_2B' THEN 'PM04'
 		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP2_EMSS = 'MVL_DQS4_3A' THEN 'PM05'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP2_EMSS = 'MVL_DQS4_3A' THEN 'PM05'
 		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP2_EMSS = 'MVL_DQS5_3B' THEN 'PM06'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP2_EMSS = 'MVL_DQS5_3B' THEN 'PM06'
 		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP2_EMSS = 'RE_DQS1_1A' THEN 'PM07'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP2_EMSS = 'RE_DQS1_1A' THEN 'PM07'
 		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP2_EMSS = 'RE_DQS2_1B' THEN 'PM08'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP2_EMSS = 'RE_DQS2_1B' THEN 'PM08'
 		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP2_EMSS = 'RE_DQS3_2A' THEN 'PM09'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP2_EMSS = 'RE_DQS3_2A' THEN 'PM09'		
 		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP2_EMSS = 'RE_DQS4_2B' THEN 'PM10'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP2_EMSS = 'RE_DQS4_2B' THEN 'PM10' 
 		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP2_EMSS = 'RE_DQS5_3' THEN 'PM11'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP2_EMSS = 'RE_DQS5_3' THEN 'PM11'
 		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP2_EMSS IS NULL THEN 'MISS'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP2_EMSS IS NULL THEN 'N/A'
 		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NULL THEN 'MISS'
 		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NULL THEN 'MISS'
	END AS MTHD_USD_PRTCTN_SCP_2
	,CASE
		WHEN BASE.ORIGEM = 'PM-P' OR BASE.ORIGEM = 'PM-F' THEN 'N/A'
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND SUBSTR(BASE.CHAVE_BEM_PRE,1,1) <> 'M' THEN 'N/A'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND SUBSTR(BASE.CHAVE_BEM_PRE,1,1) <> 'I' THEN 'N/A' 
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP3_EMSS = 'MVL_DQS3_2B' THEN 'PM04'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP3_EMSS = 'MVL_DQS3_2B' THEN 'PM04' 
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP3_EMSS = 'MVL_DQS4_3A' THEN 'PM05'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP3_EMSS = 'MVL_DQS4_3A' THEN 'PM05'
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP3_EMSS = 'MVL_DQS5_3B' THEN 'PM06'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP3_EMSS = 'MVL_DQS5_3B' THEN 'PM06'
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP3_EMSS = 'RE_DQS1_1A' THEN 'PM07'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP3_EMSS = 'RE_DQS1_1A' THEN 'PM07'
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP3_EMSS = 'RE_DQS2_1B' THEN 'PM08'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP3_EMSS = 'RE_DQS2_1B' THEN 'PM08'
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP3_EMSS = 'RE_DQS3_2A' THEN 'PM09'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP3_EMSS = 'RE_DQS3_2A' THEN 'PM09'		
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP3_EMSS = 'RE_DQS4_2B' THEN 'PM10'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP3_EMSS = 'RE_DQS4_2B' THEN 'PM10' 
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_VCLS.ORIGEM_SCP3_EMSS = 'RE_DQS5_3' THEN 'PM11'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP3_EMSS = 'RE_DQS5_3' THEN 'PM11'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP1_EMSS IS NULL AND MV_OUT_BI.ORIGEM_SCP2_EMSS IS NULL AND MV_OUT_BI.ORIGEM_SCP3_EMSS IS NULL THEN 'N/A'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP1_EMSS IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP2_EMSS IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP3_EMSS IS NULL THEN 'MISS'
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.ORIGEM_SCP3_EMSS IS NULL THEN 'MISS'	
		WHEN (BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-M') AND MV_OUT_VCLS.CHAVE_BEM IS NULL THEN 'MISS'
		WHEN (BASE.ORIGEM = 'MBI' OR BASE.ORIGEM = 'PM-I') AND MV_OUT_BI.CHAVE_BEM IS NULL THEN 'MISS'	
	END AS MTHD_USD_PRTCTN_SCP_3
	,CASE
		WHEN substr(BASE.CHAVE_BEM_PRE,1,1) <> 'I' THEN 'N'
		WHEN MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.FLG_RSC_FSC_AGD = 1 THEN 'Y'
		WHEN MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.FLG_RSC_FSC_AGD = 0 THEN 'N'
		WHEN MV_OUT_BI.CHAVE_BEM IS NULL THEN 'N' 
		ELSE 'NOK'
	END AS FLG_ACT_PHYSCL_RSK 
 	,CASE
 		WHEN substr(BASE.CHAVE_BEM_PRE,1,1) <> 'I' THEN 'N'
 		WHEN MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.FLG_RSC_FSC_CRNC = 1 THEN 'Y'
 		WHEN MV_OUT_BI.CHAVE_BEM IS NOT NULL AND MV_OUT_BI.FLG_RSC_FSC_CRNC = 0 THEN 'N'
 		WHEN MV_OUT_BI.CHAVE_BEM IS NULL THEN 'N' 
		ELSE 'NOK'
	END AS FLG_CHRNC_PHYSCL_RSK
	,CASE
		WHEN BASE.ORIGEM = 'MUG' AND GT018_MOB.CHAVE_BEM_PRE IS NOT NULL AND TRIM(GT018_MOB.CGARANT_BEM) IN ('7500','7501','7502','7503','7504','7505','7506','7507','7508','7509','7510','7511','7512','7513','7514','7515') THEN '3'
		WHEN BASE.ORIGEM = 'MUG' AND GT018_MOB.CHAVE_BEM_PRE IS NOT NULL AND TRIM(GT018_MOB.CGARANT_BEM) IN ('6101','6102') THEN '5'
		WHEN BASE.ORIGEM = 'MUG' AND GT018_MOB.CHAVE_BEM_PRE IS NOT NULL AND TRIM(GT018_MOB.CGARANT_BEM) IN ('158','182','108','107','159','197','198','106','1B5','164','169','183','1SS','160','309','321','298','105','126','125','199','104','157','1EE','181','120','186','999','101','LSA','190','501','1','111','103','1CC','196','1SW','102','133','345') THEN '7'
		WHEN BASE.ORIGEM = 'MUG' AND GT018_MOB.CHAVE_BEM_PRE IS NOT NULL AND TRIM(GT018_MOB.CGARANT_BEM) IN ('5101','5102','5103','5104') THEN '8'
		WHEN BASE.ORIGEM = 'MUG' AND GT018_MOB.CHAVE_BEM_PRE IS NOT NULL AND TRIM(GT018_MOB.CGARANT_BEM) IN ('5203','5204') THEN '9'
		WHEN BASE.ORIGEM = 'MUG' AND GT018_MOB.CHAVE_BEM_PRE IS NOT NULL AND TRIM(GT018_MOB.CGARANT_BEM) IN ('5000','5201','5202','5302','5205','5206','5207','5207','5209','5210','5211','5300','5212','5213','5214','5303','5301','5215','5216','5217','5218') THEN '10'
		WHEN BASE.ORIGEM = 'MUG' AND GT018_MOB.CHAVE_BEM_PRE IS NOT NULL AND TRIM(GT018_MOB.CGARANT_BEM) IN ('6401','6402','6403','6404','6405','6406','6407','6408') THEN '12'
		WHEN BASE.ORIGEM = 'MUG' AND GT018_MOB.CHAVE_BEM_PRE IS NOT NULL AND TRIM(GT018_MOB.CGARANT_BEM) IN ('6201','6202') THEN '15'
		WHEN BASE.ORIGEM = 'MUG' AND GT018_MOB.CHAVE_BEM_PRE IS NOT NULL AND TRIM(GT018_MOB.CGARANT_BEM) IN ('6300','6501','6502','6503','6504') THEN '18'
		WHEN BASE.ORIGEM = 'MUG' AND GT018_MOB.CHAVE_BEM_PRE IS NOT NULL AND TRIM(GT018_MOB.CGARANT_BEM) IN ('7100','7101','7102','7103','7104','7105','7106','7107','7110','7111') THEN '51'
		WHEN BASE.ORIGEM = 'MUG' AND GT018_MOB.CHAVE_BEM_PRE IS NOT NULL AND TRIM(GT018_MOB.CGARANT_BEM) IN ('7108') THEN '52'
		WHEN BASE.ORIGEM = 'MUG' AND GT018_MOB.CHAVE_BEM_PRE IS NOT NULL AND TRIM(GT018_MOB.CGARANT_BEM) IN ('7109') THEN '53'
		WHEN BASE.ORIGEM = 'PM-I' OR BASE.ORIGEM = 'PM-M' OR BASE.ORIGEM = 'PM-F' OR BASE.ORIGEM = 'PM-P' THEN LT_ESTRUT.TYP_PRTCTN
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND TRIM(PROPERTY.property_code) IN ('7500','7501','7502','7503','7504','7505','7506','7507','7508','7509','7510','7511','7512','7513','7514','7515') THEN '3'
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND TRIM(PROPERTY.property_code) IN ('6101','6102') THEN '5'
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND TRIM(PROPERTY.property_code) IN ('158','182','108','107','159','197','198','106','1B5','164','169','183','1SS','160','309','321','298','105','126','125','199','104','157','1EE','181','120','186','999','101','LSA','190','501','1','111','103','1CC','196','1SW','102','133','345') THEN '7'
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND TRIM(PROPERTY.property_code) IN ('5101','5102','5103','5104') THEN '8'
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND TRIM(PROPERTY.property_code) IN ('5203','5204') THEN '9'
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND TRIM(PROPERTY.property_code) IN ('5000','5201','5202','5302','5205','5206','5207','5207','5209','5210','5211','5300','5212','5213','5214','5303','5301','5215','5216','5217','5218') THEN '10'
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND TRIM(PROPERTY.property_code) IN ('6401','6402','6403','6404','6405','6406','6407','6408') THEN '12'
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND TRIM(PROPERTY.property_code) IN ('6201','6202') THEN '15'
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND TRIM(PROPERTY.property_code) IN ('6300','6501','6502','6503','6504') THEN '18'
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND TRIM(PROPERTY.property_code) IN ('7100','7101','7102','7103','7104','7105','7106','7107','7110','7111') THEN '51'
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND TRIM(PROPERTY.property_code) IN ('7108') THEN '52'
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND TRIM(PROPERTY.property_code) IN ('7109') THEN '53'
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND PROPERTY.property_code IS NULL THEN '99999999999'
		ELSE 'NOK'
	END AS TYP_PRTCTN 
    ,CASE
		WHEN LT_ESTRUT.PRTCTN_ID IS NOT NULL THEN LT_ESTRUT.ORGNL_PRTCTN_VL
		WHEN BASE.ORIGEM = 'MBI' THEN 99999999999
	END AS ORGNL_PRTCTN_VL 
	,CASE
		WHEN LT_ESTRUT.PRTCTN_ID IS NOT NULL THEN LT_ESTRUT.PRTCTN_VL
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND PROPERTY.LAST_APPRAISAL_AMOUNT IS NOT NULL THEN PROPERTY.LAST_APPRAISAL_AMOUNT
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND PROPERTY.LAST_APPRAISAL_AMOUNT IS NULL THEN 99999999999
		WHEN BASE.ORIGEM = 'MUG' AND GT018_MOB_2.CHAVE_BEM_PRE IS NOT NULL AND GT018_MOB_2.MAVALIAA IS NOT NULL THEN GT018_MOB_2.MAVALIAA -- 25/03: Este universo devia estar em PM, ou seja este case é de forma tática para obter valor no univ de móveis
		WHEN BASE.ORIGEM = 'MUG' AND GT018_MOB_2.CHAVE_BEM_PRE IS NOT NULL AND GT018_MOB_2.MAVALIAA IS NULL THEN 99999999999 -- 25/03: Este universo devia estar em PM, ou seja este case é de forma tática para obter valor no univ de móveis
	END AS PRTCTN_VL
	,11111111111 AS PRMRY_ENRGY_DMND_NN_RNWBL
	,'0000-00-00' AS DT_RGSTRTN 
	,'MISS' AS TYP_EMSSNS_LBL
	,'MISS' AS VHCL_EMSSNS_LBL
	,99999999999 AS VHCL_EMSSNS_SCR
	,'MISS' AS INSRNC_ID
	,'MISS' AS TYP_HZRDS_INSRD
	,99999999999 AS AMNT_CVRD_INSRNC
	,'0000-00-00' AS DT_MTRTY_INSRNC
	,'MISS' AS FLG_FRST_HM
	,CASE 
		WHEN BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-P' OR BASE.ORIGEM = 'PM-F' OR BASE.ORIGEM = 'PM-M' THEN 'N/A' 
		WHEN TRIM(UPPER(MBI.NZEB_IND))='TRUE' THEN 'ESTT02'
		ELSE 'MISS'
	END AS RL_ESTT_CRTFCTN
    ,CASE 
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND PROPERTY.net_floor_area IS NOT NULL THEN PROPERTY.net_floor_area
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND PROPERTY.net_floor_area IS NOT NULL THEN 99999999999
		WHEN BASE.ORIGEM = 'PM-I' AND PROPERTY.CHAVE_BEM IS NOT NULL AND PROPERTY.net_floor_area IS NOT NULL THEN PROPERTY.net_floor_area
		WHEN BASE.ORIGEM = 'PM-I' AND PROPERTY.CHAVE_BEM IS NOT NULL AND PROPERTY.net_floor_area IS NULL THEN 99999999999
		WHEN BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-F' OR BASE.ORIGEM = 'PM-M' OR BASE.ORIGEM = 'PM-P' THEN 11111111111
-- 		ELSE '99999999999'
	END AS BLDNG_AR
	,CASE 
    	WHEN BASE.ORIGEM = 'PM-I' AND LT_ESTRUT.PRTCTN_ID IS NOT NULL AND LT_ESTRUT.YR_CNSTRCTN IS NOT NULL THEN LT_ESTRUT.YR_CNSTRCTN
		WHEN BASE.ORIGEM = 'PM-I' AND LT_ESTRUT.PRTCTN_ID IS NOT NULL AND LT_ESTRUT.YR_CNSTRCTN IS NULL THEN 99999999999
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND PROPERTY.construction_year IS NOT NULL THEN cast(PROPERTY.construction_year as int)
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND PROPERTY.construction_year IS NULL THEN 99999999999
		WHEN BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-F' OR BASE.ORIGEM = 'PM-M' OR BASE.ORIGEM = 'PM-P' THEN 11111111111
-- -- 		ELSE '99999999999'
	END AS YR_CNSTRCTN
	,CASE 
    	WHEN BASE.ORIGEM = 'PM-I' AND LT_ESTRUT.PRTCTN_ID IS NOT NULL AND LT_ESTRUT.RL_ESTT_ADDRSS IS NOT NULL THEN LT_ESTRUT.RL_ESTT_ADDRSS
		WHEN BASE.ORIGEM = 'PM-I' AND LT_ESTRUT.PRTCTN_ID IS NOT NULL AND LT_ESTRUT.RL_ESTT_ADDRSS IS NULL THEN 'MISS'
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND PROPERTY.MORADA IS NOT NULL THEN PROPERTY.MORADA
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND PROPERTY.MORADA IS NULL THEN 'MISS'
		WHEN BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-F' OR BASE.ORIGEM = 'PM-M' OR BASE.ORIGEM = 'PM-P' THEN 'N/A'
-- 		ELSE 'MISS'
	END AS RL_ESTT_ADDRSS
		,CASE 
    	WHEN BASE.ORIGEM = 'PM-I' AND LT_ESTRUT.PRTCTN_ID IS NOT NULL AND LT_ESTRUT.RL_ESTT_CLLTRL_LCTN_INT IS NOT NULL THEN LT_ESTRUT.RL_ESTT_CLLTRL_LCTN_INT
		WHEN BASE.ORIGEM = 'PM-I' AND LT_ESTRUT.PRTCTN_ID IS NOT NULL AND LT_ESTRUT.RL_ESTT_CLLTRL_LCTN_INT IS NULL THEN 'MISS'
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND TAT.LOCALIZACAO = '99' THEN 'MISS'
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND TAT.LOCALIZACAO IS NOT NULL THEN TAT.LOCALIZACAO
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND TAT.LOCALIZACAO IS NULL THEN 'MISS'
		WHEN BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-F' OR BASE.ORIGEM = 'PM-M' OR BASE.ORIGEM = 'PM-P' THEN 'N/A'
-- 		ELSE 'MISS'
	END AS RL_ESTT_CLLTRL_LCTN_INT
			,CASE 
    	WHEN BASE.ORIGEM = 'PM-I' AND LT_ESTRUT.PRTCTN_ID IS NOT NULL AND LT_ESTRUT.RL_ESTT_CTY IS NOT NULL THEN LT_ESTRUT.RL_ESTT_CTY
		WHEN BASE.ORIGEM = 'PM-I' AND LT_ESTRUT.PRTCTN_ID IS NOT NULL AND LT_ESTRUT.RL_ESTT_CTY IS NULL THEN 'MISS'
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND TAT2.LOCALIZACAO = '99' THEN 'MISS'
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND TAT2.LOCALIZACAO IS NOT NULL THEN TAT2.LOCALIZACAO
		WHEN BASE.ORIGEM = 'MBI' AND PROPERTY.CHAVE_BEM IS NOT NULL AND TAT2.LOCALIZACAO IS NULL THEN 'MISS'
		WHEN BASE.ORIGEM = 'MUG' OR BASE.ORIGEM = 'PM-F' OR BASE.ORIGEM = 'PM-M' OR BASE.ORIGEM = 'PM-P' THEN 'N/A'
-- 		ELSE 'MISS'
	END AS RL_ESTT_CTY
	
-- select count(*)	
FROM 
	-- 1º Cruzamento: Obter Universo 
	--> OUT 2.787.519 registos | 
    --> NOV 473.962 
   (
   SELECT 
		CHAVE_BEM
		,CHAVE_BEM_PRE
		,ORIGEM
   FROM
		(
		SELECT 
			CHAVE_BEM
			,CHAVE_BEM_PRE
			,ORIGEM
			,ROW_NUMBER() OVER (PARTITION BY CHAVE_BEM ORDER BY CASE WHEN ORIGEM='MUG' OR ORIGEM='PM-F' OR ORIGEM='PM-I' OR ORIGEM='PM-P' THEN 1 ELSE 0 END DESC) AS ROW_1
        FROM
			(
			--2.569.862 Registos
				SELECT DISTINCT GT012.CHAVE_BEM, GT012.CHAVE_BEM_PRE,'MUG' AS ORIGEM
				FROM
					(
					SELECT INSTRMNT_ID
					FROM BU_LOANTAPE_WORK.LT002_INSTRUMENT
					WHERE ref_date='${ref_date}'
						AND nome_perimetro= 'Individual Corporativo'
						AND segmento= 'ESTR' 
						AND ambito= 'PM'
						AND entidade = '00100'
					) LT002
				INNER JOIN
					(
					SELECT DISTINCT 
						CONCAT (CEMPRESA_FR, CBALCAO_FR, CNUMECTA_FR, ZDEPOSIT_FR) AS CHAVE_FINREP
						,CONCAT (CEMPRESA, CBALCAO, CNUMECTA, ZDEPOSIT) AS CHAVE_MASTER
					FROM cd_captools.kt_chaves_finrep
					WHERE ref_date='${ref_date}') FR 
					ON LT002.INSTRMNT_ID = FR.CHAVE_FINREP
				INNER JOIN 
					(
					SELECT DISTINCT 
						CONCAT (CEMPRESP, CKBALRES, CKCTARES, CKREFRESP) AS CHAVE_MASTER
						,CONCAT (CEMPRESA, CKBALCAO, CKNUMCTA, COMP_ID_GAR) AS CHAVE_PROCESSO
					FROM cd_garantias.gt001_trz_rsp_gt
					WHERE ref_date='${ref_date}') GT001 
					ON FR.CHAVE_MASTER = GT001.CHAVE_MASTER
				INNER JOIN
					(
					SELECT DISTINCT 
						CONCAT (CEMPRESA, CKBALCAO, CKNUMCTA, COMP_ID_GAR) AS CHAVE_PROCESSO
						,CONCAT (CEMPBEM, CKBALBEM, CKCTABEM, CKREFBEM) AS CHAVE_BEM
						,CONCAT ('M','_',CKBALBEM,'_',CKCTABEM,'_',CKREFBEM) AS CHAVE_BEM_PRE
					FROM cd_garantias.gt012_trz_gt_mob
					WHERE ref_date='${ref_date}') GT012 ON GT001.CHAVE_PROCESSO = GT012.CHAVE_PROCESSO
					
			UNION ALL
				---384.959 Registos
				SELECT DISTINCT PROCESSO_BI.CHAVE_BEM,PROCESSO_BI.CHAVE_BEM_PRE,'MBI' AS ORIGEM 
				FROM 
					(
					SELECT 
						INSTRMNT_ID
					FROM BU_LOANTAPE_WORK.LT002_INSTRUMENT
					WHERE ref_date='${ref_date}'
						AND nome_perimetro= 'Individual Corporativo'
						AND segmento= 'ESTR' 
						AND ambito= 'PM'
						AND entidade = '00100'
					) LT002		
				INNER JOIN	
					(
					SELECT DISTINCT 
						CONCAT (CEMPRESA_FR, CBALCAO_FR, CNUMECTA_FR, ZDEPOSIT_FR) AS CHAVE_FINREP
						,CONCAT (CEMPRESA, CBALCAO, CNUMECTA, ZDEPOSIT) AS CHAVE_MASTER
					FROM cd_captools.kt_chaves_finrep
					WHERE ref_date='${ref_date}'
					) FR ON LT002.INSTRMNT_ID = FR.CHAVE_FINREP
				INNER JOIN	
					(
					SELECT DISTINCT 
						CONCAT (BANK_ID, BRANCH_CODE, CONTRACT_ID, REFERENCE_CODE) AS CHAVE_RESPONSABILIDADE,
						CONCAT (PROCESS_BANK_ID, PROCESS_BRANCH_CODE, PROCESS_ACCOUNT_ID, PROCESS_REFERENCE_CODE) AS CHAVE_PROCESSO
					FROM BU_ESG_WORK.RESPONSIBILITY_PROCESS_REL
					WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BU_ESG_WORK.RESPONSIBILITY_PROCESS_REL  WHERE DATA_DATE_PART <= '${ref_date}') 
					)CREDITO_PROCESSO ON CREDITO_PROCESSO.CHAVE_RESPONSABILIDADE = FR.CHAVE_MASTER
				INNER JOIN
					(
					SELECT DISTINCT 
						CONCAT (PROCESS_BANK_ID, PROCESS_BRANCH_CODE, PROCESS_ACCOUNT_ID, PROCESS_REFERENCE_CODE) AS CHAVE_PROCESSO
						,CONCAT ('I','_',PROPERTY_BRANCH_CODE,'_',PROPERTY_CONTRACT_ID,'_',PROPERTY_REFERENCE_CODE) AS CHAVE_BEM_PRE
						,CONCAT (PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM
						,COLLATERAL_PROPERTY_IND AS FLG_COL
						,FINANCED_PROPERTY_IND AS FLG_FIN
					FROM BU_ESG_WORK.PROCESS_PROPERTY_REL
					WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BU_ESG_WORK.PROCESS_PROPERTY_REL WHERE DATA_DATE_PART <= '${ref_date}') 
						AND (COLLATERAL_PROPERTY_IND = 1 OR FINANCED_PROPERTY_IND = 1)
					)PROCESSO_BI ON CREDITO_PROCESSO.CHAVE_PROCESSO = PROCESSO_BI.CHAVE_PROCESSO
				
			UNION ALL
				---2.513.397 Registos
				SELECT DISTINCT 
					REPLACE(SUBSTR(LT006.PRTCTN_ID,3,LENGTH(LT006.PRTCTN_ID)),'_','') AS CHAVE_BEM
					,PRTCTN_ID AS CHAVE_BEM_PRE
					,CONCAT('PM-',SUBSTR(LT006.PRTCTN_ID,1,1)) AS ORIGEM
				FROM
					(
					SELECT INSTRMNT_ID
					FROM BU_LOANTAPE_WORK.LT002_INSTRUMENT
					WHERE ref_date='${ref_date}'
						AND nome_perimetro= 'Individual Corporativo'
						AND segmento= 'ESTR' 
						AND ambito= 'PM'
						AND entidade = '00100'
					) LT002	
				INNER JOIN
					(
					SELECT INSTRMNT_ID, PRTCTN_ID
					FROM BU_LOANTAPE_WORK.lt006_instr_prot
					WHERE ref_date='${ref_date}'
						AND nome_perimetro= 'Individual Corporativo'
						AND segmento= 'ESTR' 
						AND ambito= 'PM'
					) LT006 ON LT002.INSTRMNT_ID = LT006.INSTRMNT_ID
			)UNIV_TOTAL
		) UNIV_TRAT	WHERE ROW_1 = 1 
	) BASE

LEFT JOIN 
 	-- 2º Cruzamento: LoanTape Estrutural
	--> OUT24 449.139 registos |

	(
	SELECT DISTINCT PRTCTN_ID, RL_ESTT_CLLTRL_LCTN, RL_ESTT_PST_CD, ORGNL_PRTCTN_VL, PRTCTN_VL, TYP_PRTCTN, YR_CNSTRCTN, RL_ESTT_ADDRSS, RL_ESTT_CLLTRL_LCTN_INT, RL_ESTT_CTY
	FROM  BU_LOANTAPE_WORK.LT004_PROTECTION 
	WHERE ref_date='${ref_date}'
		AND nome_perimetro= 'Individual Corporativo'
		AND segmento= 'ESTR'
		AND ambito= 'PM'
		AND entidade = '00100'
	)LT_ESTRUT ON BASE.CHAVE_BEM_PRE = LT_ESTRUT.PRTCTN_ID
		
LEFT JOIN	
	-- 3º Cruzamento: Tabela MV Output de Veículos
	--> OUT24 20.643 registos | 
	(
	SELECT DISTINCT CONCAT (CEMPBEM, CKBALBEM, CKCTABEM, CKREFBEM) AS CHAVE_BEM, SCP1_EMSS, SCP2_EMSS, SCP3_EMSS, ORIGEM_SCP1_EMSS, ORIGEM_SCP2_EMSS, ORIGEM_SCP3_EMSS
	FROM bu_esg_work.modesg_out_emss_vcls
	WHERE ref_date='${ref_date}'
	)MV_OUT_VCLS ON BASE.CHAVE_BEM = MV_OUT_VCLS.CHAVE_BEM
  
LEFT JOIN	
	-- 4º Cruzamento: Tabela MV Output de Bens Imóveis
	--> OUT24 275.429 registos || 
    (
	SELECT DISTINCT CONCAT (CEMPBEM, CKBALBEM, CKCTABEM, CKREFBEM) AS CHAVE_BEM, CONCAT (CKBALBEM, CKCTABEM, CKREFBEM) AS CHAVE_BEM_2,  FLG_RSC_FSC_AGD, FLG_RSC_FSC_CRNC, SCP1_EMSS, SCP2_EMSS, SCP3_EMSS, ORIGEM_SCP1_EMSS, ORIGEM_SCP2_EMSS, ORIGEM_SCP3_EMSS
	FROM bu_esg_work.modesg_out_bens_imoveis
	WHERE ref_date='${ref_date}'
	)MV_OUT_BI ON BASE.CHAVE_BEM = MV_OUT_BI.CHAVE_BEM_2
  
LEFT JOIN 
 	-- 5º Cruzamento: Tabela Modelo de Bens Imóveis - Tabela Output de Certificados 
	--> OUT24 275.429 registos |
	(
	SELECT DISTINCT CONCAT (PROPERTY_BRANCH_CODE, PROPERTY_CONTRACT_ID, PROPERTY_REFERENCE_CODE) AS CHAVE_BEM, EPC, ENERGY_CONSUMPTION_VALUE_YEAR, QUALITY_SCORE,NZEB_IND,EP_SCORE,SOURCE_CODE
	FROM bu_esg_work.PROPERTY_ENERGY_CERTIFICATE 
	WHERE DATA_DATE_PART IN (SELECT MAX(DATA_DATE_PART) FROM bu_esg_work.PROPERTY_ENERGY_CERTIFICATE WHERE DATA_DATE_PART <='${ref_date}')  
	)MBI ON BASE.CHAVE_BEM = MBI.CHAVE_BEM

LEFT JOIN 
 	-- 6º Cruzamento: Tabela Modelo de Bens Imóveis - Tabela de Bens 
	--> OUT24 275.429 registos |
	(
	SELECT CONCAT (PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM, POSTAL_CODE, LAST_APPRAISAL_AMOUNT, DISTRICT_MUNICIP_PARISH_CODE, property_code, net_floor_area, construction_year, concat(trim(REGEXP_REPLACE(address,'[^[:print:]\\p{S}\\p{P}\\p{L}\\p{N}]','')),' ',trim(REGEXP_REPLACE(property_number,'[^[:print:]\\p{S}\\p{P}\\p{L}\\p{N}]','')),' ',trim(REGEXP_REPLACE(floor_number,'[^[:print:]\\p{S}\\p{P}\\p{L}\\p{N}]',''))) AS MORADA
	FROM BU_ESG_WORK.PROPERTY
	WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BU_ESG_WORK.PROPERTY  WHERE DATA_DATE_PART <='${ref_date}') 
	)PROPERTY ON BASE.CHAVE_BEM = PROPERTY.CHAVE_BEM

LEFT JOIN
 	-- 7º Cruzamento: MUG - GT018 para MOB (info de cgarant)
	--> OUT24 275.429 registos |
	(
	SELECT DISTINCT CONCAT ('M','_',CKBALBEM,'_',CKCTABEM,'_',CKREFBEM) AS CHAVE_BEM_PRE ,CGARANT_BEM
	FROM CD_GARANTIAS.GT018_RATEIO_aval
	WHERE TRIM(tipologia) = 'MOB' 
		AND REF_DATE='${ref_date}'
	)GT018_MOB ON BASE.CHAVE_BEM_PRE = GT018_MOB.CHAVE_BEM_PRE

LEFT JOIN
 	-- 8º Cruzamento: MUG - GT018 Agrupada por chave 
	--> OUT24 275.429 registos |
	(
	SELECT*
	FROM
		(
		SELECT
			CASE
				WHEN TRIM(tipologia) = 'MOB' THEN CONCAT ('M','_',CKBALBEM,'_',CKCTABEM,'_',CKREFBEM) 
				WHEN TRIM(tipologia) = 'PES' THEN CONCAT ('P','_',CKBALBEM,'_',CKCTABEM,'_',CKREFBEM)
				WHEN TRIM(tipologia) = 'FIN' THEN CONCAT ('F','_',CKBALBEM,'_',CKCTABEM,'_',CKREFBEM)
				WHEN TRIM(tipologia) = 'IMO' THEN CONCAT ('I','_',CKBALBEM,'_',CKCTABEM,'_',CKREFBEM)
			END AS CHAVE_BEM_PRE, SUM(MAVALIAA) AS MAVALIAA 
		FROM cd_garantias.gt018_rateio_aval
		WHERE REF_DATE='${ref_date}'
		GROUP BY 1
		)GT018_1 WHERE GT018_1.CHAVE_BEM_PRE IS NOT NULL 
	)GT018_MOB_2 ON BASE.CHAVE_BEM_PRE = GT018_MOB_2.CHAVE_BEM_PRE

LEFT JOIN 
-- 9º Cruzamento: TAT
    (  
    SELECT tayd91c0_celemtab, tayd91c0_gelemtab as localizacao
    FROM cd_estruturais.tat91_tabelas
    WHERE tayd91c0_ctabela='J48'
    and DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM cd_estruturais.tat91_tabelas WHERE DATA_DATE_PART <='${ref_date}'and tayd91c0_ctabela='J48') 
    ) TAT ON TRIM(PROPERTY.DISTRICT_MUNICIP_PARISH_CODE) = TRIM(TAT.TAYD91C0_CELEMTAB)
    
LEFT JOIN 
-- 10º Cruzamento: TAT2
    (  
    SELECT tayd91c0_celemtab, tayd91c0_gelemtab as localizacao
    FROM cd_estruturais.tat91_tabelas
    WHERE tayd91c0_ctabela='J48'
    and DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM cd_estruturais.tat91_tabelas WHERE DATA_DATE_PART <='${ref_date}' and tayd91c0_ctabela='J48' ) 
    ) TAT2 ON TRIM(CONCAT(SUBSTRING(PROPERTY.DISTRICT_MUNICIP_PARISH_CODE,1,2),'0000')) = TRIM(TAT2.TAYD91C0_CELEMTAB)