----------------------------------------------------- Queries para 'EURO1', 'STEP 1', 'STEP 2', 'TARGET 2', 'SWIFT' -----------------------------------------------------

-- 1. RS’s – MT101 – Internas
SELECT 'RS - INTERNA',
CASE
  WHEN B.CESTADO = 'TRT' THEN 'TRT - TRATADA'
  END AS CESTADO, B.CMOEDA AS MOEDA,
SUM(B.MONTANTE) AS TOTAL_MONTANTE,
COUNT(*) AS TOTAL_OPERACOES
FROM DBSPRDX.RSVT02A0_MT101MSG A,
     DBSPRDX.RSVT03A2_MT101TRF B
wHERE A.CREFMT101 = B.CREFMT101
  AND A.ZINDEX    = B.ZINDEX
  AND B.CSISCMP   = 'BST'
  AND B.CESTADO   = 'TRT'
  AND B.DTVALTRF  = 'data do dia'
GROUP BY B.CESTADO, B.CMOEDA
ORDER BY B.CESTADO, B.CMOEDA
;

-- 2. EST81 – TGT’s Emitidos por Sintra
SELECT
  'TGT' AS MEIO,
  CASE
    WHEN IENVIO = 'P' THEN 'P - MENSAGEM ENVIADA OK        ' END AS ESTADO,
    'EUR' AS MOEDA, SUM(MONTANTE) AS TOTAL_MONTANTE,
    COUNT(*) AS TOTAL_OPERACOES
FROM DBSPRDX.ESVT81A4_SPGT
WHERE IORIGMSG = ' AI'
AND CMSG     = 1363
AND IENVIO   = 'P'
AND DATAMSG  = 'data do dia'
AND CUTULMOD <> 'OEH00525'
AND SUBSTR(GTRNDATA,118,6) = 'MT103 '
GROUP BY IENVIO
ORDER BY IENVIO
;

-- 3. Transf. Emitidas em HH
SELECT
  CASE WHEN INDESTF = 'CTA' THEN 'CTA - VOSTRO        '
       WHEN INDESTF = 'SWF' THEN 'SWF - NOSTRO        '
       WHEN INDESTF = 'EBA' THEN 'EBA - EURO1         '
       WHEN INDESTF = 'LVP' THEN 'LVP - STEP1         '
       WHEN INDESTF = 'TEI' THEN 'TEI - TEI           '
       WHEN INDESTF = 'TGT' THEN 'TGT - TARGET        '
       WHEN INDESTF = 'ABD' THEN 'ABD - ABONO DIRETO  '
       WHEN INDESTF = '   ' THEN 'SEM MEIO            '
  ELSE ' - OUTRO MEIO    '
  END AS MEIO,
  CASE WHEN INDSITCO = 'EM' THEN 'EM - EMITIDA                   '
       END AS ESTADO,
  CODMONSW AS MOEDA,
  SUM(IMPDIVPG) AS TOTAL_MONTANTE,
  COUNT(*) AS TOTAL_OPERACOES
FROM cd_transferencias.HH_TRANSF_EMIT
WHERE INDSITCO = 'EM'
AND FECALTA  = 'data do dia'
GROUP BY INDESTF, INDSITCO, CODMONSW
ORDER BY INDESTF, INDSITCO, CODMONSW;
-- Garantir que o conceito de transferências emitidas desta tabela bate com o conceito de transações enviadas que o report pede
-- Os montantes do campo TOTAL_MONTANTE, estão na moeda indicada no campo MOEDA ou já estão convertidos para Euros
-- Onde entram os CTA, SWF, TEI, ABD, SEM MEIO, OUTRO MEIO

-------------------------------------------------------------------- Queries para 'SICOI' --------------------------------------------------------------------

-- Cheques

-- 1. Query’s da Compensação Enviada e R-Transactions/Devoluções da compensação Enviada:
-- Tabelas:
--   DBSPRDX.CCVT71A0_APRESENT   -> Tabela diária com 2 meses
--   DBHPRDX.CCVT71A0_APRESENT   -> Tabela de Historico  c/10 Anos

SELECT DTCOMP AS DT_COMPENSACAO,
       CODFICH,
       CASE WHEN CODFICH = 'CENE' THEN 'CENE - APRESENTADA A OIC '
            WHEN CODFICH = 'CRCE' THEN 'CRCE - DEVOLVIDOS DE OIC '
       ELSE CODFICH || ' – OUTRO/ERRO(?)     '
       END AS TP_DETALHE,
       COUNT(*)     AS NR_CHEQUES,
       SUM(MIMPORT) AS TOT_IMPORTE_EUR
FROM DBSPRDX.CCVT71A0_APRESENT
-- FROM DBHPRDX.CCVT71A0_APRESENT
WHERE DTCOMP BETWEEN '2023-11-15' AND '2023-11-15'
AND CODFICH IN ('CENE', 'CRCE')
GROUP BY DTCOMP, CODFICH
;

-- 2. Query’s da Compensação Recebida e R-Transactions/Devoluções da compensação Recebida:
-- Tabelas:
--   DBSPRDX.CCVT72A0_RECEBIDA   -> Tabela diária com 2 meses
--   DBHPRDX.CCVT72A0_RECEBIDA   -> Tabela de Historico  c/10 Anos

SELECT DTCOMP AS DT_COMPENSACAO,
       CASE WHEN CODFICH = 'CRCE' THEN 'CRCE - APRESENTADA AO BST'
            WHEN CODFICH = 'CENE' THEN 'CENE - DEVOLVIDOS A OIC  '
       ELSE CODFICH || ' – OUTRO/ERRO(?)     '
       END AS TP_DETALHE,
       COUNT(*) AS NR_CHEQUES,
       SUM(MIMPORT) AS TOT_IMPORTE_EUR
FROM DBSPRDX.CCVT72A0_RECEBIDA
-- FROM DBHPRDX.CCVT72A0_RECEBIDA
WHERE DTCOMP BETWEEN '2023-11-15' AND '2023-11-17'
AND CODFICH IN ('CENE', 'CRCE')
GROUP BY DTCOMP, CODFICH
;

-- Operações SEPA

-- SEPA CT – OIC

SELECT COUNT(*) QUANTIDADE_TOTAL,
       SUM(MMOVIM) MONTANTE_TOTAL
FROM DBSPRDX.ORVT01B1_SEPA
WHERE 1=1
AND CINSTORD = 'E'
AND DTLIQUID >= '2023-11-01'
AND DTLIQUID <= '2023-11-30'
AND CSISCMP <> 'BST'
AND CCICLO <>'IP'


-- SEPA CT – Internas

SELECT COUNT(*) QUANTIDADE_TOTAL,
       SUM(MMOVIM) MONTANTE_TOTAL
FROM DBSPRDX.ORVT01B1_SEPA
WHERE 1=1
AND CINSTORD = 'E'
AND DTLIQUID >= '2023-11-01'
AND DTLIQUID <= '2023-11-30'
AND CSISCMP = 'BST'
AND CCICLO <>'IP'

-- SEPA Imediatas

SELECT COUNT(*) QUANTIDADE_TOTAL,
       SUM(MMOVIM) MONTANTE_TOTAL
FROM DBSPRDX.ORVT01B1_SEPA
WHERE 1=1
AND CINSTORD = 'E'
AND DTLIQUID >= '2023-11-01'
AND DTLIQUID <= '2023-11-30'
AND CCICLO = 'IP'


-- SEPA DD – OIC (também englobam o destino BST)

SELECT COUNT(*) QUANTIDADE_TOTAL,
       SUM(MMOVIM) MONTANTE_TOTAL
FROM DBSPRDX.DDVT04A5_IDDEMI
WHERE 1=1
AND CESTADO IN ('COB','RE','RV','DV', 'DR','RJ','CA','CAN')
AND DTLIQUID >= '2023-11-01'
AND DTLIQUID <= '2023-11-30'
AND ICOMPINT <> 'S'

-- SEPA DD – Compensação interna

SELECT COUNT(*) QUANTIDADE_TOTAL,
       SUM(MMOVIM) MONTANTE_TOTAL
FROM DBSPRDX.DDVT04A5_IDDEMI
WHERE 1=1
AND CESTADO IN ('COB','RE','RV','DV', 'DR','RJ','CA','CAN')
AND DTLIQUID >= '2023-11-01'
AND DTLIQUID <= '2023-11-30'
AND ICOMPINT = 'S'
