/********************************************************************************************************************************************
****   Projeto: Implementação Templates Locais                                                                     						 ****
****   Autor: BS & Neyond                                                                                                                ****
****   Data: 28/05/2025                                                                                                                  ****
****   SQL Script Descrição: Geração do Template 1																					     ****
****  ( Banking book - Climate change transition risk: Quality of exposures by sector ) 												 ****
********************************************************************************************************************************************/

/*=========================================================================================================================================*/
/*  1. Tabela granular: Obtenção do universo a reportar no âmbito do Template 1 + Marcação de metricas relevantes             			   */
/*=========================================================================================================================================*/
       

-- INSERT OVERWRITE TABLE BU_ESG_WORK.AG01_TEMP_CTO_GRA PARTITION (ID_CORRIDA,REF_DATE)
SELECT 
    UNIVERSO.ZCLIENTE,
	UNIVERSO.CEMPRESA,
	UNIVERSO.CBALCAO,
	UNIVERSO.CNUMECTA,
	UNIVERSO.ZDEPOSIT,
    UNIVERSO.VB_IMP, 
    UNIVERSO.STAGES AS STAGE, 
    UNIVERSO.CONTRAPARTE,
	NFIN.FLG_CSRD AS FLAG_NFRD,
	SUM(ASCI) AS ASCI,
	SUM(GESI) AS GESI,
	SUM(ASC2) AS ASC2,
	SUM(GESII) AS GESII,
	SUM(ASCIII) AS ASCIII,
	SUM(GESIII) AS GESIII,
	CASE
		WHEN  TRIM(UNIVERSO.CONTRAPARTE) = 'outras empresas nao financeiras' AND NFIN.FLG_EMPRS_EXCL_PARIS = 1 THEN 'excluido' 
		WHEN  TRIM(UNIVERSO.CONTRAPARTE) = 'outras empresas nao financeiras' AND NFIN.FLG_EMPRS_EXCL_PARIS = 0 THEN 'nao excluido' 
		ELSE ''
	END AS EXCLUDED_PARIS,
	CASE
        WHEN INSTRUMENTO_FINANCEIRO = 'instrumentos de capital' THEN -3 -- 'INSTRUMENTOS DE CAPITAL' : > 20 ANOS
	    WHEN UNIVERSO.DATA_VENCIMENTO  IN ('','0001-01-01','9999-12-31',NULL) AND TIPO_COLATERAL = 'Garantia Residencial' THEN -2 -- FALTA DE DATA QUALITY DE DADOS MAS GARANTIA RESIDENCIAL
    	WHEN UNIVERSO.DATA_VENCIMENTO  IN ('','0001-01-01','9999-12-31',NULL) THEN -1 -- FALTA DE DATA QUALITY DE DADOS MAS NÃO GARANTIA RESIDENCIAL
	    WHEN UPPER(UNIVERSO.PRODUTO) LIKE 'CART%CR%DITO%' OR UPPER(UNIVERSO.PRODUTO) LIKE '%REPOS%'  OR UPPER(UNIVERSO.PRODUTO) LIKE '%VISTA, DESCOBERTOS E CO%' THEN -1 -- 'COUNTERPARTY HAVING THE CHOICE OF THE REPAYMENT DATE'
        WHEN UNIVERSO.DATA_VENCIMENTO  < '${REF_DATE}' THEN -4 --'OLD CONTRACTS' 
        ELSE ROUND(DATEDIFF(TO_DATE(UNIVERSO.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25, 4)
    END AS YEARS_TO_MATURITY,
	CASE
		WHEN UNIVERSO.ZCLIENTE = '0000000000' THEN 'S'
		WHEN NFIN.COD_NACE_ESG = '' AND UNIVERSO.CONTRAPARTE = 'outras empresas nao financeiras' THEN 'S' 
		WHEN NFIN.COD_NACE_ESG = 'Nao Aplicavel' THEN '' 
		WHEN NFIN.COD_NACE_ESG IS NULL THEN ''
		ELSE NFIN.COD_NACE_ESG
	END AS COD_NACE_ESG,
	SUM(
        CASE
            WHEN TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'SPECIFIC PURPOSE' AND SFICS.NOME_SPECIFIC_ELIGIBLE = 'CCM' THEN NVL(ASCI,0) ELSE 0 END +
    	CASE 
    		WHEN TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'GENERAL PURPOSE' THEN NVL(ASCI * NFIN.CCM_TRNVR_OWN_PRFRMNCE_ALGND/100,0) ELSE 0 END + 
        CASE 
    		WHEN TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'GENERAL PURPOSE' THEN NVL(ASCI * NFIN.CCM_TRNVR_TRNSTN_ALIGND/100,0) ELSE 0 END + 
        CASE 
    		WHEN TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'GENERAL PURPOSE' THEN NVL(ASCI * NFIN.CCM_TRNVR_ENBLNG_ALGND/100,0) ELSE 0 END 
		)  AS SUSTAINABLE_CCM,
	SOURCE_EMISSION_1,
	SOURCE_EMISSION_2,
	SOURCE_EMISSION_3,
	EUROPEAN_UNION,

    -- PARTICAO
	RT.NEW_ID_CORRIDA AS ID_CORRIDA,
	'${REF_DATE}' AS REF_DATE
FROM
(    SELECT 
    	ZCLIENTE,
    	CEMPRESA,
    	CBALCAO,
    	CNUMECTA,
    	ZDEPOSIT,
        VB_IMP, 
        CONTRAPARTE,
        STAGES,
        NON_PERFORMING,
        DATA_VENCIMENTO,
        PRODUTO,
        INSTRUMENTO_FINANCEIRO,
        TIPO_COLATERAL,
		SOURCE_EMISSION_1,
		SOURCE_EMISSION_2,
		SOURCE_EMISSION_3,
		EUROPEAN_UNION,
    	SUM(AMOUNT) AS ASCI,
    	SUM(GESI) AS GESI,
    	SUM(AMOUNT) AS ASC2,
    	SUM(GESII) AS GESII,
    	SUM(AMOUNT) AS ASCIII,
    	SUM(GESIII) AS GESIII    	
    FROM
    (
        SELECT
        	EMISS.ZCLIENTE,
        	UNIVERSO.CEMPRESA,
        	UNIVERSO.CBALCAO,
        	UNIVERSO.CNUMECTA,
        	UNIVERSO.ZDEPOSIT,
            UNIVERSO.BRUTO_IMPARIDADE AS VB_IMP, 
            CONTRAPARTE,
            STAGES,
            NON_PERFORMING,
            DATA_VENCIMENTO,
            PRODUTO,
            INSTRUMENTO_FINANCEIRO,
            TIPO_COLATERAL,
			CASE 
        		WHEN EMISS.ORIGEM_SCP1_EMSS IN ('MISS','Nao Aplicavel') THEN 'SOUR3'
        		WHEN EMISS.ORIGEM_SCP1_EMSS LIKE '%DQS1%' OR EMISS.ORIGEM_SCP1_EMSS LIKE '%DQS2%' THEN 'SOUR1'
    			ELSE 'SOUR2'
    		END AS SOURCE_EMISSION_1,
			CASE 
				WHEN EMISS.ORIGEM_SCP2_EMSS IN ('MISS','Nao Aplicavel') THEN 'SOUR3'
				WHEN EMISS.ORIGEM_SCP2_EMSS LIKE '%DQS1%' OR EMISS.ORIGEM_SCP2_EMSS LIKE '%DQS2%' THEN 'SOUR1'
				ELSE 'SOUR2'
			END AS SOURCE_EMISSION_2,
			CASE 
				WHEN EMISS.ORIGEM_SCP3_EMSS IN ('MISS','Nao Aplicavel') THEN 'SOUR3'
				WHEN EMISS.ORIGEM_SCP3_EMSS LIKE '%DQS1%' OR EMISS.ORIGEM_SCP3_EMSS LIKE '%DQS2%' THEN 'SOUR1'
				ELSE 'SOUR2'
			END AS SOURCE_EMISSION_3,
			CASE
				WHEN CPAIS_RESIDENCIA IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428')
					THEN 'EU1'
				WHEN CPAIS_RESIDENCIA NOT IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428','')
					THEN 'EU2'
				ELSE '' 
			END AS EUROPEAN_UNION,
            SUM(CAST(EMISS.AMOUNT AS DECIMAL (38,6)))*-1 AS AMOUNT,
            SUM(CAST(EMISS.SCP1_EMSS_FNCD AS DECIMAL (38,16))) AS GESI,
            SUM(CAST(EMISS.SCP2_EMSS_FNCD AS DECIMAL (38,16))) AS GESII,
            SUM(CAST(EMISS.SCP3_EMSS_FNCD AS DECIMAL (38,16))) AS GESIII
        FROM
        -- TABELA DE UNIVERSO
        (
        	SELECT 
        	DISTINCT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,BRUTO_IMPARIDADE,STAGES,CONTRAPARTE,NON_PERFORMING,DATA_VENCIMENTO,PRODUTO,INSTRUMENTO_FINANCEIRO,TIPO_COLATERAL,CPAIS_RESIDENCIA
        	FROM BU_ESG_WORK.P3_FULL_CTR_CLI_LOCAL_DEZ24_V4 
        	WHERE TEMPLATE1 = 1 AND
        		  DT_RFRNC = '${REF_DATE}' AND BRUTO_IMPARIDADE = 'valor bruto'
        ) UNIVERSO
        
        LEFT JOIN 
        (   
            SELECT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,ZCLIENTE,ORIGEM_SCP1_EMSS, ORIGEM_SCP2_EMSS, ORIGEM_SCP3_EMSS,SUM(AMOUNT) AS AMOUNT,SUM(SCP1_EMSS_FNCD) AS SCP1_EMSS_FNCD,SUM(SCP2_EMSS_FNCD) AS SCP2_EMSS_FNCD,SUM(SCP3_EMSS_FNCD) AS SCP3_EMSS_FNCD
            FROM BU_ESG_WORK.MODESG_OUT_EMSS_FNCD
            WHERE REF_DATE='${REF_DATE}'
            GROUP BY 1,2,3,4,5,6,7,8
        ) EMISS
        ON  UNIVERSO.CEMPRESA = EMISS.CEMPRESA AND
            UNIVERSO.CBALCAO  = EMISS.CBALCAO AND
            UNIVERSO.CNUMECTA = EMISS.CNUMECTA AND
            UNIVERSO.ZDEPOSIT = EMISS.ZDEPOSIT 

        GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
    ) BRUTO
    GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
    UNION ALL
    SELECT
    	B.ZCLIENTE, --AJUSTAR QUANDO TIVERMOS A NOVA TABELA DE UNIVERSO
    	UNIVERSO.CEMPRESA,
    	UNIVERSO.CBALCAO,
    	UNIVERSO.CNUMECTA,
    	UNIVERSO.ZDEPOSIT,
        BRUTO_IMPARIDADE AS VB_IMP, 
        CONTRAPARTE,
        STAGES,
        NON_PERFORMING,
        DATA_VENCIMENTO,
        PRODUTO,
        INSTRUMENTO_FINANCEIRO,
        TIPO_COLATERAL,
        NULL AS SOURCE_EMISSION_1,
		NULL AS SOURCE_EMISSION_2,
		NULL AS SOURCE_EMISSION_3,
		CASE
			WHEN CPAIS_RESIDENCIA IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428')
				THEN 'EU1'
			WHEN CPAIS_RESIDENCIA NOT IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428','')
				THEN 'EU2'
			ELSE '' 
		END AS EUROPEAN_UNION,
    	SUM(MSALDO_FINAL)*-1 AS ASCI,
    	NULL AS GESI,
    	SUM(MSALDO_FINAL)*-1 AS ASC2,
    	NULL AS GESII,
    	SUM(MSALDO_FINAL)*-1 AS ASCIII,
    	NULL AS GESIII
    FROM BU_ESG_WORK.P3_FULL_CTR_CLI_LOCAL_DEZ24_V4 UNIVERSO
    LEFT JOIN 
    (
    	SELECT DISTINCT CEMPRESA, CBALCAO, CNUMECTA, ZDEPOSIT, ZCLIENTE
    	FROM BU_ESG_WORK.P3_REPARTICAO_GARANTIAS_LOCAL_DEZ24
    	WHERE DT_RFRNC='${REF_DATE}' AND 
    	      ID_CORRIDA IN (SELECT MAX(ID_CORRIDA) FROM BU_ESG_WORK.P3_REPARTICAO_GARANTIAS_LOCAL_DEZ24 WHERE DT_RFRNC = '${REF_DATE}') 
    )AS B
    ON  UNIVERSO.CEMPRESA = B.CEMPRESA AND 
    	UNIVERSO.CBALCAO  = B.CBALCAO  AND 
    	UNIVERSO.CNUMECTA = B.CNUMECTA AND 
    	UNIVERSO.ZDEPOSIT = B.ZDEPOSIT
    WHERE TEMPLATE1 = 1 AND
    	  DT_RFRNC = '${REF_DATE}' AND BRUTO_IMPARIDADE = 'imparidade'
    GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,17
) UNIVERSO
LEFT JOIN (SELECT * FROM BU_ESG_WORK.MODESG_OUT_EMPR_INFO_NFIN WHERE REF_DATE='${REF_DATE}') NFIN
ON UNIVERSO.ZCLIENTE = NFIN.ZCLIENTE 

LEFT JOIN (SELECT * FROM BU_ESG_WORK.MODESG_OUT_SFICS_TAXON_EUROPEIA WHERE REF_DATE='${REF_DATE}') SFICS
ON  UNIVERSO.CEMPRESA = SFICS.CEMPRESA AND
    UNIVERSO.CBALCAO  = SFICS.CBALCAO AND
    UNIVERSO.CNUMECTA = SFICS.CNUMECTA AND
    UNIVERSO.ZDEPOSIT = SFICS.ZDEPOSIT

LEFT JOIN
(
	SELECT NVL(MAX(ID_CORRIDA),0)+1 AS NEW_ID_CORRIDA
	FROM BU_ESG_WORK.AG01_TEMP_CTO_GRA
	WHERE REF_DATE = '${REF_DATE}'
) RT
ON  1=1

GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 16, 17, 18, 20, 21, 22, 23, 24, 25
;


/*=========================================================================================================================================*/
/*  2. TABELA FINAL: OBTENÇÃO DAS MÉTRICAS AGREGADAS A REPORTAR NO ÂMBITO DO TEMPLATE 1                  							       */
/*=========================================================================================================================================*/

-- INSERT OVERWRITE BU_ESG_WORK.AG01_TEMP_CTO_AGR PARTITION (ID_CORRIDA,REF_DATE)
SELECT  X.STAGE,
        X.CONTRAPARTE,
        X.VB_IMP,
        X.EXCLUDED_PARIS,
        X.MATURITY,
        X.COD_NACE_ESG,
        X.ASCI,
        X.GESI,
        X.ASC2,
        X.GESII,
        X.ASCIII,
        X.GESIII,
        X.FLAG_NFRD,
        X.SUSTAINABLE_CCM,
		CASE 
			WHEN VB_IMP = 'valor bruto' AND MATURITY > 0 THEN MATURITY*ASCI				
			ELSE NULL
		END AS AVEG_AUX,
		SOURCE_EMISSION_1,
        SOURCE_EMISSION_2,
        SOURCE_EMISSION_3,

		-- PARTICAO
		RT.NEW_ID_CORRIDA AS ID_CORRIDA,
		'${REF_DATE}' AS REF_DATE
FROM
(
	SELECT
		STAGE,
        CONTRAPARTE,
        VB_IMP,
        EXCLUDED_PARIS,
        ROUND(YEARS_TO_MATURITY,0) AS MATURITY,
        COD_NACE_ESG,
        ROUND(SUM(ASCI),2) AS ASCI,
        ROUND(SUM(GESI),2) AS GESI,
        ROUND(SUM(ASC2),2) AS ASC2,
        ROUND(SUM(GESII),2) AS GESII,
        ROUND(SUM(ASCIII),2) AS ASCIII,
        ROUND(SUM(GESIII),2) AS GESIII,
        FLAG_NFRD,
        ROUND(SUM(SUSTAINABLE_CCM),2) AS SUSTAINABLE_CCM,
        SOURCE_EMISSION_1,
        SOURCE_EMISSION_2,
        SOURCE_EMISSION_3
        
	FROM 
	(	
		SELECT * FROM BU_ESG_WORK.AG01_TEMP_CTO_GRA
		WHERE REF_DATE = '${REF_DATE}' 
			AND ID_CORRIDA IN (SELECT MAX(ID_CORRIDA) FROM BU_ESG_WORK.AG01_TEMP_CTO_GRA WHERE REF_DATE = '${REF_DATE}')
	) AUX  GROUP BY 1,2,3,4,5,6,13,15,16,17
) X 
LEFT JOIN
(
	SELECT NVL(MAX(ID_CORRIDA),0)+1 AS NEW_ID_CORRIDA
	FROM BU_ESG_WORK.AG01_TEMP_CTO_AGR
	WHERE REF_DATE = '${REF_DATE}'
) RT
ON 1=1
;