INSERT OVERWRITE TABLE BU_CAPTOOLS_WORK.SIMUL_LT004 PARTITION (ID_CORRIDA,REF_DATE)

SELECT 

    PRTCTN_ID 

    ,'0001-01-01' AS DT_MTRTY_PRTCTN
    
    ,PRTCTN_PRVDR_ID
        
    ,CASE
        WHEN TRIM(TIPOLOGIA) = 'PES' THEN 'Unsecured'
        WHEN TRIM(TIPOLOGIA) <> 'PES' THEN 'Secured'
        END AS FLG_SCRD
        
    ,RT.NEW_ID_CORRIDA AS ID_CORRIDA
    
     ,'${REF_DATE}' AS REF_DATE    

FROM 

--TABELA DE UNIVERSO
    (
    SELECT DISTINCT 
        PRTCTN_ID, 
        REPLACE(REPLACE(PRTCTN_ID, 'P', ''), '_', '') AS PRCTCN_ID_CLEAN,
        STRRIGHT(PRTCTN_ID,10) AS PRTCTN_PRVDR_ID
    FROM 
        (
        SELECT 
            INSTRMNT_ID
        FROM BU_CAPTOOLS_WORK.SIMUL_LT002_INSTRUMENT
        WHERE REF_DATE = '${REF_DATE}' AND ID_CORRIDA IN (SELECT MAX(ID_CORRIDA) FROM BU_CAPTOOLS_WORK.SIMUL_LT002_INSTRUMENT WHERE REF_DATE ='${REF_DATE}')
        )LT002
    LEFT JOIN

        (
        SELECT 
            CEMPRESA,
            CBALCAO,
            CNUMECTA,
            ZDEPOSIT,
            CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) AS CHAVE_IC,
            CONCAT(CEMPRESA_FR,CBALCAO_FR,CNUMECTA_FR,ZDEPOSIT_FR) AS CHAVE_FR
        FROM CD_CAPTOOLS.KT_CHAVES_FINREP
        WHERE REF_DATE = '${REF_DATE}'
        )KT_FR ON INSTRMNT_ID = CHAVE_FR

    INNER JOIN
        (
        SELECT 
            CKBALCAO,
            CKNUMCTA,
            COMP_ID_GAR,
            CKBALRES,
            CKCTARES,
            CKREFRESP,
            TIPOLOGIA AS TIPOLOGIA_GT018,
            CONCAT(CKBALCAO,CKNUMCTA,COMP_ID_GAR) AS CHAVE_PROC,
            CONCAT(CKBALRES,CKCTARES,CKREFRESP) AS CHAVE_RESP,
            CONCAT(SUBSTRING(TIPOLOGIA,1,1),'_',CKBALBEM,'_',CKCTABEM,'_',CKREFBEM) AS PRTCTN_ID
        FROM CD_GARANTIAS.GT018_RATEIO_AVAL
        WHERE REF_DATE = '${REF_DATE}'
            AND TIPOLOGIA = 'PES'
        )GT018 ON CBALCAO = CKBALRES AND CNUMECTA = CKCTARES AND ZDEPOSIT = CKREFRESP
    )UNIV --6

--OBTENÇÃO DO CAMPO "TIPOLOGIA" DA GT018_RATEIO_AVAL
LEFT JOIN
    (
    SELECT DISTINCT
        CONCAT(CKBALBEM,CKCTABEM, CKREFBEM) AS CHAVE_GARANTIA_GT018,
        TIPOLOGIA
    FROM CD_GARANTIAS.GT018_RATEIO_AVAL
    WHERE REF_DATE = '${REF_DATE}'
    )GT018 ON PRCTCN_ID_CLEAN = CHAVE_GARANTIA_GT018

-- PARTIÇÃO DA TABELA 

LEFT JOIN 
    (
    SELECT NVL(MAX(ID_CORRIDA),0)+1 AS NEW_ID_CORRIDA
    FROM BU_CAPTOOLS_WORK.SIMUL_LT004
    WHERE REF_DATE = '${REF_DATE}'
    )RT ON 1=1 
;


/*=========================================================================================================================================*/
/*  AUX. Criação da tabela                                                                             			                           */
/*=========================================================================================================================================*/

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.SIMUL_LT004;

INVALIDATE METADATA BU_CAPTOOLS_WORK.SIMUL_LT004;

CREATE TABLE BU_CAPTOOLS_WORK.SIMUL_LT004  
(

    PRTCTN_ID STRING,
    DT_MTRTY_PRTCTN STRING,
    PRTCTN_PRVDR_ID STRING,
    FLG_SCRD STRING
)
PARTITIONED BY (ID_CORRIDA BIGINT, REF_DATE STRING);