/********************************************************************************************************************************************
****   Projeto: Implementação Templates Locais                                                                     						 ****
****   Autor: BS & Neyond                                                                                                                ****
****   Data: 18/06/2025                                                                                                                  ****
****   SQL Script Descrição: Geração do Template 6,7,8,9 																				 ****
****  ( Summary of KPIs on the Taxonomy-aligned exposures )                                      										 ****
****  ( Mitigating actions: Assets for the calculation of GAR )                                      									 ****
****  ( GAR (%) )                                      										 											 ****
****  ( Mitigating actions: BTAR )                                      																 ****
********************************************************************************************************************************************/

/*=========================================================================================================================================*/
/*  1. Tabela granular: Obtenção do universo a reportar no âmbito do Template 6,7,8,9 + Marcação de metricas relevantes       			   */
/*=========================================================================================================================================*/ 

-- INSERT OVERWRITE TABLE BU_ESG_WORK.AG07_TEMP_CTO_GRA PARTITION (ID_CORRIDA,REF_DATE)
SELECT X.*,
    -- PARTICAO
	RT.NEW_ID_CORRIDA AS ID_CORRIDA,
	'${REF_DATE}' AS REF_DATE
FROM 
(
    SELECT 
        UNI.CEMPRESA,
        UNI.CBALCAO,
        UNI.CNUMECTA,
        UNI.ZDEPOSIT,
        UNI.ZCLIENTE,
        INSTRUMENTO_FINANCEIRO,
        CARTEIRA_CONTABILISTICA,
        CONTRAPARTE,
        TIPO_COLATERAL,
        ORIGINATED_DURING_PERIOD,
        FLG_SAT84,
    
        CASE
            WHEN (CCONTAB_FINAL_IDCOMB LIKE '%SC0302%' OR CCONTAB_FINAL_IDCOMB LIKE '%SC0303%') -- 'OUTRAS INSTITUICOES FINANCEIRAS','OUTRAS EMPRESAS NAO FINANCEIRAS'
                AND NFIN.FLG_CSRD = 1
            THEN 'Subject to CSRD'
            
            WHEN CCONTAB_FINAL_IDCOMB LIKE '%MC08%' AND -- JOIN VENTURES
                UPPER(CONTRAPARTE) IN ('OUTRAS INSTITUICOES FINANCEIRAS','OUTRAS EMPRESAS NAO FINANCEIRAS','INSTITUICOES DE CREDITO') AND
                NFIN.FLG_CSRD = 1
            THEN 'Subject to CSRD'   
            
            WHEN CCONTAB_FINAL_IDCOMB LIKE '%SC02%' -- 'INSTITUICOES DE CREDITO'
                AND NFIN.FLG_CSRD = 1
            THEN 'Subject to CSRD'                         
            
            WHEN (CCONTAB_FINAL_IDCOMB LIKE '%SC0302%' OR CCONTAB_FINAL_IDCOMB LIKE '%SC0303%')
                AND (NFIN.FLG_CSRD <> 1 OR NFIN.FLG_CSRD IS NULL)
            THEN 'Not Subject to CSRD'
            
            WHEN CCONTAB_FINAL_IDCOMB LIKE '%MC08%'
                AND UPPER(CONTRAPARTE) IN ('OUTRAS INSTITUICOES FINANCEIRAS','OUTRAS EMPRESAS NAO FINANCEIRAS','INSTITUICOES DE CREDITO')
                AND (NFIN.FLG_CSRD <> 1 OR NFIN.FLG_CSRD IS NULL)
            THEN 'Not Subject to CSRD' 
            
            WHEN CCONTAB_FINAL_IDCOMB LIKE '%SC02%'
                AND (NFIN.FLG_CSRD <> 1 OR NFIN.FLG_CSRD IS NULL) 
            THEN 'Not Subject to CSRD'             
            
            -- TODAS AS SC02/SC0302/SC0303 DEVERÃO TER MARCAÇÃO DE NFRD (POR ISSO TUDO O QUE NÃO CAI NO SUJEITO SERÁ NÃO SUJEITO)
            WHEN (CCONTAB_FINAL_IDCOMB LIKE '%SC0302%' OR CCONTAB_FINAL_IDCOMB LIKE '%SC0303%' OR CCONTAB_FINAL_IDCOMB LIKE '%SC02%') THEN 'Not Subject to CSRD'                
            
            WHEN CCONTAB_FINAL_IDCOMB LIKE '%MC08%' AND UPPER(CONTRAPARTE) IN ('OUTRAS INSTITUICOES FINANCEIRAS','OUTRAS EMPRESAS NAO FINANCEIRAS','INSTITUICOES DE CREDITO') THEN 'Not Subject to CSRD'                       
            
            ELSE ''
        END AS FLAG_CSRD,
    
        SUM(AMOUNT) AS AMOUNT,
    
        CASE 
            WHEN CCONTAB_FINAL_IDCOMB LIKE '%MC42%' OR CCONTAB_FINAL_IDCOMB LIKE '%MC43%' THEN '' -- Off balance
            WHEN CCONTAB_FINAL_IDCOMB LIKE '%MC13%' THEN '' 
            WHEN CCONTAB_FINAL_IDCOMB LIKE '%SC0301%' AND UPPER(CONTRAPARTE) = 'SETOR PUBLICO' 
                 AND CNATUREZA_JURI IN ('121100','121210','121220','211110','211120','211130','221100','221210','121231') THEN ''
            ELSE SFICS.NOME_PURPOSE_ESG_ALINH_TAX
        END AS NOME_PURPOSE_ESG_ALINH_TAX,
    
        CASE
            WHEN CCONTAB_FINAL_IDCOMB LIKE '%MC42%' OR CCONTAB_FINAL_IDCOMB LIKE '%MC43%' THEN '' -- Loan commitments given e Other commitments given
            WHEN CCONTAB_FINAL_IDCOMB LIKE '%MC13%' THEN ''
            ELSE SFICS.NOME_GENERAL_SPECIFIC_PURPOSE
        END AS NOME_GENERAL_SPECIFIC_PURPOSE,
    
        CASE
            WHEN CCONTAB_FINAL_IDCOMB LIKE '%MC42%' OR CCONTAB_FINAL_IDCOMB LIKE '%MC43%' THEN '' -- Loan commitments given e Other commitments given
            WHEN CCONTAB_FINAL_IDCOMB LIKE '%MC13%' THEN ''
            ELSE SFICS.NOME_SPECIFIC_ELIGIBLE
        END AS NOME_SPECIFIC_ELIGIBLE,
    
        CASE
            WHEN CCONTAB_FINAL_IDCOMB LIKE '%MC42%' OR CCONTAB_FINAL_IDCOMB LIKE '%MC43%' THEN '' -- Loan commitments given e Other commitments given
            WHEN CCONTAB_FINAL_IDCOMB LIKE '%MC13%' THEN ''
            ELSE SFICS.NOME_SPECIFIC_SUSTAINABLE
        END AS NOME_SPECIFIC_SUSTAINABLE,
    
        CASE
            WHEN (CCONTAB_FINAL_IDCOMB LIKE '%SC0301%' OR UPPER(CONTRAPARTE) = 'SETOR PUBLICO') AND 
                CNATUREZA_JURI IN ('121100','121210','121220','211110','211120','211130','221100','221210','121231') THEN 'Sovereigns'  --- LISTA PARA DEFINIR SOVEREINGS PARTILHADA POR LUÍSA E DADA POR CAPITAL
            WHEN (CCONTAB_FINAL_IDCOMB LIKE '%SC0301%' OR UPPER(CONTRAPARTE) = 'SETOR PUBLICO') THEN 'Local Governments' 
            WHEN (CCONTAB_FINAL_IDCOMB LIKE '%SC0301%' OR UPPER(CONTRAPARTE) = 'SETOR PUBLICO') THEN 'Local Governments'
            WHEN (CCONTAB_FINAL_IDCOMB LIKE '%SC0302%' OR UPPER(CONTRAPARTE) = 'OUTRAS INSTITUICOES FINANCEIRAS' ) AND COD_NACE_ESG IN ('K65.3.0','K66.1.1','K64.3.0','K66.1.2','K66.3.0')    ---  MAPEAMENTO EM REVISÃO POR BUZÓN MAS MANTER PARA PILOTO JUN23
                    THEN 'Investment firms'
            WHEN (CCONTAB_FINAL_IDCOMB LIKE '%SC0302%' OR UPPER(CONTRAPARTE) = 'OUTRAS INSTITUICOES FINANCEIRAS') AND COD_NACE_ESG IN ('K66.1.9','K64.2.0')   ---  MAPEAMENTO EM REVISÃO POR BUZÓN MAS MANTER PARA PILOTO JUN23
                THEN 'Management firms'          
            WHEN (CCONTAB_FINAL_IDCOMB LIKE '%SC0302%' OR UPPER(CONTRAPARTE) = 'OUTRAS INSTITUICOES FINANCEIRAS' ) AND COD_NACE_ESG IN ('K65.1.1','K65.1.2','K65.2.0', 'K66.2.1','K66.2.2','K66.2.9')    ---  MAPEAMENTO EM REVISÃO POR BUZÓN MAS MANTER PARA PILOTO JUN23
                THEN 'Insurance undertakings'          
            WHEN (CCONTAB_FINAL_IDCOMB LIKE '%SC0302%' OR UPPER(CONTRAPARTE) = 'OUTRAS INSTITUICOES FINANCEIRAS') THEN 'Rest of other financial corporation'
            WHEN (CCONTAB_FINAL_IDCOMB LIKE '%SC0302%' AND UPPER(CONTRAPARTE) = 'INSTITUICOES DE CREDITO')  AND COD_NACE_ESG IN ('K64.1.1','K64.1.9','K64.9.1','K64.9.2','K64.9.9') 
                THEN 'Rest of other financial corporation' ---  MAPEAMENTO EM REVISÃO POR BUZÓN MAS MANTER PARA PILOTO JUN23
            WHEN (CCONTAB_FINAL_IDCOMB LIKE '%MC08%' AND UPPER(CONTRAPARTE) = 'OUTRAS INSTITUICOES FINANCEIRAS') THEN 'Rest of other financial corporation'
            ELSE '' 
        END AS ESG_SUBSECTOR_NAME,  
        
        -- MAPEAMENTO DA FLAG DE EUROPEAN UNION: SÓ É APLICÁVEL PARA OS CASOS QUE SÃO NON-FINANCIAL CORPORATIONS E QUE NÃO SÃO SUJEITOS A FLAG NFRD 
        CASE 
            WHEN 
                (NFIN.FLG_CSRD <> 1 OR NFIN.FLG_CSRD IS NULL) AND 
                (CCONTAB_FINAL_IDCOMB LIKE '%SC0302%' OR CCONTAB_FINAL_IDCOMB LIKE '%SC0303%') AND 
                EUROPEAN_UNION = 'Y' 
            THEN 'EU1' 
            WHEN 
                (NFIN.FLG_CSRD <> 1 OR NFIN.FLG_CSRD IS NULL) AND 
                CCONTAB_FINAL_IDCOMB LIKE '%MC08%' AND
                UPPER(CONTRAPARTE) IN ('OUTRAS INSTITUICOES FINANCEIRAS','OUTRAS EMPRESAS NAO FINANCEIRAS','INSTITUICOES DE CREDITO') AND
                EUROPEAN_UNION = 'Y' 
            THEN 'EU1' 
            WHEN 
                (NFIN.FLG_CSRD <> 1 OR NFIN.FLG_CSRD IS NULL) AND 
                CCONTAB_FINAL_IDCOMB LIKE '%MC41%' AND
                UPPER(CONTRAPARTE) IN ('OUTRAS INSTITUICOES FINANCEIRAS','OUTRAS EMPRESAS NAO FINANCEIRAS','INSTITUICOES DE CREDITO') AND
                EUROPEAN_UNION = 'Y' 
            THEN 'EU1'    
            WHEN 
                (NFIN.FLG_CSRD <> 1 OR NFIN.FLG_CSRD IS NULL) AND 
                CCONTAB_FINAL_IDCOMB LIKE '%SC02%' AND
                EUROPEAN_UNION = 'Y' 
            THEN 'EU1'           	         	   
            WHEN 
                (NFIN.FLG_CSRD <> 1 OR NFIN.FLG_CSRD IS NULL) AND 
                (CCONTAB_FINAL_IDCOMB LIKE '%SC0302%' OR CCONTAB_FINAL_IDCOMB LIKE '%SC0303%') AND 
                EUROPEAN_UNION = 'N'  
            THEN 'EU2' 
            WHEN 
                (NFIN.FLG_CSRD <> 1 OR NFIN.FLG_CSRD IS NULL) AND 
                CCONTAB_FINAL_IDCOMB LIKE '%MC08%' AND
                UPPER(CONTRAPARTE) IN ('OUTRAS INSTITUICOES FINANCEIRAS','OUTRAS EMPRESAS NAO FINANCEIRAS','INSTITUICOES DE CREDITO') AND
                EUROPEAN_UNION = 'N' 
            THEN 'EU2'    		
            WHEN 
                (NFIN.FLG_CSRD <> 1 OR NFIN.FLG_CSRD IS NULL) AND 
                CCONTAB_FINAL_IDCOMB LIKE '%MC41%' AND
                UPPER(CONTRAPARTE) IN ('OUTRAS INSTITUICOES FINANCEIRAS','OUTRAS EMPRESAS NAO FINANCEIRAS','INSTITUICOES DE CREDITO') AND
                EUROPEAN_UNION = 'N' 
            THEN 'EU2'   
            WHEN 
                (NFIN.FLG_CSRD <> 1 OR NFIN.FLG_CSRD IS NULL) AND 
                CCONTAB_FINAL_IDCOMB LIKE '%SC02%' AND
                EUROPEAN_UNION = 'N' 
            THEN 'EU2'            	                	               
            ELSE '' 
        END AS EUROPEAN_UNION,
    
        CASE
            WHEN CCONTAB_FINAL_IDCOMB LIKE '%MC42%' OR CCONTAB_FINAL_IDCOMB LIKE '%MC43%' THEN '' -- Loan commitments given e Other commitments given
            WHEN CCONTAB_FINAL_IDCOMB LIKE '%MC13%' THEN ''
            WHEN CONTRAPARTE NOT IN ('outras empresas nao financeiras') THEN '' -- REGRA DEFINIDA COM BASE NAS COMBINAÇÕES POSSÍVEIS DE IDCOMBS
            WHEN SFICS.NOME_SPECIFIC_SUSTAINABLE = 'No' THEN ''   -- REGRA DEFINIDA COM BASE NAS COMBINAÇÕES POSSÍVEIS DE IDCOMBS
            WHEN SFICS.NOME_SPECIFIC_ELIGIBLE = 'No' then '' -- REGRA DEFINIDA COM BASE NAS COMBINAÇÕES POSSÍVEIS DE IDCOMBS
            WHEN NFIN.FLG_CSRD NOT IN (0,1) OR NFIN.FLG_CSRD IS NULL THEN '' -- REGRA DEFINIDA COM BASE NAS COMBINAÇÕES POSSÍVEIS DE IDCOMBS
            WHEN FLAG_PROJECT_FINANCE = '0' AND TRIM(UPPER(SFICS.NOME_PURPOSE_ESG_ALINH_TAX)) = 'BUILNDING ACQUISITION' THEN '' -- REGRA DEFINIDA COM BASE NAS COMBINAÇÕES POSSÍVEIS DE IDCOMBS                 
            WHEN FLAG_PROJECT_FINANCE = '1' AND TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'SPECIFIC PURPOSE' THEN 'Y' -- REGRA DEFINIDA COM BASE NAS COMBINAÇÕES POSSÍVEIS DE IDCOMBS
            WHEN FLAG_PROJECT_FINANCE = '0' AND TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'SPECIFIC PURPOSE' THEN 'N' -- REGRA DEFINIDA COM BASE NAS COMBINAÇÕES POSSÍVEIS DE IDCOMBS 
            WHEN TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'GENERAL PURPOSE' THEN '' -- REGRA DEFINIDA COM BASE NAS COMBINAÇÕES POSSÍVEIS DE IDCOMBS
            ELSE ''
        END AS SPECIALISED_LENDING,
    
        CASE WHEN TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'GENERAL PURPOSE' THEN NVL(AMOUNT * NFIN.CCM_TRNVR_TTL_ELGBL/100,0) END AS TUCCM,
        CASE WHEN TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'GENERAL PURPOSE' THEN NVL(AMOUNT * NFIN.CCM_TRNVR_OWN_PRFRMNCE_ALGND/100,0) END AS ETCCM,
        CASE WHEN TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'GENERAL PURPOSE' THEN NVL(AMOUNT * NFIN.CCM_TRNVR_TRNSTN_ALIGND/100,0) END AS TRANT,
        CASE WHEN TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'GENERAL PURPOSE' THEN NVL(AMOUNT * NFIN.CCM_TRNVR_ENBLNG_ALGND/100,0) END AS ENTCCM,
        CASE WHEN TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'GENERAL PURPOSE' THEN NVL(AMOUNT * NFIN.CCA_TRNVR_TTL_ELGBL/100,0) END AS TUCCA,
        CASE WHEN TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'GENERAL PURPOSE' THEN NVL(AMOUNT * NFIN.CCA_TURNOVER_OWN_PRFRMNCE_ALGND/100,0) END AS ETCCA,
        CASE WHEN TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'GENERAL PURPOSE' THEN NVL(AMOUNT * NFIN.CCA_TRNVR_ENBLNG_ALIGND/100,0) END AS ENTCCA
    FROM
    -- TABELA DE UNIVERSO
    (
        SELECT CEMPRESA, CBALCAO, CNUMECTA, ZDEPOSIT, ZCLIENTE, INSTRUMENTO_FINANCEIRO, CARTEIRA_CONTABILISTICA,CONTRAPARTE, CCONTAB_FINAL_IDCOMB,TIPO_COLATERAL, CNATUREZA_JURI, FLAG_PROJECT_FINANCE,
                CASE 
                    WHEN DATA_ABERTURA >= '${REF_DATE_INI}' THEN 'Y'		-- No reporte de junho 2024 foi utilizada a data 2024-01-01.
                    ELSE 'N'
                END AS ORIGINATED_DURING_PERIOD, 
                CASE WHEN UPPER(INSTRUMENTO_FINANCEIRO)   IN ('CREDITO CONCEDIDO E OUTROS ATIVOS FINANCEIROS',  
                                                    'INSTRUMENTOS DE DIVIDA', 
                                                    'INSTRUMENTOS DE CAPITAL')
                            AND UPPER(CARTEIRA_CONTABILISTICA) IN 
                                                ('ATIVOS FINANCEIROS MANDATORIAMENTE AO JUSTO VALOR ATRAVES DE RESULTADOS', 
                                                    'ATIVOS FINANCEIROS AO JUSTO VALOR ATRAVES DE RESULTADOS',
                                                    'ATIVOS FINANCEIROS AO CUSTO AMORTIZADO',
                                                    'ATIVOS FINANCEIROS AO JUSTO VALOR ATRAVES DE OUTRO RENDIMENTO INTEGRAL',
                                                    --'OUTROS ATIVOS TANGIVEIS',
                                                    'INVESTIMENTOS EM ASSOCIADOS E FILIAIS EXCLUSIVAS DA CONSOLIDACAO')
                    THEN 1 ELSE 0 
                END AS FLG_SAT84,
                CASE  
                    WHEN ZCLIENTE = '0000000000' THEN 'Y'                                                  
                    WHEN CPAIS_RESIDENCIA IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428')
                        THEN 'Y'
                    WHEN CPAIS_RESIDENCIA NOT IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428','')
                        THEN 'N'
                    ELSE '' 
    	        END AS EUROPEAN_UNION, SUM(MSALDO_FINAL)*-1 AS AMOUNT
        FROM BU_CAPTOOLS_WORK.P3_UNIV_LOCAL_CTO
		WHERE TEMPLATE7 = 1 AND REF_DATE = '${REF_DATE}' 
		AND ID_CORRIDA IN (SELECT MAX(ID_CORRIDA) FROM BU_CAPTOOLS_WORK.P3_UNIV_LOCAL_CTO WHERE REF_DATE = '${REF_DATE}')
		AND CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) NOT IN   
			(
			SELECT DISTINCT CHAVE FROM (
				SELECT CONCAT('31','CMAH','IMOVELGIDAP',replace(upper(lpad(COD_IMOVEL,15,'0')),' ', '0')) AS CHAVE
				FROM CD_CAPTOOLS.CT666_ADJUDIC_PROPR
				WHERE REF_DATE='${REF_DATE}'
				AND V_CONTAB_IFRS IN('199100240', '19910000', '1910000', '199100200', '199100210', '19910001', '1910008', '199100201', '199100211', '199100241')
				
				UNION ALL
				
				SELECT CONCAT('89','CMAH','IMOVELIFICS',lpad(n_imovel,15,'0')) AS CHAVE
				FROM CD_CAPTOOLS.CT668_IMOVEIS_IFIC
				WHERE REF_DATE='${REF_DATE}'
				AND V_CONTAB_IFRS IN('199100240', '19910000', '1910000', '199100200', '199100210', '19910001', '1910008', '199100201', '199100211', '199100241')
				
				UNION ALL
				
				SELECT CONCAT('00160','CMAH','IMOVELGIDTU',replace(upper(lpad(COD_IMOVEL,15,'0')),' ', '0')) AS CHAVE
				FROM CD_CAPTOOLS.CT665_STOCK_URBE
				WHERE REF_DATE='${REF_DATE}'
			) X
		)
        GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
    ) UNI
    
    LEFT JOIN 
    (
        SELECT * 
        FROM BU_ESG_WORK.MODESG_OUT_EMPR_INFO_NFIN 
        WHERE REF_DATE='${REF_DATE}'
    ) NFIN
    ON UNI.ZCLIENTE = NFIN.ZCLIENTE
    
    LEFT JOIN (SELECT * FROM BU_ESG_WORK.MODESG_OUT_SFICS_TAXON_EUROPEIA WHERE REF_DATE='${REF_DATE}') SFICS
    ON  UNI.CEMPRESA = SFICS.CEMPRESA AND
        UNI.CBALCAO  = SFICS.CBALCAO AND
        UNI.CNUMECTA = SFICS.CNUMECTA AND
        UNI.ZDEPOSIT = SFICS.ZDEPOSIT
    
    GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21,22,23,24,25,26,27
    
    UNION ALL
    
    -- ADJUDICADOS
    SELECT 
        NULL AS CEMPRESA,
        NULL AS CBALCAO,
        NULL AS CNUMECTA,
        NULL AS ZDEPOSIT,
        NULL AS ZCLIENTE,
        NULL AS INSTRUMENTO_FINANCEIRO,
        NULL AS CARTEIRA_CONTABILISTICA,
        NULL AS CONTRAPARTE,
        'Stock' AS TIPO_COLATERAL,
    	CASE 
            WHEN DATA_AQUISICAO >= '${REF_DATE_INI}' THEN 'Y' -- MAPEAR COM O PRIMEIRO DO DIA DO ANO EM ANÁLISE
            ELSE 'N'
        END AS ORIGINATED_DURING_PERIOD,
        0 AS FLG_SAT84,
        '' AS FLAG_CSRD,
        SUM(V_CONTAB) AS AMOUNT,
        '' AS NOME_PURPOSE_ESG_ALINH_TAX,
        'Specific purpose' AS NOME_GENERAL_SPECIFIC_PURPOSE,
        'No' AS NOME_SPECIFIC_ELIGIBLE,
        '' AS NOME_SPECIFIC_SUSTAINABLE,
        '' AS ESG_SUBSECTOR_NAME,
        '' AS EUROPEAN_UNION,
        '' AS SPECIALISED_LENDING,
        NULL AS TUCCM,
        NULL AS ETCCM,
        NULL AS TRANT,
        NULL AS ENTCCM,
        NULL AS TUCCA,
        NULL AS ETCCA,
        NULL AS ENTCCA
    FROM
    (
    SELECT
        V_CONTAB, 
        DATA_AQUISICAO
    FROM CD_CAPTOOLS.CT666_ADJUDIC_PROPR
    WHERE REF_DATE='${REF_DATE}'
    AND V_CONTAB_IFRS IN('199100240', '19910000', '1910000', '199100200', '199100210', '19910001', '1910008', '199100201', '199100211', '199100241')
    
    UNION ALL
    
    SELECT
        V_CONTAB,
        STRLEFT(CAST(DATE_ADD('1899-12-30', CAST(DATA_ENTRADA AS DECIMAL(12,0))) AS STRING), 10) AS DATA_AQUISICAO
    FROM CD_CAPTOOLS.CT668_IMOVEIS_IFIC
    WHERE REF_DATE='${REF_DATE}'
    AND V_CONTAB_IFRS IN('199100240', '19910000', '1910000', '199100200', '199100210', '19910001', '1910008', '199100201', '199100211', '199100241')
    
    UNION ALL
    
    SELECT
        V_CONTAB,
        DATA_AQUISICAO     
    FROM CD_CAPTOOLS.CT665_STOCK_URBE
    WHERE REF_DATE='${REF_DATE}'
    
    ) ADJUD_INPUTS
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21,22,23,24,25,26,27
) X
LEFT JOIN
(
	SELECT NVL(MAX(ID_CORRIDA),0)+1 AS NEW_ID_CORRIDA
	FROM BU_ESG_WORK.AG07_TEMP_CTO_GRA
	WHERE REF_DATE = '${REF_DATE}'
) RT
ON  1=1
