
/********************************************************************************************************************************************
****   Projeto: Convergência de Calculadora de Emissões Financiadas                                                              	     ****
****   Autor: BS & Neyond                                                                                                                ****
****   Data: 12/01/2026                                                                                                                  ****
****   SQL Script Descrição: Geração da Tabela de Emissões Financiadas  														         ****
********************************************************************************************************************************************/

/*=========================================================================================================================================*/
/*  1. INSERIR DADOS NA TABELA DE EMISSÕES FINANCIADAS COM A RELAÇÃO OPERAÇÃO/IMÓVEL                                                       */
/*=========================================================================================================================================*/

INSERT OVERWRITE TABLE BU_CAPTOOLS_WORK.PA_OUT_EMSS_FNCD PARTITION (REF_DATE)

WITH AUXILIAR_CALCULO AS 
(
	-- PROCESSO AUXILIAR AO CÁLCULO DAS EMISSÕES FINANCIADAS 
    SELECT 
        CT004.*,
        BENS.PROPERTY_BANK_ID AS CEMPBEM,
        BENS.PROPERTY_BRANCH_CODE AS CKBALBEM,
        BENS.PROPERTY_CONTRACT_ID AS CKCTABEM,
        BENS.PROPERTY_REFERENCE_CODE AS CKREFBEM,
        CT001.NOME_PERIMETRO,
        CT001.SUM_MSALDO_FINAL_CT,
        GT018_PA.PRECO_AQUISICAO,
        GT018_AGR.SUM_CTO_BEM_MAVALIA,
        GT018_AGR.SUM_CTO_BEM_MAVALIAA,
        SUM(GT018_AGR.SUM_CTO_BEM_MAVALIAA) OVER (PARTITION BY CONCAT(CT004.CEMPRESA ,CT004.CBALCAO ,CT004.CNUMECTA ,CT004.ZDEPOSIT)) AS SUM_CTO_MAVALIAA,
        SUM (
                CASE 
                    --WHEN GT018_PA.PRECO_AQUISICAO IS NOT NULL THEN GT018_PA.PRECO_AQUISICAO
                    WHEN GT018_AGR.SUM_CTO_BEM_MAVALIA IS NOT NULL THEN GT018_AGR.SUM_CTO_BEM_MAVALIA
                    ELSE GT018_AGR.SUM_CTO_BEM_MAVALIAA
                END
            ) OVER (PARTITION BY CONCAT(CT004.CEMPRESA ,CT004.CBALCAO ,CT004.CNUMECTA ,CT004.ZDEPOSIT)) AS SUM_CTO_IMOVEL_ORIGEM
        
    FROM
	-- OBTER O PROPÓSITO ASSOCIADO A CADA OPERAÇÃO
	
    (
    	SELECT DISTINCT CEMPRESA ,CBALCAO ,CNUMECTA ,ZDEPOSIT ,ZCLIENTE, PURPOSE_CODE
    	FROM CD_CAPTOOLS.CT004_UNIV_CTO
    	WHERE REF_DATE='${REF_DATE}'
    	    AND TRIM(PURPOSE_CODE) IN ('Habitacao','CRE_FC','CRE_OUTRO')
    ) CT004
    
    LEFT JOIN 
    -- OBTER O MONTANTE ASSOCIADO A CADA OPERAÇÃO  
    
    (
    	SELECT *
    	FROM 
    	(
    		SELECT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,NOME_PERIMETRO,SUM(SUM_MSALDO_FINAL_AUX) AS SUM_MSALDO_FINAL_CT
    		FROM 
    		(
    			SELECT *
    				,CASE 
    					WHEN F2.CONTA_1 IS NOT NULL AND F3.CONTA_2 IS NOT NULL THEN 'ST SGPS Cons; Individual Idcomb'
    					WHEN F2.CONTA_1 IS NOT NULL AND F3.CONTA_2 IS NULL THEN 'ST SGPS Cons'
    					WHEN F2.CONTA_1 IS NULL AND F3.CONTA_2 IS NOT NULL THEN 'Individual Idcomb'
    					WHEN F2.CONTA_1 IS NULL AND F3.CONTA_2 IS NULL THEN 'Nao Aplicavel'
    				END AS NOME_PERIMETRO 
    			
    			FROM 
    			(
    				SELECT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT
    					,CCONTAB_FINAL_ST_SGPS
    					,CCONTAB_FINAL_IDCOMB 
    					,SUM(MSALDO_FINAL) AS SUM_MSALDO_FINAL_AUX
    				FROM CD_CAPTOOLS.CT001_UNIV_SALDO
    				WHERE REF_DATE = '${REF_DATE}'
    					AND FLAG_ATIVO=1
    				GROUP BY 1,2,3,4,5,6
    			) F1
    			LEFT JOIN 
    			(
    				SELECT DISTINCT TRIM(CONTA) AS CONTA_1
    				FROM CD_CAPTOOLS.FR802_PL_CONTAS
    				WHERE REF_DATE = '${REF_DATE}'
    					AND TIPO_CONTA = 'A'
    					AND COD_PLANO = 'ST_SGPS_CONS' 
    					AND TRIM(CONTA) <> ''
    					AND TRIM(BRUTO_IMPARIDADE) NOT IN ('imparidade')
    					AND TRIM(CARTEIRA_CONTABILISTICA) NOT IN ('outros ativos - resto')
    			) F2 ON F1.CCONTAB_FINAL_ST_SGPS=F2.CONTA_1
    			LEFT JOIN 
    			(
    				SELECT DISTINCT TRIM(CONTA) AS CONTA_2
    				FROM CD_CAPTOOLS.FR802_PL_CONTAS
    				WHERE REF_DATE = '${REF_DATE}'
    					AND TIPO_CONTA = 'A'
    					AND COD_PLANO = 'BST_IDCOMB' 
    					AND TRIM(CONTA) <> ''
    					AND TRIM(BRUTO_IMPARIDADE) NOT IN ('imparidade')
    					AND TRIM(CARTEIRA_CONTABILISTICA) NOT IN ('outros ativos - resto')
    			) F3 ON F1.ccontab_final_idcomb=F3.CONTA_2 
    		) AUX_1 GROUP BY 1,2,3,4,5
    	) AUX_2 
    ) CT001 
    ON  CT004.CEMPRESA = CT001.CEMPRESA AND
    	CT004.CBALCAO = CT001.CBALCAO AND
    	CT004.CNUMECTA = CT001.CNUMECTA AND
    	CT004.ZDEPOSIT = CT001.ZDEPOSIT
    
    LEFT JOIN 
    -- OBTER O UNIVERSO DE BENS IMÓVEIS  
    
    (
        SELECT DISTINCT S1.BANK_ID, S1.BRANCH_CODE, S1.CONTRACT_ID, S1.REFERENCE_CODE, S2.PROPERTY_BANK_ID , S2.PROPERTY_BRANCH_CODE, S2.PROPERTY_CONTRACT_ID, S2.PROPERTY_REFERENCE_CODE
        FROM 
        (
        	SELECT 
        	    BANK_ID,BRANCH_CODE,CONTRACT_ID,REFERENCE_CODE
        		,PROCESS_BANK_ID,PROCESS_BRANCH_CODE,PROCESS_ACCOUNT_ID,PROCESS_REFERENCE_CODE
        	FROM BUSINESS_ASSETS.RESPONSIBILITY_PROCESS_REL
        	WHERE DATA_DATE_PART='${REF_DATE}'
        )S1
        INNER JOIN 
        (
        	SELECT PROCESS_BANK_ID, PROCESS_BRANCH_CODE, PROCESS_ACCOUNT_ID, PROCESS_REFERENCE_CODE
                ,PROPERTY_BANK_ID , PROPERTY_BRANCH_CODE, PROPERTY_CONTRACT_ID, PROPERTY_REFERENCE_CODE
        	FROM BUSINESS_ASSETS.PROCESS_PROPERTY_REL
        	WHERE DATA_DATE_PART='${REF_DATE}'
        		AND COLLATERAL_PROPERTY_IND=1
        )S2 
        ON  S1.PROCESS_BANK_ID = S2.PROCESS_BANK_ID AND
            S1.PROCESS_BRANCH_CODE = S2.PROCESS_BRANCH_CODE AND
            S1.PROCESS_ACCOUNT_ID = S2.PROCESS_ACCOUNT_ID AND
            S1.PROCESS_REFERENCE_CODE = S2.PROCESS_REFERENCE_CODE 
    ) BENS 
    ON  CT004.CEMPRESA = BENS.BANK_ID AND
    	CT004.CBALCAO = BENS.BRANCH_CODE AND
    	CT004.CNUMECTA = BENS.CONTRACT_ID AND
    	CT004.ZDEPOSIT = BENS.REFERENCE_CODE AND 
        CT001.NOME_PERIMETRO<>'Nao Aplicavel' AND 
        CT001.SUM_MSALDO_FINAL_CT<>0
    
    LEFT JOIN  
	-- OBTER O PREÇO DE AQUISIÇÃO DO IMÓVEL
	
    (
        SELECT DISTINCT CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM,PRECO_AQUISICAO
        FROM CD_GARANTIAS.GT018_RATEIO_AVAL
        WHERE REF_DATE='${REF_DATE}' AND TIPOLOGIA='IMO' AND PRECO_AQUISICAO IS NOT NULL AND PRECO_AQUISICAO<>0
    ) GT018_PA
    ON  BENS.PROPERTY_BANK_ID = GT018_PA.CEMPBEM AND
        BENS.PROPERTY_BRANCH_CODE = GT018_PA.CKBALBEM AND
        BENS.PROPERTY_CONTRACT_ID = GT018_PA.CKCTABEM AND
        BENS.PROPERTY_REFERENCE_CODE = GT018_PA.CKREFBEM        
    
	LEFT JOIN
    -- OBTER O MONTANTE DE AVALIAÇÃO DO IMÓVEL E O MONTANTE DE AVALIAÇÃO DO IMÓVEL RATEADO 
	
	(
        SELECT CEMPRESP,CKBALRES,CKCTARES,CKREFRESP,CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM,SUM(MAVALIA) AS SUM_CTO_BEM_MAVALIA,SUM(MAVALIAA) AS SUM_CTO_BEM_MAVALIAA
        FROM CD_GARANTIAS.GT018_RATEIO_AVAL
        WHERE REF_DATE='${REF_DATE}'
        GROUP BY CEMPRESP,CKBALRES,CKCTARES,CKREFRESP,CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM
    ) GT018_AGR 
    ON  CT004.CEMPRESA = GT018_AGR.CEMPRESP AND
        CT004.CBALCAO = GT018_AGR.CKBALRES AND
        CT004.CNUMECTA = GT018_AGR.CKCTARES AND
        CT004.ZDEPOSIT = GT018_AGR.CKREFRESP AND
        BENS.PROPERTY_BANK_ID = GT018_AGR.CEMPBEM AND
        BENS.PROPERTY_BRANCH_CODE = GT018_AGR.CKBALBEM AND
        BENS.PROPERTY_CONTRACT_ID = GT018_AGR.CKCTABEM AND
        BENS.PROPERTY_REFERENCE_CODE = GT018_AGR.CKREFBEM 
)

SELECT 
    BASE.CEMPRESA,
    BASE.CBALCAO,
    BASE.CNUMECTA,
    BASE.ZDEPOSIT,
    BASE.ZCLIENTE,
    BASE.CEMPBEM,
    BASE.CKBALBEM,
    BASE.CKCTABEM,
    BASE.CKREFBEM,
    BASE.AMOUNT,
    EMSS_IMO.SCP1_EMSS*(CASE WHEN -BASE.SUM_MSALDO_FINAL_CT/BASE.SUM_CTO_IMOVEL_ORIGEM>1 THEN 1 ELSE -BASE.SUM_MSALDO_FINAL_CT/BASE.SUM_CTO_IMOVEL_ORIGEM END) AS SCP1_EMSS_FNCD,
    EMSS_IMO.SCP2_EMSS*(CASE WHEN -BASE.SUM_MSALDO_FINAL_CT/BASE.SUM_CTO_IMOVEL_ORIGEM>1 THEN 1 ELSE -BASE.SUM_MSALDO_FINAL_CT/BASE.SUM_CTO_IMOVEL_ORIGEM END) AS SCP2_EMSS_FNCD,
    EMSS_IMO.ORIGEM_SCP1_EMSS,
    EMSS_IMO.ORIGEM_SCP2_EMSS,
    BASE.NOME_PERIMETRO,
	'${REF_DATE}' AS REF_DATE
    
FROM 
(
    SELECT *,
        CASE
            WHEN CKBALBEM IS NULL OR NOME_PERIMETRO='Nao Aplicavel' OR SUM_MSALDO_FINAL_CT=0 THEN SUM_MSALDO_FINAL_CT
            WHEN SUM_CTO_MAVALIAA<=-SUM_MSALDO_FINAL_CT THEN -SUM_CTO_BEM_MAVALIAA
            ELSE ABS(CAST(SUM_CTO_BEM_MAVALIAA AS DECIMAL(38,18))/CAST(SUM_CTO_MAVALIAA AS DECIMAL(38,18)))*SUM_MSALDO_FINAL_CT
        END AS AMOUNT 
    FROM AUXILIAR_CALCULO
	
UNION ALL 

	-- OBTER LINHAS NÃO COLATERIZADAS ASSOCIADAS A CADA FINANCIAMENTO 
    SELECT DISTINCT 
        CEMPRESA,
        CBALCAO,
        CNUMECTA,
        ZDEPOSIT,
        ZCLIENTE, 
        PURPOSE_CODE,
        NULL AS CEMPBEM,
        NULL AS CKBALBEM,
        NULL AS CKCTABEM,
        NULL AS CKREFBEM,
        NOME_PERIMETRO,
        SUM_MSALDO_FINAL_CT,
        NULL AS PRECO_AQUISICAO,
        NULL AS SUM_CTO_BEM_MAVALIA,
        NULL AS SUM_CTO_BEM_MAVALIAA,
        SUM_CTO_MAVALIAA,
        NULL AS SUM_CTO_IMOVEL_ORIGEM,
        SUM_MSALDO_FINAL_CT+SUM_CTO_MAVALIAA AS AMOUNT
    FROM AUXILIAR_CALCULO
    WHERE SUM_CTO_MAVALIAA<-SUM_MSALDO_FINAL_CT 
        AND NOME_PERIMETRO<>'Nao Aplicavel'
        AND SUM_MSALDO_FINAL_CT<>0
) BASE 

LEFT JOIN 
-- OBTER A COMPONENTE EMISSÕES DO IMÓVEL ASSOCIADO AO CÁLCULO DE EMISSÕES FINANCIADAS 

(
    SELECT *
    FROM BU_CAPTOOLS_WORK.PA_OUT_BENS_IMOVEIS
    WHERE REF_DATE='${REF_DATE}'
) EMSS_IMO 
ON  BASE.CEMPBEM = EMSS_IMO.CEMPBEM AND 
    BASE.CKBALBEM = EMSS_IMO.CKBALBEM AND 
    BASE.CKCTABEM = EMSS_IMO.CKCTABEM AND 
    BASE.CKREFBEM = EMSS_IMO.CKREFBEM

/*=========================================================================================================================================*/
/*  AUX. CRIAÇÃO DA TABELA                    							                                                                   */
/*=========================================================================================================================================*/

-- CREATE TABLE BU_CAPTOOLS_WORK.PA_OUT_EMSS_FNCD
-- (
--     CEMPRESA STRING,	
--     CBALCAO STRING,	
--     CNUMECTA STRING,	
--     ZDEPOSIT STRING,	
--     ZCLIENTE STRING,	
--     CEMPBEM STRING,	
--     CKBALBEM STRING,	
--     CKCTABEM STRING,	
--     CKREFBEM STRING,	
--     AMOUNT DECIMAL(38,24),
--     SCP1_EMSS_FNCD DECIMAL(38,28),
--     SCP2_EMSS_FNCD DECIMAL(38,28),	
--     ORIGEM_SCP1_EMSS STRING,	
--     ORIGEM_SCP2_EMSS STRING,	
--     NOME_PERIMETRO STRING
-- )
-- PARTITIONED BY (REF_DATE STRING)
