
/********************************************************************************************************************************************
****   Projeto: Convergência de Calculadora de Emissões Financiadas                                                              	     ****
****   Autor: BS & Neyond                                                                                                                ****
****   Data: 12/01/2026                                                                                                                  ****
****   SQL Script Descrição: Geração da Tabela de Imóveis (Informação Verde)													         ****
********************************************************************************************************************************************/

/*=========================================================================================================================================*/
/*  1. INSERIR DADOS NA TABELA DE EMISSÕES DO IMÓVEL                                                                                       */
/*=========================================================================================================================================*/

INSERT OVERWRITE TABLE BU_CAPTOOLS_WORK.PA_OUT_BENS_IMOVEIS PARTITION (REF_DATE)

WITH AUXILIAR_CALCULO_1 AS
(
	-- TABELA DE INPUT DE FATORES DE EMISSÃO FILTRADA PARA OBTER OS FATORES ASSOCIADOS A METODOLOGIA FLOOR AREA 
	SELECT *
	FROM BUSINESS_ESG.MODESG_INP_EMSS_BENS_IMOVEIS
	WHERE REF_DATE='${REF_DATE}'
		AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
		AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='FLOOR AREA'
),

AUXILIAR_CALCULO_2 AS 
(
	-- TABELA DE INPUT DE FATORES DE EMISSÃO FILTRADA PARA OBTER OS FATORES ASSOCIADOS A METODOLOGIA NUMBER OF BUILDINGS  
	SELECT *
	FROM BUSINESS_ESG.MODESG_INP_EMSS_BENS_IMOVEIS
	WHERE REF_DATE='${REF_DATE}'
		AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
		AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='DWELLING'
)

SELECT 

	-- CAMPOS IDENTIFICADORES DO BEM IMÓVEL 
	BASE.PROPERTY_BANK_ID AS CEMPBEM,
	BASE.PROPERTY_BRANCH_CODE AS CKBALBEM,
	BASE.PROPERTY_CONTRACT_ID AS CKCTABEM,
	BASE.PROPERTY_REFERENCE_CODE AS CKREFBEM,
	
	-- CÁLCULO DAS EMISSÕES DE SCOPE 1  
	CASE  
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN NULL 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP1_FTR_EMSS IS NOT NULL THEN EMISS_3.SCP1_FTR_EMSS
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP1_FTR_EMSS IS NOT NULL THEN EMISS_4.SCP1_FTR_EMSS
		ELSE NULL
	END AS SCP1_EMSS,
	
	-- CÁLCULO DAS EMISSÕES DE SCOPE 2  
	CASE  
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN NULL 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP2_FTR_EMSS IS NOT NULL THEN EMISS_3.SCP2_FTR_EMSS
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP2_FTR_EMSS IS NOT NULL THEN EMISS_4.SCP2_FTR_EMSS
		ELSE NULL
	END AS SCP2_EMSS,
	
	-- UNIDADE DE MEDIDA DAS EMISSÕES SCOPE 1 
	CASE  
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN NULL 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'tCO2e'
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'tCO2e' 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'tCO2e'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP1_FTR_EMSS IS NOT NULL THEN 'tCO2e'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP1_FTR_EMSS IS NOT NULL THEN 'tCO2e'
		ELSE NULL
	END AS UNIDADE_FUNCIONAL_SCP1_EMSS,
	
	--  UNIDADE DE MEDIDA DAS EMISSÕES SCOPE 2 
	CASE  
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN NULL 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'tCO2e'
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'tCO2e' 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'tCO2e'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP2_FTR_EMSS IS NOT NULL THEN 'tCO2e'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP2_FTR_EMSS IS NOT NULL THEN 'tCO2e'
		ELSE NULL
	END AS UNIDADE_FUNCIONAL_SCP2_EMSS,
	
	-- ORIGEM DA INFORMAÇÃO DAS EMISSÕES SCOPE 1
	CASE
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN 'Nao Aplicavel' 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS3_2A'
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP1_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP1_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		ELSE 'MISS'
	END AS ORIGEM_SCP1_EMSS,
	
	-- ORIGEM DA INFORMAÇÃO DAS EMISSÕES SCOPE 2
	CASE 
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN 'Nao Aplicavel' 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS3_2A'
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP2_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP2_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		ELSE 'MISS'
	END AS ORIGEM_SCP2_EMSS,
	
	-- DATA DE REFERÊNCIA DOS DADOS 
	'${REF_DATE}' AS REF_DATE 
	
FROM 
-- OBTENÇÃO DO UNIVERSO DE BENS IMÓVEIS 

(
	SELECT 
		PROPERTY_BANK_ID, PROPERTY_BRANCH_CODE, PROPERTY_CONTRACT_ID, PROPERTY_REFERENCE_CODE, NET_FLOOR_AREA,
		CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM 
	FROM BUSINESS_ASSETS.PROPERTY
	WHERE DATA_DATE_PART = '${REF_DATE}'
) BASE 

LEFT JOIN 
-- LIGAÇÃO COM A TABELA PROPERTY_ENERGY_CERTIFICATE PARA OBTENÇÃO DO CAMPO EPC REAL DO CERTIFICADO ENERGÉTICO DO BEM IMÓVEL
	
(
	SELECT  CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM, TRIM(UPPER(EPC)) AS EPC, TRIM(QUALITY_SCORE) AS QUALITY_SCORE
	FROM BUSINESS_ASSETS.PROPERTY_ENERGY_CERTIFICATE
	WHERE DATA_DATE_PART = '${REF_DATE}'
		AND EPC IS NOT NULL AND TRIM(EPC)<>''
) EPC ON BASE.CHAVE_BEM = EPC.CHAVE_BEM 

LEFT JOIN
-- LIGAÇÃO PARA OBTENÇÃO DO CAMPO TIPO DE FINALIDADE DO BEM IMÓVEL
	
(
	SELECT *
		-- MAPEAMENTO DA FINALIDADE DO BEM IMÓVEL
		,TRIM(UPPER(CASE
			WHEN VALOR_ORIGINAL ='1_01' THEN 'Residential Total'
			WHEN VALOR_ORIGINAL ='1_03' THEN 'Office'
			WHEN VALOR_ORIGINAL ='1_05' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_02' THEN 'Retail - high street'
			WHEN VALOR_ORIGINAL ='1_04' THEN 'Retail - warehouse'
			WHEN VALOR_ORIGINAL ='1_08' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_'   THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_07' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='1_06' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='1_11' THEN 'Healthcare'
			WHEN VALOR_ORIGINAL ='1_09' THEN 'Hotel'
			WHEN VALOR_ORIGINAL ='1_12' THEN 'Leisure/Lodging'
			WHEN VALOR_ORIGINAL ='1_14' THEN 'Retail - shopping center'
			WHEN VALOR_ORIGINAL ='1_10' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_13' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='0_01' THEN 'Residential Total'
			WHEN VALOR_ORIGINAL ='0_03' THEN 'Office'
			WHEN VALOR_ORIGINAL ='0_05' THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_02' THEN 'Retail High-street'
			WHEN VALOR_ORIGINAL ='0_04' THEN 'Retail Warehouse'
			WHEN VALOR_ORIGINAL ='0_08' THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_'   THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_07' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='0_06' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='0_11' THEN 'Healthcare'
			WHEN VALOR_ORIGINAL ='0_09' THEN 'Hotel'
			WHEN VALOR_ORIGINAL ='0_12' THEN 'Lodge/Leisure'
			WHEN VALOR_ORIGINAL ='0_14' THEN 'Shopping Center'
			WHEN VALOR_ORIGINAL ='0_10' THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_13' THEN 'Non-residential buildings'
		END)) AS TIPO_FINALIDADE_BEM
		,'NON-RESIDENTIAL BUILDINGS' AS TIPO_FINALIDADE_BEM_2
	FROM
		(
			SELECT 
				F1.*
				,CASE 
					WHEN F2.CHAVE_BEM IS NOT NULL THEN CONCAT_WS('_','1',TRIM(F1.PROPERTY_PURPOSE_CODE_MOD))
					ELSE CONCAT_WS('_','0',TRIM(F1.PROPERTY_PURPOSE_CODE_MOD))
				END AS VALOR_ORIGINAL
			FROM 
			(
				SELECT DISTINCT CHAVE_BEM,PROPERTY_PURPOSE_CODE,
					-- MAPEAMENTO DA FINALIDADE DO BEM PARA A CATEGORIA: 08 - OUTROS  
					CASE 
						WHEN TRIM(PROPERTY_PURPOSE_CODE)<>'08' THEN TRIM(PROPERTY_PURPOSE_CODE)
						WHEN TRIM(PROPERTY_PURPOSE_CODE)='08' AND TRIM(CGARANT_BEM) IN ('5101','5102') THEN '01'
						WHEN TRIM(PROPERTY_PURPOSE_CODE)='08' AND TRIM(CGARANT_BEM) IN ('5201','5202') THEN '02'
						WHEN TRIM(PROPERTY_PURPOSE_CODE)='08' AND TRIM(CGARANT_BEM) IN ('5213') THEN '10'
						WHEN TRIM(PROPERTY_PURPOSE_CODE)='08' AND TRIM(CGARANT_BEM) IN ('5215') THEN '11'
						ELSE '08'
					END AS PROPERTY_PURPOSE_CODE_MOD
				FROM 
				(
					SELECT CONCAT(PROPERTY_BANK_ID, PROPERTY_BRANCH_CODE, PROPERTY_CONTRACT_ID, PROPERTY_REFERENCE_CODE) AS CHAVE_BEM, PROPERTY_PURPOSE_CODE
					FROM BUSINESS_ASSETS.PROPERTY
					WHERE DATA_DATE_PART = '${REF_DATE}'
				) T1
				LEFT JOIN  
				(
					SELECT DISTINCT CONCAT(CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) AS CHAVE,CGARANT_BEM
					FROM CD_GARANTIAS.GT018_RATEIO_AVAL
					WHERE REF_DATE = '${REF_DATE}' 
						AND TIPOLOGIA='IMO'
				) T2 ON T1.CHAVE_BEM=T2.CHAVE 
			) F1 
			LEFT JOIN 
			(
				SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,EPC,TRIM(QUALITY_SCORE)
				FROM BUSINESS_ASSETS.PROPERTY_ENERGY_CERTIFICATE
				WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BUSINESS_ASSETS.PROPERTY WHERE DATA_DATE_PART <= '${REF_DATE}') 
					AND EPC IS NOT NULL AND TRIM(EPC)<>''
			) F2 ON F1.CHAVE_BEM = F2.CHAVE_BEM
		) AUX
) FIN_BEM ON BASE.CHAVE_BEM = FIN_BEM.CHAVE_BEM 

LEFT JOIN
-- LIGAÇÃO PARA OBTENÇÃO DOS FATORES DE EMISSÕES PARA O UNIVERSO DE BENS IMÓVEIS COM EPC REAL E ÁREA CONHECIDA (DQS=3)

(
	SELECT *
	FROM
	(
		SELECT *,
			TRIM(UPPER(EPC)) AS EPC_AUX,
			TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX,
			ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM AUXILIAR_CALCULO_1
	) AUX WHERE ROW_1=1
) EMISS_1 ON EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.EPC_AUX=EPC.EPC AND EMISS_1.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN
-- LIGAÇÃO PARA OBTENÇÃO DOS FATORES DE EMISSÕES PARA O UNIVERSO DE BENS IMÓVEIS COM EPC REAL E ÁREA CONHECIDA, MAS A LETRA DO EPC NÃO CONSTA NA TABELA DE FATORES DE EMISSÃO (DQS=4)

(
	SELECT *
	FROM
	(
		SELECT *,
			TRIM(UPPER(EPC)) AS EPC_AUX,
			TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX,
			ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM AUXILIAR_CALCULO_1
		WHERE (TRIM(EPC)='' OR EPC IS NULL)
	) AUX WHERE ROW_1=1
) EMISS_1B ON EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN 
-- LIGAÇÃO PARA OBTENÇÃO DOS FATORES DE EMISSÕES PARA O UNIVERSO DE BENS IMÓVEIS SEM EPC REAL E ÁREA CONHECIDA (DQS=4)

(
	SELECT *
	FROM
	(
		SELECT *,
			TRIM(UPPER(EPC)) AS EPC_AUX,
			TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX,
			ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM AUXILIAR_CALCULO_1
		WHERE (TRIM(EPC)='' OR EPC IS NULL)
	) AUX WHERE ROW_1=1
) EMISS_2 ON EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN 
-- LIGAÇÃO PARA OBTENÇÃO DOS FATORES DE EMISSÕES PARA O UNIVERSO DE BENS IMÓVEIS SEM EPC REAL E SEM ÁREA CONHECIDA (DQS=5)

(
	SELECT *
	FROM
	(
		SELECT *,
			TRIM(UPPER(EPC)) AS EPC_AUX,
			TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX,
			ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM AUXILIAR_CALCULO_2
		WHERE (TRIM(EPC)='' OR EPC IS NULL)
	) AUX WHERE ROW_1=1
) EMISS_3 ON BASE.NET_FLOOR_AREA=0 AND EMISS_3.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN 
-- LIGAÇÃO PARA OBTENÇÃO DOS FATORES DE EMISSÕES PARA O UNIVERSO DE BENS IMÓVEIS SEM EPC REAL E SEM ÁREA CONHECIDA, MAS NÃO FOI POSSÍVEL O CRUZAMENTO PELA FINALIDADE DO BEM (DQS=5)

(
	SELECT *
	FROM
	(
		SELECT *,
			TRIM(UPPER(EPC)) AS EPC_AUX,
			TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX,
			ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM AUXILIAR_CALCULO_2
		WHERE (TRIM(EPC)='' OR EPC IS NULL)
	) AUX WHERE ROW_1=1
) EMISS_4 ON BASE.NET_FLOOR_AREA=0 AND EMISS_4.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM_2

/*=========================================================================================================================================*/
/*  AUX. CRIAÇÃO DA TABELA                    							                                                                   */
/*=========================================================================================================================================*/

-- CREATE TABLE BU_CAPTOOLS_WORK.PA_OUT_BENS_IMOVEIS
-- (
--     CEMPBEM STRING,	
--     CKBALBEM STRING,	
--     CKCTABEM STRING,	
--     CKREFBEM STRING,	
--     SCP1_EMSS DECIMAL(38,22),	
--     SCP2_EMSS DECIMAL(38,22),	
--     UNIDADE_FUNCIONAL_SCP1_EMSS STRING,	
--     UNIDADE_FUNCIONAL_SCP2_EMSS STRING,	
--     ORIGEM_SCP1_EMSS STRING,	
--     ORIGEM_SCP2_EMSS STRING
-- )
-- PARTITIONED BY (REF_DATE STRING)