
/********************************************************************************************************************************************
****   Projeto: Convergência de Calculadora de Emissões Financiadas                                                              	     ****
****   Autor: BS & Neyond                                                                                                                ****
****   Data: 12/01/2026                                                                                                                  ****
****   SQL Script Descrição: Geração da Tabela de Emissões Financiadas por Imóvel (Real Estate)									         ****
********************************************************************************************************************************************/

/*=========================================================================================================================================*/
/*  1. INSERIR DADOS NA TABELA DE EMISSÕES FINANCIADAS POR IMÓVEL                                                                          */
/*=========================================================================================================================================*/

INSERT OVERWRITE TABLE BU_CAPTOOLS_WORK.PA_OUT_EMSS_FNCD_RE PARTITION (REF_DATE)

WITH AUXILIAR_CALCULO AS
(
	-- PROCESSO AUXILIAR AO CÁLCULO DAS EMISSÕES FINANCIADAS 
    SELECT UNIV.*,
        CT004.PURPOSE_CODE,
        CT003.CCAE,
        GT018_CGARANT.CGARANT_BEM,
        PROPERTY.PROPERTY_PURPOSE_CODE,
        PROPERTY.NET_FLOOR_AREA,
        SUM ( UNIV.AMOUNT) OVER (PARTITION BY CONCAT(UNIV.CEMPRESA ,UNIV.CBALCAO ,UNIV.CNUMECTA ,UNIV.ZDEPOSIT)) AS SUM_MSALDO_FINAL_CT,
        SUM (
                CASE 
                    WHEN GT018_PA.PRECO_AQUISICAO IS NOT NULL THEN GT018_PA.PRECO_AQUISICAO
                    WHEN GT018_AGR.SUM_CTO_BEM_MAVALIA IS NOT NULL THEN GT018_AGR.SUM_CTO_BEM_MAVALIA
                    ELSE GT018_AGR.SUM_CTO_BEM_MAVALIAA
                END
            ) OVER (PARTITION BY CONCAT(UNIV.CEMPRESA ,UNIV.CBALCAO ,UNIV.CNUMECTA ,UNIV.ZDEPOSIT)) AS SUM_CTO_IMOVEL_ORIGEM,
        MIN (
                CASE 
                    WHEN TRIM(PROPERTY.PROPERTY_PURPOSE_CODE) IN ('06','07') OR UNIV.CKBALBEM IS NULL THEN 1
                    ELSE 0
                END
            ) OVER (PARTITION BY CONCAT(UNIV.CEMPRESA ,UNIV.CBALCAO ,UNIV.CNUMECTA ,UNIV.ZDEPOSIT)) AS MIN_FLAG_ESTACION,
        MAX (
                CASE 
                    WHEN TRIM(PROPERTY.PROPERTY_PURPOSE_CODE) IN ('06','07') OR UNIV.CKBALBEM IS NULL THEN 1
                    ELSE 0
                END
            ) OVER (PARTITION BY CONCAT(UNIV.CEMPRESA ,UNIV.CBALCAO ,UNIV.CNUMECTA ,UNIV.ZDEPOSIT)) AS MAX_FLAG_ESTACION,
        MIN (
                CASE 
                    WHEN TRIM(UNIV.ORIGEM_SCP1_EMSS) IN ('MISS') OR UNIV.CKBALBEM IS NULL THEN 1
                    ELSE 0
                END
            ) OVER (PARTITION BY CONCAT(UNIV.CEMPRESA ,UNIV.CBALCAO ,UNIV.CNUMECTA ,UNIV.ZDEPOSIT)) AS MIN_FLAG_MISSING,
        MAX (
                CASE 
                    WHEN TRIM(UNIV.ORIGEM_SCP1_EMSS) IN ('MISS') OR UNIV.CKBALBEM IS NULL THEN 1
                    ELSE 0
                END
            ) OVER (PARTITION BY CONCAT(UNIV.CEMPRESA ,UNIV.CBALCAO ,UNIV.CNUMECTA ,UNIV.ZDEPOSIT)) AS MAX_FLAG_MISSING
        
    FROM 
    (
        SELECT *
        FROM BU_CAPTOOLS_WORK.PA_OUT_EMSS_FNCD
        WHERE REF_DATE='${REF_DATE}'
            AND NOME_PERIMETRO<>'Nao Aplicavel' 
    ) UNIV
    
    INNER JOIN 
    -- OBTER O UNIVERSO DE BENS IMÓVEIS 
    
    (
        SELECT DISTINCT S1.BANK_ID, S1.BRANCH_CODE, S1.CONTRACT_ID, S1.REFERENCE_CODE
        FROM 
        (
        	SELECT 
        	    BANK_ID,BRANCH_CODE,CONTRACT_ID,REFERENCE_CODE
        		,PROCESS_BANK_ID,PROCESS_BRANCH_CODE,PROCESS_ACCOUNT_ID,PROCESS_REFERENCE_CODE
        	FROM BUSINESS_ASSETS.RESPONSIBILITY_PROCESS_REL
        	WHERE DATA_DATE_PART='${REF_DATE}'
        )S1
        INNER JOIN 
        (
        	SELECT PROCESS_BANK_ID, PROCESS_BRANCH_CODE, PROCESS_ACCOUNT_ID, PROCESS_REFERENCE_CODE
                ,PROPERTY_BANK_ID , PROPERTY_BRANCH_CODE, PROPERTY_CONTRACT_ID, PROPERTY_REFERENCE_CODE
        	FROM BUSINESS_ASSETS.PROCESS_PROPERTY_REL
        	WHERE DATA_DATE_PART='${REF_DATE}'
        		AND COLLATERAL_PROPERTY_IND=1
        )S2 
        ON  S1.PROCESS_BANK_ID=S2.PROCESS_BANK_ID AND
            S1.PROCESS_BRANCH_CODE=S2.PROCESS_BRANCH_CODE AND
            S1.PROCESS_ACCOUNT_ID=S2.PROCESS_ACCOUNT_ID AND
            S1.PROCESS_REFERENCE_CODE=S2.PROCESS_REFERENCE_CODE 
    ) BENS 
    ON  UNIV.CEMPRESA = BENS.BANK_ID AND
    	UNIV.CBALCAO = BENS.BRANCH_CODE AND
    	UNIV.CNUMECTA = BENS.CONTRACT_ID AND
    	UNIV.ZDEPOSIT = BENS.REFERENCE_CODE 
    
    INNER JOIN 
    -- OBTER O PROPÓSITO ASSOCIADO A CADA OPERAÇÃO 
    
    (
     SELECT DISTINCT CEMPRESA ,CBALCAO ,CNUMECTA ,ZDEPOSIT, PURPOSE_CODE
     FROM CD_CAPTOOLS.CT004_UNIV_CTO
     WHERE REF_DATE='${REF_DATE}'
         AND TRIM(PURPOSE_CODE) IN ('Habitacao','CRE_FC','CRE_OUTRO')
    ) CT004
    ON  UNIV.CEMPRESA = CT004.CEMPRESA AND
     UNIV.CBALCAO = CT004.CBALCAO AND
     UNIV.CNUMECTA = CT004.CNUMECTA AND
     UNIV.ZDEPOSIT = CT004.ZDEPOSIT
    
    LEFT JOIN 
    -- OBTER O CCAE ASSOCIADO A CADA CLIENTE  
    
    (
		SELECT ZCLIENTE, CCAE
		FROM CD_CAPTOOLS.CT003_UNIV_CLI
		WHERE REF_DATE='${REF_DATE}'
    ) CT003 
    ON UNIV.ZCLIENTE = CT003.ZCLIENTE
    
    LEFT JOIN  
    -- OBTER O PREÇO DE AQUISIÇÃO DO IMÓVEL 
    
    (
        SELECT DISTINCT CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM,PRECO_AQUISICAO
        FROM CD_GARANTIAS.GT018_RATEIO_AVAL
        WHERE REF_DATE='${REF_DATE}' AND TIPOLOGIA='IMO' AND PRECO_AQUISICAO IS NOT NULL AND PRECO_AQUISICAO<>0
    ) GT018_PA
    ON  UNIV.CEMPBEM=GT018_PA.CEMPBEM AND
        UNIV.CKBALBEM=GT018_PA.CKBALBEM AND
        UNIV.CKCTABEM=GT018_PA.CKCTABEM AND
        UNIV.CKREFBEM=GT018_PA.CKREFBEM    
        
    LEFT JOIN  
    -- OBTER O CAMPO CGARANT_BEM ASSOCIADO A CADA IMÓVEL  
    
    (
        SELECT DISTINCT CEMPBEM, CKBALBEM, CKCTABEM, CKREFBEM, CGARANT_BEM
        FROM CD_GARANTIAS.GT018_RATEIO_AVAL
        WHERE REF_DATE='${REF_DATE}' AND TIPOLOGIA='IMO' 
    ) GT018_CGARANT
    ON  UNIV.CEMPBEM = GT018_CGARANT.CEMPBEM AND
        UNIV.CKBALBEM = GT018_CGARANT.CKBALBEM AND
        UNIV.CKCTABEM = GT018_CGARANT.CKCTABEM AND
        UNIV.CKREFBEM = GT018_CGARANT.CKREFBEM     
        
    LEFT JOIN
    -- OBTER O MONTANTE DE AVALIAÇÃO DO IMÓVEL E O MONTANTE DE AVALIAÇÃO DO IMÓVEL RATEADO
    
    (
        SELECT CEMPRESP,CKBALRES,CKCTARES,CKREFRESP,CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM,SUM(MAVALIA) AS SUM_CTO_BEM_MAVALIA,SUM(MAVALIAA) AS SUM_CTO_BEM_MAVALIAA
        FROM CD_GARANTIAS.GT018_RATEIO_AVAL
        WHERE REF_DATE='${REF_DATE}'
        GROUP BY CEMPRESP,CKBALRES,CKCTARES,CKREFRESP,CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM
    ) GT018_AGR 
    ON  UNIV.CEMPRESA = GT018_AGR.CEMPRESP AND
        UNIV.CBALCAO = GT018_AGR.CKBALRES AND
        UNIV.CNUMECTA = GT018_AGR.CKCTARES AND
        UNIV.ZDEPOSIT = GT018_AGR.CKREFRESP AND
        UNIV.CEMPBEM=GT018_AGR.CEMPBEM AND
        UNIV.CKBALBEM=GT018_AGR.CKBALBEM AND
        UNIV.CKCTABEM=GT018_AGR.CKCTABEM AND
        UNIV.CKREFBEM=GT018_AGR.CKREFBEM 

    LEFT JOIN  
    -- OBTER AS CARACTERÍSTICAS ASSOCIADAS A CADA IMÓVEL  
    
    (
        SELECT DISTINCT PROPERTY_BANK_ID, PROPERTY_BRANCH_CODE, PROPERTY_CONTRACT_ID, PROPERTY_REFERENCE_CODE, PROPERTY_PURPOSE_CODE, NET_FLOOR_AREA
        FROM BUSINESS_ASSETS.PROPERTY
        WHERE DATA_DATE_PART='${REF_DATE}' 
    ) PROPERTY
    ON  UNIV.CEMPBEM = PROPERTY.PROPERTY_BANK_ID AND
        UNIV.CKBALBEM = PROPERTY.PROPERTY_BRANCH_CODE AND
        UNIV.CKCTABEM = PROPERTY.PROPERTY_CONTRACT_ID AND
        UNIV.CKREFBEM = PROPERTY.PROPERTY_REFERENCE_CODE   
) 

SELECT 
    CEMPBEM,
    CKBALBEM,
    CKCTABEM,
    CKREFBEM,
    CASE 
    	WHEN TRIM(PROPERTY_PURPOSE_CODE)<>'08' THEN TRIM(PROPERTY_PURPOSE_CODE)
    	WHEN TRIM(PROPERTY_PURPOSE_CODE)='08' AND TRIM(CGARANT_BEM) IN ('5101','5102') THEN '01'
    	WHEN TRIM(PROPERTY_PURPOSE_CODE)='08' AND TRIM(CGARANT_BEM) IN ('5201','5202') THEN '02'
    	WHEN TRIM(PROPERTY_PURPOSE_CODE)='08' AND TRIM(CGARANT_BEM) IN ('5213') THEN '10'
    	WHEN TRIM(PROPERTY_PURPOSE_CODE)='08' AND TRIM(CGARANT_BEM) IN ('5215') THEN '11'
	    ELSE TRIM(PROPERTY_PURPOSE_CODE)
    END AS FINALIDADE_BEM,
	SUM(AREA_CTO_BEM_PONDERADA) AS AREA_PONDERADA,
	CASE 
	    WHEN PURPOSE_CODE IN ('CRE_OUTRO') AND (CCAE LIKE '41100%' OR CCAE LIKE '5511%' OR CCAE LIKE '68%') AND MIN_FLAG_MISSING=1 AND MAX_FLAG_MISSING=1 THEN 'CRE_OUTRO - MISS'
	    WHEN PURPOSE_CODE IN ('CRE_OUTRO') AND (CCAE LIKE '41100%' OR CCAE LIKE '5511%' OR CCAE LIKE '68%') THEN 'CRE_OUTRO'
	    WHEN PURPOSE_CODE IN ('CRE_OUTRO') THEN 'CRE_OUTRO - Nao Aplicavel'
	    WHEN PURPOSE_CODE IN ('Habitacao','CRE_FC') AND MIN_FLAG_MISSING=1 AND MAX_FLAG_MISSING=1 THEN CONCAT(PURPOSE_CODE,' - MISS')
	    ELSE PURPOSE_CODE
    END AS CRE_RRE,
	SUM(AMOUNT) AS AMOUNT,
    SUM(SCP1_EMSS_FNCD) AS SCP1_EMSS_FNCD,
    SUM(SCP2_EMSS_FNCD) AS SCP2_EMSS_FNCD,
    ORIGEM_SCP1_EMSS,
    ORIGEM_SCP2_EMSS,
	'${REF_DATE}' AS REF_DATE

FROM 

(
    SELECT *,
        CASE WHEN ORIGEM_SCP1_EMSS IN ('RE_DQS3_2A','RE_DQS4_2B') THEN NET_FLOOR_AREA*(CASE WHEN -SUM_MSALDO_FINAL_CT/SUM_CTO_IMOVEL_ORIGEM>1 THEN 1 ELSE -SUM_MSALDO_FINAL_CT/SUM_CTO_IMOVEL_ORIGEM END) END AS AREA_CTO_BEM_PONDERADA
    FROM AUXILIAR_CALCULO
    WHERE (MIN_FLAG_ESTACION=0 AND MAX_FLAG_ESTACION=0) OR (MIN_FLAG_ESTACION=0 AND MAX_FLAG_ESTACION=1) OR (MIN_FLAG_ESTACION=1 AND MAX_FLAG_ESTACION=0) -- EXCLUSÃO DOS FINANCIAMENTOS ASSOCIADOS EXCLUSIVAMENTE A GARAGENS/ESTACIONAMENTOS 
) AUXILIAR_INTERMEDIO

GROUP BY 1, 2, 3, 4, 5, 7, 11, 12, 13

/*=========================================================================================================================================*/
/*  AUX. CRIAÇÃO DA TABELA                    							                                                                   */
/*=========================================================================================================================================*/

-- CREATE TABLE BU_CAPTOOLS_WORK.PA_OUT_EMSS_FNCD_RE
-- (
--     CEMPBEM	STRING,	
--     CKBALBEM STRING,	
--     CKCTABEM STRING,	
--     CKREFBEM STRING,	
--     FINALIDADE_BEM STRING,	
--     AREA_PONDERADA DECIMAL(38,26),	
--     CRE_RRE STRING,
--     AMOUNT DECIMAL(38,24),
--     SCP1_EMSS_FNCD DECIMAL(38,28),	
--     SCP2_EMSS_FNCD DECIMAL(38,28),	
--     ORIGEM_SCP1_EMSS STRING,	
--     ORIGEM_SCP2_EMSS STRING
-- )
-- PARTITIONED BY (REF_DATE STRING);
