/********************************************************************************************************************************************
****   Projeto: Implementação Templates Locais                                                                     						 ****
****   Autor: BS & Neyond                                                                                                                ****
****   Data: 23/04/2025                                                                                                                  ****
****   SQL Script Descrição: Geração do Template 5 																					     ****
****  ( Banking book - Climate change physical risk: Exposures subject to physical risk  ) 												 ****
********************************************************************************************************************************************/

/*=========================================================================================================================================*/
/*  1. Tabela granular: Obtenção do universo a reportar no âmbito do Template 5 + Marcação de metricas relevantes             			   */
/*=========================================================================================================================================*/
       

-- INSERT OVERWRITE TABLE BU_ESG_WORK.AG05_TEMP_CTO_GRA PARTITION (ID_CORRIDA,REF_DATE)
SELECT XX.*,
    -- PARTICAO
	RT.NEW_ID_CORRIDA AS ID_CORRIDA,
	'${REF_DATE}' AS REF_DATE
FROM
(
    -- VALOR BRUTO
    SELECT
        UNI.ZCLIENTE, 
        UNI.COD_AJUST, 
        UNI.SOCIEDADE_CONTRAPARTE,
        UNI.CEMPRESA,
        UNI.CBALCAO,
        UNI.CNUMECTA,
        UNI.ZDEPOSIT,
        EMISS.CHAVE_BEM,
        -1*SUM(EMISS.AMOUNT) AS AMOUNT,
        UNI.BRUTO_IMPARIDADE AS VB_IMP, 
        UNI.STAGES AS STAGE, 
        UNI.CONTRAPARTE, 
        CASE
            WHEN INSTRUMENTO_FINANCEIRO = 'instrumentos de capital' THEN -3 -- 'INSTRUMENTOS DE CAPITAL' : > 20 ANOS
            WHEN UNI.DATA_VENCIMENTO  IN ('','0001-01-01','9999-12-31',NULL) AND TIPO_COLATERAL = 'Garantia Residencial' THEN -2 -- FALTA DE DATA QUALITY DE DADOS MAS GARANTIA RESIDENCIAL
            WHEN UNI.DATA_VENCIMENTO  IN ('','0001-01-01','9999-12-31',NULL) THEN -1 -- FALTA DE DATA QUALITY DE DADOS MAS NÃO GARANTIA RESIDENCIAL
            WHEN UPPER(UNI.PRODUTO) LIKE 'CART%CR%DITO%' OR UPPER(UNI.PRODUTO) LIKE '%REPOS%'  OR UPPER(UNI.PRODUTO) LIKE '%VISTA, DESCOBERTOS E CO%' THEN -1 -- 'COUNTERPARTY HAVING THE CHOICE OF THE REPAYMENT DATE'
            WHEN UNI.DATA_VENCIMENTO  < '${REF_DATE}' THEN -4 --'OLD CONTRACTS' 
            ELSE ROUND(DATEDIFF(TO_DATE(UNI.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25, 4)
        END AS YEARS_TO_MATURITY, 
        CASE
            WHEN UNI.ZCLIENTE = '0000000000' THEN 'S'
            WHEN NFIN.COD_NACE_ESG = '' AND UNI.CONTRAPARTE = 'outras empresas nao financeiras' THEN 'S' 
            WHEN NFIN.COD_NACE_ESG = 'Nao Aplicavel' THEN '' 
            WHEN NFIN.COD_NACE_ESG IS NULL THEN ''
            ELSE SUBSTR(NFIN.COD_NACE_ESG,1,1)
        END AS COD_NACE_ESG,
        TIPO_COLATERAL,
        CASE 
            WHEN FLG_ACT_PHYSCL_RSK_PRTCTN > 0 THEN 'ACUT1'
            WHEN FLG_ACT_PHYSCL_RSK_PRTCTN IS NULL AND FLG_ACT_PHYSCL_RSK_ENTTY > 0 THEN 'ACUT1' 
            ELSE 'ACUT2' 
        END AS ACUTE_CHANGES,
        CASE 
            WHEN FLG_CHRNC_PHYSCL_RSK_PRTCTN > 0 THEN 'CHRO1'
            WHEN FLG_CHRNC_PHYSCL_RSK_PRTCTN IS NULL AND FLG_CHRNC_PHYSCL_RSK_ENTTY > 0 THEN 'CHRO1' 
            ELSE 'CHRO2' 
        END AS CHRONIC_CHANGES,
        CASE
            WHEN FLG_ACT_PHYSCL_RSK_PRTCTN > 0 OR FLG_ACT_PHYSCL_RSK_ENTTY > 0 OR FLG_CHRNC_PHYSCL_RSK_PRTCTN > 0 OR FLG_CHRNC_PHYSCL_RSK_ENTTY > 0 THEN 1
            ELSE 0
        END AS FLAG_PHYSICAL_RISK

    FROM 
    -- TABELA DE UNIVERSO
    (
        SELECT DISTINCT
            ZCLIENTE    
            ,COD_AJUST
            ,SOCIEDADE_CONTRAPARTE
            ,CEMPRESA
            ,CBALCAO
            ,CNUMECTA
            ,ZDEPOSIT
            ,BRUTO_IMPARIDADE
            ,STAGES
            ,CONTRAPARTE
            ,DATA_VENCIMENTO
            ,PRODUTO
            ,TIPO_COLATERAL
            ,INSTRUMENTO_FINANCEIRO 
        FROM BU_CAPTOOLS_WORK.P3_UNIV_LOCAL_CTO
        WHERE TEMPLATE5 = 1 AND
            REF_DATE = '${REF_DATE}' AND ID_CORRIDA IN (SELECT MAX(ID_CORRIDA) FROM BU_CAPTOOLS_WORK.P3_UNIV_LOCAL_CTO WHERE REF_DATE = '${REF_DATE}') 
            AND BRUTO_IMPARIDADE = 'valor bruto'
    )UNI

    LEFT JOIN 
    (   
        SELECT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,ZCLIENTE,CHAVE_BEM,SUM(AMOUNT) AS AMOUNT
        FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX3
        WHERE FLAG_PERIMETRO LIKE '%Local%'
        GROUP BY 1,2,3,4,5,6
    ) EMISS
    ON  UNI.CEMPRESA = EMISS.CEMPRESA AND
        UNI.CBALCAO  = EMISS.CBALCAO AND
        UNI.CNUMECTA = EMISS.CNUMECTA AND
        UNI.ZDEPOSIT = EMISS.ZDEPOSIT 

    -- OBTENÇÃO DE CARACTERISTICAS DE CONTRATOS (EX. CÓDIGO NACE)
    LEFT JOIN 
    (
        SELECT *, FLG_RSC_FSC_AGD AS FLG_ACT_PHYSCL_RSK_ENTTY, FLG_RSC_FSC_CRNC AS FLG_CHRNC_PHYSCL_RSK_ENTTY  
        FROM BU_ESG_WORK.MODESG_OUT_EMPR_INFO_NFIN 
        WHERE REF_DATE='${REF_DATE}'
    ) NFIN
    ON UNI.ZCLIENTE = NFIN.ZCLIENTE

    LEFT JOIN 
    -- OBTENÇÃO DO RISCO AO NÍVEL DO COLATERAL IMÓVEL
    (
        SELECT *, FLG_RSC_FSC_AGD AS FLG_ACT_PHYSCL_RSK_PRTCTN, FLG_RSC_FSC_CRNC AS FLG_CHRNC_PHYSCL_RSK_PRTCTN  
        FROM BU_ESG_WORK.MODESG_OUT_BENS_IMOVEIS 
        WHERE REF_DATE='${REF_DATE}'
    ) MODESG_OUT_BENS_IMOVEIS
    ON  CONCAT(CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) = EMISS.CHAVE_BEM
    GROUP BY 1,2,3,4,5,6,7,8,10,11,12,13,14,15,16,17,18

    UNION ALL

    -- IMPARIDADE
    SELECT
        UNI.ZCLIENTE, 
        UNI.COD_AJUST, 
        UNI.SOCIEDADE_CONTRAPARTE,
        UNI.CEMPRESA,
        UNI.CBALCAO,
        UNI.CNUMECTA,
        UNI.ZDEPOSIT,
        NULL AS CHAVE_BEM,
        -1*SUM(MSALDO_FINAL) AS AMOUNT,
        UNI.BRUTO_IMPARIDADE AS VB_IMP, 
        UNI.STAGES AS STAGE, 
        UNI.CONTRAPARTE, 
        CASE
            WHEN INSTRUMENTO_FINANCEIRO = 'instrumentos de capital' THEN -3 -- 'INSTRUMENTOS DE CAPITAL' : > 20 ANOS
            WHEN UNI.DATA_VENCIMENTO  IN ('','0001-01-01','9999-12-31',NULL) AND TIPO_COLATERAL = 'Garantia Residencial' THEN -2 -- FALTA DE DATA QUALITY DE DADOS MAS GARANTIA RESIDENCIAL
            WHEN UNI.DATA_VENCIMENTO  IN ('','0001-01-01','9999-12-31',NULL) THEN -1 -- FALTA DE DATA QUALITY DE DADOS MAS NÃO GARANTIA RESIDENCIAL
            WHEN UPPER(UNI.PRODUTO) LIKE 'CART%CR%DITO%' OR UPPER(UNI.PRODUTO) LIKE '%REPOS%'  OR UPPER(UNI.PRODUTO) LIKE '%VISTA, DESCOBERTOS E CO%' THEN -1 -- 'COUNTERPARTY HAVING THE CHOICE OF THE REPAYMENT DATE'
            WHEN UNI.DATA_VENCIMENTO  < '${REF_DATE}' THEN -4 --'OLD CONTRACTS' 
            ELSE ROUND(DATEDIFF(TO_DATE(UNI.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25, 4)
        END AS YEARS_TO_MATURITY, 
        CASE
            WHEN UNI.ZCLIENTE = '0000000000' THEN 'S'
            WHEN NFIN.COD_NACE_ESG = '' AND UNI.CONTRAPARTE = 'outras empresas nao financeiras' THEN 'S' 
            WHEN NFIN.COD_NACE_ESG = 'Nao Aplicavel' THEN '' 
            WHEN NFIN.COD_NACE_ESG IS NULL THEN ''
            ELSE SUBSTR(NFIN.COD_NACE_ESG,1,1)
        END AS COD_NACE_ESG,
        TIPO_COLATERAL,
        CASE 
            WHEN FLG_ACT_PHYSCL_RSK_ENTTY > 0 THEN 'ACUT1' 
            ELSE 'ACUT2' 
        END AS ACUTE_CHANGES,
        CASE 
            WHEN FLG_CHRNC_PHYSCL_RSK_ENTTY > 0 THEN 'CHRO1' 
            ELSE 'CHRO2' 
        END AS CHRONIC_CHANGES,
        CASE
            WHEN FLG_ACT_PHYSCL_RSK_ENTTY > 0 OR FLG_CHRNC_PHYSCL_RSK_ENTTY > 0 THEN 1
            ELSE 0
        END AS FLAG_PHYSICAL_RISK
        
    FROM 
    -- TABELA DE UNIVERSO
    (
        SELECT * 
        FROM BU_CAPTOOLS_WORK.P3_UNIV_LOCAL_CTO 
        WHERE TEMPLATE5 = 1 AND
            REF_DATE = '${REF_DATE}' AND ID_CORRIDA IN (SELECT MAX(ID_CORRIDA) FROM BU_CAPTOOLS_WORK.P3_UNIV_LOCAL_CTO WHERE REF_DATE = '${REF_DATE}')
            AND BRUTO_IMPARIDADE = 'imparidade'
    )UNI

    -- OBTENÇÃO DE CARACTERISTICAS DE CONTRATOS (EX. CÓDIGO NACE)
    LEFT JOIN 
    (
        SELECT *, FLG_RSC_FSC_AGD AS FLG_ACT_PHYSCL_RSK_ENTTY, FLG_RSC_FSC_CRNC AS FLG_CHRNC_PHYSCL_RSK_ENTTY  
        FROM BU_ESG_WORK.MODESG_OUT_EMPR_INFO_NFIN 
        WHERE REF_DATE='${REF_DATE}'
    ) NFIN
    ON UNI.ZCLIENTE = NFIN.ZCLIENTE

    GROUP BY 1,2,3,4,5,6,7,8,10,11,12,13,14,15,16,17,18

    UNION ALL

    -- ADJUDICADOS
    SELECT *
    FROM
    (
        WITH ADJUD_INPUTS AS 
        (
            SELECT ADJUD_INPUTS.*,FLG_ACT_PHYSCL_RSK_PRTCTN,FLG_CHRNC_PHYSCL_RSK_PRTCTN
            FROM
            (
            SELECT
                '31' as PROPERTY_BANK_ID,
                'CMAH' AS PROPERTY_BRANCH_CODE, 
                'IMOVELGIDAP' AS PROPERTY_CONTRACT_ID,
                REPLACE(UPPER(LPAD(COD_IMOVEL,15,'0')),' ', '0') AS PROPERTY_REFERENCE_CODE,
                V_CONTAB, 
                PROV_LEGAL + PROV_ADICIONAL AS V_PROV
            FROM CD_CAPTOOLS.CT666_ADJUDIC_PROPR
            WHERE REF_DATE='${REF_DATE}'
            AND V_CONTAB_IFRS IN('199100240', '19910000', '1910000', '199100200', '199100210', '19910001', '1910008', '199100201', '199100211', '199100241')

            UNION ALL

            SELECT
                '89' AS PROPERTY_BANK_ID , 
                'CMAH' AS PROPERTY_BRANCH_CODE, 
                'IMOVELIFICS' AS PROPERTY_CONTRACT_ID,
                LPAD(N_IMOVEL,15,'0') AS PROPERTY_REFERENCE_CODE,
                V_CONTAB,
                PROV_TOTAL AS V_PROV
            FROM CD_CAPTOOLS.CT668_IMOVEIS_IFIC
            WHERE REF_DATE='${REF_DATE}'
            AND V_CONTAB_IFRS IN('199100240', '19910000', '1910000', '199100200', '199100210', '19910001', '1910008', '199100201', '199100211', '199100241')

            UNION ALL

            SELECT
                '00160' AS PROPERTY_BANK_ID , 
                'CMAH' AS PROPERTY_BRANCH_CODE, 
                'IMOVELGIDTU' AS PROPERTY_CONTRACT_ID, 
                LPAD(COD_IMOVEL,15,'0') AS PROPERTY_REFERENCE_CODE,
                V_CONTAB,
                PROV_TOTAL AS V_PROV     
            FROM CD_CAPTOOLS.CT665_STOCK_URBE
            WHERE REF_DATE='${REF_DATE}'

            ) ADJUD_INPUTS

            LEFT JOIN 
            -- OBTENÇÃO DO RISCO AO NÍVEL DO COLATERAL IMÓVEL
            (
                SELECT *, FLG_RSC_FSC_AGD AS FLG_ACT_PHYSCL_RSK_PRTCTN, FLG_RSC_FSC_CRNC AS FLG_CHRNC_PHYSCL_RSK_PRTCTN  
                FROM BU_ESG_WORK.MODESG_OUT_BENS_IMOVEIS 
                WHERE REF_DATE='${REF_DATE}'
            ) MODESG_OUT_BENS_IMOVEIS
            ON 
                MODESG_OUT_BENS_IMOVEIS.CEMPBEM = ADJUD_INPUTS.PROPERTY_BANK_ID  AND
                MODESG_OUT_BENS_IMOVEIS.CKBALBEM = ADJUD_INPUTS.PROPERTY_BRANCH_CODE AND
                MODESG_OUT_BENS_IMOVEIS.CKCTABEM = ADJUD_INPUTS.PROPERTY_CONTRACT_ID AND
                MODESG_OUT_BENS_IMOVEIS.CKREFBEM = ADJUD_INPUTS.PROPERTY_REFERENCE_CODE
        ) 
        -- BRUTO
        SELECT
            NULL AS ZCLIENTE,
            NULL AS COD_AJUST,
            NULL AS SOCIEDADE_CONTRAPARTE,
            NULL AS CEMPRESA,
            NULL AS CBALCAO,
            NULL AS CNUMECTA,
            NULL AS ZDEPOSIT,
            CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,
            SUM(V_CONTAB) AS MSALDO_FINAL,
            'valor bruto' AS VB_IMP,
            '' AS STAGE,
            '' AS CONTRAPARTE,
            -5 AS YEARS_TO_MATURITY,
            '' AS COD_NACE_ESG,
            'Stock' AS TIPO_COLATERAL,
            CASE 
                WHEN FLG_ACT_PHYSCL_RSK_PRTCTN > 0 THEN 'ACUT1'
                ELSE 'ACUT2' 
            END AS ACUTE_CHANGES,
            CASE 
                WHEN FLG_CHRNC_PHYSCL_RSK_PRTCTN > 0 THEN 'CHRO1' 
                ELSE 'CHRO2' 
            END AS CHRONIC_CHANGES,
            CASE
                WHEN FLG_ACT_PHYSCL_RSK_PRTCTN > 0 OR FLG_CHRNC_PHYSCL_RSK_PRTCTN > 0 THEN 1
                ELSE 0
            END AS FLAG_PHYSICAL_RISK

        FROM ADJUD_INPUTS
        WHERE CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) IN (SELECT CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) FROM CD_CAPTOOLS.CT001_UNIV_SALDO WHERE REF_DATE='${REF_DATE}' AND CCONTAB_FINAL_IDCOMB LIKE '%MC1005%')
        GROUP BY 1,2,3,4,5,6,7,8,10,11,12,13,14,15,16,17,18

        UNION ALL
        -- IMPARIDADE
        SELECT
            NULL AS ZCLIENTE,
            NULL AS COD_AJUST,
            NULL AS SOCIEDADE_CONTRAPARTE,
            NULL AS CEMPRESA,
            NULL AS CBALCAO,
            NULL AS CNUMECTA,
            NULL AS ZDEPOSIT,
            CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,
            SUM(-1*V_PROV) AS MSALDO_FINAL,
            'imparidade' AS VB_IMP,
            '' AS STAGE,
            '' AS CONTRAPARTE,
            -5 AS YEARS_TO_MATURITY,
            '' AS COD_NACE_ESG,
            'Stock' AS TIPO_COLATERAL,
            CASE 
                WHEN FLG_ACT_PHYSCL_RSK_PRTCTN > 0 THEN 'ACUT1'
                ELSE 'ACUT2' 
            END AS ACUTE_CHANGES,
            CASE 
                WHEN FLG_CHRNC_PHYSCL_RSK_PRTCTN > 0 THEN 'CHRO1' 
                ELSE 'CHRO2' 
            END AS CHRONIC_CHANGES,
            CASE
                WHEN FLG_ACT_PHYSCL_RSK_PRTCTN > 0 OR FLG_CHRNC_PHYSCL_RSK_PRTCTN > 0 THEN 1
                ELSE 0
            END AS FLAG_PHYSICAL_RISK

        FROM ADJUD_INPUTS
        WHERE CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) IN (SELECT CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) FROM CD_CAPTOOLS.CT001_UNIV_SALDO WHERE REF_DATE='${REF_DATE}' AND CCONTAB_FINAL_IDCOMB LIKE '%MC1005%')
        GROUP BY 1,2,3,4,5,6,7,8,10,11,12,13,14,15,16,17,18
    ) X
) XX

LEFT JOIN
(
	SELECT NVL(MAX(ID_CORRIDA),0)+1 AS NEW_ID_CORRIDA
	FROM BU_ESG_WORK.AG05_TEMP_CTO_GRA
	WHERE REF_DATE = '${REF_DATE}'
) RT
ON  1=1
;

/*=========================================================================================================================================*/
/*  2. TABELA FINAL: OBTENÇÃO DAS MÉTRICAS AGREGADAS A REPORTAR NO ÂMBITO DO TEMPLATE 5                  							       */
/*=========================================================================================================================================*/

-- INSERT OVERWRITE BU_ESG_WORK.AG05_TEMP_CTO_AGR PARTITION (ID_CORRIDA,REF_DATE)
SELECT X.*,
		CASE 
			WHEN VB_IMP = 'valor bruto' AND MATURITY > 0 THEN MATURITY*AMOUNT				
			ELSE NULL
		END AS AVEG_AUX,

		-- PARTICAO
		RT.NEW_ID_CORRIDA AS ID_CORRIDA,
		'${REF_DATE}' AS REF_DATE
FROM
(
	SELECT
		STAGE, 
		CONTRAPARTE,
		VB_IMP,
		TIPO_COLATERAL,
		ROUND(YEARS_TO_MATURITY,0) AS MATURITY,
		COD_NACE_ESG, 
		ACUTE_CHANGES,
		CHRONIC_CHANGES,
		FLAG_PHYSICAL_RISK,
		ROUND(SUM(AMOUNT)) AS AMOUNT		
	FROM 
	(	
		SELECT * FROM BU_ESG_WORK.AG05_TEMP_CTO_GRA
		WHERE REF_DATE = '${REF_DATE}' 
			AND ID_CORRIDA IN (SELECT MAX(ID_CORRIDA) FROM BU_ESG_WORK.AG05_TEMP_CTO_GRA WHERE REF_DATE = '${REF_DATE}')
	) AUX GROUP BY 1,2,3,4,5,6,7,8,9
) X
LEFT JOIN
(
	SELECT NVL(MAX(ID_CORRIDA),0)+1 AS NEW_ID_CORRIDA
	FROM BU_ESG_WORK.AG05_TEMP_CTO_AGR
	WHERE REF_DATE = '${REF_DATE}'
) RT
ON 1=1
;

