/********************************************************************************************************************************************
****   Projeto: Implementação Templates Locais                                                                     						 ****
****   Autor: BS & Neyond                                                                                                                ****
****   Data: 23/05/2025                                                                                                                  ****
****   SQL Script Descrição: Geração do Template 2 STE 																					 ****
****  (Banking book - Climate change transition risk: Loans collateralised by immovable property - Energy efficiency of the collateral ) ****
********************************************************************************************************************************************/

/*=========================================================================================================================================*/
/*  1. Tabela granular: Obtenção do universo a reportar no âmbito do Template 2 STE + Marcação de metricas relevantes       			   */
/*=========================================================================================================================================*/ 

-- REGISTOS DEZ24: 365.743 | MONTANTE: -26 856 052 668.538
-- INSERT OVERWRITE TABLE BU_ESG_WORK.AG02_STE_CTO_GRA PARTITION (ID_CORRIDA,REF_DATE)
SELECT 
	 A.*,
	 B.`13_GROSS_CARRYING_AMOUNT`,
	 B.CKBALBEM, 
	 B.CKCTABEM,
	 B.CKREFBEM, 
	 B.EPC, 
	 CASE 
		WHEN B.QUALITY_SCORE IS NULL THEN 'NULO'
		ELSE B.QUALITY_SCORE END AS QUALITY_SCORE,
	 B.CONSUMOS,
	 CASE
		WHEN D.VALOR_LTV IS NULL THEN 101.000000 -- POR INDICAÇÃO DA CORPORAÇÃO OS NULOS DEVERÃO SER MARCADOS NO BUCKET MAIS ELEVADO 
		WHEN D.VALOR_LTV > 150 THEN 150.000000
		ELSE D.VALOR_LTV
	 END AS VALOR_LTV,
	 CASE
		WHEN D.VALOR_LTV IS NULL THEN 1.0100000000 -- POR INDICAÇÃO DA CORPORAÇÃO OS NULOS DEVERÃO SER MARCADOS NO BUCKET MAIS ELEVADO 
		WHEN D.VALOR_LTV > 150 THEN 1.5000000000
		ELSE D.VALOR_LTV/100
	 END AS VALOR_LTV_DECIMAL,
	 CASE
		WHEN TX_JURO_LT = 99999999999.000000 THEN 0.000000 -- POR INDICAÇÃO DA CORPORAÇÃO, OS CONTRATOS QUE NÃO POSSUEM TAXA DE JURO DEVERÃO ASSUMIR TX JURO 0 
		ELSE TX_JURO_LT
	 END AS TX_JURO,
	 CASE
	  WHEN D.VALOR_LTV IS NULL THEN 'LTV5'
		WHEN D.VALOR_LTV <= 40 THEN 'LTV1'
		WHEN D.VALOR_LTV <= 60 THEN 'LTV2'
		WHEN D.VALOR_LTV <= 80 THEN 'LTV3'
		WHEN D.VALOR_LTV < 100 THEN 'LTV4'
		ELSE 'LTV5' 
	 END AS COLLATERAL_LTV,
	 CASE
		WHEN TRIM(B.EPC) LIKE 'A' THEN 'A'
		WHEN TRIM(B.EPC) LIKE 'A%' THEN 'A+'
		WHEN TRIM(B.EPC) LIKE 'B' THEN 'B'
		WHEN TRIM(B.EPC) LIKE 'B%' THEN 'B-'
		WHEN TRIM(B.EPC) LIKE 'C%' THEN 'C'
		WHEN TRIM(B.EPC) LIKE 'D%' THEN 'D'
		WHEN TRIM(B.EPC) LIKE 'E%' THEN 'E'
		WHEN TRIM(B.EPC) LIKE 'F%' THEN 'F'
		WHEN TRIM(B.EPC) LIKE 'G%' THEN 'G'
		ELSE 'Sem dados'
	 END AS EPC_LABEL, 
	 CASE 
		WHEN B.CONSUMOS <= 100 THEN 'menor_100'
		WHEN B.CONSUMOS > 100 AND B.CONSUMOS <= 200 THEN 'menor_200'
		WHEN B.CONSUMOS > 200 AND B.CONSUMOS <= 300 THEN 'menor_300'
		WHEN B.CONSUMOS > 300 AND B.CONSUMOS <= 400 THEN 'menor_400'
		WHEN B.CONSUMOS > 400 AND B.CONSUMOS <= 500 THEN 'menor_500'
		WHEN B.CONSUMOS > 500 THEN 'maior_500'
		ELSE 'Sem dados'
	 END AS EP_SCORE,
	 
	 -- PARA IMPLEMENTAÇÃO ESTRUTURAL DEVERÁ SER CONSIDERADO O SEGUINTE PEDAÇO DE CÓDIGO 
	 CASE
	     WHEN A.DATA_ABERTURA>= '${REF_DATE_INI}' THEN ''  -- VER QUE VALORES O QUALITY SCORE TOMA NA PROPERTY, FALAR COM HELDER PARA VER QUAIS CERTIFCADOS SAO CONSIDERADOS REAIS
	     WHEN B.QUALITY_SCORE NOT IN ('1-REAL','SANTANDER') OR B.QUALITY_SCORE IS NULL THEN '' -- VER QUANDO É NULL QUE VALOR ASSUME 
	     WHEN TRIM(B.EPC_LABEL_PY) LIKE 'A%' THEN 'PEPC1'
	     WHEN TRIM(B.EPC_LABEL_PY) LIKE 'B%' THEN 'PEPC2'
	     WHEN TRIM(B.EPC_LABEL_PY) LIKE 'C%' THEN 'PEPC3'
	     WHEN TRIM(B.EPC_LABEL_PY) LIKE 'D%' THEN 'PEPC4'
	     WHEN TRIM(B.EPC_LABEL_PY) LIKE 'E%' THEN 'PEPC5'
	     WHEN TRIM(B.EPC_LABEL_PY) LIKE 'F%' THEN 'PEPC6'
	     WHEN TRIM(B.EPC_LABEL_PY) LIKE 'G%' THEN 'PEPC7'
	     ELSE 'PEPC8'
	 END AS PREVIOUS_YEAR_EPC_LABEL, 
	 CASE
	     WHEN A.DATA_ABERTURA>= '${REF_DATE_INI}' THEN ''
	     WHEN B.CONSUMOS IS NULL THEN ''  -- CONFIRMAR SE EXISTEM NULLS
	     WHEN B.EP_SCORE_PY <= 100 THEN 'PEPS1'
	     WHEN B.EP_SCORE_PY > 100 AND B.EP_SCORE_PY <= 200 THEN 'PEPS2'
	     WHEN B.EP_SCORE_PY > 200 AND B.EP_SCORE_PY <= 300 THEN 'PEPS3'
	     WHEN B.EP_SCORE_PY > 300 AND B.EP_SCORE_PY <= 400 THEN 'PEPS4'
	     WHEN B.EP_SCORE_PY > 400 AND B.EP_SCORE_PY <= 500 THEN 'PEPS5'
	     WHEN B.EP_SCORE_PY > 500 THEN 'PEPS6'
	     ELSE 'PEPS7'
	 END AS PREVIOUS_YEAR_EP_SCORE,


	 -- PARA IMPLEMENTAÇÃO DA RÉPLICA DE DEZ24 DEVERÁ SER CONSIDERADO O SEGUINTE PEDAÇO DE CÓDIGO  
	--  CASE
	-- 	WHEN A.DATA_ABERTURA>= '${REF_DATE_INI}' THEN ''
	-- 	WHEN B.QUALITY_SCORE NOT IN ('1-REAL','SANTANDER') OR B.QUALITY_SCORE IS NULL THEN '' -- DE ACORDO COM O MdD, QUANDO É ESTIMADO O PREVIOUS YEAR VEM A VAZIO
	-- 	WHEN B.EPC_LABEL_PY = 'A' THEN 'PEPC1'
	-- 	WHEN B.EPC_LABEL_PY = 'B' THEN 'PEPC2'
	-- 	WHEN B.EPC_LABEL_PY = 'C' THEN 'PEPC3'
	-- 	WHEN B.EPC_LABEL_PY = 'D' THEN 'PEPC4'
	-- 	WHEN B.EPC_LABEL_PY = 'E' THEN 'PEPC5'
	-- 	WHEN B.EPC_LABEL_PY = 'F' THEN 'PEPC6'
	-- 	WHEN B.EPC_LABEL_PY = 'G' THEN 'PEPC7'
	-- 	ELSE 'PEPC8'
	--  END AS PREVIOUS_YEAR_EPC_LABEL, 
	--  CASE
	-- 	WHEN A.DATA_ABERTURA>= '${REF_DATE_INI}' THEN ''
	-- 	WHEN B.CONSUMOS IS NULL THEN '' 
	-- 	WHEN B.EP_SCORE_PY = 'menor_100' THEN 'PEPS1'
	-- 	WHEN B.EP_SCORE_PY = 'menor_200' THEN 'PEPS2'
	-- 	WHEN B.EP_SCORE_PY = 'menor_300' THEN 'PEPS3'
	-- 	WHEN B.EP_SCORE_PY = 'menor_400' THEN 'PEPS4'
	-- 	WHEN B.EP_SCORE_PY = 'menor_500' THEN 'PEPS5'
	-- 	WHEN B.EP_SCORE_PY = 'maior_500' THEN 'PEPS6'
	-- 	ELSE 'PEPS7'
	--  END AS PREVIOUS_YEAR_EP_SCORE,

	 CASE                                                    
		WHEN B.COUNTRY_CODE IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428')
		  THEN 'EU-area'
		WHEN B.COUNTRY_CODE NOT IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428', '')
		  THEN 'Non EU-area'
		WHEN B.CPAIS_RESIDENCIA IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428')
		  THEN 'EU-area'
		WHEN B.CPAIS_RESIDENCIA NOT IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428','')
	      THEN 'Non EU-area'
	 ELSE '' 
	 END AS EUROPEAN_UNION,
	 CASE
		WHEN A.CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%MC06%' THEN 'MESG4' -- REGRA DE ACORDO COM SATELITE_STRUCUTRE
		WHEN A.CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%MC08%' THEN 'MESG4' -- REGRA DE ACORDO COM SATELITE_STRUCUTRE
		WHEN A.FLAG_MESG5 = 1 THEN 'MESG5'  -- COUNTERPARTY HAVING THE CHOICE OF THE REPAYMENT DATE
		WHEN A.DATA_VENCIMENTO < '${REF_DATE}' AND (A.DATA_VENCIMENTO NOT IN ('','0001-01-01','9999-12-31') OR A.DATA_VENCIMENTO IS NOT NULL) THEN 'MESG1' -- CONTRATOS COM MATURIDADE INFERIOR À DATA DE REPORTE OU FALTA DE DATA QUALITY DE DADOS
		WHEN (A.DATA_VENCIMENTO IN ('','0001-01-01','9999-12-31') OR A.DATA_VENCIMENTO IS NULL)AND A.CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%MC02%' AND A.CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL2%' THEN 'MESG4' -- UNKNOWN MATURITY RESIDENCIAL (REGRA DE ACORDO COM SATELITE_STRUCUTRE)
		WHEN (A.DATA_VENCIMENTO IN ('','0001-01-01','9999-12-31') OR A.DATA_VENCIMENTO IS NULL)AND A.CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%MC02%' AND A.CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL3%' THEN 'MESG1' -- UNKNOWN MATURITY COMERCIAL (REGRA DE ACORDO COM SATELITE_STRUCUTRE)
		WHEN (A.DATA_VENCIMENTO IN ('','0001-01-01','9999-12-31') OR A.DATA_VENCIMENTO IS NULL)AND A.CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%MC02%' AND A.CCONTAB_FINAL_IDCOMB_TOTAL NOT LIKE '%COLL2%' AND A.CCONTAB_FINAL_IDCOMB_TOTAL NOT LIKE '%COLL3%' THEN 'MESG1' -- UNKNOWN MATURITY REST OF LOANS (REGRA DE ACORDO COM SATELITE_STRUCUTRE)
		WHEN (A.DATA_VENCIMENTO IN ('','0001-01-01','9999-12-31') OR A.DATA_VENCIMENTO IS NULL)AND A.CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%MC04%' THEN 'MESG1' -- UNKNOWN MATURITY BEBT SECURITIES (REGRA DE ACORDO COM SATELITE_STRUCUTRE)
		WHEN (A.DATA_VENCIMENTO IN ('','0001-01-01','9999-12-31') OR A.DATA_VENCIMENTO IS NULL)THEN 'MESG6' -- OTHER CONTRACTS WITH NO STATED MATURITY
		WHEN ROUND(DATEDIFF(TO_DATE(A.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25,4) < 05 THEN 'MESG1' 
		WHEN ROUND(DATEDIFF(TO_DATE(A.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25,4) <= 10 THEN 'MESG2'
		WHEN ROUND(DATEDIFF(TO_DATE(A.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25,4) <= 20 THEN 'MESG3'
		WHEN ROUND(DATEDIFF(TO_DATE(A.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25,4) > 20 THEN 'MESG4'
		ELSE 'MESG6'
	 END AS MATURITY_ESG,
	 CASE
		WHEN A.CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%MC06%'                                            THEN 0  --EXCLUSÃO DE EQUITY
		WHEN A.CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%MC08%'                                            THEN 0  --EXCLUSÃO DE INVESTMENTS IN SUBSIDIARIES
		WHEN A.FLAG_MESG5 = 1                                                                      THEN 0  --EXCLUSÃO DE COUNTERPARTY HAVING THE CHOICE OF REPAYMENT DATE
		WHEN A.DATA_VENCIMENTO IN ('','0001-01-01','9999-12-31') OR A.DATA_VENCIMENTO IS NULL      THEN 0  --EXCLUSÃO DE CONTRATOS COM FALTA DE DATA QUALITY DE DADOS
		WHEN A.DATA_VENCIMENTO < '${REF_DATE}'                                                     THEN 0  --EXCLUSÃO DE CONTRATOS COM MATURIDADE INFERIOR À DATA DE REPORTE 
		WHEN ROUND(DATEDIFF(TO_DATE(A.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25,4) <= 05    THEN 1
		WHEN ROUND(DATEDIFF(TO_DATE(A.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25,4) <= 10    THEN 1
		WHEN ROUND(DATEDIFF(TO_DATE(A.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25,4) <= 20    THEN 1
		WHEN ROUND(DATEDIFF(TO_DATE(A.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25,4) >  20    THEN 1
		ELSE 0   
	 END AS FLAG_MATURITY,
	 CASE 
		WHEN A.DATA_VENCIMENTO IN ('','0001-01-01','9999-12-31') OR A.DATA_VENCIMENTO IS NULL THEN NULL
		WHEN A.FLAG_MESG5 = 1 THEN NULL
		WHEN A.DATA_VENCIMENTO < '${REF_DATE}' THEN NULL
		ELSE ROUND(DATEDIFF(TO_DATE(A.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25, 4)
	 END AS YEARS_TO_MATURITY,
	 CASE
		WHEN (DATA_INICIO NOT IN ('','0001-01-01','9999-12-31') OR DATA_INICIO IS NOT NULL) AND DATA_INICIO >= '${REF_DATE_INI}' THEN 'NBF1' -- DATA INICIO : DATA DE REESTRUTURAÇÃO/RENEGOCIAÇÃO
		WHEN A.DATA_ABERTURA >= '${REF_DATE_INI}' THEN 'NBF2' -- '2024-01-01'
		ELSE 'NBF3'
	 END AS NEW_BUSINESS_FLOW, 

	-- PARTICAO
	RT.NEW_ID_CORRIDA AS ID_CORRIDA,
	'${REF_DATE}' AS REF_DATE

FROM 

-- TABELA DE UNIVERSO
(
	 SELECT DISTINCT 
		DATA_ABERTURA,
		DATA_VENCIMENTO,
		CEMPRESA,
		CBALCAO,
		CNUMECTA,
		ZDEPOSIT,
		TIPO_COLATERAL,
		CCONTAB_FINAL_IDCOMB_TOTAL,
		BRUTO_IMPARIDADE,
		CASE 
			WHEN UPPER(PRODUTO) LIKE 'CART%CR%DITO%' OR 
				 UPPER(PRODUTO) LIKE '%REPOS%'  OR 
				 UPPER(PRODUTO) LIKE '%VISTA, DESCOBERTOS E CO%'
					THEN 1 
		END AS FLAG_MESG5
	 FROM BU_ESG_WORK.P3_FULL_CTR_CLI_LOCAL_DEZ24_V2 
	 WHERE DT_RFRNC = '${REF_DATE}' AND 
		   TEMPLATE2=1
) AS A

LEFT JOIN  
(
	 SELECT  
	  GAR.CEMPRESA,
	  GAR.CBALCAO,
	  GAR.CNUMECTA,
	  GAR.ZDEPOSIT,
	  SUM(GAR.`13_GROSS_CARRYING_AMOUNT`) AS `13_GROSS_CARRYING_AMOUNT`,
	  GAR.CKBALBEM, 
	  GAR.CKCTABEM,
	  GAR.CKREFBEM,
	  GAR.CPAIS_RESIDENCIA, 
	  CERT_ENERG.EPC, 
	  CERT_ENERG.QUALITY_SCORE,
	  CERT_ENERG.EP_SCORE AS CONSUMOS,
	  CERT_ENERG_PREVIOUS_YEAR.EP_SCORE AS EP_SCORE_PY,
	  CERT_ENERG_PREVIOUS_YEAR.EPC AS EPC_LABEL_PY,
	  RENEGOCIADOS.DATA_INICIO,
	  PROPERTY.COUNTRY_CODE    
	 FROM
	 (
	  SELECT * 
	  FROM BU_ESG_WORK.P3_REPARTICAO_GARANTIAS_LOCAL_DEZ24
	  WHERE DT_RFRNC = '${REF_DATE}' 
	 ) GAR
	 
	 LEFT JOIN
	 -- LIGAÇÃO COM A TABELA PROPERTY PARA OBTENÇÃO DE CAMPOS CARACTERIZADORES DO BEM
	 (
	  SELECT DISTINCT
	   PROPERTY_BRANCH_CODE, 
	   PROPERTY_CONTRACT_ID, 
	   PROPERTY_REFERENCE_CODE,
	   COUNTRY_CODE 
	  FROM BUSINESS_ASSETS.PROPERTY
	  WHERE DATA_DATE_PART = '${REF_DATE}'
	 ) PROPERTY 
	 ON 
	 --GAR.CEMPBEM = PROPERTY.PROPERTY_BANK_ID AND
	 GAR.CKBALBEM = PROPERTY.PROPERTY_BRANCH_CODE AND 
	 GAR.CKCTABEM = PROPERTY.PROPERTY_CONTRACT_ID AND
	 GAR.CKREFBEM = PROPERTY.PROPERTY_REFERENCE_CODE 
	 
	 LEFT JOIN
	 -- LIGAÇÃO COM A TABELA PROPERTY_ENERGY_CERTIFICATE PARA OBTENÇÃO DE CAMPOS DE CERTIFICADOS ENERGÉTICOS
	 (
	  SELECT *
	  FROM BU_ESG_WORK.PROPERTY_ENERGY_CERTIFICATE
	  WHERE DATA_DATE_PART = '${REF_DATE}'
	 ) CERT_ENERG
	 ON 
	 --GAR.CEMPBEM = CERT_ENERG.PROPERTY_BANK_ID AND
	 GAR.CKBALBEM = CERT_ENERG.PROPERTY_BRANCH_CODE AND 
	 GAR.CKCTABEM = CERT_ENERG.PROPERTY_CONTRACT_ID AND
	 GAR.CKREFBEM = CERT_ENERG.PROPERTY_REFERENCE_CODE
	 
	-- PARA IMPLEMENTAÇÃO DA RÉPLICA DE DEZ24 DEVERÁ SER CONSIDERADO O SEGUINTE PEDAÇO DE CÓDIGO  
	--  (
	--   SELECT *
	--   FROM BU_ESG_WORK.LOCAL_PILAR3_TEMP2_DEZ23
	--  ) CERT_ENERG_PREVIOUS_YEAR
	--  ON CONCAT(COALESCE(GAR.CKBALBEM,'0'),COALESCE(GAR.CKCTABEM,'0'),COALESCE(GAR.CKREFBEM,'0')) = CONCAT(COALESCE(CERT_ENERG_PREVIOUS_YEAR.CKBALBEM,'0'),COALESCE(CERT_ENERG_PREVIOUS_YEAR.CKCTABEM,'0'),COALESCE(CERT_ENERG_PREVIOUS_YEAR.CKREFBEM,'0'))
	--  AND CONCAT(GAR.CEMPRESA,GAR.CBALCAO,GAR.CNUMECTA,GAR.ZDEPOSIT) = CONCAT(CERT_ENERG_PREVIOUS_YEAR.CEMPRESA,CERT_ENERG_PREVIOUS_YEAR.CBALCAO,CERT_ENERG_PREVIOUS_YEAR.CNUMECTA,CERT_ENERG_PREVIOUS_YEAR.ZDEPOSIT)
	 
	 -- PARA IMPLEMENTAÇÃO ESTRUTURAL DEVERÁ SER CONSIDERADO O SEGUINTE PEDAÇO DE CÓDIGO
	 LEFT JOIN
	 (
	     SELECT *
	     FROM BU_ESG_WORK.PROPERTY_ENERGY_CERTIFICATE
	     WHERE DATA_DATE_PART = '${REF_DATE_ANT}'
	 ) CERT_ENERG_PREVIOUS_YEAR
	 ON CONCAT(COALESCE(GAR.CKBALBEM,'0'),COALESCE(GAR.CKCTABEM,'0'),COALESCE(GAR.CKREFBEM,'0')) = CONCAT(COALESCE(CERT_ENERG_PREVIOUS_YEAR.PROPERTY_BRANCH_CODE,'0'),COALESCE(CERT_ENERG_PREVIOUS_YEAR.PROPERTY_CONTRACT_ID,'0'),COALESCE(CERT_ENERG_PREVIOUS_YEAR.PROPERTY_REFERENCE_CODE,'0'))
	 
	 LEFT JOIN
	 -- OBTENÇÃO DE INFORMAÇÃO SOBRE CONTRATOS RENEGOCIADOS/REESTRUTURADOS
	 (
	  SELECT SUBSTR(CONTA,1,4) AS CBALCAO, SUBSTR(CONTA,5,11) AS CNUMECTA, ZDEPOSIT, DATA_INICIO 
	  FROM BU_ESG_WORK.RNM85_RESTR_DEZ24 -- A AJUSTAR PARA CURATED_INTERNAL_MAINFRAME_RECONDUCOES.RNM85_RESTR
	  WHERE UPPER(REFINANCIAMENTO) = 'S' AND UPPER(DIFICULDADES_FINANCEIRAS) = 'N' AND DATA_DATE_PART = '${REF_DATE}'
	 ) AS RENEGOCIADOS
	 ON CONCAT(GAR.CBALCAO,GAR.CNUMECTA,GAR.ZDEPOSIT) = CONCAT(RENEGOCIADOS.CBALCAO,RENEGOCIADOS.CNUMECTA,RENEGOCIADOS.ZDEPOSIT)
	 GROUP BY 
	  GAR.CEMPRESA,
	  GAR.CBALCAO,
	  GAR.CNUMECTA,
	  GAR.ZDEPOSIT,
	  GAR.CKBALBEM, 
	  GAR.CKCTABEM,
	  GAR.CKREFBEM,
	  GAR.CPAIS_RESIDENCIA, 
	  CERT_ENERG.EPC, 
	  CERT_ENERG.QUALITY_SCORE,
	  CERT_ENERG.EP_SCORE,
	  CERT_ENERG_PREVIOUS_YEAR.EP_SCORE,
	  CERT_ENERG_PREVIOUS_YEAR.EPC,
	  RENEGOCIADOS.DATA_INICIO,
	  PROPERTY.COUNTRY_CODE      
) AS B
ON  A.CEMPRESA = B.CEMPRESA
AND A.CBALCAO  = B.CBALCAO
AND A.CNUMECTA = B.CNUMECTA
AND A.ZDEPOSIT = B.ZDEPOSIT

LEFT JOIN 
-- OBTENÇÃO DE INFORMAÇÃO DE TX DE JURO
( 
	 SELECT DISTINCT B.CEMPRESA,  B.CBALCAO, B.CNUMECTA, B.ZDEPOSIT, A.ANNLSD_AGRD_RT AS TX_JURO_LT
	 FROM
	  (
		  SELECT DISTINCT INSTRMNT_ID, ANNLSD_AGRD_RT
		  FROM CD_LOAN_TAPES_BCE.LT002_INSTRUMENT
		  WHERE REF_DATE = '${REF_DATE}' AND 
				UPPER(AMBITO) = 'PM' AND 
				UPPER(NOME_PERIMETRO) = 'INDIVIDUAL LOCAL' AND 
				UPPER(SEGMENTO) = 'ESTR'
  ) A 
 LEFT JOIN
  (SELECT DISTINCT * FROM CD_CAPTOOLS.KT_CHAVES_FINREP WHERE REF_DATE = '${REF_DATE}') B
 ON A.INSTRMNT_ID = CONCAT(B.CEMPRESA_FR,B.CBALCAO_FR,B.CNUMECTA_FR,B.ZDEPOSIT_FR)
) AS C
ON  A.CEMPRESA = C.CEMPRESA
AND A.CBALCAO  = C.CBALCAO
AND A.CNUMECTA = C.CNUMECTA
AND A.ZDEPOSIT = C.ZDEPOSIT

LEFT JOIN
-- OBTENÇÃO DE INFORMAÇÃO DE LTV
(
	 SELECT B.CEMPRESA,  B.CBALCAO, B.CNUMECTA, B.ZDEPOSIT, A.VALOR_LTV 
	 FROM
	  (
		  SELECT DISTINCT CEMPRESA, CBALCAO, CNUMECTA, ZDEPOSIT, VALOR_LTV
		  FROM CD_CAPTOOLS.FR011_CAPS_LTV 
		  WHERE REF_DATE = '${REF_DATE}'
	  ) A 
	 LEFT JOIN
	  (SELECT DISTINCT * FROM CD_CAPTOOLS.KT_CHAVES_FINREP WHERE REF_DATE = '${REF_DATE}') B
	 ON A.CEMPRESA = B.CEMPRESA_FR AND A.CBALCAO= B.CBALCAO_FR AND A.CNUMECTA = B.CNUMECTA_FR AND A.ZDEPOSIT = B.ZDEPOSIT_FR
) AS D
ON  A.CEMPRESA = D.CEMPRESA
AND A.CBALCAO  = D.CBALCAO
AND A.CNUMECTA = D.CNUMECTA
AND A.ZDEPOSIT = D.ZDEPOSIT

LEFT JOIN
(
	SELECT NVL(MAX(ID_CORRIDA),0)+1 AS NEW_ID_CORRIDA
	FROM BU_ESG_WORK.AG02_STE_CTO_GRA
	WHERE REF_DATE = '${REF_DATE}'
) RT
ON 1=1

WHERE `13_GROSS_CARRYING_AMOUNT` IS NOT NULL
;

/*=========================================================================================================================================*/
/*  2. TABELA FINAL: OBTENÇÃO DAS MÉTRICAS AGREGADAS A REPORTAR NO ÂMBITO DO TEMPLATE 2 STE                            */
/*=========================================================================================================================================*/

-- INSERT OVERWRITE TABLE BU_ESG_WORK.AG02_STE_CTO_AGR PARTITION (ID_CORRIDA,REF_DATE)
SELECT
	TIPO_COLATERAL,
	EPC_LABEL,
	EP_SCORE,
	EUROPEAN_UNION,
	ROUND(-SUM(`13_GROSS_CARRYING_AMOUNT`),0) AS AMOUNT,
	QUALITY_SCORE,
	MATURITY_ESG,
	CASE       
		WHEN FLAG_MATURITY = 0  THEN NULL
		WHEN ROUND(-SUM(`13_GROSS_CARRYING_AMOUNT`))*ROUND(AVG(YEARS_TO_MATURITY),0) < 0 THEN 0 -- ZERAR CASOS NEGATIVOS (MATURIDADE NEGATIVA NÃO PODERÁ SER CONSIDERADA)
		ELSE ROUND(-SUM(`13_GROSS_CARRYING_AMOUNT`))*ROUND(AVG(YEARS_TO_MATURITY),0) 
	END AS AVEG_AUX,
	NEW_BUSINESS_FLOW,
	PREVIOUS_YEAR_EP_SCORE,
	PREVIOUS_YEAR_EPC_LABEL,
	FLAG_MATURITY,
	CASE
		WHEN ROUND(-SUM(`13_GROSS_CARRYING_AMOUNT`)) * ROUND(AVG(TX_JURO),2) < 0 THEN 0 -- ZERAR CASOS NEGATIVOS (CONFIRMADO PELA CORPORAÇÃO NO EMAIL DE DIA 28/01/2025)
		ELSE ROUND(-SUM(`13_GROSS_CARRYING_AMOUNT`)) * ROUND(AVG(TX_JURO),2) 
	END AS INTEREST_AUX,
	CASE
		WHEN ROUND(-SUM(`13_GROSS_CARRYING_AMOUNT`)) * ROUND(AVG(VALOR_LTV_DECIMAL),2) < 0 THEN 0 -- ZERAR CASOS NEGATIVOS
		ELSE ROUND(-SUM(`13_GROSS_CARRYING_AMOUNT`)) * ROUND(AVG(VALOR_LTV_DECIMAL),2)
	END AS LTV_AUX,
	COLLATERAL_LTV,
	
	-- PARTICAO
	RT.NEW_ID_CORRIDA AS ID_CORRIDA,
	'${REF_DATE}' AS REF_DATE
    
FROM (SELECT * FROM BU_ESG_WORK.AG02_STE_CTO_GRA WHERE REF_DATE = '${REF_DATE}' AND ID_CORRIDA IN (SELECT MAX(ID_CORRIDA) FROM BU_ESG_WORK.AG02_STE_CTO_GRA WHERE REF_DATE = '${REF_DATE}')) X
LEFT JOIN
(
	SELECT NVL(MAX(ID_CORRIDA),0)+1 AS NEW_ID_CORRIDA
	FROM BU_ESG_WORK.AG02_STE_CTO_AGR
	WHERE REF_DATE = '${REF_DATE}'
) RT
ON 1=1
GROUP BY 1,2,3,4,6,7,9,10,11,12,15,16,17
;





-- -- ADJUDICADOS 
-- -- REGISTOS: 486
-- DROP TABLE IF EXISTS BU_ESG_WORK.ag02_ste_adj_gra;
-- CREATE TABLE BU_ESG_WORK.ag02_ste_adj_gra AS
-- SELECT
--     *,
--     CASE
--         WHEN TRIM(CLASE_ENERGETICA) LIKE 'A%' THEN 'A'
--         WHEN TRIM(CLASE_ENERGETICA) LIKE 'B%' THEN 'B'
--         WHEN TRIM(CLASE_ENERGETICA) LIKE 'C%' THEN 'C'
--         WHEN TRIM(CLASE_ENERGETICA) LIKE 'D%' THEN 'D'
--         WHEN TRIM(CLASE_ENERGETICA) LIKE 'E%' THEN 'E'
--         WHEN TRIM(CLASE_ENERGETICA) LIKE 'F%' THEN 'F'
--         WHEN TRIM(CLASE_ENERGETICA) LIKE 'G%' THEN 'G'
--         ELSE 'SEM DADOS'
--     END AS EPC_LABEL, 
--     CASE 
--         WHEN CONSUMOS <= 100 THEN 'MENOR_100'
--         WHEN CONSUMOS > 100 AND CONSUMOS <= 200 THEN 'MENOR_200'
--         WHEN CONSUMOS > 200 AND CONSUMOS <= 300 THEN 'MENOR_300'
--         WHEN CONSUMOS > 300 AND CONSUMOS <= 400 THEN 'MENOR_400'
--         WHEN CONSUMOS > 400 AND CONSUMOS <= 500 THEN 'MENOR_500'
--         WHEN CONSUMOS > 500 THEN 'MAIOR_500'
--         ELSE 'SEM DADOS'
--     END AS EP_SCORE,
--     'EU-area' AS EUROPEAN_UNION
    
-- FROM 
-- (   
--     SELECT *
--     FROM
--     (
--         SELECT * 
--         FROM BU_ESG_WORK.ADJUDICADOS_DEZ24_FINAL
--         WHERE TIPO_ADJUDICADO <> 'DAÇÕES+ARREMATAÇÕES' AND (CARGABAL_VC IN ('1605000', '1605010') OR CARGABAL_PROV = '2642300')
--     ) X
--     LEFT JOIN
--     (
--         SELECT *
--         FROM BU_ESG_WORK.GLOVAL_CLASE_ENERGETICA_DEZ24
--     ) CERT_ENERG
--     ON COD_IMOVEL = CHAVE_BANCO_ATUAL
-- ) X; 


-- -- TABELA FINAL
-- -- REGISTOS : 30.756
-- DROP TABLE BU_ESG_WORK.LOCAL_PILAR3_STE2_FINAL_DEZ24;
-- CREATE TABLE BU_ESG_WORK.LOCAL_PILAR3_STE2_FINAL_DEZ24 AS
-- SELECT 
--     'STOCK' AS TIPO_COLATERAL,
--     EPC_LABEL,
--     EP_SCORE,
--     EUROPEAN_UNION,
--     ROUND(SUM(VALOR_CARGABAL_VC)) AS AMOUNT,
--     FIABILIDAD,
--     TIPO_ADJUDICADO AS `32_TYPE_COLLATERAL`,
--     NULL AS MATURITY,
--     '' AS NEW_BUSINESS_FLOW,
--     '' AS PREVIOUS_YEAR_EP_SCORE,
--     '' AS PREVIOUS_YEAR_EPC_LABEL,
--     '' AS COLLATERAL_LTV,
--     NULL AS INTEREST,
--     NULL AS LOAN_TO_VALUE
-- FROM BU_ESG_WORK.LOCAL_PILAR3_STE2_ADJ_DEZ24
-- GROUP BY 1, 2, 3, 4, 6, 7,8,9,10,11,12,13,14

-- UNION ALL

-- SELECT
--     TIPO_COLATERAL,
--     EPC_LABEL,
--     EP_SCORE,
--     EUROPEAN_UNION,
--     ROUND(-SUM(`13_GROSS_CARRYING_AMOUNT`)) AS AMOUNT,
--     FIABILIDAD,
--     `32_TYPE_COLLATERAL`,
--     ROUND(YEARS_TO_MATURITY,0) AS MATURITY,
--     NEW_BUSINESS_FLOW,
--     PREVIOUS_YEAR_EP_SCORE,
--     PREVIOUS_YEAR_EPC_LABEL,
--     COLLATERAL_LTV,
--     ROUND(TX_JURO,2) AS INTEREST,
--     ROUND(VALOR_LTV_DECIMAL,2) AS LOAN_TO_VALUE   
-- FROM BU_ESG_WORK.LOCAL_PILAR3_STE2_AUX1_DEZ24
-- GROUP BY 1,2,3,4,6,7,8,9,10,11,12,13,14
-- ;