-----------------------------------------------------------------------------------------------------------------------
--------------------------- Nova criação de universo auxiliar de rentabilidade ----------------------------------------
----------------------------------------------------------------------------------------------------------------------


-- Passo 0: Passo apenas necessário até que seja reprocessada a tabela ct831 com a informação necessária
-- e esclarecida em sede de reunião com o LCM

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.CT831_AUX;
CREATE TABLE BU_CAPTOOLS_WORK.CT831_AUX AS

SELECT DISTINCT METAPRODUTO
FROM CD_CAPTOOLS.CT831_CLASS_META
WHERE REF_DATE = '${DATE}'
AND AMBITO = 'CDG'
AND UPPER(TIPO_CONTA_LOCAL) NOT LIKE "%PASSIVO%"
AND TRIM(METAPRODUTO) <> ''
;

INSERT INTO BU_CAPTOOLS_WORK.CT831_AUX (METAPRODUTO)
VALUES ('SO2001') , ('SO201A') ,('SO202A') ,('SO2035'),('SO2036'),('SO2037'),('SO2042'),('AAAAAA'),
('SO20T1'),('SO20T2'),('SO20T3'),('SO20T4'),('SO20T5'),('SO20T6'),('SO20T7');

-- Passo 1: Cruzamento entre as tabelas ct209 e ct831 
-- # Registos: 3 292 619 
DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.UNIV_RENTAB_JAN25_1;
CREATE TABLE BU_CAPTOOLS_WORK.UNIV_RENTAB_JAN25_1 AS

SELECT DISTINCT * 
FROM 
    (
    SELECT 
        CEMPCTA AS CEMPCTA_CT209 , 
        CKBALCAO AS CKBALCAO_CT209, 
        CKNUMCTA AS CKNUMCTA_CT209, 
        ZDEPOSIT AS ZDEPOSIT_CT209,
        CKPRODMI AS CKPRODMI_CT209,
        ZSEQDIV AS ZSEQDIV_CT209,
        CHCRUZA AS CHCRUZA_CT209,
        CKMETAMIS AS CKMETAMIS_CT209,
        ZCLIENTE AS ZCLIENTE_CT209,
        SUM(C001) AS C001,
        SUM(C007) AS C007, 
        SUM(C008) AS C008,
        SUM(C011) AS C011, 
        SUM(C134) AS C134, 
        SUM(C224) AS C224,
        SUM(C295) AS C295,
        SUM(C298) AS C298, 
        SUM(C299) AS C299, 
        SUM(C300) AS C300, 
        SUM(M009) AS M009, 
        SUM(AC310) AS AC310
        
    FROM CD_CAPTOOLS.CT209_RENT_KPM
    WHERE REF_DATE = '${DATE}'
    AND ORIGEM NOT IN ('CAPITAL', 'CONTABILIDADE')
    AND C325=0
    AND C453=0
    GROUP BY 1,2,3,4,5,6,7,8,9
    ) CT209 

INNER JOIN 
-- processo alternativo até ser carregada a tabela ct831 com os metamis adicionados conforme validado em reuniao com LCM
(select distinct * from BU_CAPTOOLS_WORK.CT831_AUX) ct831 
--  (
-- 	SELECT DISTINCT METAPRODUTO
-- 	FROM CD_CAPTOOLS.CT831_CLASS_META
-- 	WHERE REF_DATE = '${DATE}'
-- 	AND AMBITO = 'CDG'
-- 	AND UPPER(TIPO_CONTA_LOCAL) NOT LIKE "%PASSIVO%"
-- 	AND TRIM(METAPRODUTO) <> ''
--     ) CT831
    
ON CT209.CKMETAMIS_CT209 <=> CT831.METAPRODUTO
;

-- Passo 2:Cruzamento entre as tabelas ct211 e ct831
-- # Registos: 1 480 597
-- # Registos: 694 038
-- Create table: 1 480 597 
DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.UNIV_RENTAB_JAN25_2;
CREATE TABLE BU_CAPTOOLS_WORK.UNIV_RENTAB_JAN25_2 AS

--  SELECT COUNT (DISTINCT CEMPCTA, CKBALCAO, CKNUMCTA,ZDEPOSIT) FROM (
select distinct * 
from 
    (
    SELECT  
        CEMPCTA as CEMPCTA_CT211, 
        CKBALCAO AS CKBALCAO_CT211, 
        CKNUMCTA AS CKNUMCTA_CT211, 
        ZDEPOSIT AS ZDEPOSIT_CT211,
        CKPRODMI AS CKPRODMI_CT211,
        ZSEQDIV AS ZSEQDIV_CT211,
        CHCRUZA AS CHCRUZA_CT211,
        CMETACOM AS CMETACOM_CT211,
        ZCLIENTE AS ZCLIENTE_CT211,
        SUM(C457) AS C457,
        SUM(C458) AS C458,
        SUM(C459) AS C459,
        SUM(C460) AS C460
    
    FROM CD_CAPTOOLS.CT211_RENT_KPMCO
    WHERE REF_DATE = '${DATE}'
    AND ORIGEM NOT IN ('CAPITAL', 'CONTABILIDADE')
    AND (ABS(C457)+ABS(C458)+ABS(C459)+ABS(C460)) <> 0 
    GROUP BY 1,2,3,4,5,6,7,8,9
    ) CT211
inner join 
    (
	SELECT DISTINCT METACOMISSAO, TIPO_CONTA_LOCAL, AMBITO
	FROM CD_CAPTOOLS.CT831_CLASS_META
	WHERE REF_DATE = '${DATE}'
	AND AMBITO = 'CDG'
	AND UPPER(TIPO_CONTA_LOCAL) NOT LIKE "%PASSIVO%"
	AND TRIM(METACOMISSAO) <> ''
    ) CT831

on CT831.METACOMISSAO = CT211.CMETACOM_CT211
-- ) A
;

--Passo 3: Full join entre passo 1 e passo 2
-- # Registos: 4 108 779

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.UNIV_RENTAB_JAN25_3;
CREATE TABLE BU_CAPTOOLS_WORK.UNIV_RENTAB_JAN25_3 AS

SELECT DISTINCT
    COALESCE(CEMPCTA_CT209,CEMPCTA_CT211) AS CEMPCTA,
    COALESCE(CKBALCAO_CT209,CKBALCAO_CT211) AS CKBALCAO, 
    COALESCE(CKNUMCTA_CT209, CKNUMCTA_CT211) AS CKNUMCTA, 
    COALESCE(ZDEPOSIT_CT209,ZDEPOSIT_CT211) AS ZDEPOSIT, 
    COALESCE(ZSEQDIV_CT209,ZSEQDIV_CT211) AS ZSEQDIV, 
    COALESCE(ZCLIENTE_CT209, ZCLIENTE_CT211) AS ZCLIENTE,
    COALESCE(CKPRODMI_CT209,CKPRODMI_CT211) AS CKPRODMI, 
    COALESCE(CHCRUZA_CT209,CHCRUZA_CT211) AS CHCRUZA,
    -- CAMPOS CT209 
    C001,
    C007,
    C008,
    C011,
    C134,
    C224,
    C295,
    C298,
    C299,
    C300,
    M009,
    AC310,
    METAPRODUTO,
    -- CAMPOS CT211
    C457,
    C458,
    C459,
    C460,
    METACOMISSAO,
    TIPO_CONTA_LOCAL
FROM BU_CAPTOOLS_WORK.UNIV_RENTAB_JAN25_1 A
FULL JOIN BU_CAPTOOLS_WORK.UNIV_RENTAB_JAN25_2 B 
    
ON A.CEMPCTA_CT209=B.CEMPCTA_CT211
AND A.CKBALCAO_CT209=B.CKBALCAO_CT211
AND A.CKNUMCTA_CT209=B.CKNUMCTA_CT211
AND A.ZDEPOSIT_CT209=B.ZDEPOSIT_CT211
AND A.ZSEQDIV_CT209=B.ZSEQDIV_CT211 -- 
AND A.ZCLIENTE_CT209=B.ZCLIENTE_CT211
AND A.CKPRODMI_CT209=B.CKPRODMI_CT211
AND A.CHCRUZA_CT209=B.CHCRUZA_CT211 -- 
;

-- Passo 4: Cruzar o passo 3 com a tabela ct207 para trazer a ckarea
-- # Registos: 4 108 783 
DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.UNIV_RENTAB_JAN25_4;
CREATE TABLE BU_CAPTOOLS_WORK.UNIV_RENTAB_JAN25_4 AS

SELECT DISTINCT BASE.* , CT207.CKAREA
FROM BU_CAPTOOLS_WORK.UNIV_RENTAB_JAN25_3 BASE

LEFT JOIN 

(SELECT DISTINCT CEMPCTA, CKBALCAO, CKNUMCTA, ZDEPOSIT, ZSEQDIV, ZCLIENTE, CKPRODMI,CHCRUZA, CKAREA
FROM CD_CAPTOOLS.CT207_RENT_OVER
WHERE REF_DATE = '${DATE}'
AND ORIGEM NOT IN ('CAPITAL', 'CONTABILIDADE')) CT207

ON BASE.CEMPCTA = CT207.CEMPCTA
AND BASE.CKBALCAO = CT207.CKBALCAO
AND BASE.CKNUMCTA = CT207.CKNUMCTA
AND BASE.ZDEPOSIT = CT207.ZDEPOSIT
AND BASE.ZSEQDIV = CT207.ZSEQDIV
AND BASE.ZCLIENTE = CT207.ZCLIENTE 
AND BASE.CKPRODMI = CT207.CKPRODMI 
AND BASE.CHCRUZA = CT207.CHCRUZA
-- AND BASE.METAPRODUTO = CT207.CKMETAMIS -- Não cruzei por metaproduto por causa dos registos a NULL que temos para os contratos que só têm metacomissão 
;

-- Passo 5: Cruzar passo 4 com CT201 para trazer o DINIOPER 
-- # Registos: 4 108 783 
-- Continuamos sem considerar o cruzamento pelo zcliente ? 

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.UNIV_RENTAB_JAN25_5;
CREATE TABLE BU_CAPTOOLS_WORK.UNIV_RENTAB_JAN25_5 AS

-- select 
-- * from ( 
-- count(distinct cempcta, ckbalcao, cknumcta,zdeposit) from (
SELECT DISTINCT
    BASE.*,
    CT201.DINIOPER
FROM BU_CAPTOOLS_WORK.UNIV_RENTAB_JAN25_4 BASE 

LEFT JOIN 
    (
    SELECT DISTINCT * 
    FROM CD_CAPTOOLS.CT201_RENT_CONT 
    WHERE REF_DATE='${DATE}'
    AND ORIGEM NOT IN ('CAPITAL','CONTABILIDADE')
    AND CKPRODMI NOT LIKE '0C%' 
    AND CKPRODMI NOT LIKE 'AB%' 
    AND CKPRODMI NOT LIKE '0EF%' 
    AND CKPRODMI NOT LIKE 'SBA%' 
    -- and concat (CEMPCTA,CKBALCAO,CKNUMCTA,ZDEPOSIT) = '31003187955910011660314100000001' -- ckprodmi diferente 
    -- and concat (CEMPCTA,CKBALCAO,CKNUMCTA,ZDEPOSIT) = '31000001614195001000000000000000' -- Apresenta ativo e passivo + chcruza diferente 
    -- and concat (CEMPCTA,CKBALCAO,CKNUMCTA,ZDEPOSIT)= '31000300125424007100087533980000' -- Nao existe na ct201, mesmo retirando os filtros 
    -- and concat (CEMPCTA,CKBALCAO,CKNUMCTA) ='31000020230000106' -- apenas existe se cruzarmos sem considerar o zdeposit
    -- and concat (CEMPCTA,CKBALCAO,CKNUMCTA)='31003000595102900' --zdeposit = '000000000000000'
    -- and cempcta ='31' and ckbalcao='0003' and cknumcta ='04408638096' and zdeposit='000000000000000' -- ZSEQDIV diferente 
    -- and concat (CEMPCTA,CKBALCAO,CKNUMCTA,ZDEPOSIT) like '3100030000001500710008667471000%'
    ) CT201
ON BASE.CEMPCTA=CT201.CEMPCTA
AND BASE.CKBALCAO=CT201.CKBALCAO
AND BASE.CKNUMCTA=CT201.CKNUMCTA
AND BASE.ZDEPOSIT=CT201.ZDEPOSIT
AND BASE.ZSEQDIV=CT201.ZSEQDIV
AND BASE.CKPRODMI=CT201.CKPRODMI
AND BASE.CHCRUZA=CT201.CHCRUZA
-- ) x
-- where dinioper is null 
-- where  concat (CEMPCTA,CKBALCAO,CKNUMCTA,ZDEPOSIT) = '31003187955910011660314100000001'
-- where concat (CEMPCTA,CKBALCAO,CKNUMCTA,ZDEPOSIT) = '31000001614195001000000000000000' 
-- where  cempcta ='31' and ckbalcao='0003' and cknumcta ='04408638096' and zdeposit='000000000000000'
;

-- Passo 6: Cruzar passo 5 com os tradutores para trazer a chave FINREP 
-- # Registos: 4 257 550 
DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.UNIV_RENTAB_JAN25_6;
CREATE TABLE BU_CAPTOOLS_WORK.UNIV_RENTAB_JAN25_6 AS

SELECT 
    BASE.*, 
    TRAD.CEMPRESA_FR, 
    TRAD.CBALCAO_FR, 
    TRAD.CNUMECTA_FR, 
    TRAD.ZDEPOSIT_FR
FROM BU_CAPTOOLS_WORK.UNIV_RENTAB_JAN25_5 BASE
LEFT JOIN 
    (
    SELECT DISTINCT  
        FINREP.REF_DATE,
        FINREP.CEMPRESA_FR, 
        FINREP.CBALCAO_FR, 
        FINREP.CNUMECTA_FR, 
        FINREP.ZDEPOSIT_FR,
        MIS.CEMPCTA,
        MIS.CKBALCAO,
        MIS.CKNUMCTA,
        MIS.ZDEPOSIT_MIS
    FROM 
        (SELECT DISTINCT * 
        FROM CD_CAPTOOLS.KT_CHAVES_MIS
        WHERE REF_DATE = '${DATE}') MIS
        
    INNER JOIN 
        
        (SELECT DISTINCT *
        FROM CD_CAPTOOLS.KT_CHAVES_FINREP 
        WHERE REF_DATE = '${DATE}') FINREP
        
    ON  FINREP.CEMPRESA= MIS.CEMPRESA
    AND  FINREP.CBALCAO= MIS.CBALCAO
    AND  FINREP.CNUMECTA= MIS.CNUMECTA
    AND  FINREP.ZDEPOSIT= MIS.ZDEPOSIT
    ) TRAD 
ON TRAD.CEMPCTA = BASE.CEMPCTA
AND TRAD.CKBALCAO = BASE.CKBALCAO
AND TRAD.CKNUMCTA = BASE.CKNUMCTA
AND TRAD.ZDEPOSIT_MIS = BASE.ZDEPOSIT
;
    

---------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------- Universo LT - Green Dashboard -------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------
-- UNIVERSO PARTE 1: UNIVERSO COMUM COM PM

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE1;

CREATE TABLE BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE1 AS

SELECT *
FROM CD_LOAN_TAPES_BCE.LT002_INSTRUMENT
WHERE REF_DATE = '${DATE}'
AND AMBITO = 'PM'
AND SEGMENTO = 'ESTR'
AND NOME_PERIMETRO = 'Individual Corporativo' 
-- AND ENTIDADE = '00100'
-- AND SUBSTRING(INSTRMNT_ID,1,2) IN ('80', '31') -- 31: SANTANDER & 80: TOTTA IRELAND 
;

-----------------------------------------------------
-- UNIVERSO PARTE 2: UNIVERSO DE CONTRATOS CANCELADOS

-- UNIVERSO AUXILIXAR: CONTRATOS DE CDG QUE FORAM CANCELADOS AO LONGO DO ANO,
-- OU SEJA, PARA CADA MÊS DO ANO DE REPORTE ANALISAR OS CONTRATOS QUE NÃO TINHAM SALDO PONTUAL MAS TINHAM RENTABILIDADE

-- SELEÇÃO DAS OPERAÇÕES COM RENTABILIDADE E QUE NÃO TÊM POSIÇÃO DE FIM DE MÊS (C007=0); E NÃO TÊM CHAVE FINREP PARA O MÊS DE REPORTE

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE2_AUX1;

CREATE TABLE BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE2_AUX1 AS

SELECT DISTINCT KT_MIS.*
FROM 
    (
    SELECT * 
    FROM CD_CAPTOOLS.KT_CHAVES_MIS 
    WHERE REF_DATE='${DATE}'
    ) KT_MIS
    
INNER JOIN 
    (
    SELECT * 
    FROM CD_CAPTOOLS.CT209_RENT_KPM 
    WHERE REF_DATE='${DATE}' 
    AND C001<>0 
    AND C007=0 
    AND (ABS(C001) + ABS(C007) + ABS(C134) + ABS(C224) + ABS(C298) + ABS(C299) + ABS(C300) + ABS(AC310) + ABS(M009)) <> 0
    AND ORIGEM NOT IN ('CAPITAL','CONTABILIDADE')
    ) CT209

ON KT_MIS.CEMPCTA=CT209.CEMPCTA
AND KT_MIS.CKBALCAO=CT209.CKBALCAO
AND KT_MIS.CKNUMCTA=CT209.CKNUMCTA
AND KT_MIS.ZDEPOSIT_MIS=CT209.ZDEPOSIT

INNER JOIN 
    (
	SELECT DISTINCT METAPRODUTO 
	FROM CD_CAPTOOLS.CT831_CLASS_META
	WHERE REF_DATE = '${DATE}' 
	AND AMBITO = 'CDG'
	AND LOWER(TIPO_CONTA_LOCAL) NOT LIKE "%PASSIVO%"
	AND TRIM(METAPRODUTO) <> ''
    ) CT831
    
ON CT209.CKMETAMIS <=> CT831.METAPRODUTO

LEFT JOIN 
    (
    SELECT * 
    FROM CD_CAPTOOLS.KT_CHAVES_FINREP 
    WHERE REF_DATE = '${DATE}'
    -- WHERE REF_DATE BETWEEN '${DATE_INI}' AND '${DATE}' -- DURANTE O ANO DE REPORTE
    -- WHERE CONCAT(CEMPRESA, cbalcao, cnumecta, zdeposit) = '89000020140001123001520230387637'
    -- ORDER BY ref_date DESC
    ) FR_ATU

ON KT_MIS.CEMPRESA=FR_ATU.CEMPRESA
AND KT_MIS.CBALCAO=FR_ATU.CBALCAO
AND KT_MIS.CNUMECTA=FR_ATU.CNUMECTA
AND KT_MIS.ZDEPOSIT=FR_ATU.ZDEPOSIT

WHERE FR_ATU.CEMPRESA IS NULL
;

-- IDENTIFICAÇÃO DO UNIVERSO CANCELADO QUE SE ENCONTRAVA VIVO NO MÊS ANTERIOR (EXISTE NO TRADUTOR DO MÊS ANTERIOR),
-- E CRUZAMENTO COM A LT001 PARA NÃO TRAZER CHAVES QUE JÁ SE ENCONTRAM NO UNIVERSO DA CONTABILIDADE

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE2_AUX2;

CREATE TABLE BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE2_AUX2  AS 

SELECT DISTINCT 
    UNI.CEMPCTA, 
    UNI.CKBALCAO, 
    UNI.CKNUMCTA, 
    UNI.ZDEPOSIT_MIS, 
    KT_FR.CEMPRESA_FR, 
    KT_FR.CBALCAO_FR, 
    KT_FR.CNUMECTA_FR, 
    KT_FR.ZDEPOSIT_FR,
    '${DATE}' AS REF_DATE,
    'GD' AS AMBITO,
    'ESTR' AS SEGMENTO, 
    '1' AS ZCLIENTE

FROM BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE2_AUX1 UNI

INNER JOIN 
    (
    SELECT * 
    FROM CD_CAPTOOLS.KT_CHAVES_FINREP 
    WHERE REF_DATE='${DATE_ANT}'
    ) KT_FR
    
ON UNI.CEMPRESA=KT_FR.CEMPRESA
AND UNI.CBALCAO=KT_FR.CBALCAO
AND UNI.CNUMECTA=KT_FR.CNUMECTA
AND UNI.ZDEPOSIT=KT_FR.ZDEPOSIT

LEFT JOIN 
    (
    SELECT *
    FROM CD_LOAN_TAPES_BCE.LT001_UNIV_OPER
    WHERE REF_DATE ='${DATE}'
    AND AMBITO = 'PM'
    AND NOME_PERIMETRO = 'Individual Corporativo'
    AND SEGMENTO = 'ESTR' 
    -- AND ENTIDADE = '00100'
    -- AND CEMPRESA IN ('80', '31') -- 31: SANTANDER & 80: TOTTA IRELAND 
    ) LT001
    
ON LT001.CEMPRESA = KT_FR.CEMPRESA_FR
AND LT001.CBALCAO = KT_FR.CBALCAO_FR
AND LT001.CNUMECTA = KT_FR.CNUMECTA_FR
AND LT001.ZDEPOSIT = KT_FR.ZDEPOSIT_FR

WHERE LT001.CEMPRESA IS NULL
;

-- IDENTIFICAÇÃO DA CHAVE FINREP PARA O UNIVERSO CANCELADO QUE NÃO TINHA SIDO APANHADO NO PROCESSO ANTERIOR,
-- E CRUZAMENTO COM A LT001 PARA NÃO TRAZER CHAVES QUE JÁ SE ENCONTRAM NO UNIVERSO DA CONTABILIDADE

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE2_AUX3;

CREATE TABLE BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE2_AUX3  AS 

SELECT DISTINCT 
    CEMPCTA, 
    CKBALCAO, 
    CKNUMCTA, 
    ZDEPOSIT_MIS, 
    CEMPRESA_FR, 
    CBALCAO_FR, 
    CNUMECTA_FR, 
    ZDEPOSIT_FR,
    '${DATE}' AS REF_DATE,
    'GD' AS AMBITO,
    'ESTR' AS SEGMENTO, 
    '2' AS ZCLIENTE

FROM 
    (
    SELECT CEMPCTA, CKBALCAO, CKNUMCTA, ZDEPOSIT_MIS, CEMPRESA_FR, CBALCAO_FR, CNUMECTA_FR, ZDEPOSIT_FR
    FROM 
        (
        SELECT UNI.CEMPCTA, UNI.CKBALCAO, UNI.CKNUMCTA, UNI.ZDEPOSIT_MIS, KT_FR.CEMPRESA_FR, KT_FR.CBALCAO_FR, KT_FR.CNUMECTA_FR, KT_FR.ZDEPOSIT_FR,
        DENSE_RANK() OVER (PARTITION BY UNI.CEMPCTA, UNI.CKBALCAO, UNI.CKNUMCTA, UNI.ZDEPOSIT_MIS ORDER BY KT_FR.REF_DATE DESC) NROW
        
        FROM BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE2_AUX1 UNI
        INNER JOIN 
            (
            SELECT *
            FROM CD_CAPTOOLS.KT_CHAVES_FINREP 
            WHERE REF_DATE<'${DATE_ANT}' 
            ) KT_FR
            
        ON UNI.CEMPRESA=KT_FR.CEMPRESA
        AND UNI.CBALCAO=KT_FR.CBALCAO
        AND UNI.CNUMECTA=KT_FR.CNUMECTA
        AND UNI.ZDEPOSIT=KT_FR.ZDEPOSIT
        
        LEFT JOIN BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE2_AUX2 UNI_MORTO
        
        ON UNI.CEMPCTA=UNI_MORTO.CEMPCTA
        AND UNI.CKBALCAO=UNI_MORTO.CKBALCAO
        AND UNI.CKNUMCTA=UNI_MORTO.CKNUMCTA
        AND UNI.ZDEPOSIT_MIS=UNI_MORTO.ZDEPOSIT_MIS
        
        WHERE  UNI_MORTO.CEMPCTA IS NULL
        ) AUX
    
    WHERE AUX.NROW=1
    ) BASE

LEFT JOIN 
    (
    SELECT *
    FROM CD_LOAN_TAPES_BCE.LT001_UNIV_OPER
    WHERE REF_DATE ='${DATE}'
    AND AMBITO = 'PM'
    AND NOME_PERIMETRO = 'Individual Corporativo'
    AND SEGMENTO = 'ESTR' 
    -- AND ENTIDADE = '00100'
    -- AND CEMPRESA IN ('80', '31') -- 31: SANTANDER & 80: TOTTA IRELAND 
    ) LT001

ON LT001.CEMPRESA = BASE.CEMPRESA_FR
AND LT001.CBALCAO = BASE.CBALCAO_FR
AND LT001.CNUMECTA = BASE.CNUMECTA_FR
AND LT001.ZDEPOSIT = BASE.ZDEPOSIT_FR

WHERE LT001.CEMPRESA IS NULL
;

-- IDENTIFICAÇÃO DOS CONTRATOS CANCELADOS QUE NÃO FORAM APANHADOS EM NENHUM DOS OUTROS PASSOS E QUE POR ISSO NÃO APRESENTAM CHAVE FINREP, 
-- NESTE SENTIDO A CHAVE FINREP IRÁ CORRESPONDER À CHAVE MIS
-- E CRUZAMENTO COM A LT001 PARA NÃO TRAZER CHAVES QUE JÁ SE ENCONTRAM NO UNIVERSO DA CONTABILIDADE

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE2_AUX4;

CREATE TABLE BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE2_AUX4  AS 

SELECT DISTINCT 
    UNI.CEMPCTA, 
    UNI.CKBALCAO, 
    UNI.CKNUMCTA, 
    UNI.ZDEPOSIT_MIS,
    UNI.CEMPCTA AS CEMPRESA_FR, 
    UNI.CKBALCAO AS CBALCAO_FR, 
    UNI.CKNUMCTA AS CNUMECTA_FR, 
    UNI.ZDEPOSIT_MIS AS ZDEPOSIT_FR,
    '${DATE}' AS REF_DATE,
    'GD' AS AMBITO,
    'ESTR' AS SEGMENTO, 
    '3' AS ZCLIENTE
    
FROM BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE2_AUX1 UNI

LEFT JOIN BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE2_AUX2  UNI_MORTO

ON UNI.CEMPCTA=UNI_MORTO.CEMPCTA
AND UNI.CKBALCAO=UNI_MORTO.CKBALCAO
AND UNI.CKNUMCTA=UNI_MORTO.CKNUMCTA
AND UNI.ZDEPOSIT_MIS=UNI_MORTO.ZDEPOSIT_MIS

LEFT JOIN BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE2_AUX3 UNI_VIVO_MORTO

ON UNI.CEMPCTA=UNI_VIVO_MORTO.CEMPCTA
AND UNI.CKBALCAO=UNI_VIVO_MORTO.CKBALCAO
AND UNI.CKNUMCTA=UNI_VIVO_MORTO.CKNUMCTA
AND UNI.ZDEPOSIT_MIS=UNI_VIVO_MORTO.ZDEPOSIT_MIS

LEFT JOIN 
    ( 
    SELECT *
    FROM CD_LOAN_TAPES_BCE.LT001_UNIV_OPER
    WHERE REF_DATE ='${DATE}'
    AND AMBITO = 'PM'
    AND NOME_PERIMETRO = 'Individual Corporativo'
    AND SEGMENTO = 'ESTR' 
    -- AND ENTIDADE = '00100'
    -- AND CEMPRESA IN ('80', '31') -- 31: SANTANDER & 80: TOTTA IRELAND 
    ) LT001
ON LT001.CEMPRESA = UNI.CEMPCTA
AND LT001.CBALCAO = UNI.CKBALCAO
AND LT001.CNUMECTA = UNI.CKNUMCTA
AND LT001.ZDEPOSIT = UNI.ZDEPOSIT_MIS

WHERE UNI_MORTO.CEMPCTA IS NULL AND UNI_VIVO_MORTO.CEMPCTA IS NULL AND LT001.CEMPRESA IS NULL
;

-- AGREGAÇÃO DAS VÁRIAS TABELAS AUXILIARES REFERENTES AO PASSO 2

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE2;

CREATE TABLE BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE2  AS 

SELECT *
FROM BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE2_AUX2 
UNION ALL
SELECT *
FROM BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE2_AUX3
UNION ALL
SELECT *
FROM BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE2_AUX4
;

-- ANÁLISE DA CORRESPONDENCIA ENTRE O CÓDIGO DE EMPRESAS DAS CHAVES MIS COM AS CHAVES FINREP
SELECT DISTINCT CEMPCTA, CEMPRESA_FR
FROM BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE2 
;


-- JUNÇÃO DO UNIVERSO DA PARTE 1 (UNIV PM) E PARTE 2 (UNIV CANCELADOS COM CHAVE MIS ASSOCIADA)

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE1_2;

CREATE TABLE BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE1_2  AS 

SELECT *
FROM
    (
    SELECT DISTINCT 'COMUM PM' AS UNIV, '${DATE}' AS REF_DATE, 'GD' AS AMBITO, 'ESTR' AS SEGMENTO, INSTRMNT_ID, 'TBD' AS CEMPCTA, 'TBD' AS CKBALCAO, 'TBD' AS CKNUMCTA, 'TBD' AS ZDEPOSIT_MIS
    FROM BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE1
    ) AS PART1

UNION ALL
SELECT *
FROM 
    (
    SELECT DISTINCT 'CANCELADOS' AS UNIV, '${DATE}' AS REF_DATE, 'GD' AS AMBITO, 'ESTR' AS SEGMENTO, CONCAT(CEMPRESA_FR, CBALCAO_FR, CNUMECTA_FR, ZDEPOSIT_FR) AS INSTRMNT_ID, CEMPCTA, CKBALCAO, CKNUMCTA, ZDEPOSIT_MIS
    FROM BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE2
    ) AS PART2
;


-- ATRIBUIÇÃO DA CHAVE MIS AO UNIVERSO DE PM
-- # Registos: 2 924 517 
DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE1_2_FINAL_v2;

CREATE TABLE BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE1_2_FINAL_v2 AS 

SELECT DISTINCT
    BASE.UNIV,
    BASE.REF_DATE,
    BASE.AMBITO,
    BASE.SEGMENTO,
    BASE.INSTRMNT_ID,
    CASE WHEN UNIV='CANCELADOS' THEN BASE.CEMPCTA ELSE univ_rent.CEMPCTA END AS CEMPCTA,
    CASE WHEN UNIV='CANCELADOS' THEN BASE.CKBALCAO ELSE univ_rent.CKBALCAO END AS CKBALCAO,
    CASE WHEN UNIV='CANCELADOS' THEN BASE.CKNUMCTA ELSE univ_rent.CKNUMCTA END AS CKNUMCTA,
    CASE WHEN UNIV='CANCELADOS' THEN BASE.ZDEPOSIT_MIS ELSE univ_rent.ZDEPOSIT END AS ZDEPOSIT_MIS
    
FROM BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE1_2 BASE

LEFT JOIN BU_CAPTOOLS_WORK.UNIV_RENTAB_JAN25_6 UNIV_RENT

ON BASE.INSTRMNT_ID=CONCAT(UNIV_RENT.CEMPRESA_FR, UNIV_RENT.CBALCAO_FR, UNIV_RENT.CNUMECTA_FR, UNIV_RENT.ZDEPOSIT_FR)
;

-- ANÁLISE DOS REGISTOS COMUNS COM PM PARA OS QUAIS NÃO FOI POSSÍVEL ATRIBUIR UMA CHAVE MIS 
-- # REGISTOS: 139 (DOS QUAIS 19 REFEREM-SE A AJUSTES)

SELECT COUNT(DISTINCT INSTRMNT_ID)
FROM BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE1_2_FINAL_v2
WHERE UNIV = 'COMUM PM'
AND ZDEPOSIT_MIS IS NULL
AND INSTRMNT_ID LIKE 'S%'
;

-------------------
-- UNIVERSO PARTE 3

-- JUNÇÃO DAS BUSINESS AREAS PARA POSTERIOR CRIAÇÃO DE NOVA CHAVE PARA AS LINHAS ADICIONAIS DAS BA
-- # Registos: 2 924 824 
-- Não fiz drop da tabela anterior que tinha o nome: UNIV_LT_GD_PARTE3_AUX1 

-- Temos 6 410 registos que apresentam ckarea a NULL (e consequentemente BA a NULL) 
-- pois os registos não se encontram nas tabelas de rentabilidade 
DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE3_1;
CREATE TABLE BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE3_1  AS 

SELECT DISTINCT
    BASE.*,
    -- UNIV_RENTAB.CKMETAMIS,
    UNIV_RENTAB.CKAREA,
    CASE
        WHEN CKAREA IN ('BP','AN01010100','AN01050000') THEN 'BA1'
        WHEN CKAREA IN ('BC1015','AN01010201','AN01010500') THEN 'BA2'
        WHEN CKAREA IN ('AN01020210') THEN 'BA3'
        WHEN CKAREA IN ('BC1014','AN01020410','AN01020200') THEN 'BA4'
        WHEN CKAREA IN ('AN01040220') THEN 'BA5'
        WHEN CKAREA IN ('FC','AN06010000','AN06020000','AN06030000') THEN 'BA6'
        WHEN CKAREA IN ('AN02050600') THEN 'BA7'
        WHEN CKAREA IN ('GB0510','AN02050500','AN02050900') THEN 'BA8'
        WHEN CKAREA IN ('AN02050800') THEN 'BA9'
        WHEN CKAREA IN ('AN02030300') THEN 'BA10'
        WHEN CKAREA IN ('AN02030400') THEN 'BA11'
        WHEN CKAREA IN ('AN02030200') THEN 'BA12'
        WHEN CKAREA IN ('AN02010200') THEN 'BA13'
        WHEN CKAREA IN ('AN02030600') THEN 'BA14'
        WHEN CKAREA IN ('AN02020100') THEN 'BA15'
        WHEN CKAREA IN ('AN02020300') THEN 'BA16'
        WHEN CKAREA IN ('AN02020200') THEN 'BA17'
        WHEN CKAREA IN ('AN02020400') THEN 'BA18'
        WHEN CKAREA IN ('AN02030045') THEN 'BA20'
        WHEN CKAREA IN ('AC05','AN04010500','AN04010600','AN04010100','AN04010400','AN04010700') THEN 'BA21'
        WHEN CKAREA IN ('AN04030000') THEN 'BA22'
        WHEN CKAREA IN ('AN02040100') THEN 'BA23'
        WHEN CKAREA IN ('AN02040200') THEN 'BA24'
        WHEN CKAREA IN ('AN02040300') THEN 'BA25'
        WHEN CKAREA IN ('AN02040400') THEN 'BA26'
        WHEN CKAREA IN ('AN02040600') THEN 'BA27'
        WHEN CKAREA IN ('AN02050100') THEN 'BA28'
        WHEN CKAREA IN ('AN02040700') THEN 'BA29'
        WHEN CKAREA IN ('AN02050400') THEN 'BA30'
        WHEN CKAREA IN ('AN02030900') THEN 'BA31'
        ELSE 'ANALISE'
    END AS BSNSS_AREA

FROM BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE1_2_FINAL_v2 BASE

LEFT JOIN BU_CAPTOOLS_WORK.UNIV_RENTAB_JAN25_6 UNIV_RENTAB

ON BASE.CEMPCTA=UNIV_RENTAB.CEMPCTA
AND BASE.CKBALCAO=UNIV_RENTAB.CKBALCAO
AND BASE.CKNUMCTA=UNIV_RENTAB.CKNUMCTA
AND trim(BASE.ZDEPOSIT_MIS)=trim(UNIV_RENTAB.ZDEPOSIT)
;

-- CRIAÇÃO DA NOVA CHAVE DO INSTRMNT_ID (APÓS SELEÇÃO DE BUSINESS AREA PRINCIPAL) + SIMULAÇÃO DO CAMPO LCL_INSTMRNT_ID
-- # Registos: 2 924 824 
DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE3_2;
CREATE TABLE BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE3_2  AS 

SELECT
    UNIV,
    REF_DATE,
    AMBITO,
    SEGMENTO,
    INSTRMNT_ID_AUX,
    INSTRMNT_ID,
    INSTRMNT_ID AS LCL_INSTMRNT_ID,
    CEMPCTA,
    CKBALCAO,
    CKNUMCTA,
    ZDEPOSIT_MIS,
    CKAREA,
    BSNSS_AREA
    -- CKMETAMIS
FROM 
    (
    SELECT
        UNIV,
        REF_DATE,
        AMBITO,
        SEGMENTO,
        INSTRMNT_ID AS INSTRMNT_ID_AUX,
        CASE
            WHEN MIN(ORDEM_BA) OVER (PARTITION BY INSTRMNT_ID) = ORDEM_BA THEN INSTRMNT_ID
            ELSE CONCAT('SNCO','00000000',INSTRMNT_ID, BSNSS_AREA)
        END AS INSTRMNT_ID,
        CEMPCTA,
        CKBALCAO,
        CKNUMCTA,
        ZDEPOSIT_MIS,
        CKAREA,
        BSNSS_AREA
        -- CKMETAMIS
        -- ORDEM_BA
    FROM
        (
        SELECT
            *,
            CASE
                WHEN BSNSS_AREA = 'BA1' THEN 1
                WHEN BSNSS_AREA = 'BA2' THEN 2
                WHEN BSNSS_AREA = 'BA3' THEN 3
                WHEN BSNSS_AREA = 'BA4' THEN 4
                WHEN BSNSS_AREA = 'BA5' THEN 5
                WHEN BSNSS_AREA = 'BA6' THEN 6
                WHEN BSNSS_AREA = 'BA7' THEN 7
                WHEN BSNSS_AREA = 'BA8' THEN 8
                WHEN BSNSS_AREA = 'BA9' THEN 9
                WHEN BSNSS_AREA = 'BA10' THEN 10
                WHEN BSNSS_AREA = 'BA11' THEN 11
                WHEN BSNSS_AREA = 'BA12' THEN 12
                WHEN BSNSS_AREA = 'BA13' THEN 13
                WHEN BSNSS_AREA = 'BA14' THEN 14
                WHEN BSNSS_AREA = 'BA15' THEN 15
                WHEN BSNSS_AREA = 'BA16' THEN 16
                WHEN BSNSS_AREA = 'BA17' THEN 17
                WHEN BSNSS_AREA = 'BA18' THEN 18
                WHEN BSNSS_AREA = 'BA20' THEN 19
                WHEN BSNSS_AREA = 'BA21' THEN 20
                WHEN BSNSS_AREA = 'BA22' THEN 21
                WHEN BSNSS_AREA = 'BA25' THEN 22
                WHEN BSNSS_AREA = 'BA26' THEN 23
                WHEN BSNSS_AREA = 'BA27' THEN 24
                WHEN BSNSS_AREA = 'BA28' THEN 25
                WHEN BSNSS_AREA = 'BA29' THEN 26
                WHEN BSNSS_AREA = 'BA30' THEN 27
                WHEN BSNSS_AREA = 'BA31' THEN 28
                WHEN BSNSS_AREA = 'BA23' THEN 29
                WHEN BSNSS_AREA = 'BA24' THEN 30
                ELSE 100
            END AS ORDEM_BA
        
        FROM BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE3_1
        ) X
    ) Y
;

-- SIMULAÇÃO DO CAMPO CNCLLD_INSTRMNT_STTS
-- #Registos:
DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE3_3;

CREATE TABLE BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE3_3 AS 
;
select * from (
SELECT DISTINCT
    BASE.*,
    UNIV_RENTAB.DINIOPER,
    CASE
        WHEN FR001.ZDEPOSIT IS NOT NULL THEN 'N'
        WHEN BASE.INSTRMNT_ID_AUX LIKE 'SS%' OR BASE.INSTRMNT_ID_AUX LIKE 'NN%' OR BASE.INSTRMNT_ID_AUX LIKE 'SNC%' THEN 'N' -- CLASSIFICAR OS AJUSTES COMO NÃO SENDO CANCELADOS
        WHEN FR001.ZDEPOSIT IS NULL AND YEAR(UNIV_RENTAB.DINIOPER)=YEAR(BASE.REF_DATE) THEN 'M'
        WHEN FR001.ZDEPOSIT IS NULL AND YEAR(UNIV_RENTAB.DINIOPER)<YEAR(BASE.REF_DATE) THEN 'C'
        ELSE 'ANALISE'
    END AS CNCLLD_INSTRMNT_STTS
    
FROM BU_CAPTOOLS_WORK.UNIV_LT_GD_PARTE3_2 BASE

LEFT JOIN
    (
     SELECT *
     FROM CD_CAPTOOLS.FR001_UNIV_SALDO
     WHERE REF_DATE = '${DATE}'
    ) FR001
    
ON BASE.INSTRMNT_ID_AUX = CONCAT(FR001.CEMPRESA, FR001.CBALCAO, FR001.CNUMECTA, FR001.ZDEPOSIT)

LEFT JOIN
    (
     SELECT DISTINCT
        -- REF_DATE,
        CEMPCTA,
        CKBALCAO,
        CKNUMCTA, 
        ZDEPOSIT,
        -- CKMETAMIS, 
        CKAREA,
        DINIOPER
        
     FROM BU_CAPTOOLS_WORK.UNIV_RENTAB_JAN25_6
     WHERE DINIOPER IS NOT NULL
    ) UNIV_RENTAB

ON BASE.CEMPCTA=UNIV_RENTAB.CEMPCTA
AND BASE.CKBALCAO=UNIV_RENTAB.CKBALCAO
AND BASE.CKNUMCTA=UNIV_RENTAB.CKNUMCTA
AND BASE.ZDEPOSIT_MIS=UNIV_RENTAB.ZDEPOSIT
AND BASE.CKAREA=UNIV_RENTAB.CKAREA
-- AND BASE.CKMETAMIS=UNIV_RENTAB.CKMETAMIS

) x 
where CNCLLD_INSTRMNT_STTS = 'ANALISE'
; 

SELECT * FROM BU_CAPTOOLS_WORK.UNIV_RENTAB_JAN25_6
WHERE concat (CEMPCTA,CKBALCAO,CKNUMCTA,ZDEPOSIT) = '31641600000001120PC0648235000000';

select * from cd_captools.ct201_rent_cont
where ref_date = '2025-01-31' 
and concat(cempcta,ckbalcao,cknumcta,zdeposit) = '31641600000001120PC0648235000000'