
/********************************************************************************************************************************************
****   Projeto: Calculadora de Emissões                                                                         						 ****
****   Autor: BS & Neyond                                                                                                                ****
****   Data: 10/12/2025                                                                                                                  ****
****   SQL Script Descrição: Geração do Cálculo de Emissões de Real Estate				     										     ****
********************************************************************************************************************************************/

/*=========================================================================================================================================*/
/*  1. Tabela granular: Obtenção do universo a reportar no âmbito da carteira de RE + Marcação de metricas relevantes             	       */
/*=========================================================================================================================================*/

	-- ID_CORRIDA 1 - Sem tratamento no preço de aquisição                                                                               
	-- ID_CORRIDA 2 - Tratamento no preço de aquisição quando =0
	-- ID_CORRIDA 3 - Alteração da parametrização do campo FLG_CRE_RRE
	-- Backup das 3 corridas acima - BU_CAPTOOLS_WORK.CAL_EMI_GRA_BACKUP (criamos a tabela de novo para adicionar campos)
	-- ID_CORRIDA 1 - Adição de campos
	-- Reunião com o cliente no dia 15/12 para redefinição da metodologia.
	-- ID_CORRIDA 1 - Alteração da estrutura da tabela (e criação de uma tabela auxiliar) 

INSERT OVERWRITE TABLE BU_CAPTOOLS_WORK.CAL_EMI_GRA PARTITION (ID_CORRIDA,REF_DATE)

SELECT
    BASE.CEMPRESA,
    BASE.CBALCAO,
    BASE.CNUMECTA,
    BASE.ZDEPOSIT,
    BASE.CEMPBEM,
    BASE.CKBALBEM,
    BASE.CKCTABEM,
    BASE.CKREFBEM,
    BASE.FLAG_COBERT,
	BASE.FLAG_BEM,
    BASE.NUM_BENS,
    BASE.AMOUNT_CTO,
    BASE.AMOUNT,
    BASE.AMOUNT_CTO_COBERT,
    BASE.AMOUNT_CTO_NCOBERT,
    BASE.PURPOSE_CODE,
    BASE.PRODUTO,
    BASE.SCP1_EMSS,
    BASE.SCP2_EMSS,
    BASE.PROPERTY_PURPOSE_CODE,
    BASE.NET_FLOOR_AREA,
    BASE.COUNTRY_CODE,
    BASE.EPC,
    BASE.QUALITY_SCORE,
    BASE.CGARANT_BEM,
    BASE.CONTRAPARTE,
    BASE.PRECO_AQUISICAO_ORI,
    BASE.SUM_MAVALIA,
    BASE.SUM_MAVALIAA,
    BASE.PRECO_AQUISICAO_OP1,
    BASE.PRECO_AQUISICAO_OP2,
    BASE.FLAG_PRECO_AQUISICAO,
    BASE.ORIGEM_SCP1_EMSS,
    BASE.ORIGEM_SCP2_EMSS,
	BASE.FLG_CRE_RRE,
	PA.SUM_PRECO_AQUISICAO_OP1,
	PA.SUM_PRECO_AQUISICAO_OP2,
	CASE WHEN BEM_CTO.FLAG_BEM='MUG_IMO' THEN 'CTO_IMO' WHEN BEM_CTO.FLAG_BEM='MUG_MOV' THEN 'CTO_MOV' ELSE 'SEM COLATERAL' END AS FLAG_CTO_BEM,

    -- Cenário #1 - Metodologia sem tratamento aos rácio 
    -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1 AS RATIO_OP1,
    (SCP1_EMSS)*(-BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1) AS EMISS_SCP1_OP1,
    (SCP2_EMSS)*(-BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1) AS EMISS_SCP2_OP1,
    (SCP1_EMSS+SCP2_EMSS)*(-BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1) AS EMISS_OP1,

    -- Cenário #2 - Metodologia sem tratamento aos rácio e sem tratamento aos preços de aquisição 
    CASE WHEN -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1>1 THEN 1 ELSE -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1 END AS RATIO_OP2,
    (SCP1_EMSS)*(CASE WHEN -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1>1 THEN 1 ELSE -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1 END) AS EMISS_SCP1_OP2,
    (SCP2_EMSS)*(CASE WHEN -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1>1 THEN 1 ELSE -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1 END) AS EMISS_SCP2_OP2,
    (SCP1_EMSS+SCP2_EMSS)*(CASE WHEN -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1>1 THEN 1 ELSE -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1 END) AS EMISS_OP2,
    
    -- Cenário #3 - Metodologia sem tratamento aos rácio mas com tratamento aos preços de aquisição
    CASE WHEN -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP2>1 THEN 1 ELSE -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP2 END AS RATIO_OP3,
    (SCP1_EMSS)*(CASE WHEN -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP2>1 THEN 1 ELSE -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP2 END) AS EMISS_SCP1_OP3,
    (SCP2_EMSS)*(CASE WHEN -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP2>1 THEN 1 ELSE -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP2 END) AS EMISS_SCP2_OP3,
    (SCP1_EMSS+SCP2_EMSS)*(CASE WHEN -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP2>1 THEN 1 ELSE -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP2 END) AS EMISS_OP3,
    
    -- PARTIÇÃO DA TABELA 
    RT.NEW_ID_CORRIDA AS ID_CORRIDA,
    '${REF_DATE}' AS REF_DATE

FROM 
(
    SELECT *
    FROM BU_CAPTOOLS_WORK.CAL_EMI_AUX_GRA
    WHERE REF_DATE = '${REF_DATE}'
        AND ID_CORRIDA IN (SELECT MAX(ID_CORRIDA) FROM BU_CAPTOOLS_WORK.CAL_EMI_AUX_GRA WHERE REF_DATE='${REF_DATE}')
    
)BASE
LEFT JOIN 
(
    SELECT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT, SUM(PRECO_AQUISICAO_OP1) AS SUM_PRECO_AQUISICAO_OP1,SUM(PRECO_AQUISICAO_OP2) AS SUM_PRECO_AQUISICAO_OP2
    FROM BU_CAPTOOLS_WORK.CAL_EMI_AUX_GRA
    WHERE REF_DATE = '${REF_DATE}'
        AND ID_CORRIDA IN (SELECT MAX(ID_CORRIDA) FROM BU_CAPTOOLS_WORK.CAL_EMI_AUX_GRA WHERE REF_DATE='${REF_DATE}')
    GROUP BY 1,2,3,4
)PA
    ON  BASE.CEMPRESA = PA.CEMPRESA AND
        BASE.CBALCAO = PA.CBALCAO AND
        BASE.CNUMECTA = PA.CNUMECTA AND
        BASE.ZDEPOSIT = PA.ZDEPOSIT 
LEFT JOIN 
(
    SELECT DISTINCT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,FLAG_BEM
    FROM BU_CAPTOOLS_WORK.CAL_EMI_AUX_GRA
    WHERE REF_DATE = '${REF_DATE}'
        AND ID_CORRIDA IN (SELECT MAX(ID_CORRIDA) FROM BU_CAPTOOLS_WORK.CAL_EMI_AUX_GRA WHERE REF_DATE='${REF_DATE}')
		AND CKBALBEM IS NOT NULL 
)BEM_CTO
    ON  BASE.CEMPRESA = BEM_CTO.CEMPRESA AND
        BASE.CBALCAO = BEM_CTO.CBALCAO AND
        BASE.CNUMECTA = BEM_CTO.CNUMECTA AND
        BASE.ZDEPOSIT = BEM_CTO.ZDEPOSIT 
		
-- PARTIÇÃO DA TABELA 
LEFT JOIN 
    (
    SELECT NVL(MAX(ID_CORRIDA),0)+1 AS NEW_ID_CORRIDA
    FROM BU_CAPTOOLS_WORK.CAL_EMI_GRA
    WHERE REF_DATE = '${REF_DATE}'
    )RT ON 1=1
	
	
;
INSERT OVERWRITE TABLE BU_CAPTOOLS_WORK.CAL_EMI_GRA PARTITION (ID_CORRIDA,REF_DATE)

SELECT 
	EMSS_FNCD.*,
	CASE
		WHEN TRIM(PURPOSE_CODE) IN ('Habitacao') THEN 'RRE'
		WHEN TRIM(PURPOSE_CODE) IN ('CRE_OUTRO') THEN 'CRE'
	ELSE ''
	END AS FLG_CRE_RRE,
	
    -- Cenário #1 - Metodologia sem tratamento aos rácio 
    -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1 AS RATIO_OP1,
    (SCP1_EMSS)*(-BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1) AS EMISS_SCP1_OP1,
    (SCP2_EMSS)*(-BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1) AS EMISS_SCP2_OP1,
    (SCP1_EMSS+SCP2_EMSS)*(-BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1) AS EMISS_OP1,

    -- Cenário #2 - Metodologia sem tratamento aos rácio e sem tratamento aos preços de aquisição 
    CASE WHEN -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1>1 THEN 1 ELSE -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1 END AS RATIO_OP2,
    (SCP1_EMSS)*(CASE WHEN -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1>1 THEN 1 ELSE -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1 END) AS EMISS_SCP1_OP2,
    (SCP2_EMSS)*(CASE WHEN -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1>1 THEN 1 ELSE -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1 END) AS EMISS_SCP2_OP2,
    (SCP1_EMSS+SCP2_EMSS)*(CASE WHEN -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1>1 THEN 1 ELSE -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP1 END) AS EMISS_OP2,
    
    -- Cenário #3 - Metodologia sem tratamento aos rácio mas com tratamento aos preços de aquisição
    CASE WHEN -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP2>1 THEN 1 ELSE -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP2 END AS RATIO_OP3,
    (SCP1_EMSS)*(CASE WHEN -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP2>1 THEN 1 ELSE -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP2 END) AS EMISS_SCP1_OP3,
    (SCP2_EMSS)*(CASE WHEN -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP2>1 THEN 1 ELSE -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP2 END) AS EMISS_SCP2_OP3,
    (SCP1_EMSS+SCP2_EMSS)*(CASE WHEN -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP2>1 THEN 1 ELSE -BASE.AMOUNT_CTO/PA.SUM_PRECO_AQUISICAO_OP2 END) AS EMISS_OP3,
	
	-- PARTIÇÃO DA TABELA 
    RT.NEW_ID_CORRIDA AS ID_CORRIDA,
    '${REF_DATE}' AS REF_DATE
FROM
(
    SELECT 
        BASE.*,
        CT004.PURPOSE_CODE,
        CONCAT(CT004.CPRODUTO,CT004.CSUBPROD) AS PRODUTO,
        SCP1_EMSS, 
        SCP2_EMSS,
        PROP.PROPERTY_PURPOSE_CODE,
        PROP.NET_FLOOR_AREA,
        PROP.COUNTRY_CODE,
        PROP_ENER.EPC, 
        PROP_ENER.QUALITY_SCORE,
        GT18.CGARANT_BEM,
        CONTRAPARTE,
		GT18_PA.PRECO_AQUISICAO AS PRECO_AQUISICAO_ORI,
		GT18_AGR.SUM_MAVALIA,
		GT18_AGR.SUM_MAVALIAA,
        CASE
            WHEN GT18_PA.PRECO_AQUISICAO IS NOT NULL AND GT18_PA.PRECO_AQUISICAO<>0 THEN GT18_PA.PRECO_AQUISICAO
            WHEN (GT18_PA.PRECO_AQUISICAO IS NULL OR GT18_PA.PRECO_AQUISICAO=0) AND GT18_AGR.SUM_MAVALIA IS NOT NULL THEN GT18_AGR.SUM_MAVALIA
            ELSE GT18_AGR.SUM_MAVALIAA
        END AS PRECO_AQUISICAO_OP1,
        SUM(
            CASE
                WHEN GT18_PA.PRECO_AQUISICAO IS NOT NULL AND GT18_PA.PRECO_AQUISICAO<>0 THEN GT18_PA.PRECO_AQUISICAO
                WHEN (GT18_PA.PRECO_AQUISICAO IS NULL OR GT18_PA.PRECO_AQUISICAO=0) AND GT18_AGR.SUM_MAVALIA IS NOT NULL THEN GT18_AGR.SUM_MAVALIA
                ELSE GT18_AGR.SUM_MAVALIAA
            END
            ) OVER (PARTITION BY CONCAT(BASE.CEMPRESA,BASE.CBALCAO,BASE.CNUMECTA,BASE.ZDEPOSIT)) AS SUM_PRECO_AQUISICAO_OP1,
        CASE
            WHEN GT18_PA.PRECO_AQUISICAO IS NOT NULL AND GT18_PA.PRECO_AQUISICAO>100 THEN GT18_PA.PRECO_AQUISICAO
            WHEN (GT18_PA.PRECO_AQUISICAO IS NULL OR GT18_PA.PRECO_AQUISICAO<=100) AND GT18_AGR.SUM_MAVALIA IS NOT NULL THEN GT18_AGR.SUM_MAVALIA
            ELSE GT18_AGR.SUM_MAVALIAA
        END AS PRECO_AQUISICAO_OP2,
        SUM(
            CASE
                WHEN GT18_PA.PRECO_AQUISICAO IS NOT NULL AND GT18_PA.PRECO_AQUISICAO>100 THEN GT18_PA.PRECO_AQUISICAO
                WHEN (GT18_PA.PRECO_AQUISICAO IS NULL OR GT18_PA.PRECO_AQUISICAO<=100) AND GT18_AGR.SUM_MAVALIA IS NOT NULL THEN GT18_AGR.SUM_MAVALIA
                ELSE GT18_AGR.SUM_MAVALIAA
            END
            ) OVER (PARTITION BY CONCAT(BASE.CEMPRESA,BASE.CBALCAO,BASE.CNUMECTA,BASE.ZDEPOSIT)) AS SUM_PRECO_AQUISICAO_OP2,
        CASE
            WHEN GT18_PA.PRECO_AQUISICAO IS NOT NULL AND GT18_PA.PRECO_AQUISICAO<>0 THEN 1
            WHEN (GT18_PA.PRECO_AQUISICAO IS NULL OR GT18_PA.PRECO_AQUISICAO=0) AND GT18_AGR.SUM_MAVALIA IS NOT NULL THEN 2
            ELSE 3
        END AS FLAG_PRECO_AQUISICAO,
        BENS_IMOV.ORIGEM_SCP1_EMSS,
        BENS_IMOV.ORIGEM_SCP2_EMSS
    FROM 
    (
    SELECT AUX1.*,AUX2.AMOUNT_CTO_COBERT,AUX2.AMOUNT_CTO_NCOBERT,
		CASE WHEN BEM_CTO.FLAG_BEM='MUG_IMO' THEN 'CTO_IMO' WHEN BEM_CTO.FLAG_BEM='MUG_MOV' THEN 'CTO_MOV' ELSE 'SEM COLATERAL' END AS FLAG_CTO_BEM,
    FROM    
        (
            SELECT   CEMPRESA
                    ,CBALCAO
                    ,CNUMECTA
                    ,ZDEPOSIT
                    ,CEMPBEM
                    ,CKBALBEM
                    ,CKCTABEM
                    ,CKREFBEM
                    ,FLAG_COBERT
                    ,FLAG_BEM
					,NUM_BENS
                    ,SUM_MSALDO_FINAL_CT AS AMOUNT_CTO
                    ,AMOUNT
            FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX3
            WHERE FLAG_PERIMETRO<>'Nao Aplicavel'
        )AUX1 
        LEFT JOIN 
        (
            SELECT   CEMPRESA
                    ,CBALCAO
                    ,CNUMECTA
                    ,ZDEPOSIT
                    ,SUM(CASE WHEN (CKCTABEM IS NOT NULL AND FLAG_COBERT='SUM_COLAT_N_COBRE') OR FLAG_COBERT='SUM_COLAT_COBRE'  THEN AMOUNT END) AS AMOUNT_CTO_COBERT
                    ,SUM(CASE WHEN (CKCTABEM IS NULL AND FLAG_COBERT='SUM_COLAT_N_COBRE')  THEN AMOUNT END) AS AMOUNT_CTO_NCOBERT
            FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX3
            WHERE FLAG_PERIMETRO<>'Nao Aplicavel'
            GROUP BY 1,2,3,4
        )AUX2
        ON  AUX1.CEMPRESA = AUX2.CEMPRESA AND
            AUX1.CBALCAO = AUX2.CBALCAO AND
            AUX1.CNUMECTA = AUX2.CNUMECTA AND
            AUX1.ZDEPOSIT = AUX2.ZDEPOSIT 
		LEFT JOIN 
		(
			SELECT DISTINCT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,FLAG_BEM
            FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX3
            WHERE FLAG_PERIMETRO<>'Nao Aplicavel'
				AND CKBALBEM IS NOT NULL 
		)BEM_CTO
			ON  AUX1.CEMPRESA = BEM_CTO.CEMPRESA AND
				AUX1.CBALCAO = BEM_CTO.CBALCAO AND
				AUX1.CNUMECTA = BEM_CTO.CNUMECTA AND
				AUX1.ZDEPOSIT = BEM_CTO.ZDEPOSIT 
    )BASE
    LEFT JOIN
    (
     SELECT *
     FROM CD_CAPTOOLS.CT004_UNIV_CTO
     WHERE REF_DATE='${REF_DATE}'
    ) CT004
    ON  BASE.CEMPRESA = CT004.CEMPRESA AND
        BASE.CBALCAO = CT004.CBALCAO AND
        BASE.CNUMECTA = CT004.CNUMECTA AND
        BASE.ZDEPOSIT = CT004.ZDEPOSIT
    LEFT JOIN
    (
        SELECT *
        FROM BU_CAPTOOLS_WORK.BENS_IMOVEIS_MV_DEZ24
    ) BENS_IMOV 
    ON  BASE.CEMPBEM=BENS_IMOV.CEMPBEM AND
        BASE.CKBALBEM=BENS_IMOV.CKBALBEM AND
        BASE.CKCTABEM=BENS_IMOV.CKCTABEM AND
        BASE.CKREFBEM=BENS_IMOV.CKREFBEM    
    LEFT JOIN
    (
        SELECT *
        FROM BUSINESS_ASSETS.PROPERTY
        WHERE DATA_DATE_PART='${REF_DATE}' 
    ) PROP 
    ON  BASE.CEMPBEM=PROP.PROPERTY_BANK_ID AND
        BASE.CKBALBEM=PROP.PROPERTY_BRANCH_CODE AND
        BASE.CKCTABEM=PROP.PROPERTY_CONTRACT_ID AND
        BASE.CKREFBEM=PROP.PROPERTY_REFERENCE_CODE
    LEFT JOIN
    (
        SELECT *
        FROM BUSINESS_ASSETS.PROPERTY_ENERGY_CERTIFICATE
        WHERE DATA_DATE_PART='${REF_DATE}' 
    ) PROP_ENER 
    ON  BASE.CEMPBEM=PROP_ENER.PROPERTY_BANK_ID AND
        BASE.CKBALBEM=PROP_ENER.PROPERTY_BRANCH_CODE AND
        BASE.CKCTABEM=PROP_ENER.PROPERTY_CONTRACT_ID AND
        BASE.CKREFBEM=PROP_ENER.PROPERTY_REFERENCE_CODE        
    LEFT JOIN  
    (
        SELECT DISTINCT CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM,CGARANT_BEM
        FROM CD_GARANTIAS.GT018_RATEIO_AVAL
        WHERE REF_DATE='${REF_DATE}' AND TIPOLOGIA='IMO'
    ) GT18 
    ON  BASE.CEMPBEM=GT18.CEMPBEM AND
        BASE.CKBALBEM=GT18.CKBALBEM AND
        BASE.CKCTABEM=GT18.CKCTABEM AND
        BASE.CKREFBEM=GT18.CKREFBEM
    LEFT JOIN  
    (
        SELECT DISTINCT CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM,PRECO_AQUISICAO
        FROM CD_GARANTIAS.GT018_RATEIO_AVAL
        WHERE REF_DATE='${REF_DATE}' AND TIPOLOGIA='IMO' AND PRECO_AQUISICAO IS NOT NULL
    ) GT18_PA
    ON  BASE.CEMPBEM=GT18_PA.CEMPBEM AND
        BASE.CKBALBEM=GT18_PA.CKBALBEM AND
        BASE.CKCTABEM=GT18_PA.CKCTABEM AND
        BASE.CKREFBEM=GT18_PA.CKREFBEM        
    LEFT JOIN
    (
        SELECT CEMPRESP,CKBALRES,CKCTARES,CKREFRESP,CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM,SUM(MAVALIA) AS SUM_MAVALIA,SUM(MAVALIAA) AS SUM_MAVALIAA
        FROM CD_GARANTIAS.GT018_RATEIO_AVAL
        WHERE REF_DATE='${REF_DATE}'
        GROUP BY CEMPRESP,CKBALRES,CKCTARES,CKREFRESP,CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM
    ) GT18_AGR 
    ON  BASE.CEMPRESA = GT18_AGR.CEMPRESP AND
        BASE.CBALCAO = GT18_AGR.CKBALRES AND
        BASE.CNUMECTA = GT18_AGR.CKCTARES AND
        BASE.ZDEPOSIT = GT18_AGR.CKREFRESP AND
        BASE.CEMPBEM=GT18_AGR.CEMPBEM AND
        BASE.CKBALBEM=GT18_AGR.CKBALBEM AND
        BASE.CKCTABEM=GT18_AGR.CKCTABEM AND
        BASE.CKREFBEM=GT18_AGR.CKREFBEM
) EMSS_FNCD

-- PARTIÇÃO DA TABELA 
LEFT JOIN 
    (
    SELECT NVL(MAX(ID_CORRIDA),0)+1 AS NEW_ID_CORRIDA
    FROM BU_CAPTOOLS_WORK.CAL_EMI_AUX_GRA
    WHERE REF_DATE = '${REF_DATE}'
    )RT ON 1=1 
;
;

/*=========================================================================================================================================*/
/*  2. Query de Extração                                                                                        			               */
/*=========================================================================================================================================*/

SELECT CONTRAPARTE,FLG_CRE_RRE,
    CASE WHEN TRIM(PURPOSE_CODE)='' THEN 'BLANK' ELSE PURPOSE_CODE END AS PURPOSE_CODE,FLAG_COBERT,
    CASE WHEN FLAG_CTO_BEM='CTO_IMO' THEN 'CTO_IMO' ELSE 'OUTRO' END AS  FLAG_FINANC_IMO,
    FLAG_CTO_BEM,
    FLAG_BEM,
    SUM(EMISS_SCP1_OP1) AS SCP1_OP_1,
    SUM(EMISS_SCP2_OP1) AS SCP2_OP_1,
    SUM(EMISS_OP1) AS EMISSAO_OP_1,
    SUM(EMISS_SCP1_OP2) AS SCP1_OP_2,
    SUM(EMISS_SCP2_OP2) AS SCP2_OP_2,
    SUM(EMISS_OP2) AS EMISSAO_OP_2,
    SUM(EMISS_SCP1_OP3) AS SCP1_OP_3,
    SUM(EMISS_SCP2_OP3) AS SCP2_OP_3,
    SUM(EMISS_OP3) AS EMISSAO_OP_3,
    SUM(-AMOUNT) AS VALOR_BRUTO,
    COUNT(DISTINCT CONCAT(cempresa,cbalcao,cnumecta,zdeposit)) AS NUM_CTO_AUX -- Este número duplicada devido as linhas não colaterizadas / no excel é tratado este número
FROM BU_CAPTOOLS_WORK.CAL_EMI_GRA
GROUP BY 1,2,3,4,5,6,7
;

/*=========================================================================================================================================*/
/*  3. Controlos & Validações                                                                                   			               */
/*=========================================================================================================================================*/

	-- Controlo #1 - Controlo da finalidade do bem, e valores de emissão a null 
	
SELECT 
    CASE 
		WHEN F1.CKCTABEM IS NULL OR F1.FLAG_BEM='MUG_MOV' THEN 'OK'
        WHEN TRIM(PROPERTY_PURPOSE_CODE)=TRIM(CFINBEM) AND PROPERTY_PURPOSE_CODE IS NOT NULL AND CFINBEM IS NOT NULL THEN 'OK'
        ELSE 'NOK'
    END AS VALID_FIN_BEM 
    ,CASE
		WHEN F1.CKCTABEM IS NULL OR F1.FLAG_BEM='MUG_MOV' THEN 'OK'
        WHEN EMSS_FNC_SCP1 IS NULL AND TRIM(PROPERTY_PURPOSE_CODE) IN ('06','07') THEN 'OK'
        WHEN EMSS_FNC_SCP1 IS NULL AND ORIGEM_SCP1_EMSS='MISS' THEN 'OK'
        WHEN EMSS_FNC_SCP1 IS NULL AND PRECO_AQUISICAO=0 THEN 'OK'
        WHEN EMSS_FNC_SCP1 IS NOT NULL THEN 'OK'
        ELSE 'NOK'
    END AS SCP1_FINAL
    ,CASE
		WHEN F1.CKCTABEM IS NULL OR F1.FLAG_BEM='MUG_MOV' THEN 'OK'
        WHEN EMSS_FNC_SCP2 IS NULL AND TRIM(PROPERTY_PURPOSE_CODE) IN ('06','07') THEN 'OK'
        WHEN EMSS_FNC_SCP2 IS NULL AND ORIGEM_SCP2_EMSS='MISS' THEN 'OK'
        WHEN EMSS_FNC_SCP2 IS NULL AND PRECO_AQUISICAO=0 THEN 'OK'
        WHEN EMSS_FNC_SCP2 IS NOT NULL THEN 'OK'
        ELSE 'NOK'
    END AS SCP2_FINAL
    ,CASE 
		WHEN F1.CKCTABEM IS NULL OR F1.FLAG_BEM='MUG_MOV' THEN 'OK'
        WHEN ORIGEM_SCP1_EMSS='Nao Aplicavel' AND (TRIM(PROPERTY_PURPOSE_CODE) NOT IN ('06','07') OR PROPERTY_PURPOSE_CODE IS NULL) THEN 'NOK'
        ELSE 'OK'
    END AS SCP1_ORIGEM_FINAL
    ,CASE 
		WHEN F1.CKCTABEM IS NULL OR F1.FLAG_BEM='MUG_MOV' THEN 'OK'
        WHEN ORIGEM_SCP2_EMSS='Nao Aplicavel' AND (TRIM(PROPERTY_PURPOSE_CODE) NOT IN ('06','07') OR PROPERTY_PURPOSE_CODE IS NULL) THEN 'NOK'
        ELSE 'OK'
    END AS SCP2_ORIGEM_FINAL
	,CASE 
		WHEN F1.CKCTABEM IS NULL OR F1.FLAG_BEM='MUG_MOV' THEN 'OK'
		WHEN TRIM(ORIGEM_SCP1_EMSS)='RE_DQS3_2A' AND (QUALITY_SCORE NOT IN  ('SANTANDER','1-REAL') OR QUALITY_SCORE IS NULL) THEN 'NOK'
		ELSE 'OK'
	END AS SCP1_ORIGEM_EPC_REAL
	,CASE 
		WHEN F1.CKCTABEM IS NULL OR F1.FLAG_BEM='MUG_MOV' THEN 'OK'
		WHEN TRIM(ORIGEM_SCP2_EMSS)='RE_DQS3_2A' AND (QUALITY_SCORE NOT IN  ('SANTANDER','1-REAL') OR QUALITY_SCORE IS NULL) THEN 'NOK'
		ELSE 'OK'
	END AS SCP2_ORIGEM_EPC_REAL
    ,SUM(EMSS_FNC_SCP1) AS SUM_EMSS_FNC_SCP1
    ,SUM(EMSS_FNC_SCP2) AS SUM_EMSS_FNC_SCP2
    ,COUNT(*) AS NUM_REG
    
FROM 
    (
    SELECT *,EMISS_SCP1_OP1 AS EMSS_FNC_SCP1, EMISS_SCP2_OP1 AS EMSS_FNC_SCP2,SUM_PRECO_AQUISICAO_OP1 AS PRECO_AQUISICAO
    FROM BU_CAPTOOLS_WORK.CAL_EMI_GRA
    WHERE REF_DATE='${REF_DATE}'
    AND ID_CORRIDA IN (SELECT MAX(ID_CORRIDA) FROM BU_CAPTOOLS_WORK.CAL_EMI_GRA WHERE REF_DATE='${REF_DATE}')
    )F1 
LEFT JOIN 
    (
    SELECT CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM,CFINBEM
    FROM CD_GARANTIAS.GT009_BENS_IMOV
    WHERE REF_DATE='${REF_DATE}'
    )F2 
    ON  F1.CEMPBEM=F2.CEMPBEM AND
        F1.CKBALBEM=F2.CKBALBEM AND
        F1.CKCTABEM=F2.CKCTABEM AND
        F1.CKREFBEM=F2.CKREFBEM  
GROUP BY 1,2,3,4,5,6,7
;

	-- Controlo #2 - Valores cobertos e não cobertos  
	
SELECT * FROM
(
SELECT AUX1.*,AUX2.AMOUNT_CTO_COBERT,AUX2.AMOUNT_CTO_NCOBERT
FROM    
    (
        SELECT   CEMPRESA
                ,CBALCAO
                ,CNUMECTA
                ,ZDEPOSIT
                ,CEMPBEM
                ,CKBALBEM
                ,CKCTABEM
                ,CKREFBEM
                ,FLAG_COBERT
                ,SUM_MSALDO_FINAL_CT AS AMOUNT_CTO
                ,AMOUNT
        FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX3
        WHERE FLAG_PERIMETRO<>'Nao Aplicavel'
    )AUX1 
    LEFT JOIN 
    (
        SELECT   CEMPRESA
                ,CBALCAO
                ,CNUMECTA
                ,ZDEPOSIT
                ,SUM(CASE WHEN (CKCTABEM IS NOT NULL AND FLAG_COBERT='SUM_COLAT_N_COBRE') OR FLAG_COBERT='SUM_COLAT_COBRE'  THEN AMOUNT END) AS AMOUNT_CTO_COBERT
                ,SUM(CASE WHEN (CKCTABEM IS NULL AND FLAG_COBERT='SUM_COLAT_N_COBRE')  THEN AMOUNT END) AS AMOUNT_CTO_NCOBERT
        FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX3
        WHERE FLAG_PERIMETRO<>'Nao Aplicavel'
        GROUP BY 1,2,3,4
    )AUX2
    ON  AUX1.CEMPRESA = AUX2.CEMPRESA AND
        AUX1.CBALCAO = AUX2.CBALCAO AND
        AUX1.CNUMECTA = AUX2.CNUMECTA AND
        AUX1.ZDEPOSIT = AUX2.ZDEPOSIT 
)AUX WHERE ROUND(NVL(AMOUNT_CTO_COBERT,0)+NVL(AMOUNT_CTO_NCOBERT,0),2)<>ROUND(NVL(AMOUNT_CTO,0),2) AND FLAG_COBERT='SUM_COLAT_COBRE'
;

	-- Controlo #3 - Duplicados   

SELECT CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) AS CHAVE, COUNT(*) AS NUM_REG
FROM BU_CAPTOOLS_WORK.CAL_EMI_GRA
WHERE REF_DATE='${REF_DATE}'
    AND ID_CORRIDA IN (SELECT MAX(ID_CORRIDA) FROM BU_CAPTOOLS_WORK.CAL_EMI_GRA WHERE REF_DATE='${REF_DATE}')
GROUP BY 1 HAVING NUM_REG>1 AND CHAVE IS NOT NULL 
;

	-- Controlo #4 - Tipologia de Bens associado ao Financiamento    

SELECT CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) AS CHAVE, COUNT(DISTINCT FLAG_BEM) AS NUM_REG
FROM BU_CAPTOOLS_WORK.CAL_EMI_GRA
WHERE REF_DATE='${REF_DATE}'
    AND ID_CORRIDA IN (SELECT MAX(ID_CORRIDA) FROM BU_CAPTOOLS_WORK.CAL_EMI_GRA WHERE REF_DATE='${REF_DATE}')
GROUP BY 1 HAVING NUM_REG>1 AND CHAVE IS NOT NULL 

/*=========================================================================================================================================*/
/*  AUX. Criação da estrutura das tabelas                                                                                   			   */
/*=========================================================================================================================================*/

	-- TABELA SEM CÁLCULO DAS EMISSÕES 
	
DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.CAL_EMI_AUX_GRA;
CREATE TABLE BU_CAPTOOLS_WORK.CAL_EMI_AUX_GRA  
(
    CEMPRESA	STRING	
    ,CBALCAO	STRING	
    ,CNUMECTA	STRING	
    ,ZDEPOSIT	STRING	
    ,CEMPBEM	STRING	
    ,CKBALBEM	STRING	
    ,CKCTABEM	STRING	
    ,CKREFBEM	STRING	
    ,FLAG_COBERT	STRING	
	,FLAG_BEM STRING 
    ,NUM_BENS	BIGINT	
    ,AMOUNT_CTO	DECIMAL(38,6)	
    ,AMOUNT	DECIMAL(38,26)	
    ,AMOUNT_CTO_COBERT	DECIMAL(38,26)	
    ,AMOUNT_CTO_NCOBERT	DECIMAL(38,26)	
    ,PURPOSE_CODE	STRING	
    ,PRODUTO	STRING	
    ,SCP1_EMSS	DECIMAL(38,22)	
    ,SCP2_EMSS	DECIMAL(38,22)	
    ,PROPERTY_PURPOSE_CODE	STRING	
    ,NET_FLOOR_AREA	DECIMAL(17,2)	
    ,COUNTRY_CODE	STRING	
    ,EPC	STRING	
    ,QUALITY_SCORE	STRING	
    ,CGARANT_BEM	STRING	
    ,CONTRAPARTE	STRING	
    ,PRECO_AQUISICAO_ORI	DECIMAL(17,2)	
    ,SUM_MAVALIA	DECIMAL(38,2)	
    ,SUM_MAVALIAA	DECIMAL(38,2)	
    ,PRECO_AQUISICAO_OP1	DECIMAL(38,2)	
    ,PRECO_AQUISICAO_OP2	DECIMAL(38,2)	
    ,FLAG_PRECO_AQUISICAO	TINYINT	
    ,ORIGEM_SCP1_EMSS	STRING	
    ,ORIGEM_SCP2_EMSS	STRING	
    ,FLG_CRE_RRE	STRING		
)
PARTITIONED BY (ID_CORRIDA BIGINT, REF_DATE STRING);

	-- TABELA COM CÁLCULO DAS EMISSÕES 
	
DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.CAL_EMI_GRA;
CREATE TABLE BU_CAPTOOLS_WORK.CAL_EMI_GRA  
(
    CEMPRESA	STRING	
    ,CBALCAO	STRING	
    ,CNUMECTA	STRING	
    ,ZDEPOSIT	STRING	
    ,CEMPBEM	STRING	
    ,CKBALBEM	STRING	
    ,CKCTABEM	STRING	
    ,CKREFBEM	STRING	
    ,FLAG_COBERT	STRING	
	,FLAG_BEM STRING 
    ,NUM_BENS	BIGINT	
    ,AMOUNT_CTO	DECIMAL(38,6)	
    ,AMOUNT	DECIMAL(38,26)	
    ,AMOUNT_CTO_COBERT	DECIMAL(38,26)	
    ,AMOUNT_CTO_NCOBERT	DECIMAL(38,26)	
    ,PURPOSE_CODE	STRING	
    ,PRODUTO	STRING	
    ,SCP1_EMSS	DECIMAL(38,22)	
    ,SCP2_EMSS	DECIMAL(38,22)	
    ,PROPERTY_PURPOSE_CODE	STRING	
    ,NET_FLOOR_AREA	DECIMAL(17,2)	
    ,COUNTRY_CODE	STRING	
    ,EPC	STRING	
    ,QUALITY_SCORE	STRING	
    ,CGARANT_BEM	STRING	
    ,CONTRAPARTE	STRING	
    ,PRECO_AQUISICAO_ORI	DECIMAL(17,2)	
    ,SUM_MAVALIA	DECIMAL(38,2)	
    ,SUM_MAVALIAA	DECIMAL(38,2)	
    ,PRECO_AQUISICAO_OP1	DECIMAL(38,2)	
    ,PRECO_AQUISICAO_OP2	DECIMAL(38,2)	
    ,FLAG_PRECO_AQUISICAO	TINYINT	
    ,ORIGEM_SCP1_EMSS	STRING	
    ,ORIGEM_SCP2_EMSS	STRING	
	,FLG_CRE_RRE STRING 
	,SUM_PRECO_AQUISICAO_OP1 DECIMAL(38,2)
	,SUM_PRECO_AQUISICAO_OP2 DECIMAL(38,2)
	,FLAG_CTO_BEM STRING
    ,RATIO_OP1	DECIMAL(38,6)	
    ,EMISS_SCP1_OP1	DECIMAL(38,28)	
    ,EMISS_SCP2_OP1	DECIMAL(38,28)	
    ,EMISS_OP1	DECIMAL(38,28)	
    ,RATIO_OP2	DECIMAL(38,6)	
    ,EMISS_SCP1_OP2	DECIMAL(38,28)	
    ,EMISS_SCP2_OP2	DECIMAL(38,28)	
    ,EMISS_OP2	DECIMAL(38,28)
    ,RATIO_OP3	DECIMAL(38,6)	
    ,EMISS_SCP1_OP3	DECIMAL(38,28)	
    ,EMISS_SCP2_OP3	DECIMAL(38,28)	
    ,EMISS_OP3	DECIMAL(38,28)
)
PARTITIONED BY (ID_CORRIDA BIGINT, REF_DATE STRING);