/********************************************************************************************************************************************
****   Projeto: Implementação Templates Locais                                                                     						 ****
****   Autor: BS & Neyond                                                                                                                ****
****   Data: 24/06/2025                                                                                                                  ****
****   SQL Script Descrição: Geração do Template 4																		                 ****
****  ( Exposure to top 20 carbon intensive firms )                                      												 ****
********************************************************************************************************************************************/

/*=========================================================================================================================================*/
/*  1. Tabela granular: Obtenção do universo a reportar no âmbito do Template 4 + Marcação de metricas relevantes       	     		   */
/*=========================================================================================================================================*/ 


INSERT OVERWRITE TABLE BU_ESG_WORK.AG04_TEMP_CTO_GRA PARTITION (REF_DATE)
SELECT  
		UNIV_TEMP4.CEMPRESA,
		UNIV_TEMP4.CBALCAO,
		UNIV_TEMP4.CNUMECTA,
		UNIV_TEMP4.ZDEPOSIT,
		UNIV_TEMP4.ZCLIENTE,
		UNIV_TEMP4.BRUTO_IMPARIDADE,
		UNIV_TEMP4.CONTRAPARTE,
		UNIV_TEMP4.TIPO_COLATERAL,

		CASE
			WHEN (CCONTAB_FINAL_IDCOMB LIKE '%SC0302%' OR CCONTAB_FINAL_IDCOMB LIKE '%SC0303%') -- 'OUTRAS INSTITUICOES FINANCEIRAS','OUTRAS EMPRESAS NAO FINANCEIRAS'
				AND NFIN.FLG_CSRD = 1
			THEN 'Subject to CSRD'
			
			WHEN CCONTAB_FINAL_IDCOMB LIKE '%MC08%' AND -- JOIN VENTURES
				UPPER(CONTRAPARTE) IN ('OUTRAS INSTITUICOES FINANCEIRAS','OUTRAS EMPRESAS NAO FINANCEIRAS','INSTITUICOES DE CREDITO') AND
				NFIN.FLG_CSRD = 1
			THEN 'Subject to CSRD'   
			
			WHEN CCONTAB_FINAL_IDCOMB LIKE '%SC02%' -- 'INSTITUICOES DE CREDITO'
				AND NFIN.FLG_CSRD = 1
			THEN 'Subject to CSRD'                         
			
			WHEN (CCONTAB_FINAL_IDCOMB LIKE '%SC0302%' OR CCONTAB_FINAL_IDCOMB LIKE '%SC0303%')
				AND (NFIN.FLG_CSRD <> 1 OR NFIN.FLG_CSRD IS NULL)
			THEN 'Not Subject to CSRD'
			
			WHEN CCONTAB_FINAL_IDCOMB LIKE '%MC08%'
				AND UPPER(CONTRAPARTE) IN ('OUTRAS INSTITUICOES FINANCEIRAS','OUTRAS EMPRESAS NAO FINANCEIRAS','INSTITUICOES DE CREDITO')
				AND (NFIN.FLG_CSRD <> 1 OR NFIN.FLG_CSRD IS NULL)
			THEN 'Not Subject to CSRD' 
			
			WHEN CCONTAB_FINAL_IDCOMB LIKE '%SC02%'
				AND (NFIN.FLG_CSRD <> 1 OR NFIN.FLG_CSRD IS NULL) 
			THEN 'Not Subject to CSRD'             
			
			-- TODAS AS SC02/SC0302/SC0303 DEVERÃO TER MARCAÇÃO DE NFRD (POR ISSO TUDO O QUE NÃO CAI NO SUJEITO SERÁ NÃO SUJEITO)
			WHEN (CCONTAB_FINAL_IDCOMB LIKE '%SC0302%' OR CCONTAB_FINAL_IDCOMB LIKE '%SC0303%' OR CCONTAB_FINAL_IDCOMB LIKE '%SC02%') THEN 'Not Subject to CSRD'                
			
			WHEN CCONTAB_FINAL_IDCOMB LIKE '%MC08%' AND UPPER(CONTRAPARTE) IN ('OUTRAS INSTITUICOES FINANCEIRAS','OUTRAS EMPRESAS NAO FINANCEIRAS','INSTITUICOES DE CREDITO') THEN 'Not Subject to CSRD'                       
			
			ELSE ''
		END AS FLAG_CSRD,

		CASE
			WHEN INSTRUMENTO_FINANCEIRO = 'instrumentos de capital' THEN -3 -- 'INSTRUMENTOS DE CAPITAL' : > 20 ANOS
			WHEN DATA_VENCIMENTO  IN ('','0001-01-01','9999-12-31',NULL) AND TIPO_COLATERAL = 'Garantia Residencial' THEN -2 -- FALTA DE DATA QUALITY DE DADOS MAS GARANTIA RESIDENCIAL
			WHEN DATA_VENCIMENTO  IN ('','0001-01-01','9999-12-31',NULL) THEN -1 -- FALTA DE DATA QUALITY DE DADOS MAS NÃO GARANTIA RESIDENCIAL
			WHEN UPPER(PRODUTO) LIKE 'CART%CR%DITO%' OR UPPER(PRODUTO) LIKE '%REPOS%'  OR UPPER(PRODUTO) LIKE '%VISTA, DESCOBERTOS E CO%' THEN -1 -- 'COUNTERPARTY HAVING THE CHOICE OF THE REPAYMENT DATE'
			WHEN DATA_VENCIMENTO  < '${REF_DATE}' THEN -4 --'OLD CONTRACTS' 
			ELSE ROUND(DATEDIFF(TO_DATE(DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25, 4)
		END AS YEARS_TO_MATURITY,

		SUM(UNIV_TEMP4.MSALDO_FINAL) AS MSALDO_FINAL,

		SUM(	
			CASE
				WHEN TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'SPECIFIC PURPOSE' AND SFICS.NOME_SPECIFIC_ELIGIBLE = 'CCM' THEN NVL(UNIV_TEMP4.MSALDO_FINAL,0) ELSE 0 END +
			CASE 
				WHEN TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'GENERAL PURPOSE' THEN NVL(UNIV_TEMP4.MSALDO_FINAL * NFIN.CCM_TRNVR_OWN_PRFRMNCE_ALGND/100,0) ELSE 0 END + 
			CASE 
				WHEN TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'GENERAL PURPOSE' THEN NVL(UNIV_TEMP4.MSALDO_FINAL * NFIN.CCM_TRNVR_TRNSTN_ALIGND/100,0) ELSE 0 END + 
			CASE 
				WHEN TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'GENERAL PURPOSE' THEN NVL(UNIV_TEMP4.MSALDO_FINAL * NFIN.CCM_TRNVR_ENBLNG_ALGND/100,0) ELSE 0 END 
			)  AS SUSTAINABLE_CCM,

		-- PARTICAO
		'${REF_DATE}' AS REF_DATE			
		
FROM
(
	SELECT DISTINCT 
		UNIV_KGL.CEMPRESA,
		UNIV_KGL.CBALCAO,
		UNIV_KGL.CNUMECTA,
		UNIV_KGL.ZDEPOSIT,
		UNIV_KGL.ZCLIENTE,
		UNIV_KGL.CCONTAB_FINAL_IDCOMB,
		UNIV_KGL.MSALDO_FINAL*(-1) AS MSALDO_FINAL,
		UNIV_KGL.INSTRUMENTO_FINANCEIRO,
		UNIV_KGL.CARTEIRA_CONTABILISTICA,
		UNIV_KGL.BRUTO_IMPARIDADE,
		UNIV_KGL.PRODUTO,
		UNIV_KGL.CONTRAPARTE,
		UNIV_KGL.TIPO_COLATERAL,
		UNIV_KGL.DATA_VENCIMENTO
	FROM
	(
		SELECT  A.*
			   ,CASE WHEN RSTF.CCLIENTE IS NOT NULL THEN RSTF.CCLIENTE
					 WHEN RSTF.CCLIENTE IS NULL AND CT71_ZCLIENTE IS NOT NULL THEN CT71_ZCLIENTE
					 WHEN RSTF.CCLIENTE IS NULL AND CT71_ZCLIENTE IS NULL AND JQUEST.ZCLIENTE IS NOT NULL THEN JQUEST.ZCLIENTE  
					 ELSE 'Not found' 
				END AS ZCLIENTE_CROSS
			   ,CASE WHEN RSTF.CCLIENTE IS NOT NULL THEN RSTF.CENTLEGAL
					 WHEN RSTF.CCLIENTE IS NULL AND CT71_ZCLIENTE IS NOT NULL THEN KGL5
					 WHEN RSTF.CCLIENTE IS NULL AND CT71_ZCLIENTE IS NULL AND JQUEST.ZCLIENTE IS NOT NULL THEN CPTYPARENT_CODE  
					 ELSE 'Not found'
				END AS GCL_CODE_1
			   ,CASE WHEN RSTF.CCLIENTE IS NOT NULL THEN RSTF.CGRUPO
					 WHEN RSTF.CCLIENTE IS NULL AND CT71_ZCLIENTE IS NOT NULL THEN KGL5
					 WHEN RSTF.CCLIENTE IS NULL AND CT71_ZCLIENTE IS NULL AND JQUEST.ZCLIENTE IS NOT NULL THEN CPTYLASTPARENT_CODE  
					 ELSE 'Not found' 
				END AS GCL_CODE_2
		FROM
		(
			SELECT A1.*,A2.ZCLIENTE,A2.DATA_VENCIMENTO,
				CASE 
					WHEN A3.CONTA IS NOT NULL THEN A3.PRODUTO
					WHEN A4.CONTA IS NOT NULL THEN A4.PRODUTO
					WHEN A5.CONTA IS NOT NULL THEN A5.PRODUTO
				END AS PRODUTO
			FROM 
				(
					SELECT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,CCONTAB_FINAL_IFRS,CCONTAB_FINAL_ST_SGPS_CONS,CCONTAB_FINAL_IDCOMB,INSTRUMENTO_FINANCEIRO,CONTRAPARTE,CARTEIRA_CONTABILISTICA,COD_PLANO,
						CASE 
							WHEN CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL1%' THEN 'Sem Garantia'
							WHEN CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL2%' THEN 'Garantia Residencial'
							WHEN CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL3%' THEN 'Garantia Comercial'
							WHEN CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL4%' THEN 'Garantia Real'
						END AS TIPO_COLATERAL,
						CASE 
							WHEN TRIM(BRUTO_IMPARIDADE)='' AND CCONTAB_FINAL_IDCOMB LIKE '%TYVA01%' THEN 'valor bruto'
							WHEN TRIM(BRUTO_IMPARIDADE)='' AND CCONTAB_FINAL_IDCOMB LIKE '%TYVA02%' THEN 'imparidade'
							ELSE BRUTO_IMPARIDADE
						END AS BRUTO_IMPARIDADE, SUM(MSALDO_FINAL) AS MSALDO_FINAL
					FROM BUSINESS_ESG.MODESG_OUT_REPORTE_GRANULAR
					WHERE REF_DATE = '${REF_DATE}'
						AND REPORTE_GRANULAR='Template 4'
					GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13
					HAVING MSALDO_FINAL<>0
				) A1
			
			LEFT JOIN
			
				(
					SELECT DISTINCT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,ZCLIENTE,DDVENCIM AS DATA_VENCIMENTO
					FROM CD_CAPTOOLS.CT004_UNIV_CTO
					WHERE REF_DATE = '${REF_DATE}'
				) A2 ON A1.CEMPRESA=A2.CEMPRESA
						AND A1.CBALCAO=A2.CBALCAO
						AND A1.CNUMECTA=A2.CNUMECTA
						AND A1.ZDEPOSIT=A2.ZDEPOSIT
			LEFT JOIN 
				(
					SELECT DISTINCT CONTA, PRODUTO
					FROM CD_CAPTOOLS.FR802_PL_CONTAS
					WHERE REF_DATE = '${REF_DATE}'
						AND COD_PLANO = 'BST_IND'
						AND TRIM(CONTA) <> ''
				) A3 ON TRIM(A1.CCONTAB_FINAL_IFRS)=TRIM(A3.CONTA) AND A1.COD_PLANO = 'BST_IND'

			LEFT JOIN 
				(
					SELECT DISTINCT CONTA, PRODUTO
					FROM CD_CAPTOOLS.FR802_PL_CONTAS
					WHERE REF_DATE = '${REF_DATE}'
						AND COD_PLANO = 'ST_SGPS_CONS'
						AND TRIM(CONTA) <> ''
				) A4 ON TRIM(A1.CCONTAB_FINAL_ST_SGPS_CONS)=TRIM(A4.CONTA) AND A1.COD_PLANO = 'ST_SGPS_CONS'
				
			LEFT JOIN 
				(
					SELECT DISTINCT CONTA, PRODUTO
					FROM CD_CAPTOOLS.FR802_PL_CONTAS
					WHERE REF_DATE = '${REF_DATE}'
						AND COD_PLANO = 'BST_IDCOMB'
						AND TRIM(CONTA) <> ''
				) A5 ON TRIM(A1.CCONTAB_FINAL_IDCOMB)=TRIM(A5.CONTA) AND A1.COD_PLANO = 'BST_IDCOMB'
				
		) AS A
		LEFT JOIN
		(
			SELECT CT003.ZCLIENTE AS CCLIENTE,
				   CENTLEGAL,
				   CGRUPO
			FROM
			(
				SELECT *
				FROM CD_CAPTOOLS.CT003_UNIV_CLI
				WHERE REF_DATE='${REF_DATE}'
			) CT003
			INNER JOIN
			(
				SELECT *
				FROM CD_CAPTOOLS.CT070_UNIV_GR_CLI
				WHERE REF_DATE='${REF_DATE}' AND TIPO_RELACAO = 'CONTROLO'
			) CT70 
			ON CT003.ZCLIENTE = CT70.ZCLIENTE
			INNER JOIN
			(
				SELECT *
				FROM CD_CAPTOOLS.CT069_UNIV_GR_EC
				WHERE REF_DATE='${REF_DATE}'
			) CT069 
			ON CT069.ZGRUPO = CT70.ZGRUPO
			INNER JOIN
			( 
				SELECT CCLIENTE,
					   GCLI_KGL,
					   CENTLEGAL,
					   GNOMELEGAL,
					   CGRUPO
			   FROM CD_RISCOS.RSTF159_RATING_INTERNO
			   WHERE DATA_DATE_PART IN ( SELECT MAX(DATA_DATE_PART) FROM CD_RISCOS.RSTF159_RATING_INTERNO WHERE DATA_DATE_PART <= '${REF_DATE}' ) AND TRIM(CCLIENTE) NOT IN ('','#') 
			) RSTF 
			ON CT069.ZCLIENTE_PRINC = RSTF.CCLIENTE
			UNION ALL
			(
				SELECT  CCLIENTE
					   ,CENTLEGAL
					   ,CGRUPO
				FROM CD_RISCOS.RSTF159_RATING_INTERNO
				WHERE DATA_DATE_PART IN ( SELECT MAX(DATA_DATE_PART) FROM CD_RISCOS.RSTF159_RATING_INTERNO WHERE DATA_DATE_PART <= '${REF_DATE}' ) AND TRIM(CCLIENTE) NOT IN ('', '#') 
			)
		) AS RSTF
		ON A.ZCLIENTE = RSTF.CCLIENTE
		LEFT JOIN
		(
			SELECT  DISTINCT CT70.ZCLIENTE AS CT71_ZCLIENTE
				   ,CT70.ZGRUPO
				   ,CT71.KGL5
			FROM
			(
				SELECT  *
				FROM CD_CAPTOOLS.CT070_UNIV_GR_CLI
				WHERE REF_DATE = "${REF_DATE}"
				AND TIPO_RELACAO = 'CONTROLO'
			) CT70
			INNER JOIN
			(
				SELECT  *
				FROM CD_CAPTOOLS.CT071_RWA_GR_EC
				WHERE REF_DATE = "${REF_DATE}"
				AND TRIM(KGL5) <> ''
			) CT71
			ON CT70.ZGRUPO = CT71.ZGRUPO
		) AS CT71
		ON A.ZCLIENTE = CT71.CT71_ZCLIENTE
		LEFT JOIN
		(
			SELECT CT003.ZCLIENTE, CPTYPARENT_CODE, CPTYLASTPARENT_CODE
			FROM
				(SELECT * FROM CD_CAPTOOLS.CT003_UNIV_CLI WHERE REF_DATE='${REF_DATE}') CT003
			INNER JOIN
				(SELECT * FROM CD_CAPTOOLS.CT070_UNIV_GR_CLI WHERE REF_DATE='${REF_DATE}' AND TIPO_RELACAO = 'CONTROLO') CT70
			ON CT003.ZCLIENTE = CT70.ZCLIENTE
			LEFT JOIN
				(SELECT * FROM CD_CAPTOOLS.CT069_UNIV_GR_EC WHERE REF_DATE='${REF_DATE}') CT069
			ON CT069.ZGRUPO = CT70.ZGRUPO
			INNER JOIN
				(SELECT * FROM CD_CAPTOOLS.CT003_UNIV_CLI WHERE REF_DATE='${REF_DATE}') CT3
			ON CT069.ZCLIENTE_PRINC = CT3.ZCLIENTE    
			INNER JOIN 
				(SELECT * FROM BU_ESG_WORK.P3_CLIENT_DATA_JQUEST) JQUEST
			ON TRIM(JQUEST.CPTY_CODE) = TRIM(CT3.CCLI_KGL) 
			UNION ALL
			( 
				SELECT ZCLIENTE,CPTYPARENT_CODE, CPTYLASTPARENT_CODE 
				FROM 
					(SELECT DISTINCT ZCLIENTE, TRIM(CCLI_KGL) AS CCLI_KGL FROM CD_CAPTOOLS.CT003_UNIV_CLI WHERE REF_DATE='${REF_DATE}'AND TRIM(CCLI_KGL) <> '')CT03
				INNER JOIN 
					(SELECT * FROM BU_ESG_WORK.P3_CLIENT_DATA_JQUEST) INPUT
				ON TRIM(INPUT.CPTY_CODE) = TRIM(CT03.CCLI_KGL)
			) 
		) AS JQUEST
		ON A.ZCLIENTE = JQUEST.ZCLIENTE
	) UNIV_KGL
	WHERE  GCL_CODE_1 IN ('5CVRG','5TOFG','5XXCG','ADNOC','BRPHG','GPMXG','KWPCG','NNPPG','SHEHG','5TOPF','GP2BX','GQBGG') 
		OR GCL_CODE_2 IN ('5CVRG','5TOFG','5XXCG','ADNOC','BRPHG','GPMXG','KWPCG','NNPPG','SHEHG','5TOPF','GP2BX','GQBGG')
) UNIV_TEMP4

LEFT JOIN 
(
    SELECT * 
    FROM BUSINESS_ESG.MODESG_OUT_EMPR_INFO_NFIN 
    WHERE REF_DATE='${REF_DATE}'
) NFIN
ON UNIV_TEMP4.ZCLIENTE = NFIN.ZCLIENTE

LEFT JOIN (SELECT * FROM BUSINESS_ESG.MODESG_OUT_SFICS_TAXON_EUROPEIA WHERE REF_DATE='${REF_DATE}') SFICS
ON  UNIV_TEMP4.CEMPRESA = SFICS.CEMPRESA AND
    UNIV_TEMP4.CBALCAO  = SFICS.CBALCAO AND
    UNIV_TEMP4.CNUMECTA = SFICS.CNUMECTA AND
    UNIV_TEMP4.ZDEPOSIT = SFICS.ZDEPOSIT

GROUP BY 1,2,3,4,5,6,7,8,9,10,13
;