INSERT OVERWRITE BU_ESG_WORK.AG83_MITI_CTO_AGR PARTITION (ID_CORRIDA,REF_DATE)

SELECT 
	INFORMING_SOC,
	COUNTERPARTY_SOC, 
	ADJUSTMENT_CODE,
    CASE
    	WHEN COMB_CODE LIKE '%MC04%COLL4%' THEN REPLACE(COMB_CODE,'COLL4','COLL1')
    	WHEN COMB_CODE LIKE '%MC02%SC02%COLL3%' THEN REPLACE(COMB_CODE,'COLL3','COLL1')
    	ELSE COMB_CODE
    END AS COMB_CODE,
	ROUND(SUM(AMOUNT),0) AS AMOUNT,
	DCON,

	RT.NEW_ID_CORRIDA AS ID_CORRIDA,
	'${REF_DATE}' AS REF_DATE

FROM
(
	SELECT 
		'00411' AS INFORMING_SOC,
		CASE 
			WHEN SOCIEDADE_CONTRAPARTE = '' OR SOCIEDADE_CONTRAPARTE ='01278' THEN '00000'
			ELSE SOCIEDADE_CONTRAPARTE
		END AS COUNTERPARTY_SOC,
		'BI00411' AS ADJUSTMENT_CODE,	
		CASE
			WHEN GREEN_FINANCIAL_INSTRUMENT = 'GFI2' THEN CONCAT(IDCOMB_SATELITE,';',GREEN_FINANCIAL_INSTRUMENT)
			ELSE CONCAT(IDCOMB_SATELITE,';',PURPOSE_ESG,';',GREEN_FINANCIAL_INSTRUMENT,';',FUNDING_TYPE,';',RISK_MITIGATED_CCT,';',RISK_MITIGATED_CCP)
		END AS COMB_CODE,
		SUM(AMOUNT) AS AMOUNT,
		DCON
	FROM BU_ESG_WORK.AG83_MITI_CTO_GRA
	WHERE REF_DATE = '${REF_DATE}' 
				AND ID_CORRIDA IN (SELECT MAX(ID_CORRIDA) FROM BU_ESG_WORK.AG83_MITI_CTO_GRA WHERE REF_DATE = '${REF_DATE}')
	GROUP BY 1,2,3,4,6
) X

LEFT JOIN
    
    (
    SELECT 
        NVL(MAX(ID_CORRIDA),0)+1 AS NEW_ID_CORRIDA
    FROM BU_ESG_WORK.AG83_MITI_CTO_AGR
    WHERE REF_DATE = '${REF_DATE}'
    ) RT
    
    ON 1=1

GROUP BY 1,2,3,4,6,7,8
;