
/*===================================================================================================================================================
                                                      
											       SIMULAÇÃO JUROS & COMISSÕES - LT002
										                    NEYOND 2024 - V0.01 
															    
 ===================================================================================================================================================*/
 
--------------------------------------------------------------------------------------------------------------------------------------------------
-- 1 Criação da tabela para o mês N e mês N-1 com a informação de rentibilidade (MIS)
	 --> Na Business Area é necessário rever o CASE com a lógica dos Pais e Filhos para o mês de processamento dos dados
	 --> Os registos com KPI's igual a zero a desconsiderar na CT209 e na CT211 foram identificados no e-mail BS | Testes Pilar III ESG - MV & GD (02/08/2024) pelo Luís Silva. 
		--> Nesse e-mail são identificados KPI's que não existem nas tabelas em questão (exemplo: C007_mant)
--------------------------------------------------------------------------------------------------------------------------------------------------

-- MAI24 | Inserted 14.915.305 row(s) -- BU_CAPTOOLS_WORK.SIMUL_GD_MIS_MAI24
-- ABR24 | Inserted 14.564.518 row(s) -- BU_CAPTOOLS_WORK.SIMUL_GD_MIS_ABR24

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.SIMUL_GD_MIS_MAI24;
CREATE TABLE BU_CAPTOOLS_WORK.SIMUL_GD_MIS_MAI24 AS

SELECT 
	UNIV.CHAVE_MIS_207
	,UNIV.FLAG_ATIVO
	,UNIV.FLAG_ATIVO_PATRIMONIAL
	,UNIV.FLAG_ATIVO_PATRIMONIAL_LC
	,UNIV.FLAG_ATIVO_PATRIMONIAL_CA
	,UNIV.FLAG_BUS_AREA
	,SUM(CT209.C001) AS C001
	,SUM(CT209.C007) AS C007
	,SUM(CT209.C134) AS C134
	,SUM(CT209.C224) AS C224
	,SUM(CT209.C298) AS C298
	,SUM(CT209.C299) AS C299
	,SUM(CT209.C300) AS C300
	,SUM(CT209.M009) AS M009
	,SUM(CT209.AC310) AS AC310
	,SUM(CT211.C457) AS C457
	,SUM(CT211.C458) AS C458
	,SUM(CT211.C459) AS C459
	,SUM(CT211.C460) AS C460

FROM
	(
	SELECT DISTINCT
		UNIV_AUX.*
		,CASE WHEN CT831_1.METAPRODUTO_831 IS NOT NULL THEN 1 ELSE 0 END AS FLAG_ATIVO
		,CASE WHEN CT831_2.METAPRODUTO_831 IS NOT NULL THEN 1 ELSE 0 END AS FLAG_ATIVO_PATRIMONIAL
		,CASE WHEN CT831_3.METAPRODUTO_831 IS NOT NULL THEN 1 ELSE 0 END AS FLAG_ATIVO_PATRIMONIAL_LC
		,CASE WHEN CT831_4.METAPRODUTO_831 IS NOT NULL THEN 1 ELSE 0 END AS FLAG_ATIVO_PATRIMONIAL_CA
		,CASE 
			WHEN UNIV_AUX.CKAREA_207 IN ('AN01010100','BP','AN01050000') THEN 'BA1'
			WHEN UNIV_AUX.CKAREA_207 IN ('AN01010201','AN01010500','BC1015') THEN 'BA2'
			WHEN UNIV_AUX.CKAREA_207 IN ('BC1010') THEN 'BA3'
			WHEN UNIV_AUX.CKAREA_207 IN ('BC1014','AN01020200','AN01020410') THEN 'BA4'
			WHEN UNIV_AUX.CKAREA_207 IN ('BC1020') THEN 'BA5'
			WHEN UNIV_AUX.CKAREA_207 IN ('AN06020000','AN06010000','FC') THEN 'BA6'
			WHEN UNIV_AUX.CKAREA_207 IN ('GB0505') THEN 'BA7'
			WHEN UNIV_AUX.CKAREA_207 IN ('GB0510') THEN 'BA8'
			WHEN UNIV_AUX.CKAREA_207 IN ('GB0515') THEN 'BA9'
			WHEN UNIV_AUX.CKAREA_207 IN ('GB0525') THEN 'BA10'
			WHEN UNIV_AUX.CKAREA_207 IN ('GB0540') THEN 'BA11'
			WHEN UNIV_AUX.CKAREA_207 IN ('GB0530') THEN 'BA12'
			WHEN UNIV_AUX.CKAREA_207 IN ('GB0535') THEN 'BA13'
			WHEN UNIV_AUX.CKAREA_207 IN ('GB0545') THEN 'BA14'
			WHEN UNIV_AUX.CKAREA_207 IN ('GB1005') THEN 'BA15'
			WHEN UNIV_AUX.CKAREA_207 IN ('GB1010') THEN 'BA16'
			WHEN UNIV_AUX.CKAREA_207 IN ('GB1015') THEN 'BA17'
			WHEN UNIV_AUX.CKAREA_207 IN ('GB1025') THEN 'BA18'
			WHEN UNIV_AUX.CKAREA_207 IN ('GB2005') THEN 'BA19'
			WHEN UNIV_AUX.CKAREA_207 IN ('GB45') THEN 'BA20'
			WHEN UNIV_AUX.CKAREA_207 IN ('AN04010700','AN04010400','AN04010600','AN04010500','AN04010100','AC05') THEN 'BA21'
			WHEN UNIV_AUX.CKAREA_207 IN ('AN04020000','AC10','AN04030000') THEN 'BA22'
			WHEN UNIV_AUX.CKAREA_207 IN ('AN02090000') THEN 'BA23'
			WHEN UNIV_AUX.CKAREA_207 IN ('GB2010') THEN 'BA24'
			WHEN UNIV_AUX.CKAREA_207 IN ('GB2015') THEN 'BA25'
			WHEN UNIV_AUX.CKAREA_207 IN ('AN02060000') THEN 'BA26'
			WHEN UNIV_AUX.CKAREA_207 IN ('GA','AN03010000','AN03020000') THEN 'BA27'
			WHEN UNIV_AUX.CKAREA_207 IN ('SE') THEN 'BA28'
			WHEN UNIV_AUX.CKAREA_207 IN ('AN01060010') THEN 'BA29'
			WHEN UNIV_AUX.CKAREA_207 IN ('GB0520') THEN 'BA30'
			WHEN UNIV_AUX.CKAREA_207 IN ('GB0550') THEN 'BA31'
			WHEN UNIV_AUX.CKAREA_207 IN ('AN02030900') THEN 'BA32'
			WHEN UNIV_AUX.CKAREA_207 IN ('AN02030500') THEN 'BA33'
			WHEN UNIV_AUX.CKAREA_207 IN ('GB1020') THEN 'BA34'
			WHEN UNIV_AUX.CKAREA_207 IN ('PYM') THEN 'BA35'
			ELSE '' 
		END AS FLAG_BUS_AREA -- Comentário HF: É necessário rever este case when para o mês de processamento dos dados. (Lógica Pais e Filhos --> ct875_regras_dim (where campo='BSNN_AREA') & ct010_dim_valor & ct011_dim_hier (id_dimensao=6))
	FROM
		(
		SELECT DISTINCT
			CONCAT(TRIM(CEMPCTA),TRIM(CKBALCAO),TRIM(CKNUMCTA),TRIM(ZDEPOSIT)) AS CHAVE_MIS_207
			,TRIM(CKPRODMI) AS CKPRODMI_207
			,TRIM(ZSEQDIV) AS ZSEQDIV_207
			,TRIM(CHCRUZA) AS CHCRUZA_207
			,TRIM(CKMETAMIS) AS CKMETAMIS_207
			,TRIM(SUBSTR(CKMETAMIS,1,4)) AS CKMETAMIS_AUX_207
			,TRIM(ZCLIENTE) AS ZCLIENTE_207
			,UPPER(TRIM(CKAREA)) AS CKAREA_207
		FROM cd_captools.ct207_rent_over 
		WHERE REF_DATE = '${ref_date}'
		)UNIV_AUX
		
	LEFT JOIN
		(
		SELECT DISTINCT 
			TRIM(METAPRODUTO) AS METAPRODUTO_831
			,TRIM(TIPO_CONTA_LOCAL) AS TIPO_CONTA_LOCAL_831
		FROM CD_CAPTOOLS.CT831_CLASS_META 
			WHERE REF_DATE = '${ref_date}' 
			AND AMBITO = 'CDG' 
			AND METAPRODUTO <> ''
			AND UPPER(TRIM(TIPO_CONTA_LOCAL)) IN ('ATIVO')
		)CT831_1 ON CT831_1.METAPRODUTO_831=UNIV_AUX.CKMETAMIS_AUX_207
	LEFT JOIN
		(
		SELECT DISTINCT 
			TRIM(METAPRODUTO) AS METAPRODUTO_831
			,TRIM(TIPO_CONTA_LOCAL) AS TIPO_CONTA_LOCAL_831
		FROM CD_CAPTOOLS.CT831_CLASS_META 
			WHERE REF_DATE = '${ref_date}' 
			AND AMBITO = 'CDG' 
			AND METAPRODUTO <> ''
			AND UPPER(TRIM(TIPO_CONTA_LOCAL)) IN ('ATIVO PATRIMONIAL')
		)CT831_2 ON CT831_2.METAPRODUTO_831=UNIV_AUX.CKMETAMIS_AUX_207
	LEFT JOIN
		(
		SELECT DISTINCT 
			TRIM(METAPRODUTO) AS METAPRODUTO_831
			,TRIM(TIPO_CONTA_LOCAL) AS TIPO_CONTA_LOCAL_831
		FROM CD_CAPTOOLS.CT831_CLASS_META 
			WHERE REF_DATE = '${ref_date}' 
			AND AMBITO = 'CDG' 
			AND METAPRODUTO <> ''
			AND UPPER(TRIM(TIPO_CONTA_LOCAL)) IN ('ATIVO EXTRAPATRIMONIAL LINHAS DE CREDITO')
		)CT831_3 ON CT831_3.METAPRODUTO_831=UNIV_AUX.CKMETAMIS_AUX_207
	LEFT JOIN
		(
		SELECT DISTINCT 
			TRIM(METAPRODUTO) AS METAPRODUTO_831
			,TRIM(TIPO_CONTA_LOCAL) AS TIPO_CONTA_LOCAL_831
		FROM CD_CAPTOOLS.CT831_CLASS_META 
			WHERE REF_DATE = '${ref_date}' 
			AND AMBITO = 'CDG' 
			AND METAPRODUTO <> ''
			AND UPPER(TRIM(TIPO_CONTA_LOCAL)) IN ('ATIVO EXTRAPATRIMONIAL CREDITO ASSINATURA')
		)CT831_4 ON CT831_4.METAPRODUTO_831=UNIV_AUX.CKMETAMIS_AUX_207
	)UNIV
LEFT JOIN 
	(
	SELECT
		CONCAT(TRIM(CEMPCTA),TRIM(CKBALCAO),TRIM(CKNUMCTA),TRIM(ZDEPOSIT)) AS CHAVE_MIS_209
		,TRIM(CKPRODMI) AS CKPRODMI_209
		,TRIM(ZSEQDIV) AS ZSEQDIV_209
		,TRIM(CHCRUZA) AS CHCRUZA_209
		,TRIM(CKMETAMIS) AS CKMETAMIS_209
		,TRIM(ZCLIENTE) AS ZCLIENTE_209
		,SUM(C001) AS C001
		,SUM(C007) AS C007
		,SUM(C134) AS C134
		,SUM(C224) AS C224
		,SUM(C298) AS C298
		,SUM(C299) AS C299
		,SUM(C300) AS C300
		,SUM(M009) AS M009
		,SUM(AC310) AS AC310
	FROM
		(
		SELECT * 
		FROM cd_captools.ct209_rent_kpm
		WHERE ref_date = '${ref_date}' 
			AND C325 = 0 -- Comentário HF: IT aplica este filtro, no entanto não encontrei esta evidência nos e-mail's --> Motivo: Excluir linhas relativo a cartões.  
			AND C453 = 0 -- Comentário HF: IT aplica este filtro, no entanto não encontrei esta evidência nos e-mail's --> Motivo: Excluir linhas relativo a cartões.
			AND (ABS(C001) + ABS(C007) + ABS(C134) + ABS(C224) + ABS(C298) + ABS(C299) + ABS(C300) + ABS(AC310) + ABS(M009)) <> 0 -- Comentário HF: IT aplica este filtro --> Adicionalmente, existe evidência de parte destes filtros no e-mail BS | Testes Pilar III ESG - MV & GD (02/08/2024)
		)AUX
	GROUP BY 1,2,3,4,5,6
	)CT209 ON UNIV.CHAVE_MIS_207=CT209.CHAVE_MIS_209 
				AND UNIV.CKPRODMI_207=CT209.CKPRODMI_209 
				AND UNIV.ZSEQDIV_207=CT209.ZSEQDIV_209 
				AND UNIV.CHCRUZA_207=CT209.CHCRUZA_209
				AND UNIV.CKMETAMIS_207=CT209.CKMETAMIS_209
				AND UNIV.ZCLIENTE_207=CT209.ZCLIENTE_209
LEFT JOIN 
	(
	SELECT
		CONCAT(TRIM(CEMPCTA),TRIM(CKBALCAO),TRIM(CKNUMCTA),TRIM(ZDEPOSIT)) AS CHAVE_MIS_211
		,TRIM(CKPRODMI) AS CKPRODMI_211
		,TRIM(ZSEQDIV) AS ZSEQDIV_211
		,TRIM(CHCRUZA) AS CHCRUZA_211
		,TRIM(CKMETAMIS) AS CKMETAMIS_211
		,TRIM(ZCLIENTE) AS ZCLIENTE_211
		,SUM(C457) AS C457
		,SUM(C458) AS C458
		,SUM(C459) AS C459
		,SUM(C460) AS C460
	FROM
		(
		SELECT * 
		FROM cd_captools.ct211_rent_kpmco
		WHERE ref_date = '${ref_date}' 
			AND (ABS(C457) + ABS(C458) + ABS(C459) + ABS(C460)) <> 0 -- Comentário HF: IT aplica este filtro --> Adicionalmente, existe evidência de parte destes filtros no e-mail BS | Testes Pilar III ESG - MV & GD (02/08/2024)
		)AUX
	GROUP BY 1,2,3,4,5,6
	)CT211 ON UNIV.CHAVE_MIS_207=CT211.CHAVE_MIS_211 
				AND UNIV.CKPRODMI_207=CT211.CKPRODMI_211 
				AND UNIV.ZSEQDIV_207=CT211.ZSEQDIV_211 
				AND UNIV.CHCRUZA_207=CT211.CHCRUZA_211
				AND UNIV.CKMETAMIS_207=CT211.CKMETAMIS_211
				AND UNIV.ZCLIENTE_207=CT211.ZCLIENTE_211
GROUP BY 1,2,3,4,5,6

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 2. Métricas calculadas em MIS 
	  --> São consideradas todas as Business Areas no mês N e mês N-1 
--------------------------------------------------------------------------------------------------------------------------------------------------

-- MAI24 | Inserted 3.931.472 row(s)
 
DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.SIMUL_GD_MIS_ABR_MAI_24;
CREATE TABLE BU_CAPTOOLS_WORK.SIMUL_GD_MIS_ABR_MAI_24 AS

SELECT
	*
	,CASE
		WHEN X.CHAVE_MIS_207_MAI IS NOT NULL THEN X.CHAVE_MIS_207_MAI
		WHEN Y.CHAVE_MIS_207_ABR IS NOT NULL THEN Y.CHAVE_MIS_207_ABR
	END AS CHAVE
	,CASE
		WHEN X.CHAVE_MIS_207_MAI IS NOT NULL THEN X.FLAG_BUS_AREA_MAI
		WHEN Y.CHAVE_MIS_207_ABR IS NOT NULL THEN Y.FLAG_BUS_AREA_ABR
	END AS FLAG_BUS_AREA
    ,CASE
        WHEN X.CHAVE_MIS_207_MAI IS NOT NULL AND Y.CHAVE_MIS_207_ABR IS NOT NULL THEN 'UNIVERSO COMUM'
        WHEN X.CHAVE_MIS_207_MAI IS NOT NULL AND Y.CHAVE_MIS_207_ABR IS NULL THEN 'UNIVERSO EXCLUSIVO MAIO'
        WHEN X.CHAVE_MIS_207_MAI IS NULL AND Y.CHAVE_MIS_207_ABR IS NOT NULL THEN 'UNIVERSO EXCLUSIVO ABRIL'
    END AS CONTROLO_UNIV
    ,CASE
        WHEN FLAG_ATIVO_PATRIMONIAL_ABR=1 OR FLAG_ATIVO_PATRIMONIAL_MAI=1 THEN (NVL(X.C457_MAI,0)+NVL(X.C460_MAI,0))-(NVL(Y.C457_ABR,0)+NVL(Y.C460_ABR,0))
    END AS GRSS_FEE_CMMSSN_INCM_MIS
    ,CASE
        WHEN FLAG_ATIVO_PATRIMONIAL_MAI=1 OR FLAG_ATIVO_PATRIMONIAL_LC_MAI=1 OR FLAG_ATIVO_PATRIMONIAL_CA_MAI=1 OR FLAG_ATIVO_PATRIMONIAL_ABR=1 OR FLAG_ATIVO_PATRIMONIAL_LC_ABR=1 OR FLAG_ATIVO_PATRIMONIAL_CA_ABR=1 THEN (NVL(X.C457_MAI,0)+NVL(X.C460_MAI,0))-(NVL(Y.C457_ABR,0)+NVL(Y.C460_ABR,0))
    END AS GRSS_FEE_CMMSSN_INCM_OFF_BLNC_MIS
    ,CASE
        WHEN FLAG_ATIVO_PATRIMONIAL_MAI=1 OR FLAG_ATIVO_PATRIMONIAL_LC_MAI=1 OR FLAG_ATIVO_PATRIMONIAL_CA_MAI=1 OR FLAG_ATIVO_PATRIMONIAL_ABR=1 OR FLAG_ATIVO_PATRIMONIAL_LC_ABR=1 OR FLAG_ATIVO_PATRIMONIAL_CA_ABR=1 THEN NVL(X.C298_MAI,0)-NVL(Y.C298_ABR,0)
    END AS GRSS_INTRST_INCM_MIS
    
FROM 
    (
    SELECT
	    CHAVE_MIS_207 AS CHAVE_MIS_207_MAI
	    ,FLAG_ATIVO AS FLAG_ATIVO_MAI
	    ,FLAG_ATIVO_PATRIMONIAL AS FLAG_ATIVO_PATRIMONIAL_MAI
	    ,FLAG_ATIVO_PATRIMONIAL_LC AS FLAG_ATIVO_PATRIMONIAL_LC_MAI
	    ,FLAG_ATIVO_PATRIMONIAL_CA AS FLAG_ATIVO_PATRIMONIAL_CA_MAI
	    ,FLAG_BUS_AREA AS FLAG_BUS_AREA_MAI
	    --,C001 AS C001_MAI
	    --,C007 AS C007_MAI
	    --,C134 AS C134_MAI
	    --,C224 AS C224_MAI
	    ,C298 AS C298_MAI
	    --,C299 AS C299_MAI
	    --,C300 AS C300_MAI
	    --,M009 AS M009_MAI
	    --,AC310 AS AC310_MAI
	    ,C457 AS C457_MAI
	    --,C458 AS C458_MAI
	    --,C459 AS C459_MAI
	    ,C460 AS C460_MAI
    FROM BU_CAPTOOLS_WORK.SIMUL_GD_MIS_MAI24
    WHERE (FLAG_ATIVO + FLAG_ATIVO_PATRIMONIAL + FLAG_ATIVO_PATRIMONIAL_LC + FLAG_ATIVO_PATRIMONIAL_CA)>=1
    )X
FULL JOIN 
    (
    SELECT 
	    CHAVE_MIS_207 AS CHAVE_MIS_207_ABR
	    ,FLAG_ATIVO AS FLAG_ATIVO_ABR
	    ,FLAG_ATIVO_PATRIMONIAL AS FLAG_ATIVO_PATRIMONIAL_ABR
	    ,FLAG_ATIVO_PATRIMONIAL_LC AS FLAG_ATIVO_PATRIMONIAL_LC_ABR
	    ,FLAG_ATIVO_PATRIMONIAL_CA AS FLAG_ATIVO_PATRIMONIAL_CA_ABR
	    ,FLAG_BUS_AREA AS FLAG_BUS_AREA_ABR
	    --,C001 AS C001_ABR
	    --,C007 AS C007_ABR
	    --,C134 AS C134_ABR
	    --,C224 AS C224_ABR
	    ,C298 AS C298_ABR
	    --,C299 AS C299_ABR
	    --,C300 AS C300_ABR
	    --,M009 AS M009_ABR
	    --,AC310 AS AC310_ABR
	    ,C457 AS C457_ABR
	    --,C458 AS C458_ABR
	    --,C459 AS C459_ABR
	    ,C460 AS C460_ABR
    FROM BU_CAPTOOLS_WORK.SIMUL_GD_MIS_ABR24
    WHERE (FLAG_ATIVO + FLAG_ATIVO_PATRIMONIAL + FLAG_ATIVO_PATRIMONIAL_LC + FLAG_ATIVO_PATRIMONIAL_CA)>=1
    )Y
ON X.CHAVE_MIS_207_MAI=Y.CHAVE_MIS_207_ABR 
    AND X.FLAG_BUS_AREA_MAI=Y.FLAG_BUS_AREA_ABR
    AND X.FLAG_ATIVO_MAI=Y.FLAG_ATIVO_ABR                                -- Comentário HF: Entre Abril e Maio não identifiquei contratos a alterar esta flag de um mês para o outro 
    AND X.FLAG_ATIVO_PATRIMONIAL_MAI=Y.FLAG_ATIVO_PATRIMONIAL_ABR        -- Comentário HF: Entre Abril e Maio não identifiquei contratos a alterar esta flag de um mês para o outro
    AND X.FLAG_ATIVO_PATRIMONIAL_LC_MAI=Y.FLAG_ATIVO_PATRIMONIAL_LC_ABR  -- Comentário HF: Entre Abril e Maio não identifiquei contratos a alterar esta flag de um mês para o outro
    AND X.FLAG_ATIVO_PATRIMONIAL_CA_MAI=Y.FLAG_ATIVO_PATRIMONIAL_CA_ABR  -- Comentário HF: Entre Abril e Maio não identifiquei contratos a alterar esta flag de um mês para o outro
ORDER BY CHAVE_MIS_207_MAI

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 3. Restrição da última tabela apenas para contratos do mês N   
--------------------------------------------------------------------------------------------------------------------------------------------------

-- MAI24 | Inserted 3.881.837 row(s)

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.SIMUL_GD_MIS_REPORTE_MAI_24;
CREATE TABLE BU_CAPTOOLS_WORK.SIMUL_GD_MIS_REPORTE_MAI_24 AS

SELECT 
	CHAVE
	,FLAG_BUS_AREA
	,SUM(NVL(GRSS_FEE_CMMSSN_INCM_MIS,0)) AS GRSS_FEE_CMMSSN_INCM_MIS
	,SUM(NVL(GRSS_FEE_CMMSSN_INCM_OFF_BLNC_MIS,0)) AS GRSS_FEE_CMMSSN_INCM_OFF_BLNC_MIS
	,SUM(NVL(GRSS_INTRST_INCM_MIS,0)) AS GRSS_INTRST_INCM_MIS
FROM BU_CAPTOOLS_WORK.SIMUL_GD_MIS_ABR_MAI_24
WHERE CHAVE IN (SELECT CHAVE_MIS_207 FROM BU_CAPTOOLS_WORK.SIMUL_GD_MIS_MAI24)
GROUP BY 1,2
;











--------------------------------------------------------------------------------------------------------------------------------------------------
-- 99. EM WIP   
--------------------------------------------------------------------------------------------------------------------------------------------------

SELECT *
FROM 
    (
    SELECT 
        CASE 
            WHEN INSTR(INSTRMNT_ID,'BA')>0 THEN SUBSTRING(INSTRMNT_ID,1,INSTR(INSTRMNT_ID,'BA')-1) 
            ELSE INSTRMNT_ID
        END AS INSTRMNT_ID_MOD
        ,INSTRMNT_ID
        ,BSNSS_AREA
        ,BSNSS_AREA_CCRR
        ,BSNSS_AREA_DSTNTN
        ,GRSS_CMMSSN_INCM
        ,GRSS_CMMSSN_INCM_OFF_BLNC
        ,GRSS_INTRST_INCM
    FROM BU_CAPTOOLS_WORK.LT002_GD_COPY
    )BASE 
LEFT JOIN
    (
    SELECT
        CONCAT(CEMPRESA_FR,CBALCAO_FR,CNUMECTA_FR,ZDEPOSIT_FR) AS CHAVE_FR
        ,CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) AS CHAVE_MASTER
    FROM CD_CAPTOOLS.KT_CHAVES_FINREP
    WHERE REF_DATE = '${REF_DATE}'
    --HAVING CHAVE_FR='31003171540780011664630100000001'
    )TRAD_FINREP ON BASE.INSTRMNT_ID_MOD=TRAD_FINREP.CHAVE_FR
LEFT JOIN 
    (
    SELECT
         
        CONCAT(CEMPRESA, CBALCAO, CNUMECTA, ZDEPOSIT) AS CHAVE_MASTER
        ,CONCAT(TRIM(CEMPCTA), TRIM(CKBALCAO), TRIM(CKNUMCTA), TRIM(ZDEPOSIT_MIS)) AS CHAVE_MIS
    FROM CD_CAPTOOLS.KT_CHAVES_MIS
    WHERE REF_DATE = '${REF_DATE}'
    --HAVING CHAVE_MASTER='31003171540780011664630100000001'
    )TRAD_MIS ON TRAD_FINREP.CHAVE_MASTER=TRAD_MIS.CHAVE_MASTER
LEFT JOIN 
    (
	SELECT *
	FROM BU_CAPTOOLS_WORK.SIMUL_GD_MIS_REPORTE_MAI_24
    )MIS ON TRAD_MIS.CHAVE_MIS=MIS.CHAVE 
    
WHERE INSTRMNT_ID='31003187357380011561545100000001'

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 99. Diferenças 
--------------------------------------------------------------------------------------------------------------------------------------------------

--Exemplo 1 - 1:N

SELECT 
    CASE 
        WHEN INSTR(INSTRMNT_ID,'BA')>0 THEN SUBSTRING(INSTRMNT_ID,1,INSTR(INSTRMNT_ID,'BA')-1) 
        ELSE INSTRMNT_ID
    END AS INSTRMNT_ID_MOD
    ,INSTRMNT_ID
    ,BSNSS_AREA
    ,BSNSS_AREA_CCRR
    ,BSNSS_AREA_DSTNTN
    ,GRSS_CMMSSN_INCM
    ,GRSS_CMMSSN_INCM_OFF_BLNC
    ,GRSS_INTRST_INCM
FROM BU_CAPTOOLS_WORK.LT002_GD_COPY
HAVING INSTRMNT_ID_MOD='31003171540780011664630100000001'
;

SELECT
    CONCAT(CEMPRESA_FR,CBALCAO_FR,CNUMECTA_FR,ZDEPOSIT_FR) AS CHAVE_FR
    ,CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) AS CHAVE_MASTER
FROM CD_CAPTOOLS.KT_CHAVES_FINREP
WHERE REF_DATE = '${REF_DATE}'
HAVING CHAVE_FR='31003171540780011664630100000001'
;

SELECT * 
FROM BU_CAPTOOLS_WORK.SIMUL_GD_MIS_ABR_MAI_24
WHERE CHAVE_MIS_207_MAI IN 
    (
    SELECT
        CONCAT(TRIM(CEMPCTA), TRIM(CKBALCAO), TRIM(CKNUMCTA), TRIM(ZDEPOSIT_MIS)) AS CHAVE_MIS
    FROM CD_CAPTOOLS.KT_CHAVES_MIS
    WHERE REF_DATE = '${REF_DATE}'
        AND CONCAT(CEMPRESA, CBALCAO, CNUMECTA, ZDEPOSIT)='31003171540780011664630100000001'
    )
	
--Exemplo 2 1:1

SELECT 
    CASE 
        WHEN INSTR(INSTRMNT_ID,'BA')>0 THEN SUBSTRING(INSTRMNT_ID,1,INSTR(INSTRMNT_ID,'BA')-1) 
        ELSE INSTRMNT_ID
    END AS INSTRMNT_ID_MOD
    ,INSTRMNT_ID
    ,BSNSS_AREA
    ,BSNSS_AREA_CCRR
    ,BSNSS_AREA_DSTNTN
    ,GRSS_CMMSSN_INCM
    ,GRSS_CMMSSN_INCM_OFF_BLNC
    ,GRSS_INTRST_INCM
FROM BU_CAPTOOLS_WORK.LT002_GD_COPY
HAVING INSTRMNT_ID_MOD='31000000021520001000000000000000'
;

SELECT
    CONCAT(CEMPRESA_FR,CBALCAO_FR,CNUMECTA_FR,ZDEPOSIT_FR) AS CHAVE_FR
    ,CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) AS CHAVE_MASTER
FROM CD_CAPTOOLS.KT_CHAVES_FINREP
WHERE REF_DATE = '${REF_DATE}'
HAVING CHAVE_FR='31000000021520001000000000000000'

;

SELECT * 
FROM BU_CAPTOOLS_WORK.SIMUL_GD_MIS_ABR_MAI_24
WHERE CHAVE_MIS_207_MAI IN 
    (
    SELECT
        CONCAT(TRIM(CEMPCTA), TRIM(CKBALCAO), TRIM(CKNUMCTA), TRIM(ZDEPOSIT_MIS)) AS CHAVE_MIS
    FROM CD_CAPTOOLS.KT_CHAVES_MIS
    WHERE REF_DATE = '${REF_DATE}'
        AND CONCAT(CEMPRESA, CBALCAO, CNUMECTA, ZDEPOSIT)='31000000021520001000000000000000'
    )




