/********************************************************************************************************************************************
****   Projeto: Implementação Templates Locais                                                                     						 ****
****   Autor: BS & Neyond                                                                                                                ****
****   Data: 23/04/2025                                                                                                                  ****
****   SQL Script Descrição: Geração do Template 5 																					     ****
****  ( Banking book - Climate change physical risk: Exposures subject to physical risk  ) 												 ****
********************************************************************************************************************************************/

/*=========================================================================================================================================*/
/*  1. Tabela granular: Obtenção do universo a reportar no âmbito do Template 5 + Marcação de metricas relevantes             			   */
/*=========================================================================================================================================*/
       

INSERT OVERWRITE TABLE BU_ESG_WORK.AG05_TEMP_CTO_GRA PARTITION (REF_DATE)
SELECT XX.*,
    -- PARTICAO
	'${REF_DATE}' AS REF_DATE
FROM
(
    -- VALOR BRUTO
    SELECT
        UNI.ZCLIENTE, 
        UNI.CEMPRESA,
        UNI.CBALCAO,
        UNI.CNUMECTA,
        UNI.ZDEPOSIT,
        EMISS.CEMPBEM,
        EMISS.CKBALBEM,
        EMISS.CKCTABEM,
        EMISS.CKREFBEM,
        -1*SUM(EMISS.AMOUNT) AS AMOUNT,
        UNI.BRUTO_IMPARIDADE AS VB_IMP, 
        UNI.STAGES AS STAGE, 
        UNI.CONTRAPARTE, 
        CASE
            WHEN INSTRUMENTO_FINANCEIRO = 'instrumentos de capital' THEN -3 -- 'INSTRUMENTOS DE CAPITAL' : > 20 ANOS
            WHEN UNI.DATA_VENCIMENTO  IN ('','0001-01-01','9999-12-31',NULL) AND TIPO_COLATERAL = 'Garantia Residencial' THEN -2 -- FALTA DE DATA QUALITY DE DADOS MAS GARANTIA RESIDENCIAL
            WHEN UNI.DATA_VENCIMENTO  IN ('','0001-01-01','9999-12-31',NULL) THEN -1 -- FALTA DE DATA QUALITY DE DADOS MAS NÃO GARANTIA RESIDENCIAL
            WHEN UPPER(UNI.PRODUTO) LIKE 'CART%CR%DITO%' OR UPPER(UNI.PRODUTO) LIKE '%REPOS%'  OR UPPER(UNI.PRODUTO) LIKE '%VISTA, DESCOBERTOS E CO%' THEN -1 -- 'COUNTERPARTY HAVING THE CHOICE OF THE REPAYMENT DATE'
            WHEN UNI.DATA_VENCIMENTO  < '${REF_DATE}' THEN -4 --'OLD CONTRACTS' 
            ELSE ROUND(DATEDIFF(TO_DATE(UNI.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25, 4)
        END AS YEARS_TO_MATURITY, 
        CASE
            WHEN UNI.ZCLIENTE = '0000000000' THEN 'S'
            WHEN NFIN.COD_NACE_ESG = '' AND UNI.CONTRAPARTE = 'outras empresas nao financeiras' THEN 'S' 
            WHEN NFIN.COD_NACE_ESG = 'Nao Aplicavel' THEN '' 
            WHEN NFIN.COD_NACE_ESG IS NULL THEN ''
            ELSE SUBSTR(NFIN.COD_NACE_ESG,1,1)
        END AS COD_NACE_ESG,
        TIPO_COLATERAL,
        CASE 
            WHEN FLG_ACT_PHYSCL_RSK_PRTCTN > 0 THEN 'ACUT1'
            WHEN (FLG_ACT_PHYSCL_RSK_PRTCTN IS NULL OR FLG_ACT_PHYSCL_RSK_PRTCTN=0) AND FLG_ACT_PHYSCL_RSK_ENTTY > 0 THEN 'ACUT1' 
            ELSE 'ACUT2' 
        END AS ACUTE_CHANGES,
        CASE 
            WHEN FLG_CHRNC_PHYSCL_RSK_PRTCTN > 0 THEN 'CHRO1'
            WHEN (FLG_CHRNC_PHYSCL_RSK_PRTCTN IS NULL OR FLG_CHRNC_PHYSCL_RSK_PRTCTN=0) AND FLG_CHRNC_PHYSCL_RSK_ENTTY > 0 THEN 'CHRO1' 
            ELSE 'CHRO2' 
        END AS CHRONIC_CHANGES,
        CASE
            WHEN FLG_ACT_PHYSCL_RSK_PRTCTN > 0 OR FLG_ACT_PHYSCL_RSK_ENTTY > 0 OR FLG_CHRNC_PHYSCL_RSK_PRTCTN > 0 OR FLG_CHRNC_PHYSCL_RSK_ENTTY > 0 THEN 1
            ELSE 0
        END AS FLAG_PHYSICAL_RISK

    FROM 
    -- TABELA DE UNIVERSO
    (
			SELECT DISTINCT         
				F2.ZCLIENTE    
				,F1.CEMPRESA
				,F1.CBALCAO
				,F1.CNUMECTA
				,F1.ZDEPOSIT
				,F1.BRUTO_IMPARIDADE
				,F1.STAGES
				,F1.CONTRAPARTE
				,F2.DATA_VENCIMENTO
				,F1.PRODUTO
				,F1.TIPO_COLATERAL
				,F1.INSTRUMENTO_FINANCEIRO 
				
		FROM 
		(
			SELECT DISTINCT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,BRUTO_IMPARIDADE,CONTRAPARTE,INSTRUMENTO_FINANCEIRO,TIPO_COLATERAL,
				CASE 
					WHEN A2.CONTA IS NOT NULL THEN A2.PRODUTO
					WHEN A3.CONTA IS NOT NULL THEN A3.PRODUTO
					WHEN A4.CONTA IS NOT NULL THEN A4.PRODUTO
				END AS PRODUTO,
				CASE 
					WHEN A2.CONTA IS NOT NULL THEN A2.STAGES
					WHEN A3.CONTA IS NOT NULL THEN A3.STAGES
					WHEN A4.CONTA IS NOT NULL THEN A4.STAGES
				END AS STAGES
				
			FROM 
			(
				SELECT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,CONTRAPARTE,INSTRUMENTO_FINANCEIRO,CCONTAB_FINAL_IFRS,CCONTAB_FINAL_ST_SGPS_CONS,CCONTAB_FINAL_IDCOMB,COD_PLANO,
					CASE 
						WHEN CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL1%' THEN 'Sem Garantia'
						WHEN CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL2%' THEN 'Garantia Residencial'
						WHEN CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL3%' THEN 'Garantia Comercial'
						WHEN CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL4%' THEN 'Garantia Real'
					END AS TIPO_COLATERAL,
					CASE 
						WHEN TRIM(BRUTO_IMPARIDADE)='' AND CCONTAB_FINAL_IDCOMB LIKE '%TYVA01%' THEN 'valor bruto'
						WHEN TRIM(BRUTO_IMPARIDADE)='' AND CCONTAB_FINAL_IDCOMB LIKE '%TYVA02%' THEN 'imparidade'
						ELSE BRUTO_IMPARIDADE
					END AS BRUTO_IMPARIDADE,SUM(MSALDO_FINAL) AS MSALDO_FINAL
				FROM BUSINESS_ESG.MODESG_OUT_REPORTE_GRANULAR
				WHERE REF_DATE = '${REF_DATE}'
					AND REPORTE_GRANULAR='Template 5'
					AND CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) NOT IN (SELECT CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) FROM CD_CAPTOOLS.CT001_UNIV_SALDO WHERE REF_DATE='${REF_DATE}' AND CCONTAB_FINAL_IDCOMB LIKE '%MC1005%')
				GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12
				HAVING BRUTO_IMPARIDADE='valor bruto' 
					 AND MSALDO_FINAL<>0
			)A1
			
			LEFT JOIN 
			(
				SELECT DISTINCT CONTA, PRODUTO, STAGES
				FROM CD_CAPTOOLS.FR802_PL_CONTAS
				WHERE REF_DATE = '${REF_DATE}'
					AND COD_PLANO = 'BST_IND'
					AND TRIM(CONTA) <> ''
			) A2 ON TRIM(A1.CCONTAB_FINAL_IFRS)=TRIM(A2.CONTA) AND A1.COD_PLANO = 'BST_IND'

			LEFT JOIN 
			(
				SELECT DISTINCT CONTA, PRODUTO, STAGES
				FROM CD_CAPTOOLS.FR802_PL_CONTAS
				WHERE REF_DATE = '${REF_DATE}'
					AND COD_PLANO = 'ST_SGPS_CONS'
					AND TRIM(CONTA) <> ''
			) A3 ON TRIM(A1.CCONTAB_FINAL_ST_SGPS_CONS)=TRIM(A3.CONTA) AND A1.COD_PLANO = 'ST_SGPS_CONS'
				
			LEFT JOIN 
			(
				SELECT DISTINCT CONTA, PRODUTO, STAGES
				FROM CD_CAPTOOLS.FR802_PL_CONTAS
				WHERE REF_DATE = '${REF_DATE}'
					AND COD_PLANO = 'BST_IDCOMB'
					AND TRIM(CONTA) <> ''
			) A4 ON TRIM(A1.CCONTAB_FINAL_IDCOMB)=TRIM(A4.CONTA) AND A1.COD_PLANO = 'BST_IDCOMB'
		) F1
		   
		LEFT JOIN 
		(
			SELECT DISTINCT CEMPRESA, CBALCAO, CNUMECTA, ZDEPOSIT, ZCLIENTE, DDVENCIM AS DATA_VENCIMENTO
			FROM CD_CAPTOOLS.CT004_UNIV_CTO 
			WHERE REF_DATE = '${REF_DATE}'
		) F2
		ON  F1.CEMPRESA  = F2.CEMPRESA AND 
			F1.CBALCAO  = F2.CBALCAO AND 
			F1.CNUMECTA = F2.CNUMECTA AND 
			F1.ZDEPOSIT = F2.ZDEPOSIT
    )UNI

    LEFT JOIN 
    (   
        SELECT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,ZCLIENTE,CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM,SUM(AMOUNT) AS AMOUNT
        FROM BUSINESS_ESG.MODESG_OUT_EMSS_FNCD
        WHERE NOME_PERIMETRO LIKE '%ST SGPS Cons%'
        AND REF_DATE='${REF_DATE}'
        GROUP BY 1,2,3,4,5,6,7,8,9
    ) EMISS
    ON  UNI.CEMPRESA = EMISS.CEMPRESA AND
        UNI.CBALCAO  = EMISS.CBALCAO AND
        UNI.CNUMECTA = EMISS.CNUMECTA AND
        UNI.ZDEPOSIT = EMISS.ZDEPOSIT 

    -- OBTENÇÃO DE CARACTERISTICAS DE CLIENTES (EX. CÓDIGO NACE E RISCOS FÍSICOS)
    LEFT JOIN 
    (
        SELECT *, FLG_RSC_FSC_AGD AS FLG_ACT_PHYSCL_RSK_ENTTY, FLG_RSC_FSC_CRNC AS FLG_CHRNC_PHYSCL_RSK_ENTTY  
        FROM BUSINESS_ESG.MODESG_OUT_EMPR_INFO_NFIN 
        WHERE REF_DATE='${REF_DATE}'
    ) NFIN
    ON UNI.ZCLIENTE = NFIN.ZCLIENTE

    LEFT JOIN 
    -- OBTENÇÃO DO RISCO AO NÍVEL DO COLATERAL IMÓVEL
    (
        SELECT *, FLG_RSC_FSC_AGD AS FLG_ACT_PHYSCL_RSK_PRTCTN, FLG_RSC_FSC_CRNC AS FLG_CHRNC_PHYSCL_RSK_PRTCTN  
        FROM BUSINESS_ESG.MODESG_OUT_BENS_IMOVEIS 
        WHERE REF_DATE='${REF_DATE}'
    ) MODESG_OUT_BENS_IMOVEIS
    ON  CONCAT(MODESG_OUT_BENS_IMOVEIS.CEMPBEM,MODESG_OUT_BENS_IMOVEIS.CKBALBEM,MODESG_OUT_BENS_IMOVEIS.CKCTABEM,MODESG_OUT_BENS_IMOVEIS.CKREFBEM) = CONCAT(EMISS.CEMPBEM,EMISS.CKBALBEM,EMISS.CKCTABEM,EMISS.CKREFBEM)
    GROUP BY 1,2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,19

    UNION ALL

    -- IMPARIDADE
    SELECT
        UNI.ZCLIENTE, 
        UNI.CEMPRESA,
        UNI.CBALCAO,
        UNI.CNUMECTA,
        UNI.ZDEPOSIT,
        NULL AS CEMPBEM,
        NULL AS CKBALBEM,
        NULL AS CKCTABEM,
        NULL AS CKREFBEM,
        -1*SUM(MSALDO_FINAL) AS AMOUNT,
        UNI.BRUTO_IMPARIDADE AS VB_IMP, 
        UNI.STAGES AS STAGE, 
        UNI.CONTRAPARTE, 
        CASE
            WHEN INSTRUMENTO_FINANCEIRO = 'instrumentos de capital' THEN -3 -- 'INSTRUMENTOS DE CAPITAL' : > 20 ANOS
            WHEN UNI.DATA_VENCIMENTO  IN ('','0001-01-01','9999-12-31',NULL) AND TIPO_COLATERAL = 'Garantia Residencial' THEN -2 -- FALTA DE DATA QUALITY DE DADOS MAS GARANTIA RESIDENCIAL
            WHEN UNI.DATA_VENCIMENTO  IN ('','0001-01-01','9999-12-31',NULL) THEN -1 -- FALTA DE DATA QUALITY DE DADOS MAS NÃO GARANTIA RESIDENCIAL
            WHEN UPPER(UNI.PRODUTO) LIKE 'CART%CR%DITO%' OR UPPER(UNI.PRODUTO) LIKE '%REPOS%'  OR UPPER(UNI.PRODUTO) LIKE '%VISTA, DESCOBERTOS E CO%' THEN -1 -- 'COUNTERPARTY HAVING THE CHOICE OF THE REPAYMENT DATE'
            WHEN UNI.DATA_VENCIMENTO  < '${REF_DATE}' THEN -4 --'OLD CONTRACTS' 
            ELSE ROUND(DATEDIFF(TO_DATE(UNI.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25, 4)
        END AS YEARS_TO_MATURITY, 
        CASE
            WHEN UNI.ZCLIENTE = '0000000000' THEN 'S'
            WHEN NFIN.COD_NACE_ESG = '' AND UNI.CONTRAPARTE = 'outras empresas nao financeiras' THEN 'S' 
            WHEN NFIN.COD_NACE_ESG = 'Nao Aplicavel' THEN '' 
            WHEN NFIN.COD_NACE_ESG IS NULL THEN ''
            ELSE SUBSTR(NFIN.COD_NACE_ESG,1,1)
        END AS COD_NACE_ESG,
        TIPO_COLATERAL,
        CASE 
            WHEN FLG_ACT_PHYSCL_RSK_ENTTY > 0 THEN 'ACUT1' 
            ELSE 'ACUT2' 
        END AS ACUTE_CHANGES,
        CASE 
            WHEN FLG_CHRNC_PHYSCL_RSK_ENTTY > 0 THEN 'CHRO1' 
            ELSE 'CHRO2' 
        END AS CHRONIC_CHANGES,
        CASE
            WHEN FLG_ACT_PHYSCL_RSK_ENTTY > 0 OR FLG_CHRNC_PHYSCL_RSK_ENTTY > 0 THEN 1
            ELSE 0
        END AS FLAG_PHYSICAL_RISK
        
    FROM 
    -- TABELA DE UNIVERSO
    (
			SELECT A1.*, A5.ZCLIENTE, A5.DATA_VENCIMENTO,
				CASE 
					WHEN A2.CONTA IS NOT NULL THEN A2.PRODUTO
					WHEN A3.CONTA IS NOT NULL THEN A3.PRODUTO
					WHEN A4.CONTA IS NOT NULL THEN A4.PRODUTO
				END AS PRODUTO,
				CASE 
					WHEN A2.CONTA IS NOT NULL THEN A2.STAGES
					WHEN A3.CONTA IS NOT NULL THEN A3.STAGES
					WHEN A4.CONTA IS NOT NULL THEN A4.STAGES
				END AS STAGES
				
			FROM 
			(
				SELECT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,CONTRAPARTE,INSTRUMENTO_FINANCEIRO,CCONTAB_FINAL_IFRS,CCONTAB_FINAL_ST_SGPS_CONS,CCONTAB_FINAL_IDCOMB,COD_PLANO,
					CASE 
						WHEN CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL1%' THEN 'Sem Garantia'
						WHEN CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL2%' THEN 'Garantia Residencial'
						WHEN CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL3%' THEN 'Garantia Comercial'
						WHEN CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL4%' THEN 'Garantia Real'
					END AS TIPO_COLATERAL,
					CASE 
						WHEN TRIM(BRUTO_IMPARIDADE)='' AND CCONTAB_FINAL_IDCOMB LIKE '%TYVA01%' THEN 'valor bruto'
						WHEN TRIM(BRUTO_IMPARIDADE)='' AND CCONTAB_FINAL_IDCOMB LIKE '%TYVA02%' THEN 'imparidade'
						ELSE BRUTO_IMPARIDADE
					END AS BRUTO_IMPARIDADE,SUM(MSALDO_FINAL) AS MSALDO_FINAL
				FROM BUSINESS_ESG.MODESG_OUT_REPORTE_GRANULAR
				WHERE REF_DATE = '${REF_DATE}'
					AND REPORTE_GRANULAR='Template 5'
					AND CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) NOT IN (SELECT CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) FROM CD_CAPTOOLS.CT001_UNIV_SALDO WHERE REF_DATE='${REF_DATE}' AND CCONTAB_FINAL_IDCOMB LIKE '%MC1005%')
				GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12
				HAVING BRUTO_IMPARIDADE='imparidade' 
					 AND MSALDO_FINAL<>0
			)A1
			
			LEFT JOIN 
			(
				SELECT DISTINCT CONTA, PRODUTO, STAGES
				FROM CD_CAPTOOLS.FR802_PL_CONTAS
				WHERE REF_DATE = '${REF_DATE}'
					AND COD_PLANO = 'BST_IND'
					AND TRIM(CONTA) <> ''
			) A2 ON TRIM(A1.CCONTAB_FINAL_IFRS)=TRIM(A2.CONTA) AND A1.COD_PLANO = 'BST_IND'

			LEFT JOIN 
			(
				SELECT DISTINCT CONTA, PRODUTO, STAGES
				FROM CD_CAPTOOLS.FR802_PL_CONTAS
				WHERE REF_DATE = '${REF_DATE}'
					AND COD_PLANO = 'ST_SGPS_CONS'
					AND TRIM(CONTA) <> ''
			) A3 ON TRIM(A1.CCONTAB_FINAL_ST_SGPS_CONS)=TRIM(A3.CONTA) AND A1.COD_PLANO = 'ST_SGPS_CONS'
				
			LEFT JOIN 
			(
				SELECT DISTINCT CONTA, PRODUTO, STAGES
				FROM CD_CAPTOOLS.FR802_PL_CONTAS
				WHERE REF_DATE = '${REF_DATE}'
					AND COD_PLANO = 'BST_IDCOMB'
					AND TRIM(CONTA) <> ''
			) A4 ON TRIM(A1.CCONTAB_FINAL_IDCOMB)=TRIM(A4.CONTA) AND A1.COD_PLANO = 'BST_IDCOMB'
			
			LEFT JOIN 
			(
				SELECT DISTINCT CEMPRESA, CBALCAO, CNUMECTA, ZDEPOSIT, ZCLIENTE, DDVENCIM AS DATA_VENCIMENTO
				FROM CD_CAPTOOLS.CT004_UNIV_CTO 
				WHERE REF_DATE = '${REF_DATE}'
			) A5
			ON  A1.CEMPRESA  = A5.CEMPRESA AND 
				A1.CBALCAO  = A5.CBALCAO AND 
				A1.CNUMECTA = A5.CNUMECTA AND 
				A1.ZDEPOSIT = A5.ZDEPOSIT
    )UNI 

    -- OBTENÇÃO DE CARACTERISTICAS DE CLIENTES (EX. CÓDIGO NACE E RISCOS FÍSICOS)
    LEFT JOIN 
    (
        SELECT *, FLG_RSC_FSC_AGD AS FLG_ACT_PHYSCL_RSK_ENTTY, FLG_RSC_FSC_CRNC AS FLG_CHRNC_PHYSCL_RSK_ENTTY  
        FROM BUSINESS_ESG.MODESG_OUT_EMPR_INFO_NFIN 
        WHERE REF_DATE='${REF_DATE}'
    ) NFIN
    ON UNI.ZCLIENTE = NFIN.ZCLIENTE

    GROUP BY 1,2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,19

    UNION ALL

    -- ADJUDICADOS
    SELECT *
    FROM
    (
        WITH ADJUD_INPUTS AS 
        (
            SELECT ADJUD_INPUTS.*,FLG_ACT_PHYSCL_RSK_PRTCTN,FLG_CHRNC_PHYSCL_RSK_PRTCTN
            FROM
            (
            SELECT
                '31' as PROPERTY_BANK_ID,
                'CMAH' AS PROPERTY_BRANCH_CODE, 
                'IMOVELGIDAP' AS PROPERTY_CONTRACT_ID,
                REPLACE(UPPER(LPAD(COD_IMOVEL,15,'0')),' ', '0') AS PROPERTY_REFERENCE_CODE,
                V_CONTAB, 
                PROV_LEGAL + PROV_ADICIONAL AS V_PROV
            FROM CD_CAPTOOLS.CT666_ADJUDIC_PROPR
            WHERE REF_DATE='${REF_DATE}'
            AND V_CONTAB_IFRS IN('199100240', '19910000', '1910000', '199100200', '199100210', '19910001', '1910008', '199100201', '199100211', '199100241')

            UNION ALL

            SELECT
                '89' AS PROPERTY_BANK_ID , 
                'CMAH' AS PROPERTY_BRANCH_CODE, 
                'IMOVELIFICS' AS PROPERTY_CONTRACT_ID,
                LPAD(N_IMOVEL,15,'0') AS PROPERTY_REFERENCE_CODE,
                V_CONTAB,
                PROV_TOTAL AS V_PROV
            FROM CD_CAPTOOLS.CT668_IMOVEIS_IFIC
            WHERE REF_DATE='${REF_DATE}'
            AND V_CONTAB_IFRS IN('199100240', '19910000', '1910000', '199100200', '199100210', '19910001', '1910008', '199100201', '199100211', '199100241')

            UNION ALL

            SELECT
                '00160' AS PROPERTY_BANK_ID , 
                'CMAH' AS PROPERTY_BRANCH_CODE, 
                'IMOVELGIDTU' AS PROPERTY_CONTRACT_ID, 
                LPAD(COD_IMOVEL,15,'0') AS PROPERTY_REFERENCE_CODE,
                V_CONTAB,
                PROV_TOTAL AS V_PROV     
            FROM CD_CAPTOOLS.CT665_STOCK_URBE
            WHERE REF_DATE='${REF_DATE}'

            ) ADJUD_INPUTS

            LEFT JOIN 
            -- OBTENÇÃO DO RISCO AO NÍVEL DO COLATERAL IMÓVEL
            (
                SELECT *, FLG_RSC_FSC_AGD AS FLG_ACT_PHYSCL_RSK_PRTCTN, FLG_RSC_FSC_CRNC AS FLG_CHRNC_PHYSCL_RSK_PRTCTN  
                FROM BUSINESS_ESG.MODESG_OUT_BENS_IMOVEIS 
                WHERE REF_DATE='${REF_DATE}'
            ) MODESG_OUT_BENS_IMOVEIS
            ON 
                MODESG_OUT_BENS_IMOVEIS.CEMPBEM = ADJUD_INPUTS.PROPERTY_BANK_ID  AND
                MODESG_OUT_BENS_IMOVEIS.CKBALBEM = ADJUD_INPUTS.PROPERTY_BRANCH_CODE AND
                MODESG_OUT_BENS_IMOVEIS.CKCTABEM = ADJUD_INPUTS.PROPERTY_CONTRACT_ID AND
                MODESG_OUT_BENS_IMOVEIS.CKREFBEM = ADJUD_INPUTS.PROPERTY_REFERENCE_CODE
        ) 
        -- BRUTO
        SELECT
            NULL AS ZCLIENTE,
            NULL AS CEMPRESA,
            NULL AS CBALCAO,
            NULL AS CNUMECTA,
            NULL AS ZDEPOSIT,
            PROPERTY_BANK_ID,
            PROPERTY_BRANCH_CODE,
            PROPERTY_CONTRACT_ID,
            PROPERTY_REFERENCE_CODE,
            SUM(V_CONTAB) AS MSALDO_FINAL,
            'valor bruto' AS VB_IMP,
            '' AS STAGE,
            '' AS CONTRAPARTE,
            -5 AS YEARS_TO_MATURITY,
            '' AS COD_NACE_ESG,
            'Stock' AS TIPO_COLATERAL,
            CASE 
                WHEN FLG_ACT_PHYSCL_RSK_PRTCTN > 0 THEN 'ACUT1'
                ELSE 'ACUT2' 
            END AS ACUTE_CHANGES,
            CASE 
                WHEN FLG_CHRNC_PHYSCL_RSK_PRTCTN > 0 THEN 'CHRO1' 
                ELSE 'CHRO2' 
            END AS CHRONIC_CHANGES,
            CASE
                WHEN FLG_ACT_PHYSCL_RSK_PRTCTN > 0 OR FLG_CHRNC_PHYSCL_RSK_PRTCTN > 0 THEN 1
                ELSE 0
            END AS FLAG_PHYSICAL_RISK

        FROM ADJUD_INPUTS
        WHERE CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) IN (SELECT CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) FROM CD_CAPTOOLS.CT001_UNIV_SALDO WHERE REF_DATE='${REF_DATE}' AND CCONTAB_FINAL_IDCOMB LIKE '%MC1005%')
        GROUP BY 1,2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,19

        UNION ALL
        -- IMPARIDADE
        SELECT
            NULL AS ZCLIENTE,
            NULL AS CEMPRESA,
            NULL AS CBALCAO,
            NULL AS CNUMECTA,
            NULL AS ZDEPOSIT,
            PROPERTY_BANK_ID,
            PROPERTY_BRANCH_CODE,
            PROPERTY_CONTRACT_ID,
            PROPERTY_REFERENCE_CODE,
            SUM(-1*V_PROV) AS MSALDO_FINAL,
            'imparidade' AS VB_IMP,
            '' AS STAGE,
            '' AS CONTRAPARTE,
            -5 AS YEARS_TO_MATURITY,
            '' AS COD_NACE_ESG,
            'Stock' AS TIPO_COLATERAL,
            CASE 
                WHEN FLG_ACT_PHYSCL_RSK_PRTCTN > 0 THEN 'ACUT1'
                ELSE 'ACUT2' 
            END AS ACUTE_CHANGES,
            CASE 
                WHEN FLG_CHRNC_PHYSCL_RSK_PRTCTN > 0 THEN 'CHRO1' 
                ELSE 'CHRO2' 
            END AS CHRONIC_CHANGES,
            CASE
                WHEN FLG_ACT_PHYSCL_RSK_PRTCTN > 0 OR FLG_CHRNC_PHYSCL_RSK_PRTCTN > 0 THEN 1
                ELSE 0
            END AS FLAG_PHYSICAL_RISK

        FROM ADJUD_INPUTS
        WHERE CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) IN (SELECT CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) FROM CD_CAPTOOLS.CT001_UNIV_SALDO WHERE REF_DATE='${REF_DATE}' AND CCONTAB_FINAL_IDCOMB LIKE '%MC1005%')
        GROUP BY 1,2,3,4,5,6,7,8,9,11,12,13,14,15,16,17,18,19
    ) X
) XX
