/********************************************************************************************************************************************
****   Projeto: Implementação Templates Locais                                                                     						 ****
****   Autor: BS & Neyond                                                                                                                ****
****   Data: 28/05/2025                                                                                                                  ****
****   SQL Script Descrição: Geração do Template 1																					     ****
****  ( Banking book - Climate change transition risk: Quality of exposures by sector ) 												 ****
********************************************************************************************************************************************/

/*=========================================================================================================================================*/
/*  1. Tabela granular: Obtenção do universo a reportar no âmbito do Template 1 + Marcação de metricas relevantes             			   */
/*=========================================================================================================================================*/
       
INSERT OVERWRITE TABLE BU_ESG_WORK.AG01_TEMP_CTO_GRA PARTITION (REF_DATE)

SELECT 
    UNIVERSO.ZCLIENTE,
	UNIVERSO.CEMPRESA,
	UNIVERSO.CBALCAO,
	UNIVERSO.CNUMECTA,
	UNIVERSO.ZDEPOSIT,
    UNIVERSO.VB_IMP, 
    UNIVERSO.STAGES AS STAGE, 
    UNIVERSO.CONTRAPARTE,
	NFIN.FLG_CSRD AS FLAG_CSRD,
	SUM(ASCI) AS ASCI,
	SUM(GESI) AS GESI,
	SUM(ASC2) AS ASC2,
	SUM(GESII) AS GESII,
	SUM(ASCIII) AS ASCIII,
	SUM(GESIII) AS GESIII,
	CASE
		WHEN  TRIM(UNIVERSO.CONTRAPARTE) = 'outras empresas nao financeiras' AND NFIN.FLG_EMPRS_EXCL_PARIS = 1 THEN 'excluido' 
		WHEN  TRIM(UNIVERSO.CONTRAPARTE) = 'outras empresas nao financeiras' AND NFIN.FLG_EMPRS_EXCL_PARIS = 0 THEN 'nao excluido' 
		ELSE ''
	END AS EXCLUDED_PARIS,
	CASE
        WHEN INSTRUMENTO_FINANCEIRO = 'instrumentos de capital' THEN -3 -- 'INSTRUMENTOS DE CAPITAL' : > 20 ANOS
	    WHEN UNIVERSO.DATA_VENCIMENTO  IN ('','0001-01-01','9999-12-31',NULL) AND TIPO_COLATERAL = 'Garantia Residencial' THEN -2 -- FALTA DE DATA QUALITY DE DADOS MAS GARANTIA RESIDENCIAL
    	WHEN UNIVERSO.DATA_VENCIMENTO  IN ('','0001-01-01','9999-12-31',NULL) THEN -1 -- FALTA DE DATA QUALITY DE DADOS MAS NÃO GARANTIA RESIDENCIAL
	    WHEN UPPER(UNIVERSO.PRODUTO) LIKE 'CART%CR%DITO%' OR UPPER(UNIVERSO.PRODUTO) LIKE '%REPOS%'  OR UPPER(UNIVERSO.PRODUTO) LIKE '%VISTA, DESCOBERTOS E CO%' THEN -1 -- 'COUNTERPARTY HAVING THE CHOICE OF THE REPAYMENT DATE'
        WHEN UNIVERSO.DATA_VENCIMENTO  < '${REF_DATE}' THEN -4 --'OLD CONTRACTS' 
        ELSE ROUND(DATEDIFF(TO_DATE(UNIVERSO.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25, 4)
    END AS YEARS_TO_MATURITY,
	CASE
		WHEN UNIVERSO.ZCLIENTE = '0000000000' THEN 'S'
		WHEN NFIN.COD_NACE_ESG = '' AND UNIVERSO.CONTRAPARTE = 'outras empresas nao financeiras' THEN 'S' 
		WHEN NFIN.COD_NACE_ESG = 'Nao Aplicavel' THEN '' 
		WHEN NFIN.COD_NACE_ESG IS NULL THEN ''
		ELSE NFIN.COD_NACE_ESG
	END AS COD_NACE_ESG,
	SUM(
        CASE
            WHEN TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'SPECIFIC PURPOSE' AND SFICS.NOME_SPECIFIC_ELIGIBLE = 'CCM' THEN NVL(ASCI,0) ELSE 0 END +
    	CASE 
    		WHEN TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'GENERAL PURPOSE' THEN NVL(ASCI * NFIN.CCM_TRNVR_OWN_PRFRMNCE_ALGND/100,0) ELSE 0 END + 
        CASE 
    		WHEN TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'GENERAL PURPOSE' THEN NVL(ASCI * NFIN.CCM_TRNVR_TRNSTN_ALIGND/100,0) ELSE 0 END + 
        CASE 
    		WHEN TRIM(UPPER(SFICS.NOME_GENERAL_SPECIFIC_PURPOSE)) = 'GENERAL PURPOSE' THEN NVL(ASCI * NFIN.CCM_TRNVR_ENBLNG_ALGND/100,0) ELSE 0 END 
		)  AS SUSTAINABLE_CCM,
	SOURCE_EMISSION_1,
	SOURCE_EMISSION_2,
	SOURCE_EMISSION_3,
	EUROPEAN_UNION,

	'${REF_DATE}' AS REF_DATE
FROM
(    SELECT 
    	ZCLIENTE,
    	CEMPRESA,
    	CBALCAO,
    	CNUMECTA,
    	ZDEPOSIT,
        VB_IMP, 
        CONTRAPARTE,
        STAGES,
        DATA_VENCIMENTO,
        PRODUTO,
        INSTRUMENTO_FINANCEIRO,
        TIPO_COLATERAL,
		SOURCE_EMISSION_1,
		SOURCE_EMISSION_2,
		SOURCE_EMISSION_3,
		EUROPEAN_UNION,
    	SUM(AMOUNT) AS ASCI,
    	SUM(GESI) AS GESI,
    	SUM(AMOUNT) AS ASC2,
    	SUM(GESII) AS GESII,
    	SUM(AMOUNT) AS ASCIII,
    	SUM(GESIII) AS GESIII    	
    FROM
    (
        SELECT
        	UNIVERSO.ZCLIENTE,
        	UNIVERSO.CEMPRESA,
        	UNIVERSO.CBALCAO,
        	UNIVERSO.CNUMECTA,
        	UNIVERSO.ZDEPOSIT,
            UNIVERSO.BRUTO_IMPARIDADE AS VB_IMP, 
            CONTRAPARTE,
            STAGES,
            DATA_VENCIMENTO,
            PRODUTO,
            INSTRUMENTO_FINANCEIRO,
            TIPO_COLATERAL,
			CASE 
        		WHEN EMISS.ORIGEM_SCP1_EMSS IN ('MISS','Nao Aplicavel') THEN 'SOUR3'
        		WHEN EMISS.ORIGEM_SCP1_EMSS LIKE '%DQS1%' OR EMISS.ORIGEM_SCP1_EMSS LIKE '%DQS2%' THEN 'SOUR1'
    			ELSE 'SOUR2'
    		END AS SOURCE_EMISSION_1,
			CASE 
				WHEN EMISS.ORIGEM_SCP2_EMSS IN ('MISS','Nao Aplicavel') THEN 'SOUR3'
				WHEN EMISS.ORIGEM_SCP2_EMSS LIKE '%DQS1%' OR EMISS.ORIGEM_SCP2_EMSS LIKE '%DQS2%' THEN 'SOUR1'
				ELSE 'SOUR2'
			END AS SOURCE_EMISSION_2,
			CASE 
				WHEN EMISS.ORIGEM_SCP3_EMSS IN ('MISS','Nao Aplicavel') THEN 'SOUR3'
				WHEN EMISS.ORIGEM_SCP3_EMSS LIKE '%DQS1%' OR EMISS.ORIGEM_SCP3_EMSS LIKE '%DQS2%' THEN 'SOUR1'
				ELSE 'SOUR2'
			END AS SOURCE_EMISSION_3,
			CASE
				WHEN UNIVERSO.ZCLIENTE = '0000000000' THEN 'EU1'
				WHEN CPAIS_RESIDENCIA IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428')
					THEN 'EU1'
				WHEN CPAIS_RESIDENCIA NOT IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428','')
					THEN 'EU2'
				ELSE '' 
			END AS EUROPEAN_UNION,
            SUM(CAST(EMISS.AMOUNT AS DECIMAL (38,6)))*-1 AS AMOUNT,
            SUM(CAST(EMISS.SCP1_EMSS_FNCD AS DECIMAL (38,16))) AS GESI,
            SUM(CAST(EMISS.SCP2_EMSS_FNCD AS DECIMAL (38,16))) AS GESII,
            SUM(CAST(EMISS.SCP3_EMSS_FNCD AS DECIMAL (38,16))) AS GESIII
        FROM
        -- TABELA DE UNIVERSO
        (
		SELECT DISTINCT A1.CEMPRESA,A1.CBALCAO,A1.CNUMECTA,A1.ZDEPOSIT,A5.ZCLIENTE,A1.BRUTO_IMPARIDADE,A1.CONTRAPARTE,A5.DATA_VENCIMENTO,A1.INSTRUMENTO_FINANCEIRO,A6.CPAIS_RESIDENCIA,
				CASE 
					WHEN CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL1%' THEN 'Sem Garantia'
					WHEN CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL2%' THEN 'Garantia Residencial'
					WHEN CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL3%' THEN 'Garantia Comercial'
					WHEN CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL4%' THEN 'Garantia Real'
				END AS TIPO_COLATERAL,
				CASE 
					WHEN A2.CONTA IS NOT NULL THEN A2.PRODUTO
					WHEN A3.CONTA IS NOT NULL THEN A3.PRODUTO
					WHEN A4.CONTA IS NOT NULL THEN A4.PRODUTO
				END AS PRODUTO,
				CASE 
					WHEN A2.CONTA IS NOT NULL THEN A2.STAGES
					WHEN A3.CONTA IS NOT NULL THEN A3.STAGES
					WHEN A4.CONTA IS NOT NULL THEN A4.STAGES
				END AS STAGES
				
			FROM 
			(
				SELECT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,CONTRAPARTE,INSTRUMENTO_FINANCEIRO,CCONTAB_FINAL_IFRS,CCONTAB_FINAL_ST_SGPS_CONS,CCONTAB_FINAL_IDCOMB,CCONTAB_FINAL_IDCOMB_TOTAL,COD_PLANO,
					CASE 
						WHEN TRIM(BRUTO_IMPARIDADE)='' AND CCONTAB_FINAL_IDCOMB LIKE '%TYVA01%' THEN 'valor bruto'
						WHEN TRIM(BRUTO_IMPARIDADE)='' AND CCONTAB_FINAL_IDCOMB LIKE '%TYVA02%' THEN 'imparidade'
						ELSE BRUTO_IMPARIDADE
					END AS BRUTO_IMPARIDADE, SUM(MSALDO_FINAL) AS MSALDO_FINAL
				FROM BUSINESS_ESG.MODESG_OUT_REPORTE_GRANULAR
				WHERE REF_DATE = '${REF_DATE}'
					AND REPORTE_GRANULAR='Template 1'
				GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12
				HAVING BRUTO_IMPARIDADE='valor bruto'
					AND MSALDO_FINAL<>0
			)A1
			
			LEFT JOIN 
			(
				SELECT DISTINCT CONTA, PRODUTO, STAGES
				FROM CD_CAPTOOLS.FR802_PL_CONTAS
				WHERE REF_DATE = '${REF_DATE}'
					AND COD_PLANO = 'BST_IND'
					AND TRIM(CONTA) <> ''
			) A2 ON TRIM(A1.CCONTAB_FINAL_IFRS)=TRIM(A2.CONTA) AND A1.COD_PLANO = 'BST_IND'

			LEFT JOIN 
			(
				SELECT DISTINCT CONTA, PRODUTO, STAGES
				FROM CD_CAPTOOLS.FR802_PL_CONTAS
				WHERE REF_DATE = '${REF_DATE}'
					AND COD_PLANO = 'ST_SGPS_CONS'
					AND TRIM(CONTA) <> ''
			) A3 ON TRIM(A1.CCONTAB_FINAL_ST_SGPS_CONS)=TRIM(A3.CONTA) AND A1.COD_PLANO = 'ST_SGPS_CONS'
				
			LEFT JOIN 
			(
				SELECT DISTINCT CONTA, PRODUTO, STAGES
				FROM CD_CAPTOOLS.FR802_PL_CONTAS
				WHERE REF_DATE = '${REF_DATE}'
					AND COD_PLANO = 'BST_IDCOMB'
					AND TRIM(CONTA) <> ''
			) A4 ON TRIM(A1.CCONTAB_FINAL_IDCOMB)=TRIM(A4.CONTA) AND A1.COD_PLANO = 'BST_IDCOMB'
			
			LEFT JOIN 
			(
				SELECT DISTINCT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,ZCLIENTE,DDVENCIM AS DATA_VENCIMENTO
				FROM CD_CAPTOOLS.CT004_UNIV_CTO
				WHERE REF_DATE = '${REF_DATE}'
			) A5 ON A1.CEMPRESA=A5.CEMPRESA
					AND A1.CBALCAO=A5.CBALCAO
					AND A1.CNUMECTA=A5.CNUMECTA
					AND A1.ZDEPOSIT=A5.ZDEPOSIT
			
			LEFT JOIN 
			(
				SELECT DISTINCT ZCLIENTE,CPAIS_RESIDENCIA
				FROM CD_CAPTOOLS.CT003_UNIV_CLI
				WHERE REF_DATE = '${REF_DATE}'
			) A6 ON A5.ZCLIENTE=A6.ZCLIENTE
			
        ) UNIVERSO
        
        LEFT JOIN 
        (   
            SELECT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,ZCLIENTE,ORIGEM_SCP1_EMSS, ORIGEM_SCP2_EMSS, ORIGEM_SCP3_EMSS,SUM(AMOUNT) AS AMOUNT,SUM(SCP1_EMSS_FNCD) AS SCP1_EMSS_FNCD,SUM(SCP2_EMSS_FNCD) AS SCP2_EMSS_FNCD,SUM(SCP3_EMSS_FNCD) AS SCP3_EMSS_FNCD
			FROM BUSINESS_ESG.MODESG_OUT_EMSS_FNCD
			WHERE REF_DATE = '${REF_DATE}' AND
				NOME_PERIMETRO LIKE '%ST SGPS Cons%'
            GROUP BY 1,2,3,4,5,6,7,8
        ) EMISS
        ON  UNIVERSO.CEMPRESA = EMISS.CEMPRESA AND
            UNIVERSO.CBALCAO  = EMISS.CBALCAO AND
            UNIVERSO.CNUMECTA = EMISS.CNUMECTA AND
            UNIVERSO.ZDEPOSIT = EMISS.ZDEPOSIT 

        GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
    ) BRUTO
    GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
    UNION ALL
    SELECT
    	IMP.ZCLIENTE, 
    	IMP.CEMPRESA,
    	IMP.CBALCAO,
    	IMP.CNUMECTA,
    	IMP.ZDEPOSIT,
        BRUTO_IMPARIDADE AS VB_IMP, 
        CONTRAPARTE,
        STAGES,
        DATA_VENCIMENTO,
        PRODUTO,
        INSTRUMENTO_FINANCEIRO,
        TIPO_COLATERAL,
        NULL AS SOURCE_EMISSION_1,
		NULL AS SOURCE_EMISSION_2,
		NULL AS SOURCE_EMISSION_3,
		CASE
			WHEN IMP.ZCLIENTE = '0000000000' THEN 'EU1' 
			WHEN CPAIS_RESIDENCIA IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428')
				THEN 'EU1'
			WHEN CPAIS_RESIDENCIA NOT IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428','')
				THEN 'EU2'
			ELSE '' 
		END AS EUROPEAN_UNION,
    	SUM(MSALDO_FINAL)*-1 AS ASCI,
    	NULL AS GESI,
    	SUM(MSALDO_FINAL)*-1 AS ASC2,
    	NULL AS GESII,
    	SUM(MSALDO_FINAL)*-1 AS ASCIII,
    	NULL AS GESIII
    FROM 
	(
		SELECT A1.*,A5.ZCLIENTE,A5.DATA_VENCIMENTO,A6.CPAIS_RESIDENCIA,
				CASE 
					WHEN CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL1%' THEN 'Sem Garantia'
					WHEN CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL2%' THEN 'Garantia Residencial'
					WHEN CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL3%' THEN 'Garantia Comercial'
					WHEN CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL4%' THEN 'Garantia Real'
				END AS TIPO_COLATERAL,
				CASE 
					WHEN A2.CONTA IS NOT NULL THEN A2.PRODUTO
					WHEN A3.CONTA IS NOT NULL THEN A3.PRODUTO
					WHEN A4.CONTA IS NOT NULL THEN A4.PRODUTO
				END AS PRODUTO,
				CASE 
					WHEN A2.CONTA IS NOT NULL THEN A2.STAGES
					WHEN A3.CONTA IS NOT NULL THEN A3.STAGES
					WHEN A4.CONTA IS NOT NULL THEN A4.STAGES
				END AS STAGES
				
			FROM 
			(
				SELECT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,CONTRAPARTE,INSTRUMENTO_FINANCEIRO,CCONTAB_FINAL_IFRS,CCONTAB_FINAL_ST_SGPS_CONS,CCONTAB_FINAL_IDCOMB,CCONTAB_FINAL_IDCOMB_TOTAL,COD_PLANO,
					CASE 
						WHEN TRIM(BRUTO_IMPARIDADE)='' AND CCONTAB_FINAL_IDCOMB LIKE '%TYVA01%' THEN 'valor bruto'
						WHEN TRIM(BRUTO_IMPARIDADE)='' AND CCONTAB_FINAL_IDCOMB LIKE '%TYVA02%' THEN 'imparidade'
						ELSE BRUTO_IMPARIDADE
					END AS BRUTO_IMPARIDADE, SUM(MSALDO_FINAL) AS MSALDO_FINAL
				FROM BUSINESS_ESG.MODESG_OUT_REPORTE_GRANULAR
				WHERE REF_DATE = '${REF_DATE}'
					AND REPORTE_GRANULAR='Template 1'
				GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12
				HAVING BRUTO_IMPARIDADE='imparidade'
					AND MSALDO_FINAL<>0
			)A1
			
			LEFT JOIN 
			(
				SELECT DISTINCT CONTA, PRODUTO, STAGES
				FROM CD_CAPTOOLS.FR802_PL_CONTAS
				WHERE REF_DATE = '${REF_DATE}'
					AND COD_PLANO = 'BST_IND'
					AND TRIM(CONTA) <> ''
			) A2 ON TRIM(A1.CCONTAB_FINAL_IFRS)=TRIM(A2.CONTA) AND A1.COD_PLANO = 'BST_IND'

			LEFT JOIN 
			(
				SELECT DISTINCT CONTA, PRODUTO, STAGES
				FROM CD_CAPTOOLS.FR802_PL_CONTAS
				WHERE REF_DATE = '${REF_DATE}'
					AND COD_PLANO = 'ST_SGPS_CONS'
					AND TRIM(CONTA) <> ''
			) A3 ON TRIM(A1.CCONTAB_FINAL_ST_SGPS_CONS)=TRIM(A3.CONTA) AND A1.COD_PLANO = 'ST_SGPS_CONS'
				
			LEFT JOIN 
			(
				SELECT DISTINCT CONTA, PRODUTO, STAGES
				FROM CD_CAPTOOLS.FR802_PL_CONTAS
				WHERE REF_DATE = '${REF_DATE}'
					AND COD_PLANO = 'BST_IDCOMB'
					AND TRIM(CONTA) <> ''
			) A4 ON TRIM(A1.CCONTAB_FINAL_IDCOMB)=TRIM(A4.CONTA) AND A1.COD_PLANO = 'BST_IDCOMB'
			
			LEFT JOIN 
			(
				SELECT DISTINCT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,ZCLIENTE,DDVENCIM AS DATA_VENCIMENTO
				FROM CD_CAPTOOLS.CT004_UNIV_CTO
				WHERE REF_DATE = '${REF_DATE}'
			) A5 ON A1.CEMPRESA=A5.CEMPRESA
					AND A1.CBALCAO=A5.CBALCAO
					AND A1.CNUMECTA=A5.CNUMECTA
					AND A1.ZDEPOSIT=A5.ZDEPOSIT
			
			LEFT JOIN 
			(
				SELECT DISTINCT ZCLIENTE,CPAIS_RESIDENCIA
				FROM CD_CAPTOOLS.CT003_UNIV_CLI
				WHERE REF_DATE = '${REF_DATE}'
			) A6 ON A5.ZCLIENTE=A6.ZCLIENTE
	) IMP
	
    GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,16
) UNIVERSO

LEFT JOIN (SELECT * FROM BUSINESS_ESG.MODESG_OUT_EMPR_INFO_NFIN WHERE REF_DATE='${REF_DATE}') NFIN
ON UNIVERSO.ZCLIENTE = NFIN.ZCLIENTE 

LEFT JOIN (SELECT * FROM BUSINESS_ESG.MODESG_OUT_SFICS_TAXON_EUROPEIA WHERE REF_DATE='${REF_DATE}') SFICS
ON  UNIVERSO.CEMPRESA = SFICS.CEMPRESA AND
    UNIVERSO.CBALCAO  = SFICS.CBALCAO AND
    UNIVERSO.CNUMECTA = SFICS.CNUMECTA AND
    UNIVERSO.ZDEPOSIT = SFICS.ZDEPOSIT

GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 16, 17, 18, 20, 21, 22, 23, 24
;