
/*===================================================================================================================================================
                                                      
											     SIMULAÇÃO EMISSÕES FINANCIADAS MODELO VERDE
										                    NEYOND 2024 - V.F.
															    
 ===================================================================================================================================================*/
 
--------------------------------------------------------------------------------------------------------------------------------------------------
-- 1A. Criação da tabela auxiliar com métricas de saldos para o cálculo - VERSÃO IT 
--------------------------------------------------------------------------------------------------------------------------------------------------

	-- DEZ24: Inserted 6317957 row(s) 

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.EMI_FINAN_AUX1_IT;
CREATE TABLE BU_CAPTOOLS_WORK.EMI_FINAN_AUX1_IT AS

SELECT *
FROM 

	-- 1º CRUZAMENTO: OBTER O UNIVERSO BASE 
	--> DEZ24 6.287.849 REGISTOS         
    (
	SELECT DISTINCT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) AS CHAVE,ZCLIENTE
	FROM CD_CAPTOOLS.ct004_univ_cto
	WHERE REF_DATE='${ref_date}'
	)BASE
	
LEFT JOIN 

	-- 2º CRUZAMENTO: OBTER TODAS AS RELAÇÕES DE BENS COLATERIZADOS DO CONTRATO (IMO + MOV)
	--> DEZ24 6.298.234 REGISTOS | € XXX XXX
	(
	SELECT *
	FROM 
		(
		SELECT *
			,ROW_NUMBER() OVER (PARTITION BY CONCAT(CHAVE_CTO,CHAVE_BEM) ORDER BY FLAG_ORDEM ASC) AS ROW_BENS
		FROM 
			(
				SELECT DISTINCT S1.CHAVE_CTO,S2.CHAVE_BEM,'MUG_IMO' AS FLAG_BEM, 1 AS FLAG_ORDEM
				FROM 
					(
					SELECT CONCAT(CEMPRESP,CKBALRES,CKCTARES,CKREFRESP) AS CHAVE_CTO
						,CONCAT(CEMPRESA,CKBALCAO,CKNUMCTA,COMP_ID_GAR) AS CHAVE_PRO
					FROM CD_GARANTIAS.GT001_TRZ_RSP_GT
					WHERE REF_DATE='${ref_date}'
					)S1
				INNER JOIN  
					(
					SELECT CONCAT(CEMPRESA,CKBALCAO,CKNUMCTA,COMP_ID_GAR) AS CHAVE_PRO,
						CONCAT(CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) AS CHAVE_BEM
					FROM CD_GARANTIAS.GT008_TRZ_GT_IMV
					WHERE REF_DATE='${ref_date}'
					)S2 ON S1.CHAVE_PRO=S2.CHAVE_PRO
			UNION ALL 
				SELECT DISTINCT S1.CHAVE_CTO,S2.CHAVE_BEM,'MBI_IMO' AS FLAG_BEM,2 AS FLAG_ORDEM
				FROM 
					(
					SELECT CONCAT(BANK_ID,BRANCH_CODE,CONTRACT_ID,REFERENCE_CODE) AS CHAVE_CTO
						,CONCAT(PROCESS_BANK_ID,PROCESS_BRANCH_CODE,PROCESS_ACCOUNT_ID,PROCESS_REFERENCE_CODE) AS CHAVE_PRO
					FROM BU_ESG_WORK.RESPONSIBILITY_PROCESS_REL
					WHERE DATA_DATE_PART='${ref_date}'
					)S1
				INNER JOIN 
					(
					SELECT CONCAT(PROCESS_BANK_ID,PROCESS_BRANCH_CODE,PROCESS_ACCOUNT_ID,PROCESS_REFERENCE_CODE) AS CHAVE_PRO
						,CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM 
					FROM BU_ESG_WORK.PROCESS_PROPERTY_REL
					WHERE DATA_DATE_PART='${ref_date}'
						AND COLLATERAL_PROPERTY_IND=1
					)S2 ON S1.CHAVE_PRO=S2.CHAVE_PRO
			UNION ALL 
				SELECT DISTINCT S1.CHAVE_CTO,S2.CHAVE_BEM,'MUG_MOV' AS FLAG_BEM,3 AS FLAG_ORDEM
				FROM 
					(
					SELECT CONCAT(CEMPRESP,CKBALRES,CKCTARES,CKREFRESP) AS CHAVE_CTO
						,CONCAT(CEMPRESA,CKBALCAO,CKNUMCTA,COMP_ID_GAR) AS CHAVE_PRO
					FROM CD_GARANTIAS.GT001_TRZ_RSP_GT
					WHERE REF_DATE='${ref_date}'
					)S1
				INNER JOIN  
					(
					SELECT CONCAT(CEMPRESA,CKBALCAO,CKNUMCTA,COMP_ID_GAR) AS CHAVE_PRO,
						CONCAT(CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) AS CHAVE_BEM
					FROM CD_GARANTIAS.GT012_TRZ_GT_MOB
					WHERE REF_DATE='${ref_date}'
					)S2 ON S1.CHAVE_PRO=S2.CHAVE_PRO
			)AUX_BENS
		)BENS WHERE ROW_BENS=1
	)BENS ON BASE.CHAVE=BENS.CHAVE_CTO 

LEFT JOIN 

	-- 3º CRUZAMENTO: OBTER O SALDO DE CADA CONTRATO 
	--> DEZ24 6.317.957 REGISTOS | € XXX XXX
	(
	SELECT *
	FROM 
		(
		SELECT CHAVE_SALDO,FLAG_PERIMETRO,SUM(SUM_MSALDO_FINAL_AUX) AS SUM_MSALDO_FINAL_CT
		FROM 
			(
			SELECT *
				,CASE 
					WHEN F2.CONTA_1 IS NOT NULL AND F3.CONTA_2 IS NOT NULL THEN 'Local;Corporativo'
					WHEN F2.CONTA_1 IS NOT NULL AND F3.CONTA_2 IS NULL THEN 'Local'
					WHEN F2.CONTA_1 IS NULL AND F3.CONTA_2 IS NOT NULL THEN 'Corporativo'
					WHEN F2.CONTA_1 IS NULL AND F3.CONTA_2 IS NULL THEN 'Fora Perimetro'
				END AS FLAG_PERIMETRO 
			
			FROM 
				(
				SELECT CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) AS CHAVE_SALDO
					,CCONTAB_FINAL_ST_SGPS
					,CCONTAB_FINAL_CARGABAL
					,SUM(MSALDO_FINAL) AS SUM_MSALDO_FINAL_AUX
				FROM CD_CAPTOOLS.CT001_UNIV_SALDO
				WHERE REF_DATE = '${ref_date}'
					AND FLAG_ATIVO=1
				GROUP BY 1,2,3
				)F1
			LEFT JOIN 
				(
				SELECT DISTINCT TRIM(CONTA) AS CONTA_1
				FROM CD_CAPTOOLS.FR802_PL_CONTAS
				WHERE REF_DATE = '${ref_date}'
					AND DETALHE_CONTA = 'I'
					AND TIPO_CONTA = 'A'
					AND COD_PLANO = 'ST_SGPS_CONS' 
					AND TRIM(CONTA) <> ''
					AND TRIM(UPPER(BRUTO_IMPARIDADE)) <> 'IMPARIDADE'
					AND TRIM(CARTEIRA_CONTABILISTICA) NOT IN ('outros ativos - resto')
				)F2 ON F1.CCONTAB_FINAL_ST_SGPS=F2.CONTA_1
			LEFT JOIN 
				(
				SELECT DISTINCT TRIM(CONTA) AS CONTA_2
				FROM CD_CAPTOOLS.FR802_PL_CONTAS
				WHERE REF_DATE = '${ref_date}'
					AND DETALHE_CONTA = 'I'
					AND TIPO_CONTA = 'A'
					AND COD_PLANO = 'CARGABAL' 
					AND TRIM(CONTA) <> ''
					AND TRIM(UPPER(BRUTO_IMPARIDADE)) <> 'IMPARIDADE'
					AND TRIM(CARTEIRA_CONTABILISTICA) NOT IN ('outros ativos - resto')
				)F3 ON F1.CCONTAB_FINAL_CARGABAL=F3.CONTA_2
			)AUX_1 GROUP BY 1,2
		)AUX_2 WHERE FLAG_PERIMETRO<>'Fora Perimetro'
	)UNIV_CT ON BASE.CHAVE=UNIV_CT.CHAVE_SALDO

LEFT JOIN 

	-- 4º CRUZAMENTO: OBTER O VALOR DE CADA COLATERAL NO  CONTRATO 
	--> DEZ24 6.317.957 REGISTOS | € XXX XXX
	(
	SELECT  CONCAT(CEMPRESP,CKBALRES,CKCTARES,CKREFRESP) AS CTO_GT018,CONCAT(CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) AS BEM_GT018, SUM(mavaliaa) AS SUM_mavaliaa
	FROM CD_GARANTIAS.GT018_RATEIO_aval
	WHERE REF_DATE='${ref_date}'
	GROUP BY 1,2
	)GT018 ON BENS.CHAVE_CTO=GT018.CTO_GT018 AND BENS.CHAVE_BEM=GT018.BEM_GT018
;


--------------------------------------------------------------------------------------------------------------------------------------------------
-- 1B. Criação da tabela auxiliar com métricas de saldos para o cálculo - VERSÃO LOCAL 
--------------------------------------------------------------------------------------------------------------------------------------------------

	-- DEZ24: Inserted 6317957   row(s) 

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.EMI_FINAN_AUX1_LOCAL;
CREATE TABLE BU_CAPTOOLS_WORK.EMI_FINAN_AUX1_LOCAL AS

SELECT *
FROM 

	-- 1º CRUZAMENTO: OBTER O UNIVERSO BASE 
	--> DEZ24 6.287.849 REGISTOS         
    (
	SELECT DISTINCT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) AS CHAVE,ZCLIENTE
	FROM CD_CAPTOOLS.ct004_univ_cto
	WHERE REF_DATE='${ref_date}'
	)BASE
	
LEFT JOIN 

	-- 2º CRUZAMENTO: OBTER TODAS AS RELAÇÕES DE BENS COLATERIZADOS DO CONTRATO (IMO + MOV)
	--> DEZ24 6.298.234 REGISTOS | € XXX XXX
	(
	SELECT *
	FROM 
		(
		SELECT *
			,ROW_NUMBER() OVER (PARTITION BY CONCAT(CHAVE_CTO,CHAVE_BEM) ORDER BY FLAG_ORDEM ASC) AS ROW_BENS
		FROM 
			(
				SELECT DISTINCT S1.CHAVE_CTO,S2.CHAVE_BEM,'MUG_IMO' AS FLAG_BEM, 1 AS FLAG_ORDEM
				FROM 
					(
					SELECT CONCAT(CEMPRESP,CKBALRES,CKCTARES,CKREFRESP) AS CHAVE_CTO
						,CONCAT(CEMPRESA,CKBALCAO,CKNUMCTA,COMP_ID_GAR) AS CHAVE_PRO
					FROM CD_GARANTIAS.GT001_TRZ_RSP_GT
					WHERE REF_DATE='${ref_date}'
					)S1
				INNER JOIN  
					(
					SELECT CONCAT(CEMPRESA,CKBALCAO,CKNUMCTA,COMP_ID_GAR) AS CHAVE_PRO,
						CONCAT(CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) AS CHAVE_BEM
					FROM CD_GARANTIAS.GT008_TRZ_GT_IMV
					WHERE REF_DATE='${ref_date}'
					)S2 ON S1.CHAVE_PRO=S2.CHAVE_PRO
			UNION ALL 
				SELECT DISTINCT S1.CHAVE_CTO,S2.CHAVE_BEM,'MBI_IMO' AS FLAG_BEM,2 AS FLAG_ORDEM
				FROM 
					(
					SELECT CONCAT(BANK_ID,BRANCH_CODE,CONTRACT_ID,REFERENCE_CODE) AS CHAVE_CTO
						,CONCAT(PROCESS_BANK_ID,PROCESS_BRANCH_CODE,PROCESS_ACCOUNT_ID,PROCESS_REFERENCE_CODE) AS CHAVE_PRO
					FROM BU_ESG_WORK.RESPONSIBILITY_PROCESS_REL
					WHERE DATA_DATE_PART='${ref_date}'
					)S1
				INNER JOIN 
					(
					SELECT CONCAT(PROCESS_BANK_ID,PROCESS_BRANCH_CODE,PROCESS_ACCOUNT_ID,PROCESS_REFERENCE_CODE) AS CHAVE_PRO
						,CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM 
					FROM BU_ESG_WORK.PROCESS_PROPERTY_REL
					WHERE DATA_DATE_PART='${ref_date}'
						AND COLLATERAL_PROPERTY_IND=1
					)S2 ON S1.CHAVE_PRO=S2.CHAVE_PRO
			UNION ALL 
				SELECT DISTINCT S1.CHAVE_CTO,S2.CHAVE_BEM,'MUG_MOV' AS FLAG_BEM,3 AS FLAG_ORDEM
				FROM 
					(
					SELECT CONCAT(CEMPRESP,CKBALRES,CKCTARES,CKREFRESP) AS CHAVE_CTO
						,CONCAT(CEMPRESA,CKBALCAO,CKNUMCTA,COMP_ID_GAR) AS CHAVE_PRO
					FROM CD_GARANTIAS.GT001_TRZ_RSP_GT
					WHERE REF_DATE='${ref_date}'
					)S1
				INNER JOIN  
					(
					SELECT CONCAT(CEMPRESA,CKBALCAO,CKNUMCTA,COMP_ID_GAR) AS CHAVE_PRO,
						CONCAT(CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) AS CHAVE_BEM
					FROM CD_GARANTIAS.GT012_TRZ_GT_MOB
					WHERE REF_DATE='${ref_date}'
					)S2 ON S1.CHAVE_PRO=S2.CHAVE_PRO
			)AUX_BENS
		)BENS WHERE ROW_BENS=1
	)BENS ON BASE.CHAVE=BENS.CHAVE_CTO 

LEFT JOIN 

	-- 3º CRUZAMENTO: OBTER O SALDO DE CADA CONTRATO 
	--> DEZ24 6.317.957 REGISTOS | € XXX XXX

	(
	SELECT CHAVE_SALDO,SUM(SUM_MSALDO_FINAL) AS SUM_MSALDO_FINAL_CT
	FROM 
		(
			SELECT CHAVE_SALDO,'ST_SGPS_CONS' AS FLAG_SALDO,SUM(SUM_MSALDO_FINAL_AUX) AS SUM_MSALDO_FINAL
			FROM
				(
				SELECT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) AS CHAVE_SALDO
					,CASE 
						WHEN TRIM(CCONTAB_FINAL_ST_SGPS)<>'' THEN TRIM(CCONTAB_FINAL_ST_SGPS)
						ELSE TRIM(CCONTAB_FINAL_IFRS)
					END AS CONTA_CT001
					,CASE 
						WHEN TRIM(CCONTAB_FINAL_ST_SGPS)<>'' THEN 1
						ELSE 2
					END AS FLAG_CONTA
					,SUM(MSALDO_FINAL) AS SUM_MSALDO_FINAL_AUX
				FROM CD_CAPTOOLS.CT001_UNIV_SALDO
				WHERE REF_DATE = '${ref_date}'
					AND FLAG_ATIVO=1
				GROUP BY 1,2,3,4,5,6,7
				)F1
			INNER JOIN
				( 
				SELECT DISTINCT *
				FROM CD_CAPTOOLS.FR802_PL_CONTAS
				WHERE REF_DATE = '${ref_date}'
					AND DETALHE_CONTA = 'I'
					AND TIPO_CONTA = 'A'
					AND COD_PLANO = 'ST_SGPS_CONS' --CARGBAAL
					AND TRIM(CONTA) <> ''
					AND TRIM(UPPER(BRUTO_IMPARIDADE)) <> 'IMPARIDADE'
					AND TRIM(CARTEIRA_CONTABILISTICA) NOT IN ('outros ativos - resto')
				)F2 ON F1.CONTA_CT001= F2.CONTA AND F1.FLAG_CONTA=1 GROUP BY 1,2
--		UNION ALL 
--			SELECT CHAVE_SALDO,'BST_IND' AS FLAG_SALDO,SUM(SUM_MSALDO_FINAL_AUX) AS SUM_MSALDO_FINAL
--			FROM
--				(
--				SELECT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) AS CHAVE_SALDO
--					,CASE 
--						WHEN TRIM(CCONTAB_FINAL_ST_SGPS)<>'' THEN TRIM(CCONTAB_FINAL_ST_SGPS)
--						ELSE TRIM(CCONTAB_FINAL_IFRS)
--					END AS CONTA_CT001
--					,CASE 
--						WHEN TRIM(CCONTAB_FINAL_ST_SGPS)<>'' THEN 1
--						ELSE 2
--					END AS FLAG_CONTA
--					,SUM(MSALDO_FINAL) AS SUM_MSALDO_FINAL_AUX
--				FROM CD_CAPTOOLS.CT001_UNIV_SALDO
--				WHERE REF_DATE = '${ref_date}'
--					AND FLAG_ATIVO=1
--				GROUP BY 1,2,3,4,5,6,7
--				)F1
--			INNER JOIN
--				( 
--				SELECT DISTINCT *
--				FROM CD_CAPTOOLS.FR802_PL_CONTAS
--				WHERE REF_DATE = '${ref_date}'
--					AND DETALHE_CONTA = 'I'
--					AND TIPO_CONTA = 'A'
--					AND COD_PLANO = 'BST_IND'
--					AND TRIM(CONTA) <> ''
--					AND TRIM(UPPER(BRUTO_IMPARIDADE)) <> 'IMPARIDADE'
--					AND TRIM(CARTEIRA_CONTABILISTICA) NOT IN ('outros ativos - resto')
--				)F2 ON F1.CONTA_CT001= F2.CONTA AND F1.FLAG_CONTA=2 GROUP BY 1,2
		)AUX GROUP BY 1
	)UNIV_CT ON BASE.CHAVE=UNIV_CT.CHAVE_SALDO

LEFT JOIN 

	-- 4º CRUZAMENTO: OBTER O VALOR DE CADA COLATERAL NO  CONTRATO 
	--> DEZ24 6.317.957 REGISTOS | € XXX XXX
	(
	SELECT  CONCAT(CEMPRESP,CKBALRES,CKCTARES,CKREFRESP) AS CTO_GT018,CONCAT(CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) AS BEM_GT018, SUM(mavaliaa) AS SUM_mavaliaa
	FROM CD_GARANTIAS.GT018_RATEIO_aval
	WHERE REF_DATE='${ref_date}'
	GROUP BY 1,2
	)GT018 ON BENS.CHAVE_CTO=GT018.CTO_GT018 AND BENS.CHAVE_BEM=GT018.BEM_GT018
;

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 1B. Criação da tabela auxiliar com métricas de saldos para o cálculo - VERSÃO CORPORATIVA  
--------------------------------------------------------------------------------------------------------------------------------------------------

	-- DEZ24: Inserted 6317957  row(s) 

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.EMI_FINAN_AUX1_CORP;
CREATE TABLE BU_CAPTOOLS_WORK.EMI_FINAN_AUX1_CORP AS

SELECT *
FROM 

	-- 1º CRUZAMENTO: OBTER O UNIVERSO BASE 
	--> DEZ24 6.287.849 REGISTOS         
    (
	SELECT DISTINCT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) AS CHAVE,ZCLIENTE
	FROM CD_CAPTOOLS.ct004_univ_cto
	WHERE REF_DATE='${ref_date}'
	)BASE
	
LEFT JOIN 

	-- 2º CRUZAMENTO: OBTER TODAS AS RELAÇÕES DE BENS COLATERIZADOS DO CONTRATO (IMO + MOV)
	--> DEZ24 6.298.234 REGISTOS | € XXX XXX
	(
	SELECT *
	FROM 
		(
		SELECT *
			,ROW_NUMBER() OVER (PARTITION BY CONCAT(CHAVE_CTO,CHAVE_BEM) ORDER BY FLAG_ORDEM ASC) AS ROW_BENS
		FROM 
			(
				SELECT DISTINCT S1.CHAVE_CTO,S2.CHAVE_BEM,'MUG_IMO' AS FLAG_BEM, 1 AS FLAG_ORDEM
				FROM 
					(
					SELECT CONCAT(CEMPRESP,CKBALRES,CKCTARES,CKREFRESP) AS CHAVE_CTO
						,CONCAT(CEMPRESA,CKBALCAO,CKNUMCTA,COMP_ID_GAR) AS CHAVE_PRO
					FROM CD_GARANTIAS.GT001_TRZ_RSP_GT
					WHERE REF_DATE='${ref_date}'
					)S1
				INNER JOIN  
					(
					SELECT CONCAT(CEMPRESA,CKBALCAO,CKNUMCTA,COMP_ID_GAR) AS CHAVE_PRO,
						CONCAT(CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) AS CHAVE_BEM
					FROM CD_GARANTIAS.GT008_TRZ_GT_IMV
					WHERE REF_DATE='${ref_date}'
					)S2 ON S1.CHAVE_PRO=S2.CHAVE_PRO
			UNION ALL 
				SELECT DISTINCT S1.CHAVE_CTO,S2.CHAVE_BEM,'MBI_IMO' AS FLAG_BEM,2 AS FLAG_ORDEM
				FROM 
					(
					SELECT CONCAT(BANK_ID,BRANCH_CODE,CONTRACT_ID,REFERENCE_CODE) AS CHAVE_CTO
						,CONCAT(PROCESS_BANK_ID,PROCESS_BRANCH_CODE,PROCESS_ACCOUNT_ID,PROCESS_REFERENCE_CODE) AS CHAVE_PRO
					FROM BU_ESG_WORK.RESPONSIBILITY_PROCESS_REL
					WHERE DATA_DATE_PART='${ref_date}'
					)S1
				INNER JOIN 
					(
					SELECT CONCAT(PROCESS_BANK_ID,PROCESS_BRANCH_CODE,PROCESS_ACCOUNT_ID,PROCESS_REFERENCE_CODE) AS CHAVE_PRO
						,CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM 
					FROM BU_ESG_WORK.PROCESS_PROPERTY_REL
					WHERE DATA_DATE_PART='${ref_date}'
						AND COLLATERAL_PROPERTY_IND=1
					)S2 ON S1.CHAVE_PRO=S2.CHAVE_PRO
			UNION ALL 
				SELECT DISTINCT S1.CHAVE_CTO,S2.CHAVE_BEM,'MUG_MOV' AS FLAG_BEM,3 AS FLAG_ORDEM
				FROM 
					(
					SELECT CONCAT(CEMPRESP,CKBALRES,CKCTARES,CKREFRESP) AS CHAVE_CTO
						,CONCAT(CEMPRESA,CKBALCAO,CKNUMCTA,COMP_ID_GAR) AS CHAVE_PRO
					FROM CD_GARANTIAS.GT001_TRZ_RSP_GT
					WHERE REF_DATE='${ref_date}'
					)S1
				INNER JOIN  
					(
					SELECT CONCAT(CEMPRESA,CKBALCAO,CKNUMCTA,COMP_ID_GAR) AS CHAVE_PRO,
						CONCAT(CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) AS CHAVE_BEM
					FROM CD_GARANTIAS.GT012_TRZ_GT_MOB
					WHERE REF_DATE='${ref_date}'
					)S2 ON S1.CHAVE_PRO=S2.CHAVE_PRO
			)AUX_BENS
		)BENS WHERE ROW_BENS=1
	)BENS ON BASE.CHAVE=BENS.CHAVE_CTO 

LEFT JOIN 

	-- 3º CRUZAMENTO: OBTER O SALDO DE CADA CONTRATO 
	--> DEZ24 6.317.957 REGISTOS | € XXX XXX

	(
	SELECT CHAVE_SALDO,SUM(SUM_MSALDO_FINAL_AUX) AS SUM_MSALDO_FINAL_CT
	FROM
		(
		SELECT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) AS CHAVE_SALDO,CCONTAB_FINAL_CARGABAL AS CONTA_CT001,SUM(MSALDO_FINAL) AS SUM_MSALDO_FINAL_AUX
		FROM CD_CAPTOOLS.CT001_UNIV_SALDO
		WHERE REF_DATE = '${ref_date}'
			AND FLAG_ATIVO=1
		GROUP BY 1,2,3,4,5,6
		)F1
	INNER JOIN
		( 
		SELECT DISTINCT *
		FROM CD_CAPTOOLS.FR802_PL_CONTAS
		WHERE REF_DATE = '${ref_date}'
			AND DETALHE_CONTA = 'I'
			AND TIPO_CONTA = 'A'
			AND COD_PLANO = 'CARGABAL' 
			AND TRIM(CONTA) <> ''
			AND TRIM(UPPER(BRUTO_IMPARIDADE)) <> 'IMPARIDADE'
			AND TRIM(CARTEIRA_CONTABILISTICA) NOT IN ('outros ativos - resto')
		)F2 ON F1.CONTA_CT001= F2.CONTA  GROUP BY 1
	)UNIV_CT ON BASE.CHAVE=UNIV_CT.CHAVE_SALDO

LEFT JOIN 

	-- 4º CRUZAMENTO: OBTER O VALOR DE CADA COLATERAL NO  CONTRATO 
	--> DEZ24 6.317.957 REGISTOS | € XXX XXX
	(
	SELECT  CONCAT(CEMPRESP,CKBALRES,CKCTARES,CKREFRESP) AS CTO_GT018,CONCAT(CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) AS BEM_GT018, SUM(mavaliaa) AS SUM_mavaliaa
	FROM CD_GARANTIAS.GT018_RATEIO_aval
	WHERE REF_DATE='${ref_date}'
	GROUP BY 1,2
	)GT018 ON BENS.CHAVE_CTO=GT018.CTO_GT018 AND BENS.CHAVE_BEM=GT018.BEM_GT018
;

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 2A. Criação da tabela auxiliar com métricas auxiliares para o cálculo do saldo 
--------------------------------------------------------------------------------------------------------------------------------------------------

	-- DEZ24: Inserted 6317957  row(s) 

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.EMI_FINAN_AUX2;
CREATE TABLE BU_CAPTOOLS_WORK.EMI_FINAN_AUX2 AS

SELECT F1.*
    ,CASE 
        WHEN F2.CHAVE_CTO IS NULL THEN 0
        ELSE F2.N
    END AS NUM_BENS
    ,F3.CTO_MAVALIAA
    ,CASE
        WHEN F2.CHAVE_CTO IS NULL THEN 'SEM_COLATERAL'
		WHEN F1.SUM_MSALDO_FINAL_CT>0 THEN 'REVER'
		WHEN F3.CTO_MAVALIAA>=-F1.SUM_MSALDO_FINAL_CT AND F3.CTO_MAVALIAA IS NOT NULL AND F1.SUM_MSALDO_FINAL_CT IS NOT NULL THEN 'SUM_COLAT_COBRE'
        WHEN F3.CTO_MAVALIAA<-F1.SUM_MSALDO_FINAL_CT AND F3.CTO_MAVALIAA IS NOT NULL AND F1.SUM_MSALDO_FINAL_CT IS NOT NULL THEN 'SUM_COLAT_N_COBRE'
        WHEN F1.SUM_MSALDO_FINAL_CT IS NULL THEN 'SALDO_CT_NULL'
		WHEN F1.SUM_MSALDO_FINAL_CT=0 THEN 'SALDO_CT_ZERO'
        WHEN F3.CTO_MAVALIAA IS NULL THEN 'SALDO_COLAT_NULL'
    END AS FLAG_COBERT
    ,ABS(CAST(F1.SUM_MAVALIAA AS DECIMAL(38,20))/CAST(F3.CTO_MAVALIAA AS DECIMAL(38,20))) AS PESO_COLAT_COBERT
	,ABS(CAST(F1.SUM_MAVALIAA AS DECIMAL(38,20))/CAST(F1.SUM_MSALDO_FINAL_CT AS DECIMAL(38,20))) AS PESO_COLAT_N_COBERT
FROM 
    (
    SELECT * 
    FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX1
    )F1
LEFT JOIN 
    (
    SELECT CHAVE_CTO, COUNT(DISTINCT CHAVE_BEM) AS N
    FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX1
    WHERE CHAVE_BEM IS NOT NULL 
    GROUP BY 1
    )F2 ON F1.CHAVE_CTO=F2.CHAVE_CTO
LEFT JOIN 
    (
    SELECT CHAVE_CTO, SUM(NVL(SUM_MAVALIAA,0)) AS CTO_MAVALIAA
    FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX1
    GROUP BY 1
    )F3 ON F1.CHAVE_CTO=F3.CHAVE_CTO
;
--------------------------------------------------------------------------------------------------------------------------------------------------
-- 2B. Criação da tabela auxiliar com o cálculo do AMOUNT 
--------------------------------------------------------------------------------------------------------------------------------------------------
 
 	-- DEZ24: Inserted 6338663   row(s) 
 
DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.EMI_FINAN_AUX3;
CREATE TABLE BU_CAPTOOLS_WORK.EMI_FINAN_AUX3 AS

SELECT UNI.*
    ,CASE 
        WHEN FLAG_COBERT='SUM_COLAT_COBRE' THEN PESO_COLAT_COBERT*SUM_MSALDO_FINAL_CT 
        WHEN FLAG_COBERT='SUM_COLAT_N_COBRE' THEN PESO_COLAT_N_COBERT*SUM_MSALDO_FINAL_CT 
        ELSE SUM_MSALDO_FINAL_CT
    END AS AMOUNT
	,F2.*
	,CAST(F2.VCPIM AS DECIMAL(38,20)) AS CLIENT_OWN_FUNDS
	,(CAST(F2.VPNICSFIN AS DECIMAL(38,20)) + CAST(F2.VPNPASLF AS DECIMAL(38,20)) + CAST(F2.VPNOPFIN AS DECIMAL(38,20)) + CAST(F2.VPCICSFIN AS DECIMAL(38,20))+ CAST(F2.VPCOPFIN AS DECIMAL(38,20))+ CAST(F2.VPCPASLF AS DECIMAL(38,20))) AS CLIENT_DEBT
FROM 
    (
        SELECT *,'LINHA INI' AS FLAG_LINHAS FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX2
    UNION ALL 
        SELECT DISTINCT
            F1.CEMPRESA
            ,F1.CBALCAO
            ,F1.CNUMECTA
            ,F1.ZDEPOSIT
            ,F1.CHAVE
            ,F1.ZCLIENTE
			,F1.CHAVE_CTO
            ,NULL AS CHAVE_BEM
            ,NULL AS FLAG_BEM
            ,NULL AS FLAG_ORDEM
            ,NULL AS ROW_BENS
            ,NULL AS CHAVE_SALDO
            ,F1.SUM_MSALDO_FINAL_CT
            ,NULL AS CTO_GT018
            ,NULL AS BEM_GT018
            ,NULL AS SUM_MAVALIAA
            ,NULL AS NUM_BENS
            ,F1.CTO_MAVALIAA
            ,F1.FLAG_COBERT
            ,NULL PESO_COLAT_COBERT
            ,CAST(1-F2.PESO_REMN AS DECIMAL(38,20)) AS PESO_COLAT_N_COBERT
            ,'LINHA ADI' AS FLAG_LINHAS 
        FROM 
            (
            SELECT *
            FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX2
            WHERE FLAG_COBERT='SUM_COLAT_N_COBRE'
            )F1
        LEFT JOIN 
            (
            SELECT CHAVE,SUM(NVL(PESO_COLAT_N_COBERT,0)) AS PESO_REMN
            FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX2
            WHERE FLAG_COBERT='SUM_COLAT_N_COBRE'
            GROUP BY 1
            )F2 ON F1.CHAVE=F2.CHAVE
	)UNI
LEFT JOIN 
	(
	SELECT ZCLIENTE,CCLI_GRUPO
	FROM CD_CAPTOOLS.CT003_UNIV_CLI
	WHERE REF_DATE = "${ref_date}"
	)F1 ON UNI.ZCLIENTE=F1.ZCLIENTE
LEFT JOIN 
	(
	SELECT *
	FROM 
		(
		SELECT ROW_NUMBER() OVER (PARTITION BY BL.CCLIGRUPO ORDER BY BL.CGESTOR DESC, `TIMESTAMP` DESC) AS ROW_ORDEM_1,BL.*
		FROM 
			(
			SELECT CCLIGRUPO,
				DANO,
				CGESTOR,
				`TIMESTAMP`,
				DFIM,
				CPERIODO,
				ITIP_INF,
				DATA_DATE_PART
				,VCPIM 
				,VPNICSFIN 
				,VPNPASLF 
				,VPNOPFIN 
				,VPCICSFIN
				,VPCOPFIN 
				,VPCPASLF 
			FROM CD_RISCOS.RSV176SA1_BALANCO
			WHERE DATA_DATE_PART <= "${ref_date}"
			)BL
		INNER JOIN 
			(
			SELECT *
			FROM 	
				(
				SELECT ROW_NUMBER() OVER (PARTITION BY CCLIGRUPO ORDER BY DANO DESC, CGESTOR DESC, DFIM DESC) AS ROW_ORDEM_2
					,CCLIGRUPO
					,DANO
					,CGESTOR
					,DFIM
					,ITIP_INF
					,CPERIODO
				FROM 
					(
					SELECT BL1.*
					FROM 
						(
						SELECT 
							CCLIGRUPO
							,DANO
							,CGESTOR
							,DFIM
							,CPERIODO
							,ITIP_INF
						FROM CD_RISCOS.RSV176SA1_BALANCO
						WHERE DATA_DATE_PART <= '${ref_date}'
							AND CPERIODO = '212'
							AND ITIP_INF = 'I'
						)BL1
					INNER JOIN 
						(
						SELECT CCLI_GRUPO,DCONSTITUICAO
						FROM CD_CAPTOOLS.CT003_UNIV_CLI
						WHERE REF_DATE = "${ref_date}"
						)CLI ON CCLI_GRUPO = CCLIGRUPO
					WHERE DANO <= SUBSTR("${ref_date}",1,4) AND DANO >= SUBSTR(DCONSTITUICAO,1,4)
					)AUX_1
				)AUX_2 WHERE ROW_ORDEM_2=1
			)FS ON (FS.CCLIGRUPO = BL.CCLIGRUPO AND FS.DANO = BL.DANO AND FS.CPERIODO = BL.CPERIODO AND FS.ITIP_INF = BL.ITIP_INF)
		)AUX_3 WHERE ROW_ORDEM_1=1
	)F2 ON F1.CCLI_GRUPO=F2.CCLIGRUPO
;

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 3A. Criação da tabela final - Versão IT (apenas para testes contra a tabela de IT)
--------------------------------------------------------------------------------------------------------------------------------------------------
 
  	-- DEZ24: Inserted 6338663   row(s) 
 
DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.EMI_FINAN;
CREATE TABLE BU_CAPTOOLS_WORK.EMI_FINAN AS

SELECT UNI.*
	,CASE 
		WHEN L2.ORIGEM_SCP1_EMSS IN ('MVL_DQS3_2B','MVL_DQS4_3A','MVL_DQS4_3B') THEN CAST(L2.SCP1_EMSS AS DECIMAL(38,6))*(CAST(UNI.AMOUNT AS DECIMAL(38,6))/CAST(L5.PRECO_AQUISICAO AS DECIMAL(38,6)))	
		WHEN L3.ORIGEM_SCP1_EMSS IN ('RE_DQS3_2A','RE_DQS4_2B','RE_DQS5_3') THEN CAST(L3.SCP1_EMSS AS DECIMAL(38,6))*(CAST(UNI.AMOUNT AS DECIMAL(38,6))/CAST(L5.PRECO_AQUISICAO AS DECIMAL(38,6)))	
		WHEN L1.ORIGEM_SCP1_EMSS IN ('BCL_DQS1_SCIB','BCL_DQS2_SCIB','BCL_DQS3_SCIB','BCL_DQS4_SCIB','PF_DQS1_SCIB','PF_DQS2_SCIB','PF_DQS3_SCIB','PF_DQS4_SCIB') THEN CAST(L1.SCP1_EMSS AS DECIMAL(38,6))*(CAST(UNI.AMOUNT AS DECIMAL(38,6))/(L1.DIVIDA_TOTAL+L1.CAPITAL_PROPRIO))
		WHEN L1.ORIGEM_SCP1_EMSS IN ('BCL_DQS4_3A') THEN CAST(L1.SCP1_EMSS AS DECIMAL(38,6))*(CAST(UNI.AMOUNT AS DECIMAL(38,6))/(CAST(UNI.CLIENT_OWN_FUNDS AS DECIMAL(38,6))+CAST(UNI.CLIENT_DEBT AS DECIMAL(38,6))))
		WHEN L1.ORIGEM_SCP1_EMSS IN ('BCL_DQS5_3B','PF_DQS5_3B') THEN CAST(L1.SCP1_EMSS AS DECIMAL(38,6))
	END AS SCP1_EMSS_FNCD
	,CASE 
		WHEN L2.ORIGEM_SCP2_EMSS IN ('MVL_DQS3_2B','MVL_DQS4_3A','MVL_DQS4_3B') THEN CAST(L2.SCP2_EMSS AS DECIMAL(38,6))*(CAST(UNI.AMOUNT AS DECIMAL(38,6))/CAST(L5.PRECO_AQUISICAO AS DECIMAL(38,6)))	
		WHEN L3.ORIGEM_SCP2_EMSS IN ('RE_DQS3_2A','RE_DQS4_2B','RE_DQS5_3') THEN CAST(L3.SCP2_EMSS AS DECIMAL(38,6))*(CAST(UNI.AMOUNT AS DECIMAL(38,6))/CAST(L5.PRECO_AQUISICAO AS DECIMAL(38,6)))	
		WHEN L1.ORIGEM_SCP2_EMSS IN ('BCL_DQS1_SCIB','BCL_DQS2_SCIB','BCL_DQS3_SCIB','BCL_DQS4_SCIB','PF_DQS1_SCIB','PF_DQS2_SCIB','PF_DQS3_SCIB','PF_DQS4_SCIB') THEN CAST(L1.SCP2_EMSS AS DECIMAL(38,6))*(CAST(UNI.AMOUNT AS DECIMAL(38,6))/(L1.DIVIDA_TOTAL+L1.CAPITAL_PROPRIO))
		WHEN L1.ORIGEM_SCP2_EMSS IN ('BCL_DQS4_3A') THEN CAST(L1.SCP1_EMSS AS DECIMAL(38,6))*(CAST(UNI.AMOUNT AS DECIMAL(38,6))/(CAST(UNI.CLIENT_OWN_FUNDS AS DECIMAL(38,6))+CAST(UNI.CLIENT_DEBT AS DECIMAL(38,6))))
		WHEN L1.ORIGEM_SCP2_EMSS IN ('BCL_DQS5_3B','PF_DQS5_3B') THEN CAST(L1.SCP1_EMSS AS DECIMAL(38,6))
	END AS SCP2_EMSS_FNCD
	,CASE 
		WHEN L2.ORIGEM_SCP3_EMSS IN ('MVL_DQS3_2B','MVL_DQS4_3A','MVL_DQS4_3B') THEN CAST(L2.SCP3_EMSS AS DECIMAL(38,6))*(CAST(UNI.AMOUNT AS DECIMAL(38,6))/CAST(L5.PRECO_AQUISICAO AS DECIMAL(38,6)))	
		WHEN L3.ORIGEM_SCP3_EMSS IN ('RE_DQS3_2A','RE_DQS4_2B','RE_DQS5_3') THEN CAST(L3.SCP3_EMSS AS DECIMAL(38,6))*(CAST(UNI.AMOUNT AS DECIMAL(38,6))/CAST(L5.PRECO_AQUISICAO AS DECIMAL(38,6)))	
		WHEN L1.ORIGEM_SCP3_EMSS IN ('BCL_DQS1_SCIB','BCL_DQS2_SCIB','BCL_DQS3_SCIB','BCL_DQS4_SCIB','PF_DQS1_SCIB','PF_DQS2_SCIB','PF_DQS3_SCIB','PF_DQS4_SCIB') THEN CAST(L1.SCP3_EMSS AS DECIMAL(38,6))*(CAST(UNI.AMOUNT AS DECIMAL(38,6))/(L1.DIVIDA_TOTAL+L1.CAPITAL_PROPRIO))
		WHEN L1.ORIGEM_SCP3_EMSS IN ('BCL_DQS4_3A') THEN CAST(L1.SCP3_EMSS AS DECIMAL(38,6))*(CAST(UNI.AMOUNT AS DECIMAL(38,6))/(CAST(UNI.CLIENT_OWN_FUNDS AS DECIMAL(38,6))+CAST(UNI.CLIENT_DEBT AS DECIMAL(38,6))))
		WHEN L1.ORIGEM_SCP3_EMSS IN ('BCL_DQS5_3B','PF_DQS5_3B') THEN CAST(L1.SCP3_EMSS AS DECIMAL(38,6))
	END AS SCP3_EMSS_FNCD
	,CASE 
		WHEN L2.ORIGEM_SCP1_EMSS IS NOT NULL THEN L2.ORIGEM_SCP1_EMSS
		WHEN L3.ORIGEM_SCP1_EMSS IS NOT NULL THEN L3.ORIGEM_SCP1_EMSS
		WHEN L1.ORIGEM_SCP1_EMSS IS NOT NULL THEN L1.ORIGEM_SCP1_EMSS
	END AS ORIGEM_SCP1_EMSS
	,CASE 
		WHEN L2.ORIGEM_SCP2_EMSS IS NOT NULL THEN L2.ORIGEM_SCP2_EMSS
		WHEN L3.ORIGEM_SCP2_EMSS IS NOT NULL THEN L3.ORIGEM_SCP2_EMSS
		WHEN L1.ORIGEM_SCP2_EMSS IS NOT NULL THEN L1.ORIGEM_SCP2_EMSS
	END AS ORIGEM_SCP2_EMSS
	,CASE 
		WHEN L2.ORIGEM_SCP3_EMSS IS NOT NULL THEN L2.ORIGEM_SCP3_EMSS
		WHEN L3.ORIGEM_SCP3_EMSS IS NOT NULL THEN L3.ORIGEM_SCP3_EMSS
		WHEN L1.ORIGEM_SCP3_EMSS IS NOT NULL THEN L1.ORIGEM_SCP3_EMSS
	END AS ORIGEM_SCP3_EMSS
	,L1.SCP1_EMSS AS SCP1_EMSS_CLI,L1.SCP2_EMSS AS SCP2_EMSS_CLI,L1.SCP3_EMSS AS SCP3_EMSS_CLI
	,L1.ORIGEM_SCP1_EMSS AS ORIGEM_SCP1_EMSS_CLI,L1.ORIGEM_SCP2_EMSS AS ORIGEM_SCP2_EMSS_CLI,L1.ORIGEM_SCP3_EMSS AS ORIGEM_SCP3_EMSS_CLI
	,L1.DIVIDA_TOTAL,L1.CAPITAL_PROPRIO
	,L2.SCP1_EMSS AS SCP1_EMSS_MOB,L2.SCP2_EMSS AS SCP2_EMSS_MOB,L2.SCP3_EMSS AS SCP3_EMSS_MOB
	,L2.ORIGEM_SCP1_EMSS AS ORIGEM_SCP1_EMSS_MOB,L2.ORIGEM_SCP2_EMSS AS ORIGEM_SCP2_EMSS_MOB,L2.ORIGEM_SCP3_EMSS AS ORIGEM_SCP3_EMSS_MOB
	,L3.SCP1_EMSS AS SCP1_EMSS_IMO,L3.SCP2_EMSS AS SCP2_EMSS_IMO,L3.SCP3_EMSS AS SCP3_EMSS_IMO
	,L3.ORIGEM_SCP1_EMSS AS ORIGEM_SCP1_EMSS_IMO,L3.ORIGEM_SCP2_EMSS AS ORIGEM_SCP2_EMSS_IMO,L3.ORIGEM_SCP3_EMSS AS ORIGEM_SCP3_EMSS_IMO
FROM 
    (
	SELECT *
	FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX3
	)UNI
LEFT JOIN 
	(
	SELECT ZCLIENTE,SCP1_EMSS,SCP2_EMSS,SCP3_EMSS,ORIGEM_SCP1_EMSS,ORIGEM_SCP2_EMSS,ORIGEM_SCP3_EMSS,DIVIDA_TOTAL,CAPITAL_PROPRIO
	FROM bu_esg_work.modesg_out_empr_info_nfin
	WHERE ref_date='${ref_date}'
	)L1 ON UNI.ZCLIENTE=L1.ZCLIENTE
LEFT JOIN 
	(
	SELECT CONCAT(CEMPBEM,CKBALBEM,ckctabem,ckrefbem) AS CHAVE_MOB,SCP1_EMSS,SCP2_EMSS,SCP3_EMSS,ORIGEM_SCP1_EMSS,ORIGEM_SCP2_EMSS,ORIGEM_SCP3_EMSS
	FROM BU_ESG_WORK.modesg_out_emss_vcls 
	WHERE ref_date='${ref_date}'
	)L2 ON UNI.CHAVE_BEM=L2.CHAVE_MOB
LEFT JOIN 
	(
	SELECT CONCAT(CEMPBEM,CKBALBEM,ckctabem,ckrefbem) AS CHAVE_IMO,SCP1_EMSS,SCP2_EMSS,SCP3_EMSS,ORIGEM_SCP1_EMSS,ORIGEM_SCP2_EMSS,ORIGEM_SCP3_EMSS
	FROM BU_ESG_WORK.modesg_out_bens_imoveis 
	WHERE ref_date='${ref_date}'
	)L3 ON UNI.CHAVE_BEM=L3.CHAVE_IMO
LEFT JOIN 	
	(
	SELECT DISTINCT CONCAT(CEMPBEM,CKBALBEM,ckctabem,ckrefbem) AS CHAVE_MUG,preco_aquisicao
	FROM cd_garantias.gt018_rateio_aval
	WHERE ref_date='${ref_date}'
		and preco_aquisicao is not null 
	)L5 ON UNI.CHAVE_BEM=L5.CHAVE_MUG	
;

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 3A. Criação da tabela final - Versão Correta (e a considerar)
--------------------------------------------------------------------------------------------------------------------------------------------------
 
  	-- DEZ24: Inserted 6338663   row(s) 
 
DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.EMI_FINAN_AUX4;
CREATE TABLE BU_CAPTOOLS_WORK.EMI_FINAN_AUX4 AS

SELECT UNI.*
	,CASE 
		WHEN L1.ORIGEM_SCP1_EMSS ='Nao Aplicavel' OR L2.ORIGEM_SCP1_EMSS ='Nao Aplicavel' OR L3.ORIGEM_SCP1_EMSS ='Nao Aplicavel'  THEN NULL 
		WHEN L2.ORIGEM_SCP1_EMSS IN ('MVL_DQS3_2B','MVL_DQS4_3A','MVL_DQS4_3B','MVL_DQS5_3B') THEN CAST(L2.SCP1_EMSS AS DECIMAL(38,6))*(CAST(-UNI.AMOUNT AS DECIMAL(38,6))/CAST(L5.PRECO_AQUISICAO AS DECIMAL(38,6)))	
		WHEN L3.ORIGEM_SCP1_EMSS IN ('RE_DQS3_2A','RE_DQS4_2B','RE_DQS5_3') THEN CAST(L3.SCP1_EMSS AS DECIMAL(38,6))*(CAST(-UNI.AMOUNT AS DECIMAL(38,6))/CAST(L5.PRECO_AQUISICAO AS DECIMAL(38,6)))	
		WHEN L1.ORIGEM_SCP1_EMSS IN ('BCL_DQS1_SCIB','BCL_DQS2_SCIB','BCL_DQS3_SCIB','BCL_DQS4_SCIB','PF_DQS1_SCIB','PF_DQS2_SCIB','PF_DQS3_SCIB','PF_DQS4_SCIB') THEN CAST(L1.SCP1_EMSS AS DECIMAL(38,6))*(CAST(-UNI.AMOUNT/1000000 AS DECIMAL(38,6))/(L1.DIVIDA_TOTAL+L1.CAPITAL_PROPRIO))
		WHEN L1.ORIGEM_SCP1_EMSS IN ('BCL_DQS4_3A') THEN CAST(L1.SCP1_EMSS AS DECIMAL(38,6))*(CAST(-UNI.AMOUNT AS DECIMAL(38,6))/(CAST(UNI.CLIENT_OWN_FUNDS AS DECIMAL(38,6))+CAST(UNI.CLIENT_DEBT AS DECIMAL(38,6))))
		WHEN L1.ORIGEM_SCP1_EMSS IN ('BCL_DQS5_3B','PF_DQS5_3B') THEN CAST(L1.SCP1_EMSS AS DECIMAL(38,6)) -- Rever tema de ativo de PF 
		WHEN L1.ORIGEM_SCP1_EMSS IN ('PF_DQS1_1A') THEN CAST(L1.SCP1_EMSS AS DECIMAL(38,6))
	END AS SCP1_EMSS_FNCD_AUX
	,CASE 
		WHEN L1.ORIGEM_SCP2_EMSS ='Nao Aplicavel' OR L2.ORIGEM_SCP2_EMSS ='Nao Aplicavel' OR L3.ORIGEM_SCP2_EMSS ='Nao Aplicavel'  THEN NULL 
		WHEN L2.ORIGEM_SCP2_EMSS IN ('MVL_DQS3_2B','MVL_DQS4_3A','MVL_DQS4_3B','MVL_DQS5_3B') THEN CAST(L2.SCP2_EMSS AS DECIMAL(38,6))*(CAST(-UNI.AMOUNT AS DECIMAL(38,6))/CAST(L5.PRECO_AQUISICAO AS DECIMAL(38,6))) -- Sum do contrato/Sum de todos os preços de aquisição 	
		WHEN L3.ORIGEM_SCP2_EMSS IN ('RE_DQS3_2A','RE_DQS4_2B','RE_DQS5_3') THEN CAST(L3.SCP2_EMSS AS DECIMAL(38,6))*(CAST(-UNI.AMOUNT AS DECIMAL(38,6))/CAST(L5.PRECO_AQUISICAO AS DECIMAL(38,6)))	-- Sum do contrato/Sum de todos os preços de aquisição 
		WHEN L1.ORIGEM_SCP2_EMSS IN ('BCL_DQS1_SCIB','BCL_DQS2_SCIB','BCL_DQS3_SCIB','BCL_DQS4_SCIB','PF_DQS1_SCIB','PF_DQS2_SCIB','PF_DQS3_SCIB','PF_DQS4_SCIB') THEN CAST(L1.SCP2_EMSS AS DECIMAL(38,6))*(CAST(-UNI.AMOUNT/1000000 AS DECIMAL(38,6))/(L1.DIVIDA_TOTAL+L1.CAPITAL_PROPRIO))
		WHEN L1.ORIGEM_SCP2_EMSS IN ('BCL_DQS4_3A') THEN CAST(L1.SCP2_EMSS AS DECIMAL(38,6))*(CAST(-UNI.AMOUNT AS DECIMAL(38,6))/(CAST(UNI.CLIENT_OWN_FUNDS AS DECIMAL(38,6))+CAST(UNI.CLIENT_DEBT AS DECIMAL(38,6))))
		WHEN L1.ORIGEM_SCP2_EMSS IN ('BCL_DQS5_3B','PF_DQS5_3B') THEN CAST(L1.SCP2_EMSS AS DECIMAL(38,6))
		WHEN L1.ORIGEM_SCP2_EMSS IN ('PF_DQS1_1A') THEN CAST(L1.SCP2_EMSS AS DECIMAL(38,6))
	END AS SCP2_EMSS_FNCD_AUX
	,CASE 
		WHEN L1.ORIGEM_SCP3_EMSS ='Nao Aplicavel' OR L2.ORIGEM_SCP3_EMSS ='Nao Aplicavel' OR L3.ORIGEM_SCP3_EMSS ='Nao Aplicavel'  THEN NULL 
		WHEN L2.ORIGEM_SCP3_EMSS IN ('MVL_DQS3_2B','MVL_DQS4_3A','MVL_DQS4_3B','MVL_DQS5_3B') THEN CAST(L2.SCP3_EMSS AS DECIMAL(38,6))*(CAST(-UNI.AMOUNT AS DECIMAL(38,6))/CAST(L5.PRECO_AQUISICAO AS DECIMAL(38,6)))	
		WHEN L3.ORIGEM_SCP3_EMSS IN ('RE_DQS3_2A','RE_DQS4_2B','RE_DQS5_3') THEN CAST(L3.SCP3_EMSS AS DECIMAL(38,6))*(CAST(-UNI.AMOUNT AS DECIMAL(38,6))/CAST(L5.PRECO_AQUISICAO AS DECIMAL(38,6)))	
		WHEN L1.ORIGEM_SCP3_EMSS IN ('BCL_DQS1_SCIB','BCL_DQS2_SCIB','BCL_DQS3_SCIB','BCL_DQS4_SCIB','PF_DQS1_SCIB','PF_DQS2_SCIB','PF_DQS3_SCIB','PF_DQS4_SCIB') THEN CAST(L1.SCP3_EMSS AS DECIMAL(38,6))*(CAST(-UNI.AMOUNT/1000000 AS DECIMAL(38,6))/(L1.DIVIDA_TOTAL+L1.CAPITAL_PROPRIO))
		WHEN L1.ORIGEM_SCP3_EMSS IN ('BCL_DQS4_3A') THEN CAST(L1.SCP3_EMSS AS DECIMAL(38,6))*(CAST(-UNI.AMOUNT AS DECIMAL(38,6))/(CAST(UNI.CLIENT_OWN_FUNDS AS DECIMAL(38,6))+CAST(UNI.CLIENT_DEBT AS DECIMAL(38,6))))
		WHEN L1.ORIGEM_SCP3_EMSS IN ('BCL_DQS5_3B','PF_DQS5_3B') THEN CAST(L1.SCP3_EMSS AS DECIMAL(38,6))
		WHEN L1.ORIGEM_SCP3_EMSS IN ('PF_DQS1_1A') THEN CAST(L1.SCP3_EMSS AS DECIMAL(38,6))
	END AS SCP3_EMSS_FNCD_AUX
	,CASE 
		WHEN L2.ORIGEM_SCP1_EMSS IS NOT NULL THEN L2.ORIGEM_SCP1_EMSS
		WHEN L3.ORIGEM_SCP1_EMSS IS NOT NULL THEN L3.ORIGEM_SCP1_EMSS
		WHEN L1.ORIGEM_SCP1_EMSS IS NOT NULL THEN L1.ORIGEM_SCP1_EMSS
	END AS ORIGEM_SCP1_EMSS
	,CASE 
		WHEN L2.ORIGEM_SCP2_EMSS IS NOT NULL THEN L2.ORIGEM_SCP2_EMSS
		WHEN L3.ORIGEM_SCP2_EMSS IS NOT NULL THEN L3.ORIGEM_SCP2_EMSS
		WHEN L1.ORIGEM_SCP2_EMSS IS NOT NULL THEN L1.ORIGEM_SCP2_EMSS
	END AS ORIGEM_SCP2_EMSS
	,CASE 
		WHEN L2.ORIGEM_SCP3_EMSS IS NOT NULL THEN L2.ORIGEM_SCP3_EMSS
		WHEN L3.ORIGEM_SCP3_EMSS IS NOT NULL THEN L3.ORIGEM_SCP3_EMSS
		WHEN L1.ORIGEM_SCP3_EMSS IS NOT NULL THEN L1.ORIGEM_SCP3_EMSS
	END AS ORIGEM_SCP3_EMSS
	,L1.SCP1_EMSS AS SCP1_EMSS_CLI,L1.SCP2_EMSS AS SCP2_EMSS_CLI,L1.SCP3_EMSS AS SCP3_EMSS_CLI
	,L1.ORIGEM_SCP1_EMSS AS ORIGEM_SCP1_EMSS_CLI,L1.ORIGEM_SCP2_EMSS AS ORIGEM_SCP2_EMSS_CLI,L1.ORIGEM_SCP3_EMSS AS ORIGEM_SCP3_EMSS_CLI
	,L1.DIVIDA_TOTAL,L1.CAPITAL_PROPRIO
	,L2.SCP1_EMSS AS SCP1_EMSS_MOB,L2.SCP2_EMSS AS SCP2_EMSS_MOB,L2.SCP3_EMSS AS SCP3_EMSS_MOB
	,L2.ORIGEM_SCP1_EMSS AS ORIGEM_SCP1_EMSS_MOB,L2.ORIGEM_SCP2_EMSS AS ORIGEM_SCP2_EMSS_MOB,L2.ORIGEM_SCP3_EMSS AS ORIGEM_SCP3_EMSS_MOB
	,L3.SCP1_EMSS AS SCP1_EMSS_IMO,L3.SCP2_EMSS AS SCP2_EMSS_IMO,L3.SCP3_EMSS AS SCP3_EMSS_IMO
	,L3.ORIGEM_SCP1_EMSS AS ORIGEM_SCP1_EMSS_IMO,L3.ORIGEM_SCP2_EMSS AS ORIGEM_SCP2_EMSS_IMO,L3.ORIGEM_SCP3_EMSS AS ORIGEM_SCP3_EMSS_IMO
	,L5.preco_aquisicao
FROM 
    (
	SELECT *
	FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX3
	)UNI
LEFT JOIN 
	(
	SELECT ZCLIENTE,SCP1_EMSS,SCP2_EMSS,SCP3_EMSS,ORIGEM_SCP1_EMSS,ORIGEM_SCP2_EMSS,ORIGEM_SCP3_EMSS,DIVIDA_TOTAL,CAPITAL_PROPRIO
	FROM bu_esg_work.modesg_out_empr_info_nfin
	WHERE ref_date='${ref_date}'
	)L1 ON UNI.ZCLIENTE=L1.ZCLIENTE
LEFT JOIN 
	(
	SELECT CONCAT(CEMPBEM,CKBALBEM,ckctabem,ckrefbem) AS CHAVE_MOB,SCP1_EMSS,SCP2_EMSS,SCP3_EMSS,ORIGEM_SCP1_EMSS,ORIGEM_SCP2_EMSS,ORIGEM_SCP3_EMSS
	FROM BU_ESG_WORK.modesg_out_emss_vcls 
	WHERE ref_date='${ref_date}'
	)L2 ON UNI.CHAVE_BEM=L2.CHAVE_MOB
LEFT JOIN 
	(
	SELECT CONCAT(CEMPBEM,CKBALBEM,ckctabem,ckrefbem) AS CHAVE_IMO,SCP1_EMSS,SCP2_EMSS,SCP3_EMSS,ORIGEM_SCP1_EMSS,ORIGEM_SCP2_EMSS,ORIGEM_SCP3_EMSS
	FROM BU_ESG_WORK.modesg_out_bens_imoveis 
	WHERE ref_date='${ref_date}'
	)L3 ON UNI.CHAVE_BEM=L3.CHAVE_IMO
LEFT JOIN 	
	(
	SELECT DISTINCT CONCAT(CEMPBEM,CKBALBEM,ckctabem,ckrefbem) AS CHAVE_MUG,preco_aquisicao
	FROM cd_garantias.gt018_rateio_aval
	WHERE ref_date='${ref_date}'
		and preco_aquisicao is not null 
	)L5 ON UNI.CHAVE_BEM=L5.CHAVE_MUG	
;
--------------------------------------------------------------------------------------------------------------------------------------------------
-- 3B. Criação da tabela final - Versão Correta (e a considerar)
--------------------------------------------------------------------------------------------------------------------------------------------------
 

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.EMI_FINAN;
CREATE TABLE BU_CAPTOOLS_WORK.EMI_FINAN AS

SELECT *
	,CASE 
		WHEN SCP1_EMSS_FNCD_AUX IS NULL THEN SCP1_EMSS_FNCD_AUX
		WHEN SCP1_EMSS_FNCD_AUX<0 THEN 0
		ELSE SCP1_EMSS_FNCD_AUX
	END AS SCP1_EMSS_FNCD
	,CASE 
		WHEN SCP2_EMSS_FNCD_AUX IS NULL THEN SCP2_EMSS_FNCD_AUX
		WHEN SCP2_EMSS_FNCD_AUX<0 THEN 0
		ELSE SCP2_EMSS_FNCD_AUX
	END AS SCP2_EMSS_FNCD
	,CASE 
		WHEN SCP3_EMSS_FNCD_AUX IS NULL THEN SCP3_EMSS_FNCD_AUX
		WHEN SCP3_EMSS_FNCD_AUX<0 THEN 0
		ELSE SCP3_EMSS_FNCD_AUX
	END AS SCP3_EMSS_FNCD
	
FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX4


	
	
	
	