/********************************************************************************************************************************************
****   Projeto: Implementação Templates Locais                                                                     						 ****
****   Autor: BS & Neyond                                                                                                                ****
****   Data: 23/05/2025                                                                                                                  ****
****   SQL Script Descrição: Geração do Template 2 STE 																					 ****
****  (Banking book - Climate change transition risk: Loans collateralised by immovable property - Energy efficiency of the collateral ) ****
********************************************************************************************************************************************/

/*=========================================================================================================================================*/
/*  1. Tabela granular: Obtenção do universo a reportar no âmbito do Template 2 STE + Marcação de metricas relevantes       			   */
/*=========================================================================================================================================*/ 

-- INSERT OVERWRITE TABLE BU_ESG_WORK.AG02_STE_CTO_GRA PARTITION (ID_CORRIDA,REF_DATE)
SELECT X.*,
	-- PARTICAO
	RT.NEW_ID_CORRIDA AS ID_CORRIDA,
	'${REF_DATE}' AS REF_DATE
FROM
(
	SELECT 
        A.DATA_ABERTURA,
        A.DATA_VENCIMENTO,
        A.CEMPRESA,
        A.CBALCAO,
        A.CNUMECTA,
        A.ZDEPOSIT,
        A.TIPO_COLATERAL,
        A.CCONTAB_FINAL_IDCOMB_TOTAL,
        A.BRUTO_IMPARIDADE, 
        A.FLAG_MESG5,
		B.AMOUNT,
        B.CEMPBEM,
		B.CKBALBEM,			
		B.CKCTABEM,	
		B.CKREFBEM,	
		B.EPC, 
		CASE 
			WHEN B.QUALITY_SCORE IS NULL THEN 'NULO'
			ELSE B.QUALITY_SCORE END AS QUALITY_SCORE,
		B.CONSUMOS,
		CASE
			WHEN D.VALOR_LTV IS NULL THEN 101.000000 -- POR INDICAÇÃO DA CORPORAÇÃO OS NULOS DEVERÃO SER MARCADOS NO BUCKET MAIS ELEVADO 
			WHEN D.VALOR_LTV > 150 THEN 150.000000
			ELSE D.VALOR_LTV
		END AS VALOR_LTV,
		CASE
			WHEN D.VALOR_LTV IS NULL THEN 1.0100000000 -- POR INDICAÇÃO DA CORPORAÇÃO OS NULOS DEVERÃO SER MARCADOS NO BUCKET MAIS ELEVADO 
			WHEN D.VALOR_LTV > 150 THEN 1.5000000000
			ELSE D.VALOR_LTV/100
		END AS VALOR_LTV_DECIMAL,
		CASE
			WHEN TX_JURO_LT = 99999999999.000000 THEN 0.000000 -- POR INDICAÇÃO DA CORPORAÇÃO, OS CONTRATOS QUE NÃO POSSUEM TAXA DE JURO DEVERÃO ASSUMIR TX JURO 0 
			ELSE TX_JURO_LT
		END AS TX_JURO,
		CASE
		WHEN D.VALOR_LTV IS NULL THEN 'LTV5'
			WHEN D.VALOR_LTV <= 40 THEN 'LTV1'
			WHEN D.VALOR_LTV <= 60 THEN 'LTV2'
			WHEN D.VALOR_LTV <= 80 THEN 'LTV3'
			WHEN D.VALOR_LTV < 100 THEN 'LTV4'
			ELSE 'LTV5' 
		END AS COLLATERAL_LTV,
		CASE
			WHEN TRIM(B.EPC) LIKE 'A' THEN 'A'
			WHEN TRIM(B.EPC) LIKE 'A%' THEN 'A+'
			WHEN TRIM(B.EPC) LIKE 'B' THEN 'B'
			WHEN TRIM(B.EPC) LIKE 'B%' THEN 'B-'
			WHEN TRIM(B.EPC) LIKE 'C%' THEN 'C'
			WHEN TRIM(B.EPC) LIKE 'D%' THEN 'D'
			WHEN TRIM(B.EPC) LIKE 'E%' THEN 'E'
			WHEN TRIM(B.EPC) LIKE 'F%' THEN 'F'
			WHEN TRIM(B.EPC) LIKE 'G%' THEN 'G'
			ELSE 'Sem dados'
		END AS EPC_LABEL, 
		CASE 
			WHEN B.CONSUMOS <= 100 THEN 'menor_100'
			WHEN B.CONSUMOS > 100 AND B.CONSUMOS <= 200 THEN 'menor_200'
			WHEN B.CONSUMOS > 200 AND B.CONSUMOS <= 300 THEN 'menor_300'
			WHEN B.CONSUMOS > 300 AND B.CONSUMOS <= 400 THEN 'menor_400'
			WHEN B.CONSUMOS > 400 AND B.CONSUMOS <= 500 THEN 'menor_500'
			WHEN B.CONSUMOS > 500 THEN 'maior_500'
			ELSE 'Sem dados'
		END AS EP_SCORE,
		
		CASE
			WHEN A.DATA_ABERTURA>= '${REF_DATE_INI}' THEN ''  
			WHEN B.QUALITY_SCORE NOT IN ('1-REAL','SANTANDER') OR B.QUALITY_SCORE IS NULL THEN '' 
			WHEN TRIM(B.EPC_LABEL_PY) LIKE 'A%' THEN 'PEPC1'
			WHEN TRIM(B.EPC_LABEL_PY) LIKE 'B%' THEN 'PEPC2'
			WHEN TRIM(B.EPC_LABEL_PY) LIKE 'C%' THEN 'PEPC3'
			WHEN TRIM(B.EPC_LABEL_PY) LIKE 'D%' THEN 'PEPC4'
			WHEN TRIM(B.EPC_LABEL_PY) LIKE 'E%' THEN 'PEPC5'
			WHEN TRIM(B.EPC_LABEL_PY) LIKE 'F%' THEN 'PEPC6'
			WHEN TRIM(B.EPC_LABEL_PY) LIKE 'G%' THEN 'PEPC7'
			ELSE 'PEPC8'
		END AS PREVIOUS_YEAR_EPC_LABEL, 
		CASE
			WHEN A.DATA_ABERTURA>= '${REF_DATE_INI}' THEN ''
			WHEN B.CONSUMOS IS NULL THEN '' 
			WHEN B.EP_SCORE_PY <= 100 THEN 'PEPS1'
			WHEN B.EP_SCORE_PY > 100 AND B.EP_SCORE_PY <= 200 THEN 'PEPS2'
			WHEN B.EP_SCORE_PY > 200 AND B.EP_SCORE_PY <= 300 THEN 'PEPS3'
			WHEN B.EP_SCORE_PY > 300 AND B.EP_SCORE_PY <= 400 THEN 'PEPS4'
			WHEN B.EP_SCORE_PY > 400 AND B.EP_SCORE_PY <= 500 THEN 'PEPS5'
			WHEN B.EP_SCORE_PY > 500 THEN 'PEPS6'
			ELSE 'PEPS7'
		END AS PREVIOUS_YEAR_EP_SCORE,

		CASE
			WHEN A.ZCLIENTE = '0000000000' THEN 'EU-area'                                                    
			WHEN B.COUNTRY_CODE IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428')
			THEN 'EU-area'
			WHEN B.COUNTRY_CODE NOT IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428', '')
			THEN 'Non EU-area'
			WHEN A.CPAIS_RESIDENCIA IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428')
			THEN 'EU-area'
			WHEN A.CPAIS_RESIDENCIA NOT IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428','')
			THEN 'Non EU-area'
		ELSE '' 
		END AS EUROPEAN_UNION,
		CASE
			WHEN A.CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%MC06%' THEN 'MESG4' -- REGRA DE ACORDO COM SATELITE_STRUCUTRE
			WHEN A.CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%MC08%' THEN 'MESG4' -- REGRA DE ACORDO COM SATELITE_STRUCUTRE
			WHEN A.FLAG_MESG5 = 1 THEN 'MESG5'  -- COUNTERPARTY HAVING THE CHOICE OF THE REPAYMENT DATE
			WHEN A.DATA_VENCIMENTO < '${REF_DATE}' AND (A.DATA_VENCIMENTO NOT IN ('','0001-01-01','9999-12-31') OR A.DATA_VENCIMENTO IS NOT NULL) THEN 'MESG1' -- CONTRATOS COM MATURIDADE INFERIOR À DATA DE REPORTE OU FALTA DE DATA QUALITY DE DADOS
			WHEN (A.DATA_VENCIMENTO IN ('','0001-01-01','9999-12-31') OR A.DATA_VENCIMENTO IS NULL)AND A.CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%MC02%' AND A.CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL2%' THEN 'MESG4' -- UNKNOWN MATURITY RESIDENCIAL (REGRA DE ACORDO COM SATELITE_STRUCUTRE)
			WHEN (A.DATA_VENCIMENTO IN ('','0001-01-01','9999-12-31') OR A.DATA_VENCIMENTO IS NULL)AND A.CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%MC02%' AND A.CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%COLL3%' THEN 'MESG1' -- UNKNOWN MATURITY COMERCIAL (REGRA DE ACORDO COM SATELITE_STRUCUTRE)
			WHEN (A.DATA_VENCIMENTO IN ('','0001-01-01','9999-12-31') OR A.DATA_VENCIMENTO IS NULL)AND A.CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%MC02%' AND A.CCONTAB_FINAL_IDCOMB_TOTAL NOT LIKE '%COLL2%' AND A.CCONTAB_FINAL_IDCOMB_TOTAL NOT LIKE '%COLL3%' THEN 'MESG1' -- UNKNOWN MATURITY REST OF LOANS (REGRA DE ACORDO COM SATELITE_STRUCUTRE)
			WHEN (A.DATA_VENCIMENTO IN ('','0001-01-01','9999-12-31') OR A.DATA_VENCIMENTO IS NULL)AND A.CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%MC04%' THEN 'MESG1' -- UNKNOWN MATURITY BEBT SECURITIES (REGRA DE ACORDO COM SATELITE_STRUCUTRE)
			WHEN (A.DATA_VENCIMENTO IN ('','0001-01-01','9999-12-31') OR A.DATA_VENCIMENTO IS NULL)THEN 'MESG6' -- OTHER CONTRACTS WITH NO STATED MATURITY
			WHEN ROUND(DATEDIFF(TO_DATE(A.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25,4) < 05 THEN 'MESG1' 
			WHEN ROUND(DATEDIFF(TO_DATE(A.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25,4) <= 10 THEN 'MESG2'
			WHEN ROUND(DATEDIFF(TO_DATE(A.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25,4) <= 20 THEN 'MESG3'
			WHEN ROUND(DATEDIFF(TO_DATE(A.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25,4) > 20 THEN 'MESG4'
			ELSE 'MESG6'
		END AS MATURITY_ESG,
		CASE
			WHEN A.CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%MC06%'                                            THEN 0  --EXCLUSÃO DE EQUITY
			WHEN A.CCONTAB_FINAL_IDCOMB_TOTAL LIKE '%MC08%'                                            THEN 0  --EXCLUSÃO DE INVESTMENTS IN SUBSIDIARIES
			WHEN A.FLAG_MESG5 = 1                                                                      THEN 0  --EXCLUSÃO DE COUNTERPARTY HAVING THE CHOICE OF REPAYMENT DATE
			WHEN A.DATA_VENCIMENTO IN ('','0001-01-01','9999-12-31') OR A.DATA_VENCIMENTO IS NULL      THEN 0  --EXCLUSÃO DE CONTRATOS COM FALTA DE DATA QUALITY DE DADOS
			WHEN A.DATA_VENCIMENTO < '${REF_DATE}'                                                     THEN 0  --EXCLUSÃO DE CONTRATOS COM MATURIDADE INFERIOR À DATA DE REPORTE 
			WHEN ROUND(DATEDIFF(TO_DATE(A.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25,4) <= 05    THEN 1
			WHEN ROUND(DATEDIFF(TO_DATE(A.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25,4) <= 10    THEN 1
			WHEN ROUND(DATEDIFF(TO_DATE(A.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25,4) <= 20    THEN 1
			WHEN ROUND(DATEDIFF(TO_DATE(A.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25,4) >  20    THEN 1
			ELSE 0   
		END AS FLAG_MATURITY,
		CASE 
			WHEN A.DATA_VENCIMENTO IN ('','0001-01-01','9999-12-31') OR A.DATA_VENCIMENTO IS NULL THEN NULL
			WHEN A.FLAG_MESG5 = 1 THEN NULL
			WHEN A.DATA_VENCIMENTO < '${REF_DATE}' THEN NULL
			ELSE ROUND(DATEDIFF(TO_DATE(A.DATA_VENCIMENTO), TO_DATE('${REF_DATE}'))/365.25, 4)
		END AS YEARS_TO_MATURITY,
		CASE
			WHEN (DATA_INICIO NOT IN ('','0001-01-01','9999-12-31') OR DATA_INICIO IS NOT NULL) AND DATA_INICIO >= '${REF_DATE_INI}' THEN 'NBF1' -- DATA INICIO : DATA DE REESTRUTURAÇÃO/RENEGOCIAÇÃO
			WHEN A.DATA_ABERTURA >= '${REF_DATE_INI}' THEN 'NBF2' -- '2024-01-01'
			ELSE 'NBF3'
		END AS NEW_BUSINESS_FLOW,
		B.SOURCE_CODE 

	FROM 

	-- TABELA DE UNIVERSO
	(
		SELECT DISTINCT 
			DATA_ABERTURA,
			DATA_VENCIMENTO,
			CEMPRESA,
			CBALCAO,
			CNUMECTA,
			ZDEPOSIT,
			TIPO_COLATERAL,
            CPAIS_RESIDENCIA,
			CCONTAB_FINAL_IDCOMB_TOTAL,
			BRUTO_IMPARIDADE,
			ZCLIENTE,
			CASE 
				WHEN UPPER(PRODUTO) LIKE 'CART%CR%DITO%' OR 
					UPPER(PRODUTO) LIKE '%REPOS%'  OR 
					UPPER(PRODUTO) LIKE '%VISTA, DESCOBERTOS E CO%'
						THEN 1 
			END AS FLAG_MESG5
		FROM BU_CAPTOOLS_WORK.P3_UNIV_LOCAL_CTO
		WHERE REF_DATE = '${REF_DATE}' AND ID_CORRIDA IN (SELECT MAX(ID_CORRIDA) FROM BU_CAPTOOLS_WORK.P3_UNIV_LOCAL_CTO WHERE REF_DATE = '${REF_DATE}')
			AND TEMPLATE2=1 AND CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) NOT IN (SELECT CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) FROM CD_CAPTOOLS.CT001_UNIV_SALDO WHERE REF_DATE='${REF_DATE}' AND CCONTAB_FINAL_IDCOMB LIKE '%MC1005%')
	) AS A

	LEFT JOIN  
	(
		SELECT  
		GAR.CEMPRESA,
		GAR.CBALCAO,
		GAR.CNUMECTA,
		GAR.ZDEPOSIT,
		-1*SUM(GAR.AMOUNT) AS AMOUNT,
        GAR.CEMPBEM,
		GAR.CKBALBEM,
		GAR.CKCTABEM,
		GAR.CKREFBEM,
		CERT_ENERG.EPC, 
		CERT_ENERG.QUALITY_SCORE,
		CERT_ENERG.EP_SCORE AS CONSUMOS,
		CASE
			WHEN SPLIT_PART(TRIM(CERT_ENERG.SOURCE_CODE), ';', 2) IS NULL THEN 'NULO'  
			WHEN SPLIT_PART(TRIM(CERT_ENERG.SOURCE_CODE), ';', 2) = 'ADENE' THEN '1-REAL'
			WHEN SPLIT_PART(TRIM(CERT_ENERG.SOURCE_CODE), ';', 2) = 'OCR' THEN '1-REAL'
			WHEN SPLIT_PART(TRIM(CERT_ENERG.SOURCE_CODE), ';', 2) = 'GLOVAL' THEN 'ESTIMADO'
			WHEN SPLIT_PART(TRIM(CERT_ENERG.SOURCE_CODE), ';', 2) = 'MISS' THEN ''
		END AS SOURCE_CODE,
		CERT_ENERG_PREVIOUS_YEAR.EP_SCORE AS EP_SCORE_PY,
		CERT_ENERG_PREVIOUS_YEAR.EPC AS EPC_LABEL_PY,
		RENEGOCIADOS.DATA_INICIO,
		PROPERTY.COUNTRY_CODE    
		FROM
		(
        SELECT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,ZCLIENTE,CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM,SUM(AMOUNT) AS AMOUNT 
        FROM BU_ESG_WORK.MODESG_OUT_EMSS_FNCD
		WHERE NOME_PERIMETRO LIKE '%ST SGPS Cons%'
		AND REF_DATE='${REF_DATE}'
        GROUP BY 1,2,3,4,5,6,7,8,9
		) GAR
		
		LEFT JOIN
		-- LIGAÇÃO COM A TABELA PROPERTY PARA OBTENÇÃO DE CAMPOS CARACTERIZADORES DO BEM
		(
		SELECT DISTINCT
        PROPERTY_BANK_ID,
		PROPERTY_BRANCH_CODE, 
		PROPERTY_CONTRACT_ID, 
		PROPERTY_REFERENCE_CODE,
		COUNTRY_CODE 
		FROM BUSINESS_ASSETS.PROPERTY
		WHERE DATA_DATE_PART = '${REF_DATE}'
		) PROPERTY 
		ON CONCAT(GAR.CEMPBEM,GAR.CKBALBEM,GAR.CKCTABEM,GAR.CKREFBEM) = CONCAT(PROPERTY.PROPERTY_BANK_ID,PROPERTY.PROPERTY_BRANCH_CODE,PROPERTY.PROPERTY_CONTRACT_ID,PROPERTY.PROPERTY_REFERENCE_CODE) 
		
		LEFT JOIN
		-- LIGAÇÃO COM A TABELA PROPERTY_ENERGY_CERTIFICATE PARA OBTENÇÃO DE CAMPOS DE CERTIFICADOS ENERGÉTICOS
		(
		SELECT *
		FROM BU_ESG_WORK.PROPERTY_ENERGY_CERTIFICATE
		WHERE DATA_DATE_PART = '${REF_DATE}'
		) CERT_ENERG
		ON CONCAT(GAR.CEMPBEM,GAR.CKBALBEM,GAR.CKCTABEM,GAR.CKREFBEM) = CONCAT(CERT_ENERG.PROPERTY_BANK_ID,CERT_ENERG.PROPERTY_BRANCH_CODE,CERT_ENERG.PROPERTY_CONTRACT_ID,CERT_ENERG.PROPERTY_REFERENCE_CODE)  
		
		LEFT JOIN
		-- LIGAÇÃO COM A TABELA PROPERTY_ENERGY_CERTIFICATE PARA OBTENÇÃO DE CAMPOS DE CERTIFICADOS ENERGÉTICOS RELATIVOS AO ANO DE REPORTE ANTERIOR
		(
			SELECT *
			FROM BU_ESG_WORK.PROPERTY_ENERGY_CERTIFICATE
			WHERE DATA_DATE_PART = '${REF_DATE_ANT}'
		) CERT_ENERG_PREVIOUS_YEAR
        ON CONCAT(GAR.CEMPBEM,GAR.CKBALBEM,GAR.CKCTABEM,GAR.CKREFBEM) = CONCAT(CERT_ENERG_PREVIOUS_YEAR.PROPERTY_BANK_ID,CERT_ENERG_PREVIOUS_YEAR.PROPERTY_BRANCH_CODE,CERT_ENERG_PREVIOUS_YEAR.PROPERTY_CONTRACT_ID,CERT_ENERG_PREVIOUS_YEAR.PROPERTY_REFERENCE_CODE)  
		
		LEFT JOIN
		-- OBTENÇÃO DE INFORMAÇÃO SOBRE CONTRATOS RENEGOCIADOS/REESTRUTURADOS
		(
		SELECT SUBSTR(CONTA,1,4) AS CBALCAO, SUBSTR(CONTA,5,11) AS CNUMECTA, ZDEPOSIT, DATA_INICIO 
		FROM BU_ESG_WORK.RNM85_RESTR_DEZ24 -- A AJUSTAR PARA CURATED_INTERNAL_MAINFRAME_RECONDUCOES.RNM85_RESTR
		WHERE UPPER(REFINANCIAMENTO) = 'S' AND UPPER(DIFICULDADES_FINANCEIRAS) = 'N' AND DATA_DATE_PART = '${REF_DATE}'
		) AS RENEGOCIADOS
		ON CONCAT(GAR.CBALCAO,GAR.CNUMECTA,GAR.ZDEPOSIT) = CONCAT(RENEGOCIADOS.CBALCAO,RENEGOCIADOS.CNUMECTA,RENEGOCIADOS.ZDEPOSIT)
		GROUP BY 
		GAR.CEMPRESA,
		GAR.CBALCAO,
		GAR.CNUMECTA,
		GAR.ZDEPOSIT,
		GAR.CEMPBEM,
		GAR.CKBALBEM,
		GAR.CKCTABEM,
		GAR.CKREFBEM,
		CERT_ENERG.EPC, 
		CERT_ENERG.QUALITY_SCORE,
		CERT_ENERG.EP_SCORE,
		SOURCE_CODE,
		CERT_ENERG_PREVIOUS_YEAR.EP_SCORE,
		CERT_ENERG_PREVIOUS_YEAR.EPC,
		RENEGOCIADOS.DATA_INICIO,
		PROPERTY.COUNTRY_CODE      
	) AS B
	ON  A.CEMPRESA = B.CEMPRESA
	AND A.CBALCAO  = B.CBALCAO
	AND A.CNUMECTA = B.CNUMECTA
	AND A.ZDEPOSIT = B.ZDEPOSIT

	LEFT JOIN 
	-- OBTENÇÃO DE INFORMAÇÃO DE TX DE JURO
	( 
		SELECT DISTINCT B.CEMPRESA,  B.CBALCAO, B.CNUMECTA, B.ZDEPOSIT, A.ANNLSD_AGRD_RT AS TX_JURO_LT
		FROM
		(
			SELECT DISTINCT INSTRMNT_ID, ANNLSD_AGRD_RT
			FROM CD_LOAN_TAPES_BCE.LT002_INSTRUMENT
			WHERE REF_DATE = '${REF_DATE}' AND 
					UPPER(AMBITO) = 'PM' AND 
					UPPER(NOME_PERIMETRO) = 'INDIVIDUAL LOCAL' AND 
					UPPER(SEGMENTO) = 'ESTR'
	) A 
	LEFT JOIN
	(SELECT DISTINCT * FROM CD_CAPTOOLS.KT_CHAVES_FINREP WHERE REF_DATE = '${REF_DATE}') B
	ON A.INSTRMNT_ID = CONCAT(B.CEMPRESA_FR,B.CBALCAO_FR,B.CNUMECTA_FR,B.ZDEPOSIT_FR)
	) AS C
	ON  A.CEMPRESA = C.CEMPRESA
	AND A.CBALCAO  = C.CBALCAO
	AND A.CNUMECTA = C.CNUMECTA
	AND A.ZDEPOSIT = C.ZDEPOSIT

	LEFT JOIN
	-- OBTENÇÃO DE INFORMAÇÃO DE LTV
	(
		SELECT B.CEMPRESA,  B.CBALCAO, B.CNUMECTA, B.ZDEPOSIT, A.VALOR_LTV 
		FROM
		(
			SELECT DISTINCT CEMPRESA, CBALCAO, CNUMECTA, ZDEPOSIT, VALOR_LTV
			FROM CD_CAPTOOLS.FR011_CAPS_LTV 
			WHERE REF_DATE = '${REF_DATE}'
		) A 
		LEFT JOIN
		(SELECT DISTINCT * FROM CD_CAPTOOLS.KT_CHAVES_FINREP WHERE REF_DATE = '${REF_DATE}') B
		ON A.CEMPRESA = B.CEMPRESA_FR AND A.CBALCAO= B.CBALCAO_FR AND A.CNUMECTA = B.CNUMECTA_FR AND A.ZDEPOSIT = B.ZDEPOSIT_FR
	) AS D
	ON  A.CEMPRESA = D.CEMPRESA
	AND A.CBALCAO  = D.CBALCAO
	AND A.CNUMECTA = D.CNUMECTA
	AND A.ZDEPOSIT = D.ZDEPOSIT
	WHERE AMOUNT IS NOT NULL

	UNION ALL
	-- ADJUDICADOS
	SELECT
		NULL AS DATA_ABERTURA,
		NULL AS DATA_VENCIMENTO, 
		NULL AS CEMPRESA,
		NULL AS CBALCAO,
		NULL AS CNUMECTA,
		NULL AS ZDEPOSIT,
		'Stock' AS TIPO_COLATERAL,
		NULL AS CCONTAB_FINAL_IDCOMB_TOTAL,
		NULL AS BRUTO_IMPARIDADE,
		NULL AS FLAG_MESG5,
		ADJUD_INPUTS.V_CONTAB AS AMOUNT,
		ADJUD_INPUTS.PROPERTY_BANK_ID,
		ADJUD_INPUTS.PROPERTY_BRANCH_CODE,
		ADJUD_INPUTS.PROPERTY_CONTRACT_ID,
		ADJUD_INPUTS.PROPERTY_REFERENCE_CODE,
		CERT_ENERG.EPC, 
		CASE 
			WHEN CERT_ENERG.QUALITY_SCORE IS NULL THEN 'NULO'
			ELSE CERT_ENERG.QUALITY_SCORE 
		end as QUALITY_SCORE,
		CERT_ENERG.EP_SCORE AS CONSUMOS,
		NULL AS VALOR_LTV,
		NULL AS VALOR_LTV_DECIMAL,
		NULL AS TX_JURO,
		'' AS COLLATERAL_LTV,
		CASE
			WHEN TRIM(CERT_ENERG.EPC) LIKE 'A' THEN 'A'
			WHEN TRIM(CERT_ENERG.EPC) LIKE 'A%' THEN 'A+'
			WHEN TRIM(CERT_ENERG.EPC) LIKE 'B' THEN 'B'
			WHEN TRIM(CERT_ENERG.EPC) LIKE 'B%' THEN 'B-'
			WHEN TRIM(CERT_ENERG.EPC) LIKE 'C%' THEN 'C'
			WHEN TRIM(CERT_ENERG.EPC) LIKE 'D%' THEN 'D'
			WHEN TRIM(CERT_ENERG.EPC) LIKE 'E%' THEN 'E'
			WHEN TRIM(CERT_ENERG.EPC) LIKE 'F%' THEN 'F'
			WHEN TRIM(CERT_ENERG.EPC) LIKE 'G%' THEN 'G'
			ELSE 'Sem dados'
		END AS EPC_LABEL, 
		CASE 
			WHEN CERT_ENERG.EP_SCORE <= 100 THEN 'menor_100'
			WHEN CERT_ENERG.EP_SCORE > 100 AND CERT_ENERG.EP_SCORE <= 200 THEN 'menor_200'
			WHEN CERT_ENERG.EP_SCORE > 200 AND CERT_ENERG.EP_SCORE <= 300 THEN 'menor_300'
			WHEN CERT_ENERG.EP_SCORE > 300 AND CERT_ENERG.EP_SCORE <= 400 THEN 'menor_400'
			WHEN CERT_ENERG.EP_SCORE > 400 AND CERT_ENERG.EP_SCORE <= 500 THEN 'menor_500'
			WHEN CERT_ENERG.EP_SCORE > 500 THEN 'maior_500'
			ELSE 'Sem dados'
		END AS EP_SCORE,
		'' AS PREVIOUS_YEAR_EPC_LABEL,
		'' AS PREVIOUS_YEAR_EP_SCORE,
		CASE                                                    
			WHEN PROPERTY.COUNTRY_CODE IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428')
			THEN 'EU-area'
			WHEN PROPERTY.COUNTRY_CODE NOT IN ('276', '040',  '056', '100', '196', '191', '208','705', '724',  '233','246', '250','300','348','372','380', '440', '442',  '470', '616', '620', '203','703', '642', '752', '528', '428', '')
			THEN 'Non EU-area'
		ELSE '' 
		END AS EUROPEAN_UNION,
		'MESG4' AS MATURITY_ESG,
		0 AS FLAG_MATURITY,
		NULL AS YEARS_TO_MATURITY,
		'' AS NEW_BUSINESS_FLOW,
		CASE
			WHEN SPLIT_PART(TRIM(CERT_ENERG.SOURCE_CODE), ';', 2) IS NULL THEN 'NULO' 
			WHEN SPLIT_PART(TRIM(CERT_ENERG.SOURCE_CODE), ';', 2) = 'ADENE' THEN '1-REAL'
			WHEN SPLIT_PART(TRIM(CERT_ENERG.SOURCE_CODE), ';', 2) = 'OCR' THEN '1-REAL'
			WHEN SPLIT_PART(TRIM(CERT_ENERG.SOURCE_CODE), ';', 2) = 'GLOVAL' THEN 'ESTIMADO'
			WHEN SPLIT_PART(TRIM(CERT_ENERG.SOURCE_CODE), ';', 2) = 'MISS' THEN ''
		END AS SOURCE_CODE
		
	FROM 
	-- TABELA DE UNIVERSO
	(
	SELECT
		'31' as PROPERTY_BANK_ID,
		'CMAH' AS PROPERTY_BRANCH_CODE, 
		'IMOVELGIDAP' AS PROPERTY_CONTRACT_ID,
		REPLACE(UPPER(LPAD(COD_IMOVEL,15,'0')),' ', '0') AS PROPERTY_REFERENCE_CODE,
		V_CONTAB
	FROM CD_CAPTOOLS.CT666_ADJUDIC_PROPR
	WHERE REF_DATE='${REF_DATE}'
	AND V_CONTAB_IFRS IN('199100240', '19910000', '1910000', '199100200', '199100210', '19910001', '1910008', '199100201', '199100211', '199100241')

	UNION ALL

	SELECT
		'89' AS PROPERTY_BANK_ID , 
		'CMAH' AS PROPERTY_BRANCH_CODE, 
		'IMOVELIFICS' AS PROPERTY_CONTRACT_ID,
		LPAD(N_IMOVEL,15,'0') AS PROPERTY_REFERENCE_CODE,
		V_CONTAB
	FROM CD_CAPTOOLS.CT668_IMOVEIS_IFIC
	WHERE REF_DATE='${REF_DATE}'
	AND V_CONTAB_IFRS IN('199100240', '19910000', '1910000', '199100200', '199100210', '19910001', '1910008', '199100201', '199100211', '199100241')

	UNION ALL

	SELECT
		'00160' AS PROPERTY_BANK_ID , 
		'CMAH' AS PROPERTY_BRANCH_CODE, 
		'IMOVELGIDTU' AS PROPERTY_CONTRACT_ID, 
		LPAD(COD_IMOVEL,15,'0') AS PROPERTY_REFERENCE_CODE,
		V_CONTAB
	FROM CD_CAPTOOLS.CT665_STOCK_URBE
	WHERE REF_DATE='${REF_DATE}'
	) ADJUD_INPUTS

	LEFT JOIN
	-- LIGAÇÃO COM A TABELA PROPERTY PARA OBTENÇÃO DE CAMPOS CARACTERIZADORES DO BEM
	(
		SELECT DISTINCT
			PROPERTY_BANK_ID,
			PROPERTY_BRANCH_CODE, 
			PROPERTY_CONTRACT_ID, 
			PROPERTY_REFERENCE_CODE,
			COUNTRY_CODE 
		FROM BU_ESG_WORK.PROPERTY
		WHERE DATA_DATE_PART = '${REF_DATE}'
	) PROPERTY 
	ON CONCAT(PROPERTY.PROPERTY_BANK_ID,PROPERTY.PROPERTY_BRANCH_CODE,PROPERTY.PROPERTY_CONTRACT_ID,PROPERTY.PROPERTY_REFERENCE_CODE) = CONCAT(ADJUD_INPUTS.PROPERTY_BANK_ID,ADJUD_INPUTS.PROPERTY_BRANCH_CODE,ADJUD_INPUTS.PROPERTY_CONTRACT_ID,ADJUD_INPUTS.PROPERTY_REFERENCE_CODE)

	LEFT JOIN
	-- LIGAÇÃO COM A TABELA PROPERTY_ENERGY_CERTIFICATE PARA OBTENÇÃO DE CAMPOS DE CERTIFICADOS ENERGÉTICOS
	(
		SELECT *
		FROM BU_ESG_WORK.PROPERTY_ENERGY_CERTIFICATE
		WHERE DATA_DATE_PART = '${REF_DATE}'
	) CERT_ENERG 
	ON CONCAT(CERT_ENERG.PROPERTY_BANK_ID,CERT_ENERG.PROPERTY_BRANCH_CODE,CERT_ENERG.PROPERTY_CONTRACT_ID,CERT_ENERG.PROPERTY_REFERENCE_CODE) = CONCAT(ADJUD_INPUTS.PROPERTY_BANK_ID,ADJUD_INPUTS.PROPERTY_BRANCH_CODE,ADJUD_INPUTS.PROPERTY_CONTRACT_ID,ADJUD_INPUTS.PROPERTY_REFERENCE_CODE) 

	WHERE CONCAT(ADJUD_INPUTS.PROPERTY_BANK_ID,ADJUD_INPUTS.PROPERTY_BRANCH_CODE,ADJUD_INPUTS.PROPERTY_CONTRACT_ID,ADJUD_INPUTS.PROPERTY_REFERENCE_CODE) IN (SELECT CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) FROM CD_CAPTOOLS.CT001_UNIV_SALDO WHERE REF_DATE='${REF_DATE}' AND CCONTAB_FINAL_IDCOMB LIKE '%MC1005%')
) X

LEFT JOIN
(
	SELECT NVL(MAX(ID_CORRIDA),0)+1 AS NEW_ID_CORRIDA
	FROM BU_ESG_WORK.AG02_STE_CTO_GRA
	WHERE REF_DATE = '${REF_DATE}'
) RT
ON 1=1
;

/*=========================================================================================================================================*/
/*  2. TABELA FINAL: OBTENÇÃO DAS MÉTRICAS AGREGADAS A REPORTAR NO ÂMBITO DO TEMPLATE 2 STE                         					   */
/*=========================================================================================================================================*/

-- INSERT OVERWRITE TABLE BU_ESG_WORK.AG02_STE_CTO_AGR PARTITION (ID_CORRIDA,REF_DATE)
SELECT
	TIPO_COLATERAL,
	EPC_LABEL,
	EP_SCORE,
	EUROPEAN_UNION,
	ROUND(SUM(AMOUNT),0) AS AMOUNT,
	QUALITY_SCORE,
	MATURITY_ESG,
	CASE       
		WHEN FLAG_MATURITY = 0  THEN NULL
		WHEN ROUND(SUM(AMOUNT))*ROUND(AVG(YEARS_TO_MATURITY),0) < 0 THEN 0 -- ZERAR CASOS NEGATIVOS (MATURIDADE NEGATIVA NÃO PODERÁ SER CONSIDERADA)
		ELSE ROUND(SUM(AMOUNT))*ROUND(AVG(YEARS_TO_MATURITY),0) 
	END AS AVEG_AUX,
	NEW_BUSINESS_FLOW,
	PREVIOUS_YEAR_EP_SCORE,
	PREVIOUS_YEAR_EPC_LABEL,
	FLAG_MATURITY,
	CASE
		WHEN ROUND(SUM(AMOUNT)) * ROUND(AVG(TX_JURO),2) < 0 THEN 0 -- ZERAR CASOS NEGATIVOS (CONFIRMADO PELA CORPORAÇÃO NO EMAIL DE DIA 28/01/2025)
		ELSE ROUND(SUM(AMOUNT)) * ROUND(AVG(TX_JURO),2) 
	END AS INTEREST_AUX,
	CASE
		WHEN ROUND(SUM(AMOUNT)) * ROUND(AVG(VALOR_LTV_DECIMAL),2) < 0 THEN 0 -- ZERAR CASOS NEGATIVOS
		ELSE ROUND(SUM(AMOUNT)) * ROUND(AVG(VALOR_LTV_DECIMAL),2)
	END AS LTV_AUX,
	COLLATERAL_LTV,
	SOURCE_CODE,
	
	-- PARTICAO
	RT.NEW_ID_CORRIDA AS ID_CORRIDA,
	'${REF_DATE}' AS REF_DATE
    
FROM (SELECT * FROM BU_ESG_WORK.AG02_STE_CTO_GRA WHERE REF_DATE = '${REF_DATE}' AND ID_CORRIDA IN (SELECT MAX(ID_CORRIDA) FROM BU_ESG_WORK.AG02_STE_CTO_GRA WHERE REF_DATE = '${REF_DATE}')) X
LEFT JOIN
(
	SELECT NVL(MAX(ID_CORRIDA),0)+1 AS NEW_ID_CORRIDA
	FROM BU_ESG_WORK.AG02_STE_CTO_AGR
	WHERE REF_DATE = '${REF_DATE}'
) RT
ON 1=1
GROUP BY 1,2,3,4,6,7,9,10,11,12,15,16,17,18
;

