
/*===================================================================================================================================================
                                                      
											     SIMULAÇÃO EMISSÕES FINANCIADAS MODELO VERDE
										                    NEYOND 2024 - V1.0
															    
 ===================================================================================================================================================*/
 
--------------------------------------------------------------------------------------------------------------------------------------------------
-- 1A. Criação da tabela auxiliar com métricas de saldos para o cálculo e junção de os bens associados ao contrato
--------------------------------------------------------------------------------------------------------------------------------------------------

	-- JUN25: Inserted 8.302.893 row(s) 
 	
DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.EMI_FINAN_AUX1 PURGE;
CREATE TABLE BU_CAPTOOLS_WORK.EMI_FINAN_AUX1 AS

SELECT BASE.*,L6.PURPOSE_CODE,UNIV_CT.FLAG_PERIMETRO,UNIV_CT.SUM_MSALDO_FINAL_CT,BENS.CHAVE_CTO,BENS.CEMPBEM,BENS.CKBALBEM,BENS.CKCTABEM,BENS.CKREFBEM,BENS.CHAVE_BEM,BENS.FLAG_BEM,L5.cgarant_bem,GT018.SUM_mavaliaa,L5.preco_aquis
	,CASE
		WHEN L5.preco_aquis IS NOT NULL THEN L5.preco_aquis
		ELSE GT018.SUM_mavaliaa
	END AS PRECO_AQUISICAO
FROM 

	-- 1º CRUZAMENTO: OBTER O UNIVERSO BASE 
	--> DEZ24 6.287.849 REGISTOS         
    (
	SELECT DISTINCT CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT,CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) AS CHAVE,ZCLIENTE
	FROM CD_CAPTOOLS.ct004_univ_cto
	WHERE REF_DATE='${ref_date}'
	)BASE
	
LEFT JOIN 

	-- 2º CRUZAMENTO: OBTER O SALDO DE CADA CONTRATO 
	--> DEZ24 6.317.957 REGISTOS | € XXX XXX
	(
	SELECT *
	FROM 
		(
		SELECT CHAVE_SALDO,FLAG_PERIMETRO,SUM(SUM_MSALDO_FINAL_AUX) AS SUM_MSALDO_FINAL_CT
		FROM 
			(
			SELECT *
				,CASE 
					WHEN F2.CONTA_1 IS NOT NULL AND F3.CONTA_2 IS NOT NULL THEN 'ST SGPS Cons;Individual Idcomb'
					WHEN F2.CONTA_1 IS NOT NULL AND F3.CONTA_2 IS NULL THEN 'ST SGPS Cons'
					WHEN F2.CONTA_1 IS NULL AND F3.CONTA_2 IS NOT NULL THEN 'Individual Idcomb'
					WHEN F2.CONTA_1 IS NULL AND F3.CONTA_2 IS NULL THEN 'Nao Aplicavel'
				END AS FLAG_PERIMETRO 
			
			FROM 
				(
				SELECT CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) AS CHAVE_SALDO
					,CCONTAB_FINAL_ST_SGPS
					,ccontab_final_idcomb --CCONTAB_FINAL_CARGABAL
					,SUM(MSALDO_FINAL) AS SUM_MSALDO_FINAL_AUX
				FROM CD_CAPTOOLS.CT001_UNIV_SALDO
				WHERE REF_DATE = '${ref_date}'
					AND FLAG_ATIVO=1
				GROUP BY 1,2,3
				)F1
			LEFT JOIN 
				(
				SELECT DISTINCT TRIM(CONTA) AS CONTA_1
				FROM CD_CAPTOOLS.FR802_PL_CONTAS
				WHERE REF_DATE = '${ref_date}'
					--AND DETALHE_CONTA = 'I'
					AND TIPO_CONTA = 'A'
					AND COD_PLANO = 'ST_SGPS_CONS' 
					AND TRIM(CONTA) <> ''
					AND TRIM(BRUTO_IMPARIDADE) NOT IN ('imparidade')
					AND TRIM(CARTEIRA_CONTABILISTICA) NOT IN ('outros ativos - resto')
				)F2 ON F1.CCONTAB_FINAL_ST_SGPS=F2.CONTA_1
			LEFT JOIN 
				(
				SELECT DISTINCT TRIM(CONTA) AS CONTA_2
				FROM CD_CAPTOOLS.FR802_PL_CONTAS
				WHERE REF_DATE = '${ref_date}'
					-- AND DETALHE_CONTA = 'I'
					AND TIPO_CONTA = 'A'
					AND COD_PLANO = 'BST_IDCOMB'  --CARGABAL
					AND TRIM(CONTA) <> ''
					AND TRIM(BRUTO_IMPARIDADE) NOT IN ('imparidade')
					AND TRIM(CARTEIRA_CONTABILISTICA) NOT IN ('outros ativos - resto')
				)F3 ON F1.ccontab_final_idcomb=F3.CONTA_2 --CCONTAB_FINAL_CARGABAL
			)AUX_1 GROUP BY 1,2
		)AUX_2 --WHERE FLAG_PERIMETRO<>'Fora Perimetro' --26/06 - Tem de entrar os saldos todos para a tabela suportar o universo todo 
	)UNIV_CT ON BASE.CHAVE=UNIV_CT.CHAVE_SALDO
	
LEFT JOIN 

	-- 3º CRUZAMENTO: OBTER TODAS AS RELAÇÕES DE BENS COLATERIZADOS DO CONTRATO (IMO + MOV)
	--> DEZ24 6.298.234 REGISTOS | € XXX XXX
	(
	SELECT *
	FROM 
		(
		SELECT *
			,ROW_NUMBER() OVER (PARTITION BY CONCAT(CHAVE_CTO,CHAVE_BEM) ORDER BY FLAG_ORDEM ASC) AS ROW_BENS
		FROM 
			(
				SELECT DISTINCT S1.CHAVE_CTO,S2.CEMPBEM,S2.CKBALBEM,S2.CKCTABEM,S2.CKREFBEM,S2.CHAVE_BEM,'MUG_IMO' AS FLAG_BEM, 1 AS FLAG_ORDEM
				FROM 
					(
					SELECT CONCAT(CEMPRESP,CKBALRES,CKCTARES,CKREFRESP) AS CHAVE_CTO
						,CONCAT(CEMPRESA,CKBALCAO,CKNUMCTA,COMP_ID_GAR) AS CHAVE_PRO
					FROM CD_GARANTIAS.GT001_TRZ_RSP_GT
					WHERE REF_DATE='${ref_date}'
					)S1
				INNER JOIN  
					(
					SELECT CONCAT(CEMPRESA,CKBALCAO,CKNUMCTA,COMP_ID_GAR) AS CHAVE_PRO,
						CONCAT(CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) AS CHAVE_BEM,
						CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM
					FROM CD_GARANTIAS.GT008_TRZ_GT_IMV
					WHERE REF_DATE='${ref_date}'
					)S2 ON S1.CHAVE_PRO=S2.CHAVE_PRO
			UNION ALL 
				SELECT DISTINCT S1.CHAVE_CTO,S2.CEMPBEM,S2.CKBALBEM,S2.CKCTABEM,S2.CKREFBEM,S2.CHAVE_BEM,'MBI_IMO' AS FLAG_BEM,2 AS FLAG_ORDEM
				FROM 
					(
					SELECT CONCAT(BANK_ID,BRANCH_CODE,CONTRACT_ID,REFERENCE_CODE) AS CHAVE_CTO
						,CONCAT(PROCESS_BANK_ID,PROCESS_BRANCH_CODE,PROCESS_ACCOUNT_ID,PROCESS_REFERENCE_CODE) AS CHAVE_PRO
					FROM BU_ESG_WORK.RESPONSIBILITY_PROCESS_REL
					WHERE DATA_DATE_PART='${ref_date}'
					)S1
				INNER JOIN 
					(
					SELECT CONCAT(PROCESS_BANK_ID,PROCESS_BRANCH_CODE,PROCESS_ACCOUNT_ID,PROCESS_REFERENCE_CODE) AS CHAVE_PRO
						,CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM 
						,PROPERTY_BANK_ID AS CEMPBEM
						,PROPERTY_BRANCH_CODE AS CKBALBEM
						,PROPERTY_CONTRACT_ID AS CKCTABEM
						,PROPERTY_REFERENCE_CODE AS CKREFBEM
					FROM BU_ESG_WORK.PROCESS_PROPERTY_REL
					WHERE DATA_DATE_PART='${ref_date}'
						AND COLLATERAL_PROPERTY_IND=1
					)S2 ON S1.CHAVE_PRO=S2.CHAVE_PRO
			UNION ALL 
				SELECT DISTINCT S1.CHAVE_CTO,S2.CEMPBEM,S2.CKBALBEM,S2.CKCTABEM,S2.CKREFBEM,S2.CHAVE_BEM,'MUG_MOV' AS FLAG_BEM,3 AS FLAG_ORDEM
				FROM 
					(
					SELECT CONCAT(CEMPRESP,CKBALRES,CKCTARES,CKREFRESP) AS CHAVE_CTO
						,CONCAT(CEMPRESA,CKBALCAO,CKNUMCTA,COMP_ID_GAR) AS CHAVE_PRO
					FROM CD_GARANTIAS.GT001_TRZ_RSP_GT
					WHERE REF_DATE='${ref_date}'
					)S1
				INNER JOIN  
					(
					SELECT CONCAT(CEMPRESA,CKBALCAO,CKNUMCTA,COMP_ID_GAR) AS CHAVE_PRO,
						CONCAT(CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) AS CHAVE_BEM,
						CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM
					FROM CD_GARANTIAS.GT012_TRZ_GT_MOB
					WHERE REF_DATE='${ref_date}'
					)S2 ON S1.CHAVE_PRO=S2.CHAVE_PRO
			)AUX_BENS
		)BENS WHERE ROW_BENS=1
	)BENS ON BASE.CHAVE=BENS.CHAVE_CTO AND UNIV_CT.FLAG_PERIMETRO<>'Nao Aplicavel' AND UNIV_CT.SUM_MSALDO_FINAL_CT<>0

LEFT JOIN 

	-- 4º CRUZAMENTO: OBTER O VALOR DE CADA COLATERAL NO  CONTRATO 
	--> DEZ24 6.317.957 REGISTOS | € XXX XXX
	(
	SELECT  CONCAT(CEMPRESP,CKBALRES,CKCTARES,CKREFRESP) AS CTO_GT018,CONCAT(CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) AS BEM_GT018, SUM(mavaliaa) AS SUM_mavaliaa
	FROM CD_GARANTIAS.GT018_RATEIO_aval
	WHERE REF_DATE='${ref_date}'
	GROUP BY 1,2
	)GT018 ON BENS.CHAVE_CTO=GT018.CTO_GT018 AND BENS.CHAVE_BEM=GT018.BEM_GT018
LEFT JOIN 	
	(
	SELECT DISTINCT CONCAT(CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) AS CHAVE_MUG,preco_aquisicao AS PRECO_AQUIS,cgarant_bem
	FROM CD_GARANTIAS.GT018_RATEIO_AVAL
	WHERE REF_DATE='${ref_date}'
		AND PRECO_AQUISICAO IS NOT NULL 
	)L5 ON BENS.CHAVE_BEM=L5.CHAVE_MUG	
LEFT JOIN 	
	(
	SELECT CONCAT(CEMPRESA,CBALCAO,CNUMECTA,ZDEPOSIT) AS CHAVE_PURP,PURPOSE_CODE 
	FROM CD_CAPTOOLS.CT004_UNIV_CTO
	WHERE REF_DATE='${ref_date}'
	)L6 ON BASE.CHAVE=L6.chave_PURP
	
;

	-- VALIDAÇÃO #1 - Valores de saldo 

SELECT CHAVE,count(DISTINCT flag_perimetro) AS N 
FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX1
WHERE FLAG_PERIMETRO<>'Nao Aplicavel' AND sum_msaldo_final_ct<>0
GROUP BY 1 ORDER BY N DESC
;
	-- Todos os contratos da query acima são ajustes sem bens 
SELECT DISTINCT flag_bem
FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX1
WHERE CHAVE IN 
    (
    SELECT CHAVE 
    FROM 
        (
        SELECT CHAVE,count(DISTINCT flag_perimetro) AS N 
        FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX1
        WHERE FLAG_PERIMETRO<>'Nao Aplicavel' AND sum_msaldo_final_ct<>0
        GROUP BY 1 HAVING N>1
        )AUX
    )
;

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 2A. Criação da tabela auxiliar com métricas auxiliares para o cálculo do saldo 
--------------------------------------------------------------------------------------------------------------------------------------------------

	-- DEZ24: Inserted 8.302.893 row(s) 

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.EMI_FINAN_AUX2 PURGE;
CREATE TABLE BU_CAPTOOLS_WORK.EMI_FINAN_AUX2 AS

SELECT F1.*
    ,CASE 
        WHEN F2.CHAVE_CTO IS NULL THEN 0
        ELSE F2.N
    END AS NUM_BENS
    ,F3.CTO_MAVALIAA
    ,CASE
        WHEN F2.CHAVE_CTO IS NULL THEN 'SEM_COLATERAL'
		WHEN F1.SUM_MSALDO_FINAL_CT>0 THEN 'REVER'
		WHEN F3.CTO_MAVALIAA>=-F1.SUM_MSALDO_FINAL_CT AND F3.CTO_MAVALIAA IS NOT NULL AND F1.SUM_MSALDO_FINAL_CT IS NOT NULL THEN 'SUM_COLAT_COBRE'
        WHEN F3.CTO_MAVALIAA<-F1.SUM_MSALDO_FINAL_CT AND F3.CTO_MAVALIAA IS NOT NULL AND F1.SUM_MSALDO_FINAL_CT IS NOT NULL THEN 'SUM_COLAT_N_COBRE'
        WHEN F1.SUM_MSALDO_FINAL_CT IS NULL THEN 'SALDO_CT_NULL'
		WHEN F1.SUM_MSALDO_FINAL_CT=0 THEN 'SALDO_CT_ZERO'
        WHEN F3.CTO_MAVALIAA IS NULL THEN 'SALDO_COLAT_NULL'
    END AS FLAG_COBERT
    ,ABS(CAST(F1.SUM_MAVALIAA AS DECIMAL(38,20))/CAST(F3.CTO_MAVALIAA AS DECIMAL(38,20))) AS PESO_COLAT_COBERT
	,ABS(CAST(F1.SUM_MAVALIAA AS DECIMAL(38,20))/CAST(F1.SUM_MSALDO_FINAL_CT AS DECIMAL(38,20))) AS PESO_COLAT_N_COBERT
FROM 
    (
    SELECT * 
    FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX1
    )F1
LEFT JOIN 
    (
    SELECT CHAVE_CTO, COUNT(DISTINCT CHAVE_BEM) AS N
    FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX1
    WHERE CHAVE_BEM IS NOT NULL 
    GROUP BY 1
    )F2 ON F1.CHAVE_CTO=F2.CHAVE_CTO
LEFT JOIN 
    (
    SELECT CHAVE_CTO,SUM(NVL(SUM_MAVALIAA,0)) AS CTO_MAVALIAA --27/06 - Não pode existir casos que seja local/corp e em simultaneo que seja local ou corp com bens associados // Após correr esta tabela correr validação #1
    FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX1
    GROUP BY 1
    )F3 ON F1.CHAVE_CTO=F3.CHAVE_CTO
;

	-- VALIDAÇÃO #1 - VALOR DOS BENS 

SELECT *
FROM 
    (
    SELECT CHAVE,FLAG_PERIMETRO,SUM(SUM_MAVALIAA) AS TESTE
    FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX2
    GROUP BY 1,2
    )F1
LEFT JOIN 
    (
    SELECT DISTINCT CHAVE,FLAG_PERIMETRO,cto_mavaliaa
    FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX2
    )F2
ON F1.CHAVE=F2.CHAVE AND F1.FLAG_PERIMETRO=F2.FLAG_PERIMETRO
WHERE (TESTE<>cto_mavaliaa) OR (TESTE IS NOT NULL AND cto_mavaliaa IS NULL) OR (TESTE IS NULL AND cto_mavaliaa IS NOT NULL)

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 2B. Criação da tabela auxiliar com o cálculo do AMOUNT 
--------------------------------------------------------------------------------------------------------------------------------------------------
 
 	-- JUN25: Inserted 8.324.120 row(s) 
 
DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.EMI_FINAN_AUX3 PURGE;
CREATE TABLE BU_CAPTOOLS_WORK.EMI_FINAN_AUX3 AS

SELECT UNI.*
    ,CASE 
        WHEN FLAG_COBERT='SUM_COLAT_COBRE' THEN PESO_COLAT_COBERT*SUM_MSALDO_FINAL_CT 
        WHEN FLAG_COBERT='SUM_COLAT_N_COBRE' THEN PESO_COLAT_N_COBERT*SUM_MSALDO_FINAL_CT 
        ELSE SUM_MSALDO_FINAL_CT
    END AS AMOUNT
	,F2.*
	,CAST(F2.VCPIM AS DECIMAL(38,20)) AS CLIENT_OWN_FUNDS
	,(CAST(F2.VPNICSFIN AS DECIMAL(38,20)) + CAST(F2.VPNPASLF AS DECIMAL(38,20)) + CAST(F2.VPNOPFIN AS DECIMAL(38,20)) + CAST(F2.VPCICSFIN AS DECIMAL(38,20))+ CAST(F2.VPCOPFIN AS DECIMAL(38,20))+ CAST(F2.VPCPASLF AS DECIMAL(38,20))) AS CLIENT_DEBT
FROM 
    (
        SELECT *,'LINHA INI' AS FLAG_LINHAS FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX2
    UNION ALL 
        SELECT DISTINCT
            F1.CEMPRESA
            ,F1.CBALCAO
            ,F1.CNUMECTA
            ,F1.ZDEPOSIT
            ,F1.CHAVE
            ,F1.ZCLIENTE
			,F1.PURPOSE_CODE
			,F1.FLAG_PERIMETRO
			,F1.SUM_MSALDO_FINAL_CT
			,F1.CHAVE_CTO
			,NULL AS CEMPBEM
			,NULL AS CKBALBEM
			,NULL AS CKCTABEM
			,NULL AS CKREFBEM
            ,NULL AS CHAVE_BEM
            ,NULL AS FLAG_BEM
			,NULL AS cgarant_bem
            ,NULL AS SUM_MAVALIAA
			,NULL AS preco_aquis
			,NULL AS preco_aquisicao
            ,NULL AS NUM_BENS
            ,F1.CTO_MAVALIAA
            ,F1.FLAG_COBERT			
            ,NULL PESO_COLAT_COBERT
            ,CAST(1-F2.PESO_REMN AS DECIMAL(38,20)) AS PESO_COLAT_N_COBERT
            ,'LINHA ADI' AS FLAG_LINHAS  
        FROM 
            (
            SELECT *
            FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX2
            WHERE FLAG_COBERT='SUM_COLAT_N_COBRE'
            )F1
        LEFT JOIN 
            (
            SELECT CHAVE,SUM(NVL(PESO_COLAT_N_COBERT,0)) AS PESO_REMN
            FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX2
            WHERE FLAG_COBERT='SUM_COLAT_N_COBRE'
            GROUP BY 1
            )F2 ON F1.CHAVE=F2.CHAVE
	)UNI
LEFT JOIN 
	(
	SELECT ZCLIENTE,CCLI_GRUPO
	FROM CD_CAPTOOLS.CT003_UNIV_CLI
	WHERE REF_DATE = "${ref_date}"
	)F1 ON UNI.ZCLIENTE=F1.ZCLIENTE
LEFT JOIN 
	(
	SELECT *
	FROM 
		(
		SELECT ROW_NUMBER() OVER (PARTITION BY BL.CCLIGRUPO ORDER BY BL.CGESTOR DESC, `TIMESTAMP` DESC) AS ROW_ORDEM_1,BL.*
		FROM 
			(
			SELECT CCLIGRUPO,
				DANO,
				CGESTOR,
				`TIMESTAMP`,
				DFIM,
				CPERIODO,
				ITIP_INF,
				DATA_DATE_PART
				,VCPIM 
				,VPNICSFIN 
				,VPNPASLF 
				,VPNOPFIN 
				,VPCICSFIN
				,VPCOPFIN 
				,VPCPASLF 
			FROM CD_RISCOS.RSV176SA1_BALANCO
			WHERE DATA_DATE_PART <= "${ref_date}"
			)BL
		INNER JOIN 
			(
			SELECT *
			FROM 	
				(
				SELECT ROW_NUMBER() OVER (PARTITION BY CCLIGRUPO ORDER BY DANO DESC, CGESTOR DESC, DFIM DESC) AS ROW_ORDEM_2
					,CCLIGRUPO
					,DANO
					,CGESTOR
					,DFIM
					,ITIP_INF
					,CPERIODO
				FROM 
					(
					SELECT BL1.*
					FROM 
						(
						SELECT 
							CCLIGRUPO
							,DANO
							,CGESTOR
							,DFIM
							,CPERIODO
							,ITIP_INF
						FROM CD_RISCOS.RSV176SA1_BALANCO
						WHERE DATA_DATE_PART <= '${ref_date}'
							AND CPERIODO = '212'
							AND ITIP_INF = 'I'
						)BL1
					INNER JOIN 
						(
						SELECT CCLI_GRUPO,DCONSTITUICAO
						FROM CD_CAPTOOLS.CT003_UNIV_CLI
						WHERE REF_DATE = "${ref_date}"
						)CLI ON CCLI_GRUPO = CCLIGRUPO
					WHERE DANO <= SUBSTR("${ref_date}",1,4) AND DANO >= SUBSTR(DCONSTITUICAO,1,4)
					)AUX_1
				)AUX_2 WHERE ROW_ORDEM_2=1
			)FS ON (FS.CCLIGRUPO = BL.CCLIGRUPO AND FS.DANO = BL.DANO AND FS.CPERIODO = BL.CPERIODO AND FS.ITIP_INF = BL.ITIP_INF)
		)AUX_3 WHERE ROW_ORDEM_1=1
	)F2 ON F1.CCLI_GRUPO=F2.CCLIGRUPO
;

	-- VALIDAÇÃO #2 -SALDOS - CORRER ESTA VALIDAÇÃO APÓS A CRIAÇÃO DESTA TABELA 
SELECT *
FROM 
    (
    SELECT DISTINCT CHAVE,flag_perimetro,SUM_MSALDO_FINAL_CT
    FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX1
    )F1
LEFT JOIN 
    (
    SELECT CHAVE,flag_perimetro,SUM(AMOUNT) AS AMOUNT_TESTE
    FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX3
    GROUP BY 1,2
    )F2 ON F1.CHAVE=F2.CHAVE AND F1.flag_perimetro=F2.flag_perimetro
WHERE ROUND(AMOUNT_TESTE,2)<>ROUND(SUM_MSALDO_FINAL_CT,2) OR (AMOUNT_TESTE IS NULL AND SUM_MSALDO_FINAL_CT IS NOT NULL)  OR (AMOUNT_TESTE IS NOT NULL AND SUM_MSALDO_FINAL_CT IS NULL)
;

	-- VALIDAÇÃO #3 - Linhas adicionadas referentes apenas a bens  
SELECT DISTINCT flag_bem
FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX3
WHERE CHAVE IN 
    (
    SELECT DISTINCT CHAVE 
    FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX3
    WHERE FLAG_LINHAS='LINHA ADI'
    )
AND FLAG_LINHAS<>'LINHA ADI'
AND flag_perimetro<>'Nao Aplicavel'
;

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 3A. Criação da tabela final 
--------------------------------------------------------------------------------------------------------------------------------------------------
 
 	-- JUN25: Inserted 8.324.120 row(s) 
 
DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.EMI_FINAN_AUX4 PURGE;
CREATE TABLE BU_CAPTOOLS_WORK.EMI_FINAN_AUX4 AS

SELECT UNI.*
	,L1.SCP1_EMSS AS SCP1_EMSS_CLI,L1.SCP2_EMSS AS SCP2_EMSS_CLI,L1.SCP3_EMSS AS SCP3_EMSS_CLI
	,L1.ORIGEM_SCP1_EMSS AS ORIGEM_SCP1_EMSS_CLI,L1.ORIGEM_SCP2_EMSS AS ORIGEM_SCP2_EMSS_CLI,L1.ORIGEM_SCP3_EMSS AS ORIGEM_SCP3_EMSS_CLI
	,L1.DIVIDA_TOTAL,L1.CAPITAL_PROPRIO
	,L2.SCP1_EMSS AS SCP1_EMSS_MOB,L2.SCP2_EMSS AS SCP2_EMSS_MOB,L2.SCP3_EMSS AS SCP3_EMSS_MOB
	,L2.ORIGEM_SCP1_EMSS AS ORIGEM_SCP1_EMSS_MOB,L2.ORIGEM_SCP2_EMSS AS ORIGEM_SCP2_EMSS_MOB,L2.ORIGEM_SCP3_EMSS AS ORIGEM_SCP3_EMSS_MOB
	,L3.SCP1_EMSS AS SCP1_EMSS_IMO,L3.SCP2_EMSS AS SCP2_EMSS_IMO,L3.SCP3_EMSS AS SCP3_EMSS_IMO
	,L3.ORIGEM_SCP1_EMSS AS ORIGEM_SCP1_EMSS_IMO,L3.ORIGEM_SCP2_EMSS AS ORIGEM_SCP2_EMSS_IMO,L3.ORIGEM_SCP3_EMSS AS ORIGEM_SCP3_EMSS_IMO
	-- Flag para identificar se o bem deve calcular emissão financiada (ou seja 1) ou não (ou seja 0) // Se o contrato tiver todos os bens com 0 então a emissão deve ser calculada ao nível do cliente 
	,CASE 
		WHEN TRIM(UNI.PURPOSE_CODE) IN ('Habitacao','CRE_FC','CRE_OUTRO','CRE') AND UNI.FLAG_BEM='MUG_IMO' AND L3.CHAVE_IMO IS NULL THEN 0 
		WHEN TRIM(UNI.PURPOSE_CODE) IN ('Habitacao','CRE_FC','CRE_OUTRO','CRE') AND UNI.FLAG_BEM='MUG_IMO' AND TRIM(L3.ORIGEM_SCP1_EMSS)='Nao Aplicavel' AND TRIM(L3.ORIGEM_SCP2_EMSS)='Nao Aplicavel' AND TRIM(L3.ORIGEM_SCP3_EMSS)='Nao Aplicavel' THEN 0
		WHEN TRIM(UNI.PURPOSE_CODE) IN ('Habitacao','CRE_FC','CRE_OUTRO','CRE') AND UNI.FLAG_BEM='MUG_IMO' THEN 1 
		WHEN TRIM(UNI.PURPOSE_CODE) NOT IN ('Habitacao','CRE_FC','CRE_OUTRO','CRE') AND UNI.FLAG_BEM='MUG_MOV' AND L2.CHAVE_MOB IS NULL THEN 0
		WHEN TRIM(UNI.PURPOSE_CODE) NOT IN ('Habitacao','CRE_FC','CRE_OUTRO','CRE') AND UNI.FLAG_BEM='MUG_MOV' AND TRIM(L2.ORIGEM_SCP1_EMSS)='Nao Aplicavel' AND TRIM(L2.ORIGEM_SCP2_EMSS)='Nao Aplicavel' AND TRIM(L2.ORIGEM_SCP3_EMSS)='Nao Aplicavel' THEN 0
		WHEN TRIM(UNI.PURPOSE_CODE) NOT IN ('Habitacao','CRE_FC','CRE_OUTRO','CRE') AND UNI.FLAG_BEM='MUG_MOV' THEN 1 
		ELSE 0
	END AS FLAG_AUX_METODO
FROM 
    (
	SELECT *
	FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX3
	)UNI
LEFT JOIN 
	(
	SELECT ZCLIENTE,SCP1_EMSS,SCP2_EMSS,SCP3_EMSS,ORIGEM_SCP1_EMSS,ORIGEM_SCP2_EMSS,ORIGEM_SCP3_EMSS,DIVIDA_TOTAL,CAPITAL_PROPRIO
	FROM bu_esg_work.modesg_out_empr_info_nfin
	WHERE ref_date='${ref_date}'
	)L1 ON UNI.ZCLIENTE=L1.ZCLIENTE
LEFT JOIN 
	(
	SELECT CONCAT(CEMPBEM,CKBALBEM,ckctabem,ckrefbem) AS CHAVE_MOB,SCP1_EMSS,SCP2_EMSS,SCP3_EMSS,ORIGEM_SCP1_EMSS,ORIGEM_SCP2_EMSS,ORIGEM_SCP3_EMSS
	FROM BU_ESG_WORK.modesg_out_emss_vcls 
	WHERE ref_date='${ref_date}'
	)L2 ON UNI.CHAVE_BEM=L2.CHAVE_MOB
LEFT JOIN 
	(
	SELECT CONCAT(CEMPBEM,CKBALBEM,ckctabem,ckrefbem) AS CHAVE_IMO,SCP1_EMSS,SCP2_EMSS,SCP3_EMSS,ORIGEM_SCP1_EMSS,ORIGEM_SCP2_EMSS,ORIGEM_SCP3_EMSS
	FROM BU_ESG_WORK.modesg_out_bens_imoveis 
	WHERE ref_date='${ref_date}'
	)L3 ON UNI.CHAVE_BEM=L3.CHAVE_IMO
;
--------------------------------------------------------------------------------------------------------------------------------------------------
-- 3B. Criação da tabela final 
--------------------------------------------------------------------------------------------------------------------------------------------------

 	-- JUN25: Inserted 8.324.120 row(s)

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.EMI_FINAN PURGE;
CREATE TABLE BU_CAPTOOLS_WORK.EMI_FINAN AS

SELECT BASE.*
	,L1.FLAG_AUX_METODO_CTO -- Se for 1 então a emissão financiada é calculada pelo bem, caso contrário, pelo cliente 
	,L2.PRECO_AQUISICAO_CTO
	,L3.fatr_indv_PME
	,CASE
		WHEN FLAG_PERIMETRO='Nao Aplicavel' THEN NULL
		WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_IMO) IN ('RE_DQS3_2A','RE_DQS4_2B','RE_DQS5_3') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN CAST(BASE.SCP1_EMSS_IMO AS DECIMAL(38,6))*(CAST(-BASE.SUM_MSALDO_FINAL_CT AS DECIMAL(38,6))/CAST(L2.PRECO_AQUISICAO_CTO AS DECIMAL(38,6)))
		WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_IMO) IN ('Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
		WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_MOB) IN ('MVL_DQS3_2B','MVL_DQS4_3A','MVL_DQS4_3B','MVL_DQS5_3B') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN CAST(BASE.SCP1_EMSS_MOB/1000 AS DECIMAL(38,6))*(CAST(-BASE.SUM_MSALDO_FINAL_CT AS DECIMAL(38,6))/CAST(L2.PRECO_AQUISICAO_CTO AS DECIMAL(38,6)))
		WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_MOB) IN ('Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL
		WHEN BASE.FLAG_AUX_METODO=0 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
		WHEN BASE.FLAG_LINHAS='LINHA ADI' AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
		WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_CLI) IN ('BCL_DQS1_SCIB','BCL_DQS2_SCIB','BCL_DQS3_SCIB','BCL_DQS4_SCIB','PF_DQS1_SCIB','PF_DQS2_SCIB','PF_DQS3_SCIB','PF_DQS4_SCIB') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP1_EMSS_CLI AS DECIMAL(38,6))*(CAST(-BASE.AMOUNT/1000000 AS DECIMAL(38,6))/(CAST(BASE.DIVIDA_TOTAL AS DECIMAL(38,6))+CAST(NVL(BASE.CAPITAL_PROPRIO,0) AS DECIMAL(38,6))))
		WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_CLI) IN ('BCL_DQS4_3A') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(L3.FATR_INDV_PME/1000000 AS DECIMAL(38,6))*CAST(BASE.SCP1_EMSS_CLI AS DECIMAL(38,6))*(CAST(-BASE.AMOUNT AS DECIMAL(38,6))/(CAST(BASE.CLIENT_OWN_FUNDS AS DECIMAL(38,6))+CAST(BASE.CLIENT_DEBT AS DECIMAL(38,6))))
		WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_CLI) IN ('BCL_DQS5_3B','PF_DQS5_3B') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP1_EMSS_CLI AS DECIMAL(38,6))*CAST(-BASE.AMOUNT/1000000 AS DECIMAL(38,6))  
		WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_CLI) IN ('PF_DQS1_1A') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP1_EMSS_CLI AS DECIMAL(38,6)) 
		WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_CLI) IN ('Nao Aplicavel','MISS') AND L1.FLAG_AUX_METODO_CTO=0 THEN NULL  	
	END AS SCP1_EMSS_FNCD_AUX
	,CAST
		(
			(
			CASE WHEN 
				(
				CASE
					WHEN FLAG_PERIMETRO='Nao Aplicavel' THEN NULL
					WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_IMO) IN ('RE_DQS3_2A','RE_DQS4_2B','RE_DQS5_3') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN CAST(BASE.SCP1_EMSS_IMO AS DECIMAL(38,6))*(CAST(-BASE.SUM_MSALDO_FINAL_CT AS DECIMAL(38,6))/CAST(L2.PRECO_AQUISICAO_CTO AS DECIMAL(38,6)))
					WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_IMO) IN ('Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
					WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_MOB) IN ('MVL_DQS3_2B','MVL_DQS4_3A','MVL_DQS4_3B','MVL_DQS5_3B') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN CAST(BASE.SCP1_EMSS_MOB/1000 AS DECIMAL(38,6))*(CAST(-BASE.SUM_MSALDO_FINAL_CT AS DECIMAL(38,6))/CAST(L2.PRECO_AQUISICAO_CTO AS DECIMAL(38,6)))
					WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_MOB) IN ('Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL
					WHEN BASE.FLAG_AUX_METODO=0 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
					WHEN BASE.FLAG_LINHAS='LINHA ADI' AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
					WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_CLI) IN ('BCL_DQS1_SCIB','BCL_DQS2_SCIB','BCL_DQS3_SCIB','BCL_DQS4_SCIB','PF_DQS1_SCIB','PF_DQS2_SCIB','PF_DQS3_SCIB','PF_DQS4_SCIB') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP1_EMSS_CLI AS DECIMAL(38,6))*(CAST(-BASE.AMOUNT/1000000 AS DECIMAL(38,6))/(CAST(BASE.DIVIDA_TOTAL AS DECIMAL(38,6))+CAST(NVL(BASE.CAPITAL_PROPRIO,0) AS DECIMAL(38,6))))
					WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_CLI) IN ('BCL_DQS4_3A') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(L3.FATR_INDV_PME/1000000 AS DECIMAL(38,6))*CAST(BASE.SCP1_EMSS_CLI AS DECIMAL(38,6))*(CAST(-BASE.AMOUNT AS DECIMAL(38,6))/(CAST(BASE.CLIENT_OWN_FUNDS AS DECIMAL(38,6))+CAST(BASE.CLIENT_DEBT AS DECIMAL(38,6))))
					WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_CLI) IN ('BCL_DQS5_3B','PF_DQS5_3B') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP1_EMSS_CLI AS DECIMAL(38,6))*CAST(-BASE.AMOUNT/1000000 AS DECIMAL(38,6))  
					WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_CLI) IN ('PF_DQS1_1A') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP1_EMSS_CLI AS DECIMAL(38,6)) 
					WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_CLI) IN ('Nao Aplicavel','MISS') AND L1.FLAG_AUX_METODO_CTO=0 THEN NULL 
				END
				)<0 THEN 0 
			ELSE 
				(
				CASE
					WHEN FLAG_PERIMETRO='Nao Aplicavel' THEN NULL
					WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_IMO) IN ('RE_DQS3_2A','RE_DQS4_2B','RE_DQS5_3') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN CAST(BASE.SCP1_EMSS_IMO AS DECIMAL(38,6))*(CAST(-BASE.SUM_MSALDO_FINAL_CT AS DECIMAL(38,6))/CAST(L2.PRECO_AQUISICAO_CTO AS DECIMAL(38,6)))
					WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_IMO) IN ('Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
					WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_MOB) IN ('MVL_DQS3_2B','MVL_DQS4_3A','MVL_DQS4_3B','MVL_DQS5_3B') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN CAST(BASE.SCP1_EMSS_MOB/1000 AS DECIMAL(38,6))*(CAST(-BASE.SUM_MSALDO_FINAL_CT AS DECIMAL(38,6))/CAST(L2.PRECO_AQUISICAO_CTO AS DECIMAL(38,6)))
					WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_MOB) IN ('Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL
					WHEN BASE.FLAG_AUX_METODO=0 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
					WHEN BASE.FLAG_LINHAS='LINHA ADI' AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
					WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_CLI) IN ('BCL_DQS1_SCIB','BCL_DQS2_SCIB','BCL_DQS3_SCIB','BCL_DQS4_SCIB','PF_DQS1_SCIB','PF_DQS2_SCIB','PF_DQS3_SCIB','PF_DQS4_SCIB') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP1_EMSS_CLI AS DECIMAL(38,6))*(CAST(-BASE.AMOUNT/1000000 AS DECIMAL(38,6))/(CAST(BASE.DIVIDA_TOTAL AS DECIMAL(38,6))+CAST(NVL(BASE.CAPITAL_PROPRIO,0) AS DECIMAL(38,6))))
					WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_CLI) IN ('BCL_DQS4_3A') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(L3.FATR_INDV_PME/1000000 AS DECIMAL(38,6))*CAST(BASE.SCP1_EMSS_CLI AS DECIMAL(38,6))*(CAST(-BASE.AMOUNT AS DECIMAL(38,6))/(CAST(BASE.CLIENT_OWN_FUNDS AS DECIMAL(38,6))+CAST(BASE.CLIENT_DEBT AS DECIMAL(38,6))))
					WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_CLI) IN ('BCL_DQS5_3B','PF_DQS5_3B') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP1_EMSS_CLI AS DECIMAL(38,6))*CAST(-BASE.AMOUNT/1000000 AS DECIMAL(38,6))  
					WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_CLI) IN ('PF_DQS1_1A') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP1_EMSS_CLI AS DECIMAL(38,6)) 
					WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_CLI) IN ('Nao Aplicavel','MISS') AND L1.FLAG_AUX_METODO_CTO=0 THEN NULL 
				END
				)
			END
			)
		AS DECIMAL(38,6)
		)
	AS SCP1_EMSS_FNCD
	,CASE
		WHEN FLAG_PERIMETRO='Nao Aplicavel' THEN 'Nao Aplicavel'
		WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_IMO) IN ('RE_DQS3_2A','RE_DQS4_2B','RE_DQS5_3','Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN TRIM(BASE.ORIGEM_SCP1_EMSS_IMO)
		WHEN TRIM(BASE.ORIGEM_SCP1_EMSS_MOB) IN ('MVL_DQS3_2B','MVL_DQS4_3A','MVL_DQS4_3B','MVL_DQS5_3B','Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN TRIM(BASE.ORIGEM_SCP1_EMSS_MOB)
		WHEN BASE.FLAG_AUX_METODO=0 AND L1.FLAG_AUX_METODO_CTO=1 THEN 'Nao Aplicavel'
		WHEN BASE.FLAG_LINHAS='LINHA ADI' AND L1.FLAG_AUX_METODO_CTO=1 THEN 'Nao Aplicavel' 
		WHEN L1.FLAG_AUX_METODO_CTO=0 AND BASE.ORIGEM_SCP1_EMSS_CLI IS NULL THEN 'MISS' 
		WHEN L1.FLAG_AUX_METODO_CTO=0 THEN TRIM(BASE.ORIGEM_SCP1_EMSS_CLI)
	END AS ORIGEM_SCP1_EMSS
	,CASE
		WHEN FLAG_PERIMETRO='Nao Aplicavel' THEN NULL
		WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_IMO) IN ('RE_DQS3_2A','RE_DQS4_2B','RE_DQS5_3') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN CAST(BASE.SCP2_EMSS_IMO AS DECIMAL(38,6))*(CAST(-BASE.SUM_MSALDO_FINAL_CT AS DECIMAL(38,6))/CAST(L2.PRECO_AQUISICAO_CTO AS DECIMAL(38,6)))
		WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_IMO) IN ('Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
		WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_MOB) IN ('MVL_DQS3_2B','MVL_DQS4_3A','MVL_DQS4_3B','MVL_DQS5_3B') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN CAST(BASE.SCP2_EMSS_MOB/1000 AS DECIMAL(38,6))*(CAST(-BASE.SUM_MSALDO_FINAL_CT AS DECIMAL(38,6))/CAST(L2.PRECO_AQUISICAO_CTO AS DECIMAL(38,6)))
		WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_MOB) IN ('Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL
		WHEN BASE.FLAG_AUX_METODO=0 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
		WHEN BASE.FLAG_LINHAS='LINHA ADI' AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
		WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_CLI) IN ('BCL_DQS1_SCIB','BCL_DQS2_SCIB','BCL_DQS3_SCIB','BCL_DQS4_SCIB','PF_DQS1_SCIB','PF_DQS2_SCIB','PF_DQS3_SCIB','PF_DQS4_SCIB') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP2_EMSS_CLI AS DECIMAL(38,6))*(CAST(-BASE.AMOUNT/1000000 AS DECIMAL(38,6))/(CAST(BASE.DIVIDA_TOTAL AS DECIMAL(38,6))+CAST(NVL(BASE.CAPITAL_PROPRIO,0) AS DECIMAL(38,6))))
		WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_CLI) IN ('BCL_DQS4_3A') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(L3.FATR_INDV_PME/1000000 AS DECIMAL(38,6))*CAST(BASE.SCP2_EMSS_CLI AS DECIMAL(38,6))*(CAST(-BASE.AMOUNT AS DECIMAL(38,6))/(CAST(BASE.CLIENT_OWN_FUNDS AS DECIMAL(38,6))+CAST(BASE.CLIENT_DEBT AS DECIMAL(38,6))))
		WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_CLI) IN ('BCL_DQS5_3B','PF_DQS5_3B') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP2_EMSS_CLI AS DECIMAL(38,6))*CAST(-BASE.AMOUNT/1000000 AS DECIMAL(38,6))  
		WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_CLI) IN ('PF_DQS1_1A') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP2_EMSS_CLI AS DECIMAL(38,6)) 
		WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_CLI) IN ('Nao Aplicavel','MISS') AND L1.FLAG_AUX_METODO_CTO=0 THEN NULL  
	END AS SCP2_EMSS_FNCD_AUX
	,CAST
		(
			(
			CASE WHEN 
				(
				CASE
					WHEN FLAG_PERIMETRO='Nao Aplicavel' THEN NULL
					WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_IMO) IN ('RE_DQS3_2A','RE_DQS4_2B','RE_DQS5_3') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN CAST(BASE.SCP2_EMSS_IMO AS DECIMAL(38,6))*(CAST(-BASE.SUM_MSALDO_FINAL_CT AS DECIMAL(38,6))/CAST(L2.PRECO_AQUISICAO_CTO AS DECIMAL(38,6)))
					WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_IMO) IN ('Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
					WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_MOB) IN ('MVL_DQS3_2B','MVL_DQS4_3A','MVL_DQS4_3B','MVL_DQS5_3B') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN CAST(BASE.SCP2_EMSS_MOB/1000 AS DECIMAL(38,6))*(CAST(-BASE.SUM_MSALDO_FINAL_CT AS DECIMAL(38,6))/CAST(L2.PRECO_AQUISICAO_CTO AS DECIMAL(38,6)))
					WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_MOB) IN ('Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL
					WHEN BASE.FLAG_AUX_METODO=0 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
					WHEN BASE.FLAG_LINHAS='LINHA ADI' AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
					WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_CLI) IN ('BCL_DQS1_SCIB','BCL_DQS2_SCIB','BCL_DQS3_SCIB','BCL_DQS4_SCIB','PF_DQS1_SCIB','PF_DQS2_SCIB','PF_DQS3_SCIB','PF_DQS4_SCIB') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP2_EMSS_CLI AS DECIMAL(38,6))*(CAST(-BASE.AMOUNT/1000000 AS DECIMAL(38,6))/(CAST(BASE.DIVIDA_TOTAL AS DECIMAL(38,6))+CAST(NVL(BASE.CAPITAL_PROPRIO,0) AS DECIMAL(38,6))))
					WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_CLI) IN ('BCL_DQS4_3A') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(L3.FATR_INDV_PME/1000000 AS DECIMAL(38,6))*CAST(BASE.SCP2_EMSS_CLI AS DECIMAL(38,6))*(CAST(-BASE.AMOUNT AS DECIMAL(38,6))/(CAST(BASE.CLIENT_OWN_FUNDS AS DECIMAL(38,6))+CAST(BASE.CLIENT_DEBT AS DECIMAL(38,6))))
					WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_CLI) IN ('BCL_DQS5_3B','PF_DQS5_3B') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP2_EMSS_CLI AS DECIMAL(38,6))*CAST(-BASE.AMOUNT/1000000 AS DECIMAL(38,6))  
					WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_CLI) IN ('PF_DQS1_1A') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP2_EMSS_CLI AS DECIMAL(38,6)) 
					WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_CLI) IN ('Nao Aplicavel','MISS') AND L1.FLAG_AUX_METODO_CTO=0 THEN NULL 
				END
				)<0 THEN 0 
			ELSE 
				(
				CASE
					WHEN FLAG_PERIMETRO='Nao Aplicavel' THEN NULL
					WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_IMO) IN ('RE_DQS3_2A','RE_DQS4_2B','RE_DQS5_3') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN CAST(BASE.SCP2_EMSS_IMO AS DECIMAL(38,6))*(CAST(-BASE.SUM_MSALDO_FINAL_CT AS DECIMAL(38,6))/CAST(L2.PRECO_AQUISICAO_CTO AS DECIMAL(38,6)))
					WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_IMO) IN ('Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
					WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_MOB) IN ('MVL_DQS3_2B','MVL_DQS4_3A','MVL_DQS4_3B','MVL_DQS5_3B') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN CAST(BASE.SCP2_EMSS_MOB/1000 AS DECIMAL(38,6))*(CAST(-BASE.SUM_MSALDO_FINAL_CT AS DECIMAL(38,6))/CAST(L2.PRECO_AQUISICAO_CTO AS DECIMAL(38,6)))
					WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_MOB) IN ('Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL
					WHEN BASE.FLAG_AUX_METODO=0 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
					WHEN BASE.FLAG_LINHAS='LINHA ADI' AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
					WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_CLI) IN ('BCL_DQS1_SCIB','BCL_DQS2_SCIB','BCL_DQS3_SCIB','BCL_DQS4_SCIB','PF_DQS1_SCIB','PF_DQS2_SCIB','PF_DQS3_SCIB','PF_DQS4_SCIB') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP2_EMSS_CLI AS DECIMAL(38,6))*(CAST(-BASE.AMOUNT/1000000 AS DECIMAL(38,6))/(CAST(BASE.DIVIDA_TOTAL AS DECIMAL(38,6))+CAST(NVL(BASE.CAPITAL_PROPRIO,0) AS DECIMAL(38,6))))
					WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_CLI) IN ('BCL_DQS4_3A') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(L3.FATR_INDV_PME/1000000 AS DECIMAL(38,6))*CAST(BASE.SCP2_EMSS_CLI AS DECIMAL(38,6))*(CAST(-BASE.AMOUNT AS DECIMAL(38,6))/(CAST(BASE.CLIENT_OWN_FUNDS AS DECIMAL(38,6))+CAST(BASE.CLIENT_DEBT AS DECIMAL(38,6))))
					WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_CLI) IN ('BCL_DQS5_3B','PF_DQS5_3B') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP2_EMSS_CLI AS DECIMAL(38,6))*CAST(-BASE.AMOUNT/1000000 AS DECIMAL(38,6))  
					WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_CLI) IN ('PF_DQS1_1A') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP2_EMSS_CLI AS DECIMAL(38,6)) 
					WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_CLI) IN ('Nao Aplicavel','MISS') AND L1.FLAG_AUX_METODO_CTO=0 THEN NULL 
				END
				)
			END
			)
		AS DECIMAL(38,6)
		)
	AS SCP2_EMSS_FNCD
	,CASE
		WHEN FLAG_PERIMETRO='Nao Aplicavel' THEN 'Nao Aplicavel'
		WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_IMO) IN ('RE_DQS3_2A','RE_DQS4_2B','RE_DQS5_3','Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN TRIM(BASE.ORIGEM_SCP2_EMSS_IMO)
		WHEN TRIM(BASE.ORIGEM_SCP2_EMSS_MOB) IN ('MVL_DQS3_2B','MVL_DQS4_3A','MVL_DQS4_3B','MVL_DQS5_3B','Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN TRIM(BASE.ORIGEM_SCP2_EMSS_MOB)
		WHEN BASE.FLAG_AUX_METODO=0 AND L1.FLAG_AUX_METODO_CTO=1 THEN 'Nao Aplicavel'
		WHEN BASE.FLAG_LINHAS='LINHA ADI' AND L1.FLAG_AUX_METODO_CTO=1 THEN 'Nao Aplicavel' 
		WHEN L1.FLAG_AUX_METODO_CTO=0 AND BASE.ORIGEM_SCP2_EMSS_CLI IS NULL THEN 'MISS' 
		WHEN L1.FLAG_AUX_METODO_CTO=0 THEN TRIM(BASE.ORIGEM_SCP2_EMSS_CLI)
	END AS ORIGEM_SCP2_EMSS
	,CASE
		WHEN FLAG_PERIMETRO='Nao Aplicavel' THEN NULL
		WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_IMO) IN ('RE_DQS3_2A','RE_DQS4_2B','RE_DQS5_3') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN CAST(BASE.SCP3_EMSS_IMO AS DECIMAL(38,6))*(CAST(-BASE.SUM_MSALDO_FINAL_CT AS DECIMAL(38,6))/CAST(L2.PRECO_AQUISICAO_CTO AS DECIMAL(38,6)))
		WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_IMO) IN ('Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
		WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_MOB) IN ('MVL_DQS3_2B','MVL_DQS4_3A','MVL_DQS4_3B','MVL_DQS5_3B') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN CAST(BASE.SCP3_EMSS_MOB/1000 AS DECIMAL(38,6))*(CAST(-BASE.SUM_MSALDO_FINAL_CT AS DECIMAL(38,6))/CAST(L2.PRECO_AQUISICAO_CTO AS DECIMAL(38,6)))
		WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_MOB) IN ('Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL
		WHEN BASE.FLAG_AUX_METODO=0 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
		WHEN BASE.FLAG_LINHAS='LINHA ADI' AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
		WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_CLI) IN ('BCL_DQS1_SCIB','BCL_DQS2_SCIB','BCL_DQS3_SCIB','BCL_DQS4_SCIB','PF_DQS1_SCIB','PF_DQS2_SCIB','PF_DQS3_SCIB','PF_DQS4_SCIB') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP3_EMSS_CLI AS DECIMAL(38,6))*(CAST(-BASE.AMOUNT/1000000 AS DECIMAL(38,6))/(CAST(BASE.DIVIDA_TOTAL AS DECIMAL(38,6))+CAST(NVL(BASE.CAPITAL_PROPRIO,0) AS DECIMAL(38,6))))
		WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_CLI) IN ('BCL_DQS4_3A') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(L3.FATR_INDV_PME/1000000 AS DECIMAL(38,6))*CAST(BASE.SCP3_EMSS_CLI AS DECIMAL(38,6))*(CAST(-BASE.AMOUNT AS DECIMAL(38,6))/(CAST(BASE.CLIENT_OWN_FUNDS AS DECIMAL(38,6))+CAST(BASE.CLIENT_DEBT AS DECIMAL(38,6))))
		WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_CLI) IN ('BCL_DQS5_3B','PF_DQS5_3B') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP3_EMSS_CLI AS DECIMAL(38,6))*CAST(-BASE.AMOUNT/1000000 AS DECIMAL(38,6))  
		WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_CLI) IN ('PF_DQS1_1A') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP3_EMSS_CLI AS DECIMAL(38,6)) 
		WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_CLI) IN ('Nao Aplicavel','MISS') AND L1.FLAG_AUX_METODO_CTO=0 THEN NULL  
	END AS SCP3_EMSS_FNCD_AUX
	,CAST
		(
			(
			CASE WHEN 
				(
				CASE
					WHEN FLAG_PERIMETRO='Nao Aplicavel' THEN NULL
					WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_IMO) IN ('RE_DQS3_2A','RE_DQS4_2B','RE_DQS5_3') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN CAST(BASE.SCP3_EMSS_IMO AS DECIMAL(38,6))*(CAST(-BASE.SUM_MSALDO_FINAL_CT AS DECIMAL(38,6))/CAST(L2.PRECO_AQUISICAO_CTO AS DECIMAL(38,6)))
					WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_IMO) IN ('Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
					WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_MOB) IN ('MVL_DQS3_2B','MVL_DQS4_3A','MVL_DQS4_3B','MVL_DQS5_3B') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN CAST(BASE.SCP3_EMSS_MOB/1000 AS DECIMAL(38,6))*(CAST(-BASE.SUM_MSALDO_FINAL_CT AS DECIMAL(38,6))/CAST(L2.PRECO_AQUISICAO_CTO AS DECIMAL(38,6)))
					WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_MOB) IN ('Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL
					WHEN BASE.FLAG_AUX_METODO=0 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
					WHEN BASE.FLAG_LINHAS='LINHA ADI' AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
					WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_CLI) IN ('BCL_DQS1_SCIB','BCL_DQS2_SCIB','BCL_DQS3_SCIB','BCL_DQS4_SCIB','PF_DQS1_SCIB','PF_DQS2_SCIB','PF_DQS3_SCIB','PF_DQS4_SCIB') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP3_EMSS_CLI AS DECIMAL(38,6))*(CAST(-BASE.AMOUNT/1000000 AS DECIMAL(38,6))/(CAST(BASE.DIVIDA_TOTAL AS DECIMAL(38,6))+CAST(NVL(BASE.CAPITAL_PROPRIO,0) AS DECIMAL(38,6))))
					WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_CLI) IN ('BCL_DQS4_3A') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(L3.FATR_INDV_PME/1000000 AS DECIMAL(38,6))*CAST(BASE.SCP3_EMSS_CLI AS DECIMAL(38,6))*(CAST(-BASE.AMOUNT AS DECIMAL(38,6))/(CAST(BASE.CLIENT_OWN_FUNDS AS DECIMAL(38,6))+CAST(BASE.CLIENT_DEBT AS DECIMAL(38,6))))
					WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_CLI) IN ('BCL_DQS5_3B','PF_DQS5_3B') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP3_EMSS_CLI AS DECIMAL(38,6))*CAST(-BASE.AMOUNT/1000000 AS DECIMAL(38,6))  
					WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_CLI) IN ('PF_DQS1_1A') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP3_EMSS_CLI AS DECIMAL(38,6)) 
					WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_CLI) IN ('Nao Aplicavel','MISS') AND L1.FLAG_AUX_METODO_CTO=0 THEN NULL 
				END
				)<0 THEN 0 
			ELSE 
				(
				CASE
					WHEN FLAG_PERIMETRO='Nao Aplicavel' THEN NULL
					WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_IMO) IN ('RE_DQS3_2A','RE_DQS4_2B','RE_DQS5_3') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN CAST(BASE.SCP3_EMSS_IMO AS DECIMAL(38,6))*(CAST(-BASE.SUM_MSALDO_FINAL_CT AS DECIMAL(38,6))/CAST(L2.PRECO_AQUISICAO_CTO AS DECIMAL(38,6)))
					WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_IMO) IN ('Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
					WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_MOB) IN ('MVL_DQS3_2B','MVL_DQS4_3A','MVL_DQS4_3B','MVL_DQS5_3B') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN CAST(BASE.SCP3_EMSS_MOB/1000 AS DECIMAL(38,6))*(CAST(-BASE.SUM_MSALDO_FINAL_CT AS DECIMAL(38,6))/CAST(L2.PRECO_AQUISICAO_CTO AS DECIMAL(38,6)))
					WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_MOB) IN ('Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL
					WHEN BASE.FLAG_AUX_METODO=0 AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
					WHEN BASE.FLAG_LINHAS='LINHA ADI' AND L1.FLAG_AUX_METODO_CTO=1 THEN NULL 
					WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_CLI) IN ('BCL_DQS1_SCIB','BCL_DQS2_SCIB','BCL_DQS3_SCIB','BCL_DQS4_SCIB','PF_DQS1_SCIB','PF_DQS2_SCIB','PF_DQS3_SCIB','PF_DQS4_SCIB') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP3_EMSS_CLI AS DECIMAL(38,6))*(CAST(-BASE.AMOUNT/1000000 AS DECIMAL(38,6))/(CAST(BASE.DIVIDA_TOTAL AS DECIMAL(38,6))+CAST(NVL(BASE.CAPITAL_PROPRIO,0) AS DECIMAL(38,6))))
					WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_CLI) IN ('BCL_DQS4_3A') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(L3.FATR_INDV_PME/1000000 AS DECIMAL(38,6))*CAST(BASE.SCP3_EMSS_CLI AS DECIMAL(38,6))*(CAST(-BASE.AMOUNT AS DECIMAL(38,6))/(CAST(BASE.CLIENT_OWN_FUNDS AS DECIMAL(38,6))+CAST(BASE.CLIENT_DEBT AS DECIMAL(38,6))))
					WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_CLI) IN ('BCL_DQS5_3B','PF_DQS5_3B') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP3_EMSS_CLI AS DECIMAL(38,6))*CAST(-BASE.AMOUNT/1000000 AS DECIMAL(38,6))  
					WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_CLI) IN ('PF_DQS1_1A') AND L1.FLAG_AUX_METODO_CTO=0 THEN CAST(BASE.SCP3_EMSS_CLI AS DECIMAL(38,6)) 
					WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_CLI) IN ('Nao Aplicavel','MISS') AND L1.FLAG_AUX_METODO_CTO=0 THEN NULL 
				END
				)
			END
			)
		AS DECIMAL(38,6)
		)
	AS SCP3_EMSS_FNCD
	,CASE
		WHEN FLAG_PERIMETRO='Nao Aplicavel' THEN 'Nao Aplicavel'
		WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_IMO) IN ('RE_DQS3_2A','RE_DQS4_2B','RE_DQS5_3','Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN TRIM(BASE.ORIGEM_SCP3_EMSS_IMO)
		WHEN TRIM(BASE.ORIGEM_SCP3_EMSS_MOB) IN ('MVL_DQS3_2B','MVL_DQS4_3A','MVL_DQS4_3B','MVL_DQS5_3B','Nao Aplicavel','MISS') AND BASE.FLAG_AUX_METODO=1 AND L1.FLAG_AUX_METODO_CTO=1 THEN TRIM(BASE.ORIGEM_SCP3_EMSS_MOB)
		WHEN BASE.FLAG_AUX_METODO=0 AND L1.FLAG_AUX_METODO_CTO=1 THEN 'Nao Aplicavel'
		WHEN BASE.FLAG_LINHAS='LINHA ADI' AND L1.FLAG_AUX_METODO_CTO=1 THEN 'Nao Aplicavel' 
		WHEN L1.FLAG_AUX_METODO_CTO=0 AND BASE.ORIGEM_SCP3_EMSS_CLI IS NULL THEN 'MISS' 
		WHEN L1.FLAG_AUX_METODO_CTO=0 THEN TRIM(BASE.ORIGEM_SCP3_EMSS_CLI)
	END AS ORIGEM_SCP3_EMSS

FROM 
	(
	SELECT *
	FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX4
	)BASE
LEFT JOIN 
	(
	SELECT CHAVE,MAX(FLAG_AUX_METODO) AS FLAG_AUX_METODO_CTO
	FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX4
	GROUP BY 1 
	)L1 ON BASE.CHAVE=L1.CHAVE
LEFT JOIN 
	(
	SELECT CHAVE,SUM(PRECO_AQUISICAO) AS PRECO_AQUISICAO_CTO
	FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX4
	WHERE FLAG_AUX_METODO=1
	GROUP BY 1 
	)L2 ON BASE.CHAVE=L2.CHAVE
LEFT JOIN 
    (
    SELECT ZCLIENTE AS ZCLIENTE_PME,SUM(fatr_indv) AS fatr_indv_PME 
    FROM cd_captools.ct063_univ_pme 
    WHERE REF_DATE = '${ref_date}' 
	GROUP BY 1
    )L3 ON BASE.ZCLIENTE=L3.ZCLIENTE_PME
;

	-- VALIDAÇÃO #4 - TEMA DOS TAMANHOS DAS CHAVES // EX: 89000020240000104001520250318653
SELECT 
    CASE 
        WHEN SCOPE_6 IS NULL AND SCOPE_20 IS NOT NULL THEN 'APENAS TAM 20 PREENCH'
        WHEN SCOPE_6 IS NOT NULL AND SCOPE_20 IS  NULL THEN 'APENAS TAM 6 PREECH'
        WHEN SCOPE_6 IS NULL AND SCOPE_20 IS  NULL THEN 'AMBOS NULL'
        WHEN SCOPE_6=0 AND SCOPE_20<>0 THEN 'AMBOS PREENC - TAM 20 CORRETO'
        WHEN SCOPE_6<>0 AND SCOPE_20=0 THEN 'AMBOS PREENC - TAM 6 CORRETO'
        WHEN ABS(SCOPE_6-SCOPE_20)<0.1 THEN 'OK'
        WHEN ABS(SCOPE_6-SCOPE_20)>0.1 THEN 'NOK'
    END AS FLAG,SUM(SCOPE_6) AS SUM_SCOPE_6,SUM(SCOPE_20) AS SUM_SCOPE_20
FROM 
    (
    SELECT *
        ,CAST((CASE WHEN SCP1_EMSS_FNCD_AUX_2<0 THEN 0 ELSE SCP1_EMSS_FNCD_AUX_2 END) AS DECIMAL(38,6)) AS SCOPE_20
        ,CAST((CASE WHEN SCP1_EMSS_FNCD_AUX<0 THEN 0 ELSE SCP1_EMSS_FNCD_AUX END) AS DECIMAL(38,6)) AS SCOPE_6
    FROM BU_CAPTOOLS_WORK.EMI_FINAN 
    )AUX
GROUP BY 1 

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 4A. VALIDAÇÕES TABELA DE TESTES 
--------------------------------------------------------------------------------------------------------------------------------------------------

	-- VALIDAÇÃO #4 - ORIGENS DISTINTAS PARA CADA CHAVE   
	
SELECT CHAVE,COUNT(DISTINCT substr(ORIGEM_SCP1_EMSS,1,3)) AS N 
FROM BU_CAPTOOLS_WORK.EMI_FINAN
WHERE ORIGEM_SCP1_EMSS NOT IN ('Nao Aplicavel','MISS')
GROUP BY 1 HAVING N>1
;

	-- VALIDAÇÃO #5 - Número de flags de perimetro    
	
SELECT CHAVE,COUNT(DISTINCT CHAVE_BEM) AS N 
FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX1
WHERE CHAVE IN 
    (
    SELECT CHAVE 
    FROM 
        (
        SELECT CHAVE,COUNT(DISTINCT FLAG_PERIMETRO) AS N 
        FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX1
        WHERE FLAG_PERIMETRO<>'Nao Aplicavel'
        GROUP BY 1 HAVING N>1
        )AUX
    )
    AND CHAVE_BEM IS NOT NULL
    AND SUM_MSALDO_FINAL_CT<>0
    AND FLAG_PERIMETRO<>'Nao Aplicavel'
GROUP BY 1 ORDER BY N DESC
;
	-- VALIDAÇÃO #6 - Saldos 
SELECT *
FROM
    (
    SELECT DISTINCT CHAVE,SUM_MSALDO_FINAL_CT
    FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX1
    WHERE FLAG_PERIMETRO='ST SGPS Cons;Individual Idcomb'
    )F1
LEFT JOIN 
    (
    SELECT DISTINCT CHAVE,SUM_MSALDO_FINAL_CT
    FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX1
    WHERE FLAG_PERIMETRO='ST SGPS Cons'
        AND CHAVE IN    
            (
            SELECT DISTINCT CHAVE
            FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX1
            WHERE FLAG_PERIMETRO='ST SGPS Cons;Individual Idcomb'
            )
    )F2 ON F1.CHAVE=F2.CHAVE
LEFT JOIN 
    (
    SELECT DISTINCT CHAVE,SUM_MSALDO_FINAL_CT
    FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX1
    WHERE FLAG_PERIMETRO='ST SGPS Cons'
        AND CHAVE IN    
            (
            SELECT DISTINCT CHAVE
            FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX1
            WHERE FLAG_PERIMETRO='Individual Idcomb'
            )
    )F3 ON F1.CHAVE=F3.CHAVE
    WHERE F2.SUM_MSALDO_FINAL_CT<>0 OR F3.SUM_MSALDO_FINAL_CT<>0 
	
--------------------------------------------------------------------------------------------------------------------------------------------------
-- 4B. VALIDAÇÕES TABELA DE TESTES VS TABELA IT
--------------------------------------------------------------------------------------------------------------------------------------------------

	-- VALIDAÇÃO #1 - CHAVE CONTRATO 	

SELECT 
    CASE
        WHEN CHAVE_IT IS NOT NULL AND CHAVE IS NOT NULL THEN 'UNIV COMUM'
        WHEN CHAVE_IT IS NULL AND CHAVE IS NOT NULL THEN 'EXCLUSIVO TESTE'
        WHEN CHAVE_IT IS NOT NULL AND CHAVE IS NULL THEN 'EXCLUSIVO IT'
    END AS FLAG_UNIV, count(*) AS NUM_REG
FROM 
    (
    SELECT DISTINCT concat(cempresa,cbalcao,cnumecta,zdeposit) AS CHAVE_IT
    FROM bu_esg_work.modesg_out_emss_fncd
    WHERE ref_date='2025-06-30'
    )F1
FULL JOIN 
    (
    SELECT DISTINCT CHAVE
    FROM BU_CAPTOOLS_WORK.EMI_FINAN
    )F2 ON F1.CHAVE_IT=F2.CHAVE
GROUP BY 1
;

	-- VALIDAÇÃO #2 - CHAVE CONTRATO + CHAVE BEM 
	
SELECT 
    CASE
        WHEN CHAVE_IT IS NOT NULL AND CHAVE_TESTE IS NOT NULL THEN 'UNIV COMUM'
        WHEN CHAVE_IT IS NULL AND CHAVE_TESTE IS NOT NULL THEN 'EXCLUSIVO TESTE'
        WHEN CHAVE_IT IS NOT NULL AND CHAVE_TESTE IS NULL THEN 'EXCLUSIVO IT'
    END AS FLAG_UNIV,COUNT(*) AS NUM_REG
FROM 
    (
    SELECT DISTINCT CONCAT(cempresa,cbalcao,cnumecta,zdeposit) AS CHAVE,TRIM(concat(cempresa,cbalcao,cnumecta,zdeposit,NVL(CEMPBEM,''),NVL(CKBALBEM,''),NVL(CKCTABEM,''),NVL(CKREFBEM,''))) AS CHAVE_IT
    FROM bu_esg_work.modesg_out_emss_fncd
    WHERE ref_date='2025-06-30'
    )F1
FULL JOIN 
    (
    SELECT DISTINCT TRIM(CONCAT(CHAVE,NVL(CHAVE_BEM,''))) AS CHAVE_TESTE
    FROM BU_CAPTOOLS_WORK.EMI_FINAN
    )F2 ON F1.CHAVE_IT=F2.CHAVE_TESTE
GROUP BY 1
;

	-- VALIDAÇÃO #3 - CHAVE CONTRATO + CHAVE BEM + PERIMETRO 
	
SELECT 
    CASE
        WHEN CHAVE_IT IS NOT NULL AND CHAVE_TESTE IS NOT NULL THEN 'UNIV COMUM'
        WHEN CHAVE_IT IS NULL AND CHAVE_TESTE IS NOT NULL THEN 'EXCLUSIVO TESTE'
        WHEN CHAVE_IT IS NOT NULL AND CHAVE_TESTE IS NULL THEN 'EXCLUSIVO IT'
    END AS FLAG_UNIV,COUNT(*) AS NUM_REG
FROM 
    (
    SELECT CONCAT(cempresa,cbalcao,cnumecta,zdeposit) AS CHAVE
        ,TRIM(concat(cempresa,cbalcao,cnumecta,zdeposit,NVL(CEMPBEM,''),NVL(CKBALBEM,''),NVL(CKCTABEM,''),NVL(CKREFBEM,''))) AS CHAVE_IT
        ,NOME_PERIMETRO
    FROM bu_esg_work.modesg_out_emss_fncd
    WHERE ref_date='2025-06-30'
    )F1
FULL JOIN 
    (
    SELECT TRIM(CONCAT(CHAVE,NVL(CHAVE_BEM,''))) AS CHAVE_TESTE
        ,CASE 
            WHEN FLAG_PERIMETRO='ST SGPS Cons;Individual Idcomb' THEN 'ST SGPS Cons; Individual Idcomb'
            ELSE FLAG_PERIMETRO
        END AS FLAG_PERIMETRO_MOD
    FROM BU_CAPTOOLS_WORK.EMI_FINAN
    )F2 ON F1.CHAVE_IT=F2.CHAVE_TESTE AND F1.NOME_PERIMETRO=F2.FLAG_PERIMETRO_MOD
GROUP BY 1
;

	-- VALIDAÇÃO #4 - SCOPE 1
SELECT 
    CASE 
        WHEN F1.ORIGEM_SCP1_EMSS=F2.ORIGEM_SCP1_EMSS THEN 'OK'
        ELSE 'NOK'
    END AS VALID_ORI_SCP1
    ,CASE
        WHEN F2.SCP1_EMSS_FNCD IS NOT NULL AND F1.SCP1_EMSS_FNCD IS NOT NULL AND ABS(F1.SCP1_EMSS_FNCD-F2.SCP1_EMSS_FNCD)<=0.1 THEN 'OK - AMBOS PREENCH'
        WHEN F2.SCP1_EMSS_FNCD IS NOT NULL AND F1.SCP1_EMSS_FNCD IS NOT NULL AND ABS(F1.SCP1_EMSS_FNCD-F2.SCP1_EMSS_FNCD)>0.1 THEN 'NOK - AMBOS PREENCH'
        WHEN F2.SCP1_EMSS_FNCD IS NULL AND F1.SCP1_EMSS_FNCD IS NULL THEN 'AMBOS A NULL'
        WHEN F2.SCP1_EMSS_FNCD IS NOT NULL AND F1.SCP1_EMSS_FNCD IS NULL THEN 'IT A NULL'
        WHEN F2.SCP1_EMSS_FNCD IS NULL AND F1.SCP1_EMSS_FNCD IS NOT NULL THEN 'TESTES A NULL'
    END AS VALID_SCP1,count(*)
FROM 
    (
    SELECT CONCAT(cempresa,cbalcao,cnumecta,zdeposit) AS CHAVE
        ,TRIM(concat(cempresa,cbalcao,cnumecta,zdeposit,NVL(CEMPBEM,''),NVL(CKBALBEM,''),NVL(CKCTABEM,''),NVL(CKREFBEM,''))) AS CHAVE_IT
        ,*
    FROM bu_esg_work.modesg_out_emss_fncd
    WHERE ref_date='2025-06-30'
    )F1
INNER JOIN 
    (
    SELECT TRIM(CONCAT(CHAVE,NVL(CHAVE_BEM,''))) AS CHAVE_TESTE
        ,CASE 
            WHEN FLAG_PERIMETRO='ST SGPS Cons;Individual Idcomb' THEN 'ST SGPS Cons; Individual Idcomb'
            ELSE FLAG_PERIMETRO
        END AS FLAG_PERIMETRO_MOD,*
    FROM BU_CAPTOOLS_WORK.EMI_FINAN
    )F2 ON F1.CHAVE_IT=F2.CHAVE_TESTE AND F1.NOME_PERIMETRO=F2.FLAG_PERIMETRO_MOD
GROUP BY 1,2
;
--VER EXEMPLOS
SELECT 
    CASE 
        WHEN F1.ORIGEM_SCP1_EMSS=F2.ORIGEM_SCP1_EMSS THEN 'OK'
        ELSE 'NOK'
    END AS VALID_ORI_SCP1
    ,CASE
        WHEN F2.SCP1_EMSS_FNCD IS NOT NULL AND F1.SCP1_EMSS_FNCD IS NOT NULL AND ABS(F1.SCP1_EMSS_FNCD-F2.SCP1_EMSS_FNCD)<=0.1 THEN 'OK - AMBOS PREENCH'
        WHEN F2.SCP1_EMSS_FNCD IS NOT NULL AND F1.SCP1_EMSS_FNCD IS NOT NULL AND ABS(F1.SCP1_EMSS_FNCD-F2.SCP1_EMSS_FNCD)>0.1 THEN 'NOK - AMBOS PREENCH'
        WHEN F2.SCP1_EMSS_FNCD IS NULL AND F1.SCP1_EMSS_FNCD IS NULL THEN 'AMBOS A NULL'
        WHEN F2.SCP1_EMSS_FNCD IS NOT NULL AND F1.SCP1_EMSS_FNCD IS NULL THEN 'IT A NULL'
        WHEN F2.SCP1_EMSS_FNCD IS NULL AND F1.SCP1_EMSS_FNCD IS NOT NULL THEN 'TESTES A NULL'
    END AS VALID_SCP1,*
FROM 
    (
    SELECT CONCAT(cempresa,cbalcao,cnumecta,zdeposit) AS CHAVE
        ,TRIM(concat(cempresa,cbalcao,cnumecta,zdeposit,NVL(CEMPBEM,''),NVL(CKBALBEM,''),NVL(CKCTABEM,''),NVL(CKREFBEM,''))) AS CHAVE_IT
        ,*
    FROM bu_esg_work.modesg_out_emss_fncd
    WHERE ref_date='2025-06-30'
    )F1
INNER JOIN 
    (
    SELECT TRIM(CONCAT(CHAVE,NVL(CHAVE_BEM,''))) AS CHAVE_TESTE
        ,CASE 
            WHEN FLAG_PERIMETRO='ST SGPS Cons;Individual Idcomb' THEN 'ST SGPS Cons; Individual Idcomb'
            ELSE FLAG_PERIMETRO
        END AS FLAG_PERIMETRO_MOD,*
    FROM BU_CAPTOOLS_WORK.EMI_FINAN
    )F2 ON F1.CHAVE_IT=F2.CHAVE_TESTE AND F1.NOME_PERIMETRO=F2.FLAG_PERIMETRO_MOD
HAVING VALID_ORI_SCP1='OK' AND VALID_SCP1='NOK - AMBOS PREENCH'
;

    -- Tipologia de Erro #1 - As emissões do contrato tem de ser calculadas pelos bens // Cada um destes contratos tem emissões pelo bem e cliente em simultâneo 
    
SELECT *
FROM bu_esg_work.modesg_out_emss_fncd
WHERE ref_date='2025-06-30'
    AND CONCAT(cempresa,cbalcao,cnumecta,zdeposit) IN ('89000000000234032000420000653970','89000000000248198000420000400143','89000000000220615000420000688408')
;

    -- Tipologia de Erro #2 - Sem emissões na tabela de IT // Emissões do contrato calculadas através do bem imóvel  
    
SELECT *
FROM bu_esg_work.modesg_out_emss_fncd
WHERE ref_date='2025-06-30'
    AND CONCAT(cempresa,cbalcao,cnumecta,zdeposit) IN ('31000800943728096000000000000000','31000321576391096000000000000000','31000312051230096000000000000000')
;

    -- Tipologia de Erro #3 - Sem emissões na tabela de IT // Emissões do contrato calculadas através do bem imóvel  
    
SELECT *
FROM bu_esg_work.modesg_out_emss_fncd
WHERE ref_date='2025-06-30'
    AND CONCAT(cempresa,cbalcao,cnumecta,zdeposit) IN ('31000800943728096000000000000000','31000321576391096000000000000000','31000312051230096000000000000000')
;

    -- Tipologia de Erro #4 - Origens deviam ser MISS ao invés de N/A para as linhas com bem   
    
SELECT *
FROM bu_esg_work.modesg_out_emss_fncd
WHERE ref_date='2025-06-30'
    AND CONCAT(cempresa,cbalcao,cnumecta,zdeposit) IN ('31000800014363096000000000000000','31000800135416096000000000000000','31000600843625096000000000000000')
;

    -- Tipologia de Erro #5 - Origens iguais mas cálculo das emissões diferente    
    
SELECT *
FROM bu_esg_work.modesg_out_emss_fncd
WHERE ref_date='2025-06-30'
    AND CONCAT(cempresa,cbalcao,cnumecta,zdeposit) IN ('31000300217429007100090728240000','89000020180925471001520250239446','31000312167192096000000000000000')
    
;	
	-- VALIDAÇÕES 01 OUT 2025

SELECT 
    CASE 
        WHEN F1.ORIGEM_SCP3_EMSS=F2.ORIGEM_SCP3_EMSS THEN 'OK'
        ELSE 'NOK'
    END AS VALID_ORI_SCP1
    ,CASE
        WHEN F2.SCP3_EMSS_FNCD IS NOT NULL AND F1.SCP3_EMSS_FNCD IS NOT NULL AND ABS(F1.SCP3_EMSS_FNCD-F2.SCP3_EMSS_FNCD)<=0.1 THEN 'OK - AMBOS PREENCH'
        WHEN F2.SCP3_EMSS_FNCD IS NOT NULL AND F1.SCP3_EMSS_FNCD IS NOT NULL AND ABS(F1.SCP3_EMSS_FNCD-F2.SCP3_EMSS_FNCD)>0.1 THEN 'NOK - AMBOS PREENCH'
        WHEN F2.SCP3_EMSS_FNCD IS NULL AND F1.SCP3_EMSS_FNCD IS NULL THEN 'AMBOS A NULL'
        WHEN F2.SCP3_EMSS_FNCD IS NOT NULL AND F1.SCP3_EMSS_FNCD IS NULL THEN 'IT A NULL'
        WHEN F2.SCP3_EMSS_FNCD IS NULL AND F1.SCP3_EMSS_FNCD IS NOT NULL THEN 'TESTES A NULL'
    END AS VALID_SCP3,count(*)
FROM 
    (
    SELECT CONCAT(cempresa,cbalcao,cnumecta,zdeposit) AS CHAVE
        ,TRIM(concat(cempresa,cbalcao,cnumecta,zdeposit,NVL(CEMPBEM,''),NVL(CKBALBEM,''),NVL(CKCTABEM,''),NVL(CKREFBEM,''))) AS CHAVE_IT
        ,*
    FROM bu_esg_work.modesg_out_emss_fncd
    WHERE ref_date='2025-06-30'
    )F1
INNER JOIN 
    (
    SELECT TRIM(CONCAT(CHAVE,NVL(CHAVE_BEM,''))) AS CHAVE_TESTE
        ,CASE 
            WHEN FLAG_PERIMETRO='ST SGPS Cons;Individual Idcomb' THEN 'ST SGPS Cons; Individual Idcomb'
            ELSE FLAG_PERIMETRO
        END AS FLAG_PERIMETRO_MOD,*
    FROM bu_esg_work.emi_finan_v4
    )F2 ON F1.CHAVE_IT=F2.CHAVE_TESTE AND F1.NOME_PERIMETRO=F2.FLAG_PERIMETRO_MOD
GROUP BY 1,2
;

SELECT *
FROM 
    (
    SELECT nome_perimetro,origem_scp1_emss,origem_scp2_emss,origem_scp3_emss
        ,sum(scp1_emss_fncd) AS SCP1,sum(scp2_emss_fncd) AS SCP2,sum(scp3_emss_fncd) AS SCP3,sum(amount) AS MONT
    FROM bu_esg_work.modesg_out_emss_fncd
    WHERE ref_date='2025-06-30'
    GROUP BY 1,2,3,4
    )F1
FULL JOIN 
    (
    SELECT CASE 
            WHEN FLAG_PERIMETRO='ST SGPS Cons;Individual Idcomb' THEN 'ST SGPS Cons; Individual Idcomb'
            ELSE FLAG_PERIMETRO
        END AS NOME_PERIMETRO,origem_scp1_emss,origem_scp2_emss,origem_scp3_emss
        ,sum(scp1_emss_fncd) AS SCP1,sum(scp2_emss_fncd) AS SCP2,sum(scp3_emss_fncd) AS SCP3,sum(amount) AS MONT
    FROM bu_esg_work.emi_finan_v4
    GROUP BY 1,2,3,4
    )F2
ON F1.nome_perimetro=F2.nome_perimetro
AND F1.origem_scp1_emss=F2.origem_scp1_emss
AND F1.origem_scp2_emss=F2.origem_scp2_emss
AND F1.origem_scp3_emss=F2.origem_scp3_emss
;
SELECT F1.CHAVE,F1.ORIGEM_SCP1_EMSS,F2.CHAVE_BEM,F1.SCP3_EMSS_FNCD,F2.SCP3_EMSS_FNCD,ABS(NVL(F1.SCP3_EMSS_FNCD,0)-NVL(F2.SCP3_EMSS_FNCD,0)) AS DIFF
FROM 
    (
    SELECT CONCAT(cempresa,cbalcao,cnumecta,zdeposit) AS CHAVE
        ,TRIM(concat(cempresa,cbalcao,cnumecta,zdeposit,NVL(CEMPBEM,''),NVL(CKBALBEM,''),NVL(CKCTABEM,''),NVL(CKREFBEM,''))) AS CHAVE_IT
        ,*
    FROM bu_esg_work.modesg_out_emss_fncd
    WHERE ref_date='2025-06-30'
    )F1
INNER JOIN 
    (
    SELECT TRIM(CONCAT(CHAVE,NVL(CHAVE_BEM,''))) AS CHAVE_TESTE
        ,CASE 
            WHEN FLAG_PERIMETRO='ST SGPS Cons;Individual Idcomb' THEN 'ST SGPS Cons; Individual Idcomb'
            ELSE FLAG_PERIMETRO
        END AS FLAG_PERIMETRO_MOD,*
    FROM bu_esg_work.emi_finan_v4
    )F2 ON F1.CHAVE_IT=F2.CHAVE_TESTE 
            AND F1.NOME_PERIMETRO=F2.FLAG_PERIMETRO_MOD
            AND F1.origem_scp1_emss=F2.origem_scp1_emss
            AND F1.origem_scp2_emss=F2.origem_scp2_emss
            AND F1.origem_scp3_emss=F2.origem_scp3_emss
ORDER BY DIFF DESC
--------------------------------------------------------------------------------------------------------------------------------------------------
-- 5. ESTR vs TEMP1 reportado a DEZ24 
--------------------------------------------------------------------------------------------------------------------------------------------------

SELECT METO_DEZ24,METO_JUN25,SUM(F1.SCP1),sum(F2.EMI_DEZ_SCP1),SUM(F1.SCP1)-sum(F2.EMI_DEZ_SCP1),count(*)
FROM 
    (
    SELECT CHAVE
        ,CASE
            WHEN FLAG_AUX_METODO_CTO=1 AND FLAG_BEM='MUG_MOV' THEN 'EMI BEM MOV'
            WHEN FLAG_AUX_METODO_CTO=1 AND FLAG_BEM='MUG_IMO' THEN 'EMI BEM IMO'
            WHEN FLAG_AUX_METODO_CTO=0 THEN 'EMI CLIENTE'
        END AS METO_JUN25
        ,SUM(SCP1_EMSS_FNCD) AS SCP1
        ,SUM(SCP2_EMSS_FNCD) AS SCP2
        ,SUM(SCP3_EMSS_FNCD) AS SCP3
    FROM BU_CAPTOOLS_WORK.EMI_FINAN
    WHERE FLAG_PERIMETRO LIKE '%ST SGPS Cons%'
        AND scp1_emss_fncd IS NOT NULL 
        AND origem_scp1_emss<>'Nao Aplicavel'
    GROUP BY 1,2
    )F1
INNER JOIN 
    (
    SELECT CONCAT(cempresa_ct,cbalcao_ct,cnumecta_ct,zdeposit_ct) AS CHAVE_CT
        ,CASE 
            WHEN TRIM(calculation_approach)='CAAP4' THEN 'EMI MVL'
            WHEN TRIM(calculation_approach)='CAAP3' THEN 'EMI RE'
            WHEN TRIM(calculation_approach) IN ('CAAP1','CAAP2') THEN 'EMI CLIENTE'
        END AS METO_DEZ24
        ,SUM(NVL(gesi_aux_ctr,0) + NVL(gesi_aux_2,0)) AS EMI_DEZ_SCP1
        ,SUM(NVL(gesii_aux_ctr,0) + NVL(gesii_aux_2,0)) AS EMI_DEZ_SCP2
        ,SUM(NVL(gesiii_aux_ctr,0)) AS EMI_DEZ_SCP3
    from bu_esg_work.local_pilar3_temp1_emi_tabaux18_dez24
    WHERE VB_IMP='valor bruto'
    GROUP BY 1,2
    )F2 ON F1.CHAVE=F2.CHAVE_CT
-- ORDER BY ABS(NVL(SCP1,0)-NVL(EMI_DEZ_SCP1,0)) DESC
GROUP BY 1,2

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 6.  Calculadora de Emissões // Validação Saldos DEZ24
--------------------------------------------------------------------------------------------------------------------------------------------------
	
SELECT *
FROM 
    (
    SELECT CHAVE,SUM(amount) AS AMOUNT
    FROM BU_CAPTOOLS_WORK.EMI_FINAN_AUX3
    WHERE flag_perimetro<>'Nao Aplicavel'
    GROUP BY 1
    )F1
LEFT JOIN 
    (
    SELECT L1.CHAVE_IC,sum(VALOR) AS MONT
    FROM 
        (
        SELECT CONCAT(cempresa,cbalcao,cnumecta,zdeposit) AS CHAVE_IC, concat(cempresa_fr,cbalcao_fr,cnumecta_fr,zdeposit_fr) AS CHAVE_FR
        FROM cd_captools.kt_chaves_finrep
        WHERE ref_date='2024-12-31'
        )L1
    INNER JOIN 
        (
        SELECT concat(cempresa,cbalcao,cnumecta,zdeposit) AS CHAVE_SALDO,SUM(valor_bruto_on_a) AS VALOR
        FROM cd_captools.fr004_cto
        WHERE ref_date='2024-12-31'
        GROUP BY 1
        )L2 ON L1.CHAVE_FR=L2.CHAVE_SALDO
    GROUP BY 1 
    )F2 ON F1.chave=f2.CHAVE_IC
WHERE CHAVE NOT LIKE '%CMAH%'
    AND CHAVE NOT LIKE '%NCON%'
    AND CHAVE NOT LIKE '316416%'
    -- AND CHAVE NOT LIKE '%NCONS%'
ORDER BY ABS(F1.AMOUNT-F2.MONT) DESC