
/*===================================================================================================================================================
                                                      
													  SIMULAÇÃO CERTIFICADOS - MBI
										                    NEYOND 2024 - v1.0
															    
 ===================================================================================================================================================*/
 
--------------------------------------------------------------------------------------------------------------------------------------------------
-- 1.A. Criação de uma Tabela Auxiliar com o tratamento de informação da OCR do Modelo de Gestão de Empreendimentos
		--> Tratamento dos registos duplicados por Certificado para a mesma data de validade 
		--> Passos 1 e 2 especificados nos Tratamentos necessários 
--------------------------------------------------------------------------------------------------------------------------------------------------

-- DEZ24 | Inserted 118.955 row(s)

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.INPUT_GESTEMPR_OCR_DEZ24;
CREATE TABLE BU_CAPTOOLS_WORK.INPUT_GESTEMPR_OCR_DEZ24 AS

SELECT *
FROM
	(
	SELECT *
		,RANK() OVER (PARTITION BY CONCAT(COLLATERALASSETID_OCR,ENERGY_CERTIFICATION_SYSTEM_CODE_OCR) ORDER BY CAST(ID_OCR AS DECIMAL(18,6)) DESC) AS RANK_TRAT_4
	FROM
		(
		SELECT *
			,RANK() OVER (PARTITION BY CONCAT(COLLATERALASSETID_OCR,ENERGY_CERTIFICATION_SYSTEM_CODE_OCR) ORDER BY OCRUPDATEDATE_OCR DESC) AS RANK_TRAT_3
		FROM
			(
			SELECT *
				,RANK() OVER (PARTITION BY CONCAT(COLLATERALASSETID_OCR,ENERGY_CERTIFICATION_SYSTEM_CODE_OCR) ORDER BY CREATIONDATE_OCR DESC) AS RANK_TRAT_2
			FROM
				(
				SELECT *
					,RANK() OVER (PARTITION BY CONCAT(COLLATERALASSETID_OCR,ENERGY_CERTIFICATION_SYSTEM_CODE_OCR) ORDER BY FLAG_CAMPOS_PREENC DESC) AS RANK_TRAT_1
				FROM
					(
					SELECT *,
						CASE WHEN TRIM(BASE_OCR.EPC_OCR)='' OR BASE_OCR.EPC_OCR IS NULL THEN 0 ELSE 1 END 
							+ CASE WHEN TRIM(BASE_OCR.EPC_EXPIRATION_DATE_OCR)='' OR BASE_OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN 0 ELSE 1 END
							+ CASE WHEN TRIM(BASE_OCR.ENERGY_CERTIFICATION_SYSTEM_CODE_OCR)='' OR BASE_OCR.ENERGY_CERTIFICATION_SYSTEM_CODE_OCR IS NULL THEN 0 ELSE 1 END
							+ CASE WHEN TRIM(DOC_1.LAND_REGISTRY_OFFICE_CODE_OCR)='' OR DOC_1.LAND_REGISTRY_OFFICE_CODE_OCR IS NULL THEN 0 ELSE 1 END 
							+ CASE WHEN TRIM(DOC_1.PROPERTY_IDENTIFICATION_CODE_OCR)='' OR DOC_1.PROPERTY_IDENTIFICATION_CODE_OCR IS NULL THEN 0 ELSE 1 END 
							+ CASE WHEN TRIM(DOC_2.CADASTRAL_REGISTER_CODE_OCR)='' OR DOC_2.CADASTRAL_REGISTER_CODE_OCR IS NULL THEN 0 ELSE 1 END 
							+ CASE WHEN TRIM(BUILD_CERT.CERTIFICATE_TYPE_OCR)='' OR BUILD_CERT.CERTIFICATE_TYPE_OCR IS NULL THEN 0 ELSE 1 END 
							+ CASE WHEN TRIM(BUILD_CERT.PROPERTY_PURPOSE_CODE_OCR)='' OR BUILD_CERT.PROPERTY_PURPOSE_CODE_OCR IS NULL THEN 0 ELSE 1 END 
							+ CASE WHEN TRIM(BUILD_CERT.LOCALITY_OCR)='' OR BUILD_CERT.LOCALITY_OCR IS NULL THEN 0 ELSE 1 END 
							+ CASE WHEN TRIM(BUILD_CERT.NET_FLOOR_AREA_OCR)='' OR BUILD_CERT.NET_FLOOR_AREA_OCR IS NULL THEN 0 ELSE 1 END 
							+ CASE WHEN TRIM(BUILD_CERT.REN_ENERGY_PRODUCED_VALUE_OCR)='' OR BUILD_CERT.REN_ENERGY_PRODUCED_VALUE_OCR IS NULL THEN 0 ELSE 1 END 
							+ CASE WHEN TRIM(BUILD_CERT.CARBON_EMISSION_VALUE_YEAR_OCR)='' OR BUILD_CERT.CARBON_EMISSION_VALUE_YEAR_OCR IS NULL THEN 0 ELSE 1 END 
							+ CASE WHEN TRIM(BUILD_CERT.NZEB_IND_OCR)='' OR BUILD_CERT.NZEB_IND_OCR IS NULL THEN 0 ELSE 1 END 
							+ CASE WHEN TRIM(BUILD_CERT.EPC_ISSUING_DATE_OCR)='' OR BUILD_CERT.EPC_ISSUING_DATE_OCR IS NULL THEN 0 ELSE 1 END 
							+ CASE WHEN TRIM(BUILD_CERT.GPS_LATITUDE_OCR)='' OR BUILD_CERT.GPS_LATITUDE_OCR IS NULL THEN 0 ELSE 1 END 
							+ CASE WHEN TRIM(BUILD_CERT.GPS_LONGITUDE_OCR)='' OR BUILD_CERT.GPS_LONGITUDE_OCR IS NULL THEN 0 ELSE 1 END 
							+ CASE WHEN TRIM(BUILD_CERT.DISTRICT_MUNICIP_PARISH_CODE_OCR)='' OR BUILD_CERT.DISTRICT_MUNICIP_PARISH_CODE_OCR IS NULL THEN 0 ELSE 1 END 
							+ CASE WHEN TRIM(BUILD_CERT.FLOOR_NUMBER_OCR)='' OR BUILD_CERT.FLOOR_NUMBER_OCR IS NULL THEN 0 ELSE 1 END 
							+ CASE WHEN TRIM(BUILD_CERT.ADDRESS_CODE_OCR)='' OR BUILD_CERT.ADDRESS_CODE_OCR IS NULL THEN 0 ELSE 1 END 
							+ CASE WHEN TRIM(MAJOR_1.PRIMARY_ENERGY_REQ_VALUE_OCR)='' OR MAJOR_1.PRIMARY_ENERGY_REQ_VALUE_OCR IS NULL THEN 0 ELSE 1 END 
							+ CASE WHEN TRIM(MAJOR_2.ENERGY_CONSUMPTION_VALUE_YEAR_OCR)='' OR MAJOR_2.ENERGY_CONSUMPTION_VALUE_YEAR_OCR IS NULL THEN 0 ELSE 1 END 
							+ CASE WHEN TRIM(BUILD_CERT.CURRENT_ENERGY_RATING_PERCENTAGE_OCR)='' OR BUILD_CERT.CURRENT_ENERGY_RATING_PERCENTAGE_OCR IS NULL THEN 0 ELSE 1 END -- Sem impacto: O campo nunca esta preenchido 
						AS FLAG_CAMPOS_PREENC
						,CASE 
							WHEN TRIM(BASE_OCR.EPC_OCR)='A+' THEN 1
							WHEN TRIM(BASE_OCR.EPC_OCR)='A' THEN 2
							WHEN TRIM(BASE_OCR.EPC_OCR)='A-' THEN 3
							WHEN TRIM(BASE_OCR.EPC_OCR)='B+' THEN 4
							WHEN TRIM(BASE_OCR.EPC_OCR)='B' THEN 5
							WHEN TRIM(BASE_OCR.EPC_OCR)='B-' THEN 6
							WHEN TRIM(BASE_OCR.EPC_OCR)='C' THEN 7
							WHEN TRIM(BASE_OCR.EPC_OCR)='D' THEN 8
							WHEN TRIM(BASE_OCR.EPC_OCR)='E' THEN 9
							WHEN TRIM(BASE_OCR.EPC_OCR)='F' THEN 10
							WHEN TRIM(BASE_OCR.EPC_OCR)='G' THEN 11
						END AS FLAG_ORDEM_EPC 
						,RANK() OVER (PARTITION BY BASE_OCR.COLLATERALASSETID_OCR ORDER BY COALESCE(BASE_OCR.EPC_EXPIRATION_DATE_OCR, '01-01-1900') DESC) AS RANK_DT_VALIDADE
						FROM 
						
							-- 1º Cruzamento: Informação base da Property Certificate 
							--> OUT24 110.742 Registos 
							(
							SELECT 
								TRIM(ID) AS ID_OCR
								,TRIM(COLLATERALASSETID) AS COLLATERALASSETID_OCR
								,TRIM(GNID) AS GNID_OCR
								,'OCR' AS SOURCE_CODE_OCR
								,TRIM(CREATIONDATE) AS CREATIONDATE_OCR
								,TRIM(OCRUPDATEDATE) AS OCRUPDATEDATE_OCR
								,TRIM(ENERGYEFFICIENCYRATING) AS EPC_OCR
								,TRIM(EPCREFERENCENUMBER) AS ENERGY_CERTIFICATION_SYSTEM_CODE_OCR
								,TRIM(EPCEXPIRATIONDATE) AS EPC_EXPIRATION_DATE_OCR
								,DATA_DATE_PART AS DATA_DATE_PART_OCR 
								,DATA_TIMESTAMP_PART AS DATA_TIMESTAMP_PART_OCR    
							FROM CURATED_INTERNAL_GESTAOIMOVEIS.PROPERTYCERTIFICATE
							WHERE TRIM(UPPER(ENERGYEFFICIENCYRATING)) NOT IN ('+','-','S','N','J','')
								AND TRIM(DOCUMENTTYPE)<>'ADENE' 
								AND DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM CURATED_INTERNAL_GESTAOIMOVEIS.PROPERTYCERTIFICATE WHERE DATA_DATE_PART <= '${ref_date}')
							)BASE_OCR
						
						LEFT JOIN
							-- 2º Cruzamento: Informação da DOCUMENTS via chave ID da info da ADENE 
							--> OUT24 110.742 Registos 	
							(
							SELECT
								TRIM(BUILDINGENERGYCERTIFICATEID) AS BUILDINGENERGYCERTIFICATEID_OCR_DOC1
								,TRIM(ISSUERENTITY) AS LAND_REGISTRY_OFFICE_CODE_OCR
								,TRIM(DOCUMENTNUMBER) AS PROPERTY_IDENTIFICATION_CODE_OCR
							FROM curated_internal_gestaoimoveis.Documents
							WHERE DOCUMENTTYPEDESCRIPTION = 'Nº de inscrição na Conservatória'
							AND DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM CURATED_INTERNAL_GESTAOIMOVEIS.DOCUMENTS WHERE DATA_DATE_PART <= '${ref_date}')
							)DOC_1 ON BASE_OCR.ID_OCR=DOC_1.BUILDINGENERGYCERTIFICATEID_OCR_DOC1
						
						LEFT JOIN 
							-- 3º Cruzamento: Informação da DOCUMENTS via chave ID da info da ADENE 
							--> OUT24 110.742 Registos 
							(
							SELECT
								TRIM(BUILDINGENERGYCERTIFICATEID) AS BUILDINGENERGYCERTIFICATEID_OCR_DOC2
								,TRIM(DOCUMENTNUMBER) AS CADASTRAL_REGISTER_CODE_OCR
								FROM curated_internal_gestaoimoveis.Documents
								WHERE DOCUMENTTYPEDESCRIPTION = 'Artigo Matricial nº'
									AND DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM curated_internal_gestaoimoveis.Documents WHERE DATA_DATE_PART <= '${ref_date}')
							)DOC_2 ON BASE_OCR.ID_OCR=DOC_2.BUILDINGENERGYCERTIFICATEID_OCR_DOC2
						
						LEFT JOIN
							-- 4º Cruzamento: Informação da BuildingEnergyCertificate via chave ID da info da ADENE 
							--> OUT24 110.742 Registos  
							(
							SELECT 
								TRIM(PROPERTYCERTIFICATEID) AS PROPERTYCERTIFICATEID_OCR
								,TRIM(TYPEDESCRIPTION) AS CERTIFICATE_TYPE_OCR
								,TRIM(BUILDINGPURPOSEDESCRIPTION) AS PROPERTY_PURPOSE_CODE_OCR
								,TRIM(BUILDINGGEOLOCATIONPOSTALADDRESSTOWNNAME) AS LOCALITY_OCR
								,TRIM(BUILTUPAREAQUANTITY) AS NET_FLOOR_AREA_OCR
								,TRIM(RENEWABLEENERGYCONTRIBUTIONVALUE) AS REN_ENERGY_PRODUCED_VALUE_OCR
								,TRIM(CURRENTCARBONFOOTPRINTVALUE) AS CARBON_EMISSION_VALUE_YEAR_OCR
								,TRIM(NEARZEROBUILDINGINDICATOR) AS NZEB_IND_OCR
								,TRIM(ISSUEDATE) AS EPC_ISSUING_DATE_OCR
								,TRIM(BUILDINGGEOLOCATIONLATITUDE) AS GPS_LATITUDE_OCR
								,TRIM(BUILDINGGEOLOCATIONLONGITUDE) AS GPS_LONGITUDE_OCR
								,TRIM(BUILDINGGEOLOCATIONPOSTALADDRESSCITYNAME) AS DISTRICT_MUNICIP_PARISH_CODE_OCR
								,TRIM(BUILDINGGEOLOCATIONPOSTALADDRESSUNITTYPE) AS FLOOR_NUMBER_OCR
								,TRIM(BUILDINGGEOLOCATIONPOSTALADDRESSFULLADDRESS) AS ADDRESS_CODE_OCR
								,TRIM(CURRENTEFFICIENCYRATINGPERCENTAGE) AS CURRENT_ENERGY_RATING_PERCENTAGE_OCR
							FROM CURATED_INTERNAL_GESTAOIMOVEIS.BUILDINGENERGYCERTIFICATE
							WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM CURATED_INTERNAL_GESTAOIMOVEIS.BUILDINGENERGYCERTIFICATE WHERE DATA_DATE_PART <= '${ref_date}')
							)BUILD_CERT ON BASE_OCR.ID_OCR=BUILD_CERT.PROPERTYCERTIFICATEID_OCR
						LEFT JOIN
							-- 5º Cruzamento: Informação da MajorIndicators via chave ID da info da ADENE 
							--> OUT24 110.742 Registos
							(
							SELECT 
								TRIM(BUILDINGENERGYCERTIFICATEID) AS BUILDINGENERGYCERTIFICATEID_OCR_MAJOR1
								,TRIM(MAJORINDVALUE) AS PRIMARY_ENERGY_REQ_VALUE_OCR
							FROM CURATED_INTERNAL_GESTAOIMOVEIS.MAJORINDICATORS
							WHERE TYPECODE IN ('Ntc','IEE')  
								AND DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM CURATED_INTERNAL_GESTAOIMOVEIS.MAJORINDICATORS WHERE DATA_DATE_PART <= '${ref_date}')
							)MAJOR_1 ON BASE_OCR.ID_OCR=MAJOR_1.BUILDINGENERGYCERTIFICATEID_OCR_MAJOR1
					
						LEFT JOIN
							-- 6º Cruzamento: Informação da MajorIndicators via chave ID da info da ADENE 
							--> OUT24 110.742 Registos
							(
							SELECT 
							TRIM(BUILDINGENERGYCERTIFICATEID) AS BUILDINGENERGYCERTIFICATEID_OCR_MAJOR2
							,TRIM(MAJORINDVALUE) AS  ENERGY_CONSUMPTION_VALUE_YEAR_OCR
							FROM CURATED_INTERNAL_GESTAOIMOVEIS.MAJORINDICATORS
							WHERE TYPECODE = 'IEE'
								AND DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM CURATED_INTERNAL_GESTAOIMOVEIS.MAJORINDICATORS WHERE DATA_DATE_PART <= '${ref_date}')
							)MAJOR_2 ON BASE_OCR.ID_OCR=MAJOR_2.BUILDINGENERGYCERTIFICATEID_OCR_MAJOR2
					)TRATAMENTO_0 WHERE RANK_DT_VALIDADE=1 
				)TRATAMENTO_1 WHERE RANK_TRAT_1=1
			)TRATAMENTO_2 WHERE RANK_TRAT_2=1
		)TRATAMENTO_3 WHERE RANK_TRAT_3=1
	)TRATAMENTO_4 WHERE RANK_TRAT_4=1
 ;
 
--------------------------------------------------------------------------------------------------------------------------------------------------
-- 1.B. Criação de uma Tabela Auxiliar com o tratamento de informação da OCR do Modelo de Gestão de Empreendimentos
		--> Tratamento dos registos duplicados por Certificado para a mesma data de validade 
		--> Passos 3 especificados nos Tratamentos necessários 
		--> ESTE PASSO NÃO É CONSIDERADO (Motivo: Depois do tratamento da creation data mais recente, verificamos casos com 2º/3º.. creation dates duplicadas)
			--> Ex1: collateralassetid_ocr='003016979790000' AND energy_certification_system_code_ocr='SCE140467830'
			--> Ex2: collateralassetid_ocr='003016350180000' AND energy_certification_system_code_ocr='SCE115667834'
--------------------------------------------------------------------------------------------------------------------------------------------------

--DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.INPUT_GESTEMPR_OCR_AUX2_DEZ24;
--CREATE TABLE BU_CAPTOOLS_WORK.INPUT_GESTEMPR_OCR_AUX2_DEZ24 AS
--
--SELECT 
--	F1.ID_OCR
--	F1.COLLATERALASSETID_OCR
--	F1.GNID_OCR
--	F1.SOURCE_CODE_OCR
--	F1.CREATIONDATE_OCR
--	F1.OCRUPDATEDATE_OCR
--	F1.EPC_OCR
--	F1.ENERGY_CERTIFICATION_SYSTEM_CODE_OCR
--	F1.EPC_EXPIRATION_DATE_OCR
--	F1.DATA_DATE_PART_OCR
--	F1.DATA_TIMESTAMP_PART_OCR
--	F1.BUILDINGENERGYCERTIFICATEID_OCR_DOC1
--	CASE WHEN NUM_REG_TRAT_2=1 AND (TRIM(F1.LAND_REGISTRY_OFFICE_CODE_OCR)='' OR F1.LAND_REGISTRY_OFFICE_CODE_OCR IS NULL THEN F2.LAND_REGISTRY_OFFICE_CODE_OCR) ELSE F1.LAND_REGISTRY_OFFICE_CODE_OCR END AS LAND_REGISTRY_OFFICE_CODE_OCR
--	CASE WHEN NUM_REG_TRAT_2=1 AND (TRIM(F1.PROPERTY_IDENTIFICATION_CODE_OCR)='' OR F1.PROPERTY_IDENTIFICATION_CODE_OCR IS NULL THEN F2.PROPERTY_IDENTIFICATION_CODE_OCR) ELSE F1.PROPERTY_IDENTIFICATION_CODE_OCR END AS PROPERTY_IDENTIFICATION_CODE_OCR
--	F1.BUILDINGENERGYCERTIFICATEID_OCR_DOC2
--	CASE WHEN NUM_REG_TRAT_2=1 AND (TRIM(F1.CADASTRAL_REGISTER_CODE_OCR)='' OR F1.CADASTRAL_REGISTER_CODE_OCR IS NULL THEN F2.CADASTRAL_REGISTER_CODE_OCR) ELSE F1.CADASTRAL_REGISTER_CODE_OCR END AS CADASTRAL_REGISTER_CODE_OCR
--	CASE WHEN NUM_REG_TRAT_2=1 AND (TRIM(F1.PROPERTYCERTIFICATEID_OCR)='' OR F1.PROPERTYCERTIFICATEID_OCR IS NULL THEN F2.PROPERTYCERTIFICATEID_OCR) ELSE F1.PROPERTYCERTIFICATEID_OCR END AS PROPERTYCERTIFICATEID_OCR
--	CASE WHEN NUM_REG_TRAT_2=1 AND (TRIM(F1.CERTIFICATE_TYPE_OCR)='' OR F1.CERTIFICATE_TYPE_OCR IS NULL THEN F2.CERTIFICATE_TYPE_OCR) ELSE F1.CERTIFICATE_TYPE_OCR END AS CERTIFICATE_TYPE_OCR
--	CASE WHEN NUM_REG_TRAT_2=1 AND (TRIM(F1.PROPERTY_PURPOSE_CODE_OCR)='' OR F1.PROPERTY_PURPOSE_CODE_OCR IS NULL THEN F2.PROPERTY_PURPOSE_CODE_OCR) ELSE F1.PROPERTY_PURPOSE_CODE_OCR END AS PROPERTY_PURPOSE_CODE_OCR
--	CASE WHEN NUM_REG_TRAT_2=1 AND (TRIM(F1.LOCALITY_OCR)='' OR F1.LOCALITY_OCR IS NULL THEN F2.LOCALITY_OCR) ELSE F1.LOCALITY_OCR END AS LOCALITY_OCR
--	CASE WHEN NUM_REG_TRAT_2=1 AND (TRIM(F1.NET_FLOOR_AREA_OCR)='' OR F1.NET_FLOOR_AREA_OCR IS NULL THEN F2.NET_FLOOR_AREA_OCR) ELSE F1.NET_FLOOR_AREA_OCR END AS NET_FLOOR_AREA_OCR
--	CASE WHEN NUM_REG_TRAT_2=1 AND (TRIM(F1.REN_ENERGY_PRODUCED_VALUE_OCR)='' OR F1.REN_ENERGY_PRODUCED_VALUE_OCR IS NULL THEN F2.REN_ENERGY_PRODUCED_VALUE_OCR) ELSE F1.REN_ENERGY_PRODUCED_VALUE_OCR END AS REN_ENERGY_PRODUCED_VALUE_OCR
--	CASE WHEN NUM_REG_TRAT_2=1 AND (TRIM(F1.CARBON_EMISSION_VALUE_YEAR_OCR)='' OR F1.CARBON_EMISSION_VALUE_YEAR_OCR IS NULL THEN F2.CARBON_EMISSION_VALUE_YEAR_OCR) ELSE F1.CARBON_EMISSION_VALUE_YEAR_OCR END AS CARBON_EMISSION_VALUE_YEAR_OCR
--	CASE WHEN NUM_REG_TRAT_2=1 AND (TRIM(F1.NZEB_IND_OCR)='' OR F1.NZEB_IND_OCR IS NULL THEN F2.NZEB_IND_OCR) ELSE F1.NZEB_IND_OCR END AS NZEB_IND_OCR
--	CASE WHEN NUM_REG_TRAT_2=1 AND (TRIM(F1.EPC_ISSUING_DATE_OCR)='' OR F1.EPC_ISSUING_DATE_OCR IS NULL THEN F2.EPC_ISSUING_DATE_OCR) ELSE F1.EPC_ISSUING_DATE_OCR END AS EPC_ISSUING_DATE_OCR
--	CASE WHEN NUM_REG_TRAT_2=1 AND (TRIM(F1.GPS_LATITUDE_OCR)='' OR F1.GPS_LATITUDE_OCR IS NULL THEN F2.GPS_LATITUDE_OCR) ELSE F1.GPS_LATITUDE_OCR END AS GPS_LATITUDE_OCR
--	CASE WHEN NUM_REG_TRAT_2=1 AND (TRIM(F1.GPS_LONGITUDE_OCR)='' OR F1.GPS_LONGITUDE_OCR IS NULL THEN F2.GPS_LONGITUDE_OCR) ELSE F1.GPS_LONGITUDE_OCR END AS GPS_LONGITUDE_OCR
--	CASE WHEN NUM_REG_TRAT_2=1 AND (TRIM(F1.DISTRICT_MUNICIP_PARISH_CODE_OCR)='' OR F1.DISTRICT_MUNICIP_PARISH_CODE_OCR IS NULL THEN F2.DISTRICT_MUNICIP_PARISH_CODE_OCR) ELSE F1.DISTRICT_MUNICIP_PARISH_CODE_OCR END AS DISTRICT_MUNICIP_PARISH_CODE_OCR
--	CASE WHEN NUM_REG_TRAT_2=1 AND (TRIM(F1.FLOOR_NUMBER_OCR)='' OR F1.FLOOR_NUMBER_OCR IS NULL THEN F2.FLOOR_NUMBER_OCR) ELSE F1.FLOOR_NUMBER_OCR END AS FLOOR_NUMBER_OCR
--	CASE WHEN NUM_REG_TRAT_2=1 AND (TRIM(F1.ADDRESS_CODE_OCR)='' OR F1.ADDRESS_CODE_OCR IS NULL THEN F2.ADDRESS_CODE_OCR) ELSE F1.ADDRESS_CODE_OCR END AS ADDRESS_CODE_OCR
--	F1.BUILDINGENERGYCERTIFICATEID_OCR_MAJOR1
--	CASE WHEN NUM_REG_TRAT_2=1 AND (TRIM(F1.PRIMARY_ENERGY_REQ_VALUE_OCR)='' OR F1.PRIMARY_ENERGY_REQ_VALUE_OCR IS NULL THEN F2.PRIMARY_ENERGY_REQ_VALUE_OCR) ELSE F1.PRIMARY_ENERGY_REQ_VALUE_OCR END AS PRIMARY_ENERGY_REQ_VALUE_OCR
--	F1.BUILDINGENERGYCERTIFICATEID_OCR_MAJOR2
--	CASE WHEN NUM_REG_TRAT_2=1 AND (TRIM(F1.ENERGY_CONSUMPTION_VALUE_YEAR_OCR)='' OR F1.ENERGY_CONSUMPTION_VALUE_YEAR_OCR IS NULL THEN F2.ENERGY_CONSUMPTION_VALUE_YEAR_OCR) ELSE F1.ENERGY_CONSUMPTION_VALUE_YEAR_OCR END AS ENERGY_CONSUMPTION_VALUE_YEAR_OCR
--	F1.FLAG_CAMPOS_PREENC
--	F1.FLAG_ORDEM_EPC
--	F1.RANK_DT_VALIDADE
--	F1.RANK_TRAT_1
--	F1.RANK_TRAT_2
--	F1.NUM_REG_TRAT_2
--FROM 
--	(
--	SELECT *
--	FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_OCR_AUX1_DEZ24
--	WHERE RANK_TRAT_2=1
--	)F1 
--LEFT JOIN 
--	(
--	SELECT * 
--	FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_OCR_AUX1_DEZ24
--	WHERE RANK_TRAT_3=2
--	)F2 ON F1.COLLATERALASSETID_OCR=F2.COLLATERALASSETID_OCR AND F1.ENERGY_CERTIFICATION_SYSTEM_CODE_OCR=F2.ENERGY_CERTIFICATION_SYSTEM_CODE_OCR
--;

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 1.C. Criação de uma Tabela Auxiliar com o tratamento de informação da OCR do Modelo de Gestão de Empreendimentos
		--> Tratamento dos registos duplicados por Certificado para a mesma data de validade 
		--> Passos 4 especificados nos Tratamentos necessários 
		--> 1 registo por certificado. No entanto, 1 bem pode ter múltiplos certificados para a mesma data de validade 
		--> ESTE PASSO NÃO É CONSIDERADO 
--------------------------------------------------------------------------------------------------------------------------------------------------

--DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.INPUT_GESTEMPR_OCR_DEZ24;
--CREATE TABLE BU_CAPTOOLS_WORK.INPUT_GESTEMPR_OCR_DEZ24 AS
--
--SELECT *
--FROM
--	(
--	SELECT *
--		,RANK() OVER (PARTITION BY CONCAT(COLLATERALASSETID_OCR,ENERGY_CERTIFICATION_SYSTEM_CODE_OCR) ORDER BY CAST(ID_OCR AS DECIMAL(18,6)) DESC) AS RANK_TRAT_4
--	FROM
--		(
--		SELECT *
--			,RANK() OVER (PARTITION BY CONCAT(COLLATERALASSETID_OCR,ENERGY_CERTIFICATION_SYSTEM_CODE_OCR) ORDER BY OCRUPDATEDATE_OCR DESC) AS RANK_TRAT_3
--		FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_OCR_AUX2_DEZ24
--		)TRATAMENTO_3 WHERE RANK_TRAT_3=1
--	)TRATAMENTO_4 WHERE RANK_TRAT_4=1
--;

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 1.D. Criação de uma Tabela Auxiliar com o tratamento de informação da OCR do Modelo de Gestão de Empreendimentos
		--> Tratamento para a escolha do certificado por bem para aprovisionar os campos da Tipologia de Informação I & IV
		--> 1 Registo por bem 
--------------------------------------------------------------------------------------------------------------------------------------------------

-- DEZ24 | Inserted 117.228 row(s)

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.INPUT_GESTEMPR_OCR_STEP2_DEZ24;
CREATE TABLE BU_CAPTOOLS_WORK.INPUT_GESTEMPR_OCR_STEP2_DEZ24 AS

SELECT *
FROM
	(
	SELECT *
		,RANK() OVER (PARTITION BY COLLATERALASSETID_OCR ORDER BY ID_OCR DESC) AS RANK_TRAT_10
	FROM
		(
		SELECT *
			,RANK() OVER (PARTITION BY COLLATERALASSETID_OCR ORDER BY CREATIONDATE_OCR DESC) AS RANK_TRAT_9
		FROM
			(
			SELECT *
				,RANK() OVER (PARTITION BY COLLATERALASSETID_OCR ORDER BY FLAG_CAMPOS_PREENC DESC) AS RANK_TRAT_8
			FROM
				(
				SELECT *
					,RANK() OVER (PARTITION BY COLLATERALASSETID_OCR ORDER BY NVL(CAST(REGEXP_REPLACE(REGEXP_REPLACE(NET_FLOOR_AREA_OCR,'[^0-9,.]',''),',','.') AS DECIMAL(18,6)),0) DESC) AS RANK_TRAT_7
				FROM 
					(
					SELECT *
						,RANK() OVER (PARTITION BY COLLATERALASSETID_OCR ORDER BY FLAG_ORDEM_EPC DESC) AS RANK_TRAT_6
					FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_OCR_DEZ24
					)TRATAMENTO_5 WHERE RANK_TRAT_6=1
				)TRATAMENTO_6 WHERE RANK_TRAT_7=1
			)TRATAMENTO_7 WHERE RANK_TRAT_8=1
		)TRATAMENTO_8 WHERE RANK_TRAT_9=1
	)TRATAMENTO_9 WHERE RANK_TRAT_10=1
;

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 1.E. Criação de uma Tabela Auxiliar com o tratamento de informação da OCR do Modelo de Gestão de Empreendimentos
		--> Tratamento da informação para aprovisionar o campos da Tipologia de Informação II & III 
--------------------------------------------------------------------------------------------------------------------------------------------------

-- DEZ24 | Inserted 118.955 row(s)

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.INPUT_GESTEMPR_OCR_STEP3_DEZ24;
CREATE TABLE BU_CAPTOOLS_WORK.INPUT_GESTEMPR_OCR_STEP3_DEZ24 AS

SELECT *
	,CAST(REGEXP_REPLACE(REGEXP_REPLACE(F1.NET_FLOOR_AREA_OCR,'[^0-9,.]',''),',','.') AS DECIMAL(18,6))/F2.SUM_NET_FLOOR_AREA_OCR AS PERCENTAGEM
	,(CAST(REGEXP_REPLACE(REGEXP_REPLACE(F1.NET_FLOOR_AREA_OCR,'[^0-9,.]',''),',','.') AS DECIMAL(18,6))/F2.SUM_NET_FLOOR_AREA_OCR)*CAST(REGEXP_REPLACE(REGEXP_REPLACE(F1.REN_ENERGY_PRODUCED_VALUE_OCR,'[^0-9,.]',''),',','.')  AS DECIMAL(18,6)) AS POND_REN_ENERGY_PRODUCED_VALUE
	--,(CAST(REGEXP_REPLACE(REGEXP_REPLACE(F1.NET_FLOOR_AREA_OCR,'[^0-9,.]',''),',','.') AS DECIMAL(18,6))/F2.SUM_NET_FLOOR_AREA_OCR)*CAST(REGEXP_REPLACE(REGEXP_REPLACE(F1.CURRENT_ENERGY_RATING_PERCENTAGE_OCR,'[^0-9,.]',''),',','.')  AS DECIMAL(18,6)) AS POND_CURRENT_ENERGY_RATING_PERCENTAGE --21/04 - Sem necessidade de cálculo uma vez que este valor vai ser obtido no certificado (sem desenvolvimento do filtro a aplicar)

FROM
	(
	SELECT 	COLLATERALASSETID_OCR
		,NET_FLOOR_AREA_OCR
		,CARBON_EMISSION_VALUE_YEAR_OCR
		,ENERGY_CONSUMPTION_VALUE_YEAR_OCR
		,PRIMARY_ENERGY_REQ_VALUE_OCR
		,REN_ENERGY_PRODUCED_VALUE_OCR
		,CURRENT_ENERGY_RATING_PERCENTAGE_OCR
	FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_OCR_DEZ24 
	)F1 
LEFT JOIN 
	(
	SELECT 
		COLLATERALASSETID_OCR AS SUM_COLLATERALASSETID_OCR 
		,SUM(CAST(REGEXP_REPLACE(REGEXP_REPLACE(NET_FLOOR_AREA_OCR,'[^0-9,.]',''),',','.') AS DECIMAL(18,6))) AS SUM_NET_FLOOR_AREA_OCR
		,SUM(CAST(REGEXP_REPLACE(REGEXP_REPLACE(CARBON_EMISSION_VALUE_YEAR_OCR,'[^0-9,.]',''),',','.')  AS DECIMAL(18,6))) AS SUM_CARBON_EMISSION_VALUE_YEAR_OCR
		,SUM(CAST(REGEXP_REPLACE(REGEXP_REPLACE(ENERGY_CONSUMPTION_VALUE_YEAR_OCR,'[^0-9,.]',''),',','.')  AS DECIMAL(18,6))) AS SUM_ENERGY_CONSUMPTION_VALUE_YEAR_OCR
		,SUM(CAST(REGEXP_REPLACE(REGEXP_REPLACE(PRIMARY_ENERGY_REQ_VALUE_OCR,'[^0-9,.]',''),',','.')  AS DECIMAL(18,6))) AS SUM_PRIMARY_ENERGY_REQ_VALUE_OCR
	FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_OCR_DEZ24
	GROUP BY 1
	)F2 ON F1.COLLATERALASSETID_OCR=F2.SUM_COLLATERALASSETID_OCR
;

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 2.A.1. Criação de uma Tabela Auxiliar com o tratamento de informação da ADENE do Modelo de Gestão de Empreendimentos
		  --> Tratamento dos registos duplicados por Certificado para a mesma data de validade 
		  --> Passo 1,2 e 3 especificados nos Tratamentos necessários 
--------------------------------------------------------------------------------------------------------------------------------------------------


-- DEZ24 | Inserted 111.794 row(s)

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_AUX1_DEZ24;
CREATE TABLE BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_AUX1_DEZ24 AS

SELECT *
	,COUNT(*) OVER (PARTITION BY CONCAT(COLLATERALASSETID_ADENE,ENERGY_CERTIFICATION_SYSTEM_CODE_ADENE,CREATIONDATE_ADENE)) AS NUM_REG_TRAT_3
FROM
	(
    SELECT *
		,RANK() OVER (PARTITION BY CONCAT(COLLATERALASSETID_ADENE,ENERGY_CERTIFICATION_SYSTEM_CODE_ADENE) ORDER BY CREATIONDATE_ADENE DESC) AS RANK_TRAT_3
	FROM
		(
		SELECT *
			,RANK() OVER (PARTITION BY CONCAT(COLLATERALASSETID_ADENE,ENERGY_CERTIFICATION_SYSTEM_CODE_ADENE) ORDER BY FLAG_CRUZA_ADENE_OCR DESC) AS RANK_TRAT_2
		FROM
			(
			SELECT *
				,RANK() OVER (PARTITION BY CONCAT(COLLATERALASSETID_ADENE,ENERGY_CERTIFICATION_SYSTEM_CODE_ADENE) ORDER BY FLAG_CAMPOS_PREENC DESC) AS RANK_TRAT_1
			FROM
				(
				SELECT *
					,CASE WHEN TRIM(BASE_ADENE.EPC_ADENE)='' OR BASE_ADENE.EPC_ADENE IS NULL THEN 0 ELSE 1 END 
						+ CASE WHEN TRIM(BASE_ADENE.EPC_EXPIRATION_DATE_ADENE)='' OR BASE_ADENE.EPC_EXPIRATION_DATE_ADENE IS NULL THEN 0 ELSE 1 END
						+ CASE WHEN TRIM(BASE_ADENE.ENERGY_CERTIFICATION_SYSTEM_CODE_ADENE)='' OR BASE_ADENE.ENERGY_CERTIFICATION_SYSTEM_CODE_ADENE IS NULL THEN 0 ELSE 1 END
						+ CASE WHEN TRIM(BUILD_CERT.CERTIFICATE_TYPE_ADENE)='' OR BUILD_CERT.CERTIFICATE_TYPE_ADENE IS NULL THEN 0 ELSE 1 END 
						+ CASE WHEN TRIM(BUILD_CERT.PROPERTY_PURPOSE_CODE_ADENE)='' OR BUILD_CERT.PROPERTY_PURPOSE_CODE_ADENE IS NULL THEN 0 ELSE 1 END 
						+ CASE WHEN TRIM(BUILD_CERT.LOCALITY_ADENE)='' OR BUILD_CERT.LOCALITY_ADENE IS NULL THEN 0 ELSE 1 END 
						+ CASE WHEN TRIM(BUILD_CERT.NET_FLOOR_AREA_ADENE)='' OR BUILD_CERT.NET_FLOOR_AREA_ADENE IS NULL THEN 0 ELSE 1 END 
						+ CASE WHEN TRIM(BUILD_CERT.REN_ENERGY_PRODUCED_VALUE_ADENE)='' OR BUILD_CERT.REN_ENERGY_PRODUCED_VALUE_ADENE IS NULL THEN 0 ELSE 1 END 
						+ CASE WHEN TRIM(BUILD_CERT.CARBON_EMISSION_VALUE_YEAR_ADENE)='' OR BUILD_CERT.CARBON_EMISSION_VALUE_YEAR_ADENE IS NULL THEN 0 ELSE 1 END 
						+ CASE WHEN TRIM(BUILD_CERT.NZEB_IND_ADENE)='' OR BUILD_CERT.NZEB_IND_ADENE IS NULL THEN 0 ELSE 1 END 
						+ CASE WHEN TRIM(BUILD_CERT.EPC_ISSUING_DATE_ADENE)='' OR BUILD_CERT.EPC_ISSUING_DATE_ADENE IS NULL THEN 0 ELSE 1 END  
						+ CASE WHEN TRIM(MAJOR_1.PRIMARY_ENERGY_REQ_VALUE_ADENE)='' OR MAJOR_1.PRIMARY_ENERGY_REQ_VALUE_ADENE IS NULL THEN 0 ELSE 1 END 
						+ CASE WHEN TRIM(MAJOR_2.ENERGY_CONSUMPTION_VALUE_YEAR_ADENE)='' OR MAJOR_2.ENERGY_CONSUMPTION_VALUE_YEAR_ADENE IS NULL THEN 0 ELSE 1 END
						+ CASE WHEN TRIM(BUILD_CERT.CURRENT_ENERGY_RATING_PERCENTAGE_ADENE)='' OR BUILD_CERT.CURRENT_ENERGY_RATING_PERCENTAGE_ADENE IS NULL THEN 0 ELSE 1 END						
					AS FLAG_CAMPOS_PREENC
					,CASE 
						WHEN TRIM(BASE_ADENE.EPC_ADENE)='A+' THEN 1
						WHEN TRIM(BASE_ADENE.EPC_ADENE)='A' THEN 2
						WHEN TRIM(BASE_ADENE.EPC_ADENE)='A-' THEN 3
						WHEN TRIM(BASE_ADENE.EPC_ADENE)='B+' THEN 4
						WHEN TRIM(BASE_ADENE.EPC_ADENE)='B' THEN 5
						WHEN TRIM(BASE_ADENE.EPC_ADENE)='B-' THEN 6
						WHEN TRIM(BASE_ADENE.EPC_ADENE)='C' THEN 7
						WHEN TRIM(BASE_ADENE.EPC_ADENE)='D' THEN 8
						WHEN TRIM(BASE_ADENE.EPC_ADENE)='E' THEN 9
						WHEN TRIM(BASE_ADENE.EPC_ADENE)='F' THEN 10
						WHEN TRIM(BASE_ADENE.EPC_ADENE)='G' THEN 11
					END AS FLAG_ORDEM_EPC 
					,CASE 
						WHEN OCR.ENERGY_CERTIFICATION_SYSTEM_CODE_OCR IS NOT NULL THEN 1
						ELSE 0
					END AS FLAG_CRUZA_ADENE_OCR
                    ,RANK() OVER (PARTITION BY BASE_ADENE.COLLATERALASSETID_ADENE ORDER BY COALESCE(BASE_ADENE.EPC_EXPIRATION_DATE_ADENE, '01-01-1900') DESC) AS RANK_DT_VALIDADE
                    FROM 
                    
                      	-- 1º Cruzamento: Informação base da Property Certificate 
                      	--> OUT24 110.742 Registos 
                        (
                      	SELECT 
              		        TRIM(ID) AS ID_ADENE
              		        ,TRIM(COLLATERALASSETID) AS COLLATERALASSETID_ADENE
              		        ,TRIM(GNID) AS GNID_ADENE
              		        ,'ADENE' AS SOURCE_CODE_ADENE
              		        ,TRIM(CREATIONDATE) AS CREATIONDATE_ADENE
              		        ,TRIM(OCRUPDATEDATE) AS OCRUPDATEDATE_ADENE
              		        ,TRIM(ENERGYEFFICIENCYRATING) AS EPC_ADENE
              		        ,TRIM(EPCREFERENCENUMBER) AS ENERGY_CERTIFICATION_SYSTEM_CODE_ADENE
              		        ,TRIM(EPCEXPIRATIONDATE) AS EPC_EXPIRATION_DATE_ADENE
              		        ,DATA_DATE_PART AS DATA_DATE_PART_ADENE 
							,DATA_TIMESTAMP_PART AS DATA_TIMESTAMP_PART_ADENE    
                      	FROM CURATED_INTERNAL_GESTAOIMOVEIS.PROPERTYCERTIFICATE
                      	WHERE TRIM(UPPER(ENERGYEFFICIENCYRATING)) NOT IN ('+','-','S','N','J','')
                      		AND TRIM(DOCUMENTTYPE)='ADENE' 
                      		AND DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM CURATED_INTERNAL_GESTAOIMOVEIS.PROPERTYCERTIFICATE WHERE DATA_DATE_PART <= '${ref_date}')
                        )BASE_ADENE
                      
                      LEFT JOIN
                      	-- 2º Cruzamento: Informação da DOCUMENTS via chave ID da info da ADENE 
                      	--> OUT24 110.742 Registos 	
                        (
                      	SELECT
                      	    TRIM(BUILDINGENERGYCERTIFICATEID) AS BUILDINGENERGYCERTIFICATEID_ADENE_DOC1
                      		,TRIM(ISSUERENTITY) AS LAND_REGISTRY_OFFICE_CODE_ADENE
                      		,TRIM(DOCUMENTNUMBER) AS PROPERTY_IDENTIFICATION_CODE_ADENE
						FROM curated_internal_gestaoimoveis.Documents
                      	WHERE DOCUMENTTYPEDESCRIPTION = 'Nº de inscrição na Conservatória'
						AND DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM CURATED_INTERNAL_GESTAOIMOVEIS.DOCUMENTS WHERE DATA_DATE_PART <= '${ref_date}')
                        )DOC_1 ON BASE_ADENE.ID_ADENE=DOC_1.BUILDINGENERGYCERTIFICATEID_ADENE_DOC1
                      
                      LEFT JOIN 
                      	-- 3º Cruzamento: Informação da DOCUMENTS via chave ID da info da ADENE 
                      	--> OUT24 110.742 Registos 
                        (
                      	SELECT
                      	    TRIM(BUILDINGENERGYCERTIFICATEID) AS BUILDINGENERGYCERTIFICATEID_ADENE_DOC2
                      		,TRIM(DOCUMENTNUMBER) AS CADASTRAL_REGISTER_CODE_ADENE
                      	    FROM curated_internal_gestaoimoveis.Documents
                      		WHERE DOCUMENTTYPEDESCRIPTION = 'Artigo Matricial nº'
                      	        AND DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM curated_internal_gestaoimoveis.Documents WHERE DATA_DATE_PART <= '${ref_date}')
                        )DOC_2 ON BASE_ADENE.ID_ADENE=DOC_2.BUILDINGENERGYCERTIFICATEID_ADENE_DOC2
                      
                      LEFT JOIN
                      	-- 4º Cruzamento: Informação da BuildingEnergyCertificate via chave ID da info da ADENE 
                      	--> OUT24 110.742 Registos  
                        (
                      	SELECT 
              	            TRIM(PROPERTYCERTIFICATEID) AS PROPERTYCERTIFICATEID_ADENE
              	            ,TRIM(TYPEDESCRIPTION) AS CERTIFICATE_TYPE_ADENE
              	            ,TRIM(BUILDINGPURPOSEDESCRIPTION) AS PROPERTY_PURPOSE_CODE_ADENE
              	            ,TRIM(BUILDINGGEOLOCATIONPOSTALADDRESSTOWNNAME) AS LOCALITY_ADENE
              	            ,TRIM(BUILTUPAREAQUANTITY) AS NET_FLOOR_AREA_ADENE
              	            ,TRIM(RENEWABLEENERGYCONTRIBUTIONVALUE) AS REN_ENERGY_PRODUCED_VALUE_ADENE
              	            ,TRIM(CURRENTCARBONFOOTPRINTVALUE) AS CARBON_EMISSION_VALUE_YEAR_ADENE
              	            ,TRIM(NEARZEROBUILDINGINDICATOR) AS NZEB_IND_ADENE
              	            ,TRIM(ISSUEDATE) AS EPC_ISSUING_DATE_ADENE
              	            ,TRIM(BUILDINGGEOLOCATIONLATITUDE) AS GPS_LATITUDE_ADENE
              	            ,TRIM(BUILDINGGEOLOCATIONLONGITUDE) AS GPS_LONGITUDE_ADENE
              	            ,TRIM(BUILDINGGEOLOCATIONPOSTALADDRESSCITYNAME) AS DISTRICT_MUNICIP_PARISH_CODE_ADENE
              	            ,TRIM(BUILDINGGEOLOCATIONPOSTALADDRESSUNITTYPE) AS FLOOR_NUMBER_ADENE
              	            ,TRIM(BUILDINGGEOLOCATIONPOSTALADDRESSFULLADDRESS) AS ADDRESS_CODE_ADENE
							,TRIM(CURRENTEFFICIENCYRATINGPERCENTAGE) AS CURRENT_ENERGY_RATING_PERCENTAGE_ADENE
                      	FROM CURATED_INTERNAL_GESTAOIMOVEIS.BUILDINGENERGYCERTIFICATE
                      	WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM CURATED_INTERNAL_GESTAOIMOVEIS.BUILDINGENERGYCERTIFICATE WHERE DATA_DATE_PART <= '${ref_date}')
                        )BUILD_CERT ON BASE_ADENE.ID_ADENE=BUILD_CERT.PROPERTYCERTIFICATEID_ADENE
          	        LEFT JOIN
          	        	-- 5º Cruzamento: Informação da MajorIndicators via chave ID da info da ADENE 
          	        	--> OUT24 110.742 Registos
                        (
                        SELECT 
							TRIM(BUILDINGENERGYCERTIFICATEID) AS BUILDINGENERGYCERTIFICATEID_ADENE_MAJOR1
							,TRIM(MAJORINDVALUE) AS PRIMARY_ENERGY_REQ_VALUE_ADENE
                        FROM CURATED_INTERNAL_GESTAOIMOVEIS.MAJORINDICATORS
                        WHERE TYPECODE IN ('Ntc','IEE')
							AND DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM CURATED_INTERNAL_GESTAOIMOVEIS.MAJORINDICATORS WHERE DATA_DATE_PART <= '${ref_date}')
                        )MAJOR_1 ON BASE_ADENE.ID_ADENE=MAJOR_1.BUILDINGENERGYCERTIFICATEID_ADENE_MAJOR1
                  
          	        LEFT JOIN
          	        	-- 6º Cruzamento: Informação da MajorIndicators via chave ID da info da ADENE 
          	        	--> OUT24 110.742 Registos
                        (
                        SELECT 
                      	  TRIM(BUILDINGENERGYCERTIFICATEID) AS BUILDINGENERGYCERTIFICATEID_ADENE_MAJOR2
                      	  ,TRIM(MAJORINDVALUE) AS  ENERGY_CONSUMPTION_VALUE_YEAR_ADENE
                        FROM CURATED_INTERNAL_GESTAOIMOVEIS.MAJORINDICATORS
                        WHERE TYPECODE = 'IEE'
                            AND DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM CURATED_INTERNAL_GESTAOIMOVEIS.MAJORINDICATORS WHERE DATA_DATE_PART <= '${ref_date}')
                        )MAJOR_2 ON BASE_ADENE.ID_ADENE=MAJOR_2.BUILDINGENERGYCERTIFICATEID_ADENE_MAJOR2
          	        
					LEFT JOIN
          	        	-- 7º Cruzamento: Informação dos campos exclusivos da OCR
          	        	--> OUT24 110.742 Registos
						(
						SELECT 
							ID_OCR
							,COLLATERALASSETID_OCR
							,ENERGY_CERTIFICATION_SYSTEM_CODE_OCR
							,LAND_REGISTRY_OFFICE_CODE_OCR
							,PROPERTY_IDENTIFICATION_CODE_OCR
							,CADASTRAL_REGISTER_CODE_OCR
							,GPS_LATITUDE_OCR
							,GPS_LONGITUDE_OCR
							,DISTRICT_MUNICIP_PARISH_CODE_OCR
							,FLOOR_NUMBER_OCR
							,ADDRESS_CODE_OCR
						FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_OCR_DEZ24 --Alterar esta tabela consoante o mês que se corre
						)OCR ON BASE_ADENE.GNID_ADENE=OCR.ENERGY_CERTIFICATION_SYSTEM_CODE_OCR AND BASE_ADENE.COLLATERALASSETID_ADENE=OCR.COLLATERALASSETID_OCR
                )TRATAMENTO_0 WHERE RANK_DT_VALIDADE=1 
            )TRATAMENTO_1 WHERE RANK_TRAT_1=1
        )TRATAMENTO_2 WHERE RANK_TRAT_2=1
    )TRATAMENTO_3 WHERE RANK_TRAT_3=1
 
;
--------------------------------------------------------------------------------------------------------------------------------------------------
-- 2.A.2. Criação de uma Tabela Auxiliar com o tratamento de informação da ADENE do Modelo de Gestão de Empreendimentos
		  --> Tratamento dos registos duplicados por Certificado para a mesma data de validade 
		  --> Passo 3 especificado nos Tratamentos necessários / Para os meses de testes (OUT E NOV) existe no máximo 2 registos. 
--------------------------------------------------------------------------------------------------------------------------------------------------

-- OUT24 | Inserted 108.946 row(s)
-- NOV24 | Inserted 110.446 row(s)

--DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_AUX2_DEZ24;
--CREATE TABLE BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_AUX2_DEZ24 AS
--
--SELECT 
--	F1.ID_ADENE
--	,F1.COLLATERALASSETID_ADENE
--	,F1.GNID_ADENE
--	,F1.SOURCE_CODE_ADENE
--	,F1.CREATIONDATE_ADENE
--	,F1.OCRUPDATEDATE_ADENE
--	,CASE WHEN NUM_REG_TRAT_3=1 AND(TRIM(F1.EPC_ADENE)='' OR F1.EPC_ADENE IS NULL THEN F2.EPC_ADENE) ELSE F1.EPC_ADENE END AS EPC_ADENE
--	,F1.ENERGY_CERTIFICATION_SYSTEM_CODE_ADENE
--	,F1.EPC_EXPIRATION_DATE_ADENE
--	,F1.DATA_DATE_PART_ADENE
--	,F1.DATA_TIMESTAMP_PART_ADENE
--	,F1.BUILDINGENERGYCERTIFICATEID_ADENE_DOC1
--	,CASE WHEN NUM_REG_TRAT_3=1 AND (TRIM(F1.LAND_REGISTRY_OFFICE_CODE_ADENE)='' OR F1.LAND_REGISTRY_OFFICE_CODE_ADENE IS NULL THEN F2.LAND_REGISTRY_OFFICE_CODE_ADENE ELSE F1.LAND_REGISTRY_OFFICE_CODE_ADENE END AS LAND_REGISTRY_OFFICE_CODE_ADENE
--	,CASE WHEN NUM_REG_TRAT_3=1 AND (TRIM(F1.PROPERTY_IDENTIFICATION_CODE_ADENE)='' OR F1.PROPERTY_IDENTIFICATION_CODE_ADENE IS NULL THEN F2.PROPERTY_IDENTIFICATION_CODE_ADENE) ELSE F1.PROPERTY_IDENTIFICATION_CODE_ADENE END AS PROPERTY_IDENTIFICATION_CODE_ADENE
--	,F1.BUILDINGENERGYCERTIFICATEID_ADENE_DOC2
--	,CASE WHEN NUM_REG_TRAT_3=1 AND (TRIM(F1.CADASTRAL_REGISTER_CODE_ADENE)='' OR F1.CADASTRAL_REGISTER_CODE_ADENE IS NULL THEN F2.CADASTRAL_REGISTER_CODE_ADENE) ELSE F1.CADASTRAL_REGISTER_CODE_ADENE END AS CADASTRAL_REGISTER_CODE_ADENE
--	,F1.PROPERTYCERTIFICATEID_ADENE
--	,CASE WHEN NUM_REG_TRAT_3=1 AND (TRIM(F1.CERTIFICATE_TYPE_ADENE)='' OR F1.CERTIFICATE_TYPE_ADENE IS NULL THEN F2.CERTIFICATE_TYPE_ADENE) ELSE F1.CERTIFICATE_TYPE_ADENE END AS CERTIFICATE_TYPE_ADENE
--	,CASE WHEN NUM_REG_TRAT_3=1 AND (TRIM(F1.PROPERTY_PURPOSE_CODE_ADENE)='' OR F1.PROPERTY_PURPOSE_CODE_ADENE IS NULL THEN F2.PROPERTY_PURPOSE_CODE_ADENE) ELSE F1.PROPERTY_PURPOSE_CODE_ADENE END AS PROPERTY_PURPOSE_CODE_ADENE
--	,CASE WHEN NUM_REG_TRAT_3=1 AND (TRIM(F1.LOCALITY_ADENE)='' OR F1.LOCALITY_ADENE IS NULL THEN F2.LOCALITY_ADENE) ELSE F1.LOCALITY_ADENE END AS LOCALITY_ADENE
--	,CASE WHEN NUM_REG_TRAT_3=1 AND (TRIM(F1.NET_FLOOR_AREA_ADENE)='' OR F1.NET_FLOOR_AREA_ADENE IS NULL THEN F2.NET_FLOOR_AREA_ADENE) ELSE F1.NET_FLOOR_AREA_ADENE END AS NET_FLOOR_AREA_ADENE
--	,CASE WHEN NUM_REG_TRAT_3=1 AND (TRIM(F1.REN_ENERGY_PRODUCED_VALUE_ADENE)='' OR F1.REN_ENERGY_PRODUCED_VALUE_ADENE IS NULL THEN F2.REN_ENERGY_PRODUCED_VALUE_ADENE) ELSE F1.REN_ENERGY_PRODUCED_VALUE_ADENE END AS REN_ENERGY_PRODUCED_VALUE_ADENE
--	,CASE WHEN NUM_REG_TRAT_3=1 AND (TRIM(F1.CARBON_EMISSION_VALUE_YEAR_ADENE)='' OR F1.CARBON_EMISSION_VALUE_YEAR_ADENE IS NULL THEN F2.CARBON_EMISSION_VALUE_YEAR_ADENE) ELSE F1.CARBON_EMISSION_VALUE_YEAR_ADENE END AS CARBON_EMISSION_VALUE_YEAR_ADENE
--	,CASE WHEN NUM_REG_TRAT_3=1 AND (TRIM(F1.NZEB_IND_ADENE)='' OR F1.NZEB_IND_ADENE IS NULL THEN F2.NZEB_IND_ADENE ELSE F1.NZEB_IND_ADENE) END AS NZEB_IND_ADENE
--	,CASE WHEN NUM_REG_TRAT_3=1 AND (TRIM(F1.EPC_ISSUING_DATE_ADENE)='' OR F1.EPC_ISSUING_DATE_ADENE IS NULL THEN F2.EPC_ISSUING_DATE_ADENE) ELSE F1.EPC_ISSUING_DATE_ADENE END AS EPC_ISSUING_DATE_ADENE
--	,CASE WHEN NUM_REG_TRAT_3=1 AND (TRIM(F1.GPS_LATITUDE_ADENE)='' OR F1.GPS_LATITUDE_ADENE IS NULL THEN F2.GPS_LATITUDE_ADENE ELSE F1.GPS_LATITUDE_ADENE) END AS GPS_LATITUDE_ADENE
--	,CASE WHEN NUM_REG_TRAT_3=1 AND (TRIM(F1.GPS_LONGITUDE_ADENE)='' OR F1.GPS_LONGITUDE_ADENE IS NULL THEN F2.GPS_LONGITUDE_ADENE ELSE F1.GPS_LONGITUDE_ADENE) END AS GPS_LONGITUDE_ADENE
--	,CASE WHEN NUM_REG_TRAT_3=1 AND (TRIM(F1.DISTRICT_MUNICIP_PARISH_CODE_ADENE)='' OR F1.DISTRICT_MUNICIP_PARISH_CODE_ADENE IS NULL THEN F2.DISTRICT_MUNICIP_PARISH_CODE_ADENE) ELSE F1.DISTRICT_MUNICIP_PARISH_CODE_ADENE END AS DISTRICT_MUNICIP_PARISH_CODE_ADENE
--	,CASE WHEN NUM_REG_TRAT_3=1 AND (TRIM(F1.FLOOR_NUMBER_ADENE)='' OR F1.FLOOR_NUMBER_ADENE IS NULL THEN F2.FLOOR_NUMBER_ADENE) ELSE F1.FLOOR_NUMBER_ADENE END AS FLOOR_NUMBER_ADENE
--	,CASE WHEN NUM_REG_TRAT_3=1 AND (TRIM(F1.ADDRESS_CODE_ADENE)='' OR F1.ADDRESS_CODE_ADENE IS NULL THEN F2.ADDRESS_CODE_ADENE) ELSE F1.ADDRESS_CODE_ADENE END AS ADDRESS_CODE_ADENE
--	,F1.BUILDINGENERGYCERTIFICATEID_ADENE_MAJOR1
--	,CASE WHEN NUM_REG_TRAT_3=1 AND (TRIM(F1.PRIMARY_ENERGY_REQ_VALUE_ADENE)='' OR F1.PRIMARY_ENERGY_REQ_VALUE_ADENE IS NULL THEN F2.PRIMARY_ENERGY_REQ_VALUE_ADENE) ELSE F1.PRIMARY_ENERGY_REQ_VALUE_ADENE END AS PRIMARY_ENERGY_REQ_VALUE_ADENE
--	,F1.BUILDINGENERGYCERTIFICATEID_ADENE_MAJOR2
--	,CASE WHEN NUM_REG_TRAT_3=1 AND (TRIM(F1.ENERGY_CONSUMPTION_VALUE_YEAR_ADENE)='' OR F1.ENERGY_CONSUMPTION_VALUE_YEAR_ADENE IS NULL THEN F2.ENERGY_CONSUMPTION_VALUE_YEAR_ADENE) ELSE F1.ENERGY_CONSUMPTION_VALUE_YEAR_ADENE END AS ENERGY_CONSUMPTION_VALUE_YEAR_ADENE
--	,F1.FLAG_CRUZA_ADENE_OCR
--	,F1.FLAG_CAMPOS_PREENC
--	,F1.FLAG_ORDEM_EPC
--	,F1.RANK_TRAT_1
--	,F1.RANK_TRAT_2
--	,F1.RANK_TRAT_3
--	,F1.ID_OCR
--	,F1.COLLATERALASSETID_OCR
--	,F1.ENERGY_CERTIFICATION_SYSTEM_CODE_OCR
--	,F1.LAND_REGISTRY_OFFICE_CODE_OCR
--	,F1.PROPERTY_IDENTIFICATION_CODE_OCR
--	,F1.CADASTRAL_REGISTER_CODE_OCR
--	,F1.GPS_LATITUDE_OCR
--	,F1.GPS_LONGITUDE_OCR
--	,F1.DISTRICT_MUNICIP_PARISH_CODE_OCR
--	,F1.FLOOR_NUMBER_OCR
--	,F1.ADDRESS_CODE_OCR
--FROM 
--	(
--	SELECT *
--	FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_AUX1_DEZ24
--	WHERE RANK_TRAT_3=1
--	)F1 
--LEFT JOIN 
--	(
--	SELECT * 
--	FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_AUX1_DEZ24
--	WHERE RANK_TRAT_3=2
--	)F2 ON F1.COLLATERALASSETID_ADENE=F2.COLLATERALASSETID_ADENE AND F1.ENERGY_CERTIFICATION_SYSTEM_CODE_ADENE=F2.ENERGY_CERTIFICATION_SYSTEM_CODE_ADENE
--;

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 2.A.3. Criação de uma Tabela Auxiliar com o tratamento de informação da ADENE do Modelo de Gestão de Empreendimentos
		  --> Tratamento dos registos duplicados por Certificado para a mesma data de validade 
		  --> Passo 5 especificado nos Tratamentos necessários (O passo 4 é aplicado apenas para a OCR)
		  --> Este passo é necessário correr em HIVE e depois fazer um INVALIDATE METADATA a tabela no IMPALA
--------------------------------------------------------------------------------------------------------------------------------------------------

-- DEZ24 | Inserted row(s)

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_AUX3_DEZ24;
CREATE TABLE BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_AUX3_DEZ24 AS	

SELECT *
	,LEVENSHTEIN (F1.GNID_ADENE,F2.ENERGY_CERTIFICATION_SYSTEM_CODE_OCR) AS FLAG_TROCAS
FROM
	(
	SELECT ID_ADENE,COLLATERALASSETID_ADENE,ENERGY_CERTIFICATION_SYSTEM_CODE_ADENE,TRIM(GNID_ADENE) AS GNID_ADENE
	FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_AUX1_DEZ24
	)F1
LEFT JOIN 
	(
	SELECT DISTINCT COLLATERALASSETID_OCR,TRIM(ENERGY_CERTIFICATION_SYSTEM_CODE_OCR) AS ENERGY_CERTIFICATION_SYSTEM_CODE_OCR
	FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_OCR_DEZ24
	)F2 ON F1.COLLATERALASSETID_ADENE=F2.COLLATERALASSETID_OCR
;
--------------------------------------------------------------------------------------------------------------------------------------------------
-- 2.A.4. Criação de uma Tabela Auxiliar com o tratamento de informação da ADENE do Modelo de Gestão de Empreendimentos
		  --> Tratamento dos registos duplicados por Certificado para a mesma data de validade 
		  --> Passo 5 especificado nos Tratamentos necessários (O passo 4 é aplicado apenas para a OCR)
		  --> Este passo é necessário correr em HIVE e depois fazer um INVALIDATE METADATA a tabela no IMPALA
--------------------------------------------------------------------------------------------------------------------------------------------------

-- DEZ24 | Inserted 111.792 row(s)

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_DEZ24;
CREATE TABLE BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_DEZ24 AS

SELECT *
FROM
	(
	SELECT *
		,RANK() OVER (PARTITION BY CONCAT(COLLATERALASSETID_ADENE,ENERGY_CERTIFICATION_SYSTEM_CODE_ADENE) ORDER BY LENGTH(TRIM(GNID_ADENE)) DESC) AS RANK_TRAT_6
	FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_AUX1_DEZ24
	WHERE ID_ADENE NOT IN 
		(
		SELECT ID_ADENE
		FROM
			(
			SELECT *
				,RANK() OVER (PARTITION BY CONCAT(COLLATERALASSETID_ADENE,ENERGY_CERTIFICATION_SYSTEM_CODE_ADENE) ORDER BY FLAG_TROCAS ASC) AS RANK_TRAT_5
			FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_AUX3_DEZ24
			WHERE ID_ADENE IN (SELECT ID_ADENE FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_AUX1_DEZ24 WHERE CONCAT(COLLATERALASSETID_ADENE,ENERGY_CERTIFICATION_SYSTEM_CODE_ADENE) IN (SELECT CHAVE FROM (SELECT CONCAT(COLLATERALASSETID_ADENE,ENERGY_CERTIFICATION_SYSTEM_CODE_ADENE) AS CHAVE,COUNT(*) AS NUM_REG FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_AUX1_DEZ24 GROUP BY 1 HAVING NUM_REG>1)AUX))
			)TRATAMENTO_5 WHERE RANK_TRAT_5>1 --Este rank elimina os ID que tem mais trocas face ao rank=1
		)
	)TRATAMENTO_6 WHERE RANK_TRAT_6=1
;
--------------------------------------------------------------------------------------------------------------------------------------------------
-- 2.B. Criação de uma Tabela Auxiliar com o tratamento de informação da ADENE do Modelo de Gestão de Empreendimentos
		--> Tratamento dos registos duplicados por Certificado para a mesma data de validade 
		--> Passo 5 especificado nos Tratamentos necessários (O passo 4 é aplicado apenas para a OCR)
		--> Este passo é necessário correr em HIVE e depois fazer um 
--------------------------------------------------------------------------------------------------------------------------------------------------

-- DEZ24 | Inserted 111.259 row(s)

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_STEP2_DEZ24;
CREATE TABLE BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_STEP2_DEZ24 AS

SELECT *
FROM
	(
	SELECT *
		,RANK() OVER (PARTITION BY COLLATERALASSETID_ADENE ORDER BY ID_ADENE DESC) AS RANK_TRAT_12
	FROM
		(
		SELECT *
			,RANK() OVER (PARTITION BY COLLATERALASSETID_ADENE ORDER BY CREATIONDATE_ADENE DESC) AS RANK_TRAT_11
		FROM
			(
			SELECT *
				,RANK() OVER (PARTITION BY COLLATERALASSETID_ADENE ORDER BY FLAG_CRUZA_ADENE_OCR DESC) AS RANK_TRAT_10
			FROM
				(
				SELECT *
					,RANK() OVER (PARTITION BY COLLATERALASSETID_ADENE ORDER BY FLAG_CAMPOS_PREENC DESC) AS RANK_TRAT_9
				FROM
					(
					SELECT *
						,RANK() OVER (PARTITION BY COLLATERALASSETID_ADENE ORDER BY NVL(CAST(REGEXP_REPLACE(REGEXP_REPLACE(NET_FLOOR_AREA_ADENE,'[^0-9,.]',''),',','.') AS DECIMAL(18,6)),0) DESC) AS RANK_TRAT_8
					FROM 
						(
						SELECT *
							,RANK() OVER (PARTITION BY COLLATERALASSETID_ADENE ORDER BY FLAG_ORDEM_EPC DESC) AS RANK_TRAT_7
						FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_DEZ24
						)TRATAMENTO_7 WHERE RANK_TRAT_7=1
					)TRATAMENTO_8 WHERE RANK_TRAT_8=1
				)TRATAMENTO_9 WHERE RANK_TRAT_9=1
			)TRATAMENTO_10 WHERE RANK_TRAT_10=1
		)TRATAMENTO_11 WHERE RANK_TRAT_11=1
	)TRATAMENTO_12 WHERE RANK_TRAT_12=1
;
--------------------------------------------------------------------------------------------------------------------------------------------------
-- 2.C. Criação de uma Tabela Auxiliar com o tratamento de informação da ADENE do Modelo de Gestão de Empreendimentos
		--> Tratamento dos registos duplicados por Certificado para a mesma data de validade 
		--> Passo 5 especificado nos Tratamentos necessários (O passo 4 é aplicado apenas para a OCR)
		--> Este passo é necessário correr em HIVE e depois fazer um 
--------------------------------------------------------------------------------------------------------------------------------------------------

-- DEZ24 | Inserted 111.792 row(s)

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_STEP3_DEZ24;
CREATE TABLE BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_STEP3_DEZ24 AS

SELECT *
	,CAST(REGEXP_REPLACE(REGEXP_REPLACE(F1.NET_FLOOR_AREA_ADENE,'[^0-9,.]',''),',','.')  AS DECIMAL(18,6))/F2.SUM_NET_FLOOR_AREA_ADENE AS PERCENTAGEM
	,(CAST(REGEXP_REPLACE(REGEXP_REPLACE(F1.NET_FLOOR_AREA_ADENE,'[^0-9,.]',''),',','.')  AS DECIMAL(18,6))/F2.SUM_NET_FLOOR_AREA_ADENE)*CAST(REGEXP_REPLACE(REGEXP_REPLACE(F1.REN_ENERGY_PRODUCED_VALUE_ADENE,'[^0-9,.]',''),',','.')  AS DECIMAL(18,6)) AS POND_REN_ENERGY_PRODUCED_VALUE
	--,(CAST(REGEXP_REPLACE(REGEXP_REPLACE(F1.NET_FLOOR_AREA_ADENE,'[^0-9,.]',''),',','.') AS DECIMAL(18,6))/F2.SUM_NET_FLOOR_AREA_ADENE)*CAST(REGEXP_REPLACE(REGEXP_REPLACE(F1.CURRENT_ENERGY_RATING_PERCENTAGE_ADENE,'[^0-9,.]',''),',','.')  AS DECIMAL(18,6)) AS POND_CURRENT_ENERGY_RATING_PERCENTAGE --21/04 - Sem necessidade de cálculo uma vez que este valor vai ser obtido no certificado (sem desenvolvimento do filtro a aplicar)

FROM
	(
	SELECT COLLATERALASSETID_ADENE
		,NET_FLOOR_AREA_ADENE
		,CARBON_EMISSION_VALUE_YEAR_ADENE
		,ENERGY_CONSUMPTION_VALUE_YEAR_ADENE
		,PRIMARY_ENERGY_REQ_VALUE_ADENE
		,REN_ENERGY_PRODUCED_VALUE_ADENE
		,CURRENT_ENERGY_RATING_PERCENTAGE_ADENE
	FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_DEZ24 
	)F1 
LEFT JOIN 
	(
	SELECT 
		COLLATERALASSETID_ADENE AS SUM_COLLATERALASSETID_ADENE 
		,SUM(CAST(REGEXP_REPLACE(REGEXP_REPLACE(NET_FLOOR_AREA_ADENE,'[^0-9,.]',''),',','.') AS DECIMAL(18,6))) AS SUM_NET_FLOOR_AREA_ADENE
		,SUM(CAST(REGEXP_REPLACE(REGEXP_REPLACE(CARBON_EMISSION_VALUE_YEAR_ADENE,'[^0-9,.]',''),',','.')  AS DECIMAL(18,6))) AS SUM_CARBON_EMISSION_VALUE_YEAR_ADENE
		,SUM(CAST(REGEXP_REPLACE(REGEXP_REPLACE(ENERGY_CONSUMPTION_VALUE_YEAR_ADENE,'[^0-9,.]',''),',','.')  AS DECIMAL(18,6))) AS SUM_ENERGY_CONSUMPTION_VALUE_YEAR_ADENE
		,SUM(CAST(REGEXP_REPLACE(REGEXP_REPLACE(PRIMARY_ENERGY_REQ_VALUE_ADENE,'[^0-9,.]',''),',','.')  AS DECIMAL(18,6))) AS SUM_PRIMARY_ENERGY_REQ_VALUE_ADENE
	FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_DEZ24
	GROUP BY 1
	)F2 ON F1.COLLATERALASSETID_ADENE=F2.SUM_COLLATERALASSETID_ADENE
;	
--------------------------------------------------------------------------------------------------------------------------------------------------
-- 3. Criação de uma Tabela Auxiliar com o tratamento de informação da ADENE do Modelo de Gestão de Empreendimentos
--------------------------------------------------------------------------------------------------------------------------------------------------	

-- DEZ24 | Inserted 128.162 row(s)
 
DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.INPUT_GESTEMPR_DEZ24;
CREATE TABLE BU_CAPTOOLS_WORK.INPUT_GESTEMPR_DEZ24 AS

SELECT 
	BASE.CHAVE_BEM
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE.SOURCE_CODE_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR.SOURCE_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE.SOURCE_CODE_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE.SOURCE_CODE_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE.SOURCE_CODE_ADENE
		ELSE OCR.SOURCE_CODE_OCR
	END AS SOURCE_CODE
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE.EPC_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR.EPC_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE.EPC_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE.EPC_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE.EPC_ADENE
		ELSE OCR.EPC_OCR	
	END AS EPC
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE.ENERGY_CERTIFICATION_SYSTEM_CODE_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR.ENERGY_CERTIFICATION_SYSTEM_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE.ENERGY_CERTIFICATION_SYSTEM_CODE_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE.ENERGY_CERTIFICATION_SYSTEM_CODE_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE.ENERGY_CERTIFICATION_SYSTEM_CODE_ADENE
		ELSE OCR.ENERGY_CERTIFICATION_SYSTEM_CODE_OCR
	END AS ENERGY_CERTIFICATION_SYSTEM_CODE
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE.EPC_EXPIRATION_DATE_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR.EPC_EXPIRATION_DATE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE.EPC_EXPIRATION_DATE_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE.EPC_EXPIRATION_DATE_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE.EPC_EXPIRATION_DATE_ADENE
		ELSE OCR.EPC_EXPIRATION_DATE_OCR
	END AS EPC_EXPIRATION_DATE
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE.LAND_REGISTRY_OFFICE_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR.LAND_REGISTRY_OFFICE_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE.LAND_REGISTRY_OFFICE_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE.LAND_REGISTRY_OFFICE_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE.LAND_REGISTRY_OFFICE_CODE_OCR
		ELSE OCR.LAND_REGISTRY_OFFICE_CODE_OCR
	END AS LAND_REGISTRY_OFFICE_CODE
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE.PROPERTY_IDENTIFICATION_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR.PROPERTY_IDENTIFICATION_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE.PROPERTY_IDENTIFICATION_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE.PROPERTY_IDENTIFICATION_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE.PROPERTY_IDENTIFICATION_CODE_OCR
		ELSE OCR.PROPERTY_IDENTIFICATION_CODE_OCR
	END AS PROPERTY_IDENTIFICATION_CODE
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE.CADASTRAL_REGISTER_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR.CADASTRAL_REGISTER_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE.CADASTRAL_REGISTER_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE.CADASTRAL_REGISTER_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE.CADASTRAL_REGISTER_CODE_OCR
		ELSE OCR.CADASTRAL_REGISTER_CODE_OCR
	END AS CADASTRAL_REGISTER_CODE
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE.CERTIFICATE_TYPE_ADENE 
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR.CERTIFICATE_TYPE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE.CERTIFICATE_TYPE_ADENE 
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE.CERTIFICATE_TYPE_ADENE 
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE.CERTIFICATE_TYPE_ADENE 
		ELSE OCR.CERTIFICATE_TYPE_OCR
	END AS CERTIFICATE_TYPE
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE.PROPERTY_PURPOSE_CODE_ADENE  
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR.PROPERTY_PURPOSE_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE.PROPERTY_PURPOSE_CODE_ADENE 
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE.PROPERTY_PURPOSE_CODE_ADENE 
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE.PROPERTY_PURPOSE_CODE_ADENE 
		ELSE OCR.PROPERTY_PURPOSE_CODE_OCR
	END AS PROPERTY_PURPOSE_CODE
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE.LOCALITY_ADENE  
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR.LOCALITY_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE.LOCALITY_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE.LOCALITY_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE.LOCALITY_ADENE
		ELSE OCR.LOCALITY_OCR
	END AS LOCALITY
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE_SUM.SUM_NET_FLOOR_AREA_ADENE  
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR_SUM.SUM_NET_FLOOR_AREA_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE_SUM.SUM_NET_FLOOR_AREA_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE_SUM.SUM_NET_FLOOR_AREA_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE_SUM.SUM_NET_FLOOR_AREA_ADENE
		ELSE OCR_SUM.SUM_NET_FLOOR_AREA_OCR
	END AS NET_FLOOR_AREA
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE_SUM.SUM_POND_REN_ENERGY_PRODUCED_VALUE  
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR_SUM.SUM_POND_REN_ENERGY_PRODUCED_VALUE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE_SUM.SUM_POND_REN_ENERGY_PRODUCED_VALUE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE_SUM.SUM_POND_REN_ENERGY_PRODUCED_VALUE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE_SUM.SUM_POND_REN_ENERGY_PRODUCED_VALUE
		ELSE OCR_SUM.SUM_POND_REN_ENERGY_PRODUCED_VALUE
	END AS REN_ENERGY_PRODUCED_VALUE
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE_SUM.SUM_PRIMARY_ENERGY_REQ_VALUE_ADENE  
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR_SUM.SUM_PRIMARY_ENERGY_REQ_VALUE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE_SUM.SUM_PRIMARY_ENERGY_REQ_VALUE_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE_SUM.SUM_PRIMARY_ENERGY_REQ_VALUE_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE_SUM.SUM_PRIMARY_ENERGY_REQ_VALUE_ADENE
		ELSE OCR_SUM.SUM_PRIMARY_ENERGY_REQ_VALUE_OCR
	END AS CURRENT_ENERGY_RATING_PERCENTAGE --21/04: Falta colocar o denominador (sem desenvolvimento a data)
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN (ADENE_SUM.SUM_CARBON_EMISSION_VALUE_YEAR_ADENE*1000)/ADENE_SUM.SUM_NET_FLOOR_AREA_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN (OCR_SUM.SUM_CARBON_EMISSION_VALUE_YEAR_OCR*1000)/OCR_SUM.SUM_NET_FLOOR_AREA_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN (ADENE_SUM.SUM_CARBON_EMISSION_VALUE_YEAR_ADENE*1000)/ADENE_SUM.SUM_NET_FLOOR_AREA_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN (ADENE_SUM.SUM_CARBON_EMISSION_VALUE_YEAR_ADENE*1000)/ADENE_SUM.SUM_NET_FLOOR_AREA_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN (ADENE_SUM.SUM_CARBON_EMISSION_VALUE_YEAR_ADENE*1000)/ADENE_SUM.SUM_NET_FLOOR_AREA_ADENE
		ELSE (OCR_SUM.SUM_CARBON_EMISSION_VALUE_YEAR_OCR*1000)/OCR_SUM.SUM_NET_FLOOR_AREA_OCR
	END AS CARBON_EMISSION_VALUE_YEAR
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE.NZEB_IND_ADENE  
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR.NZEB_IND_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE.NZEB_IND_ADENE 
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE.NZEB_IND_ADENE 
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE.NZEB_IND_ADENE 
		ELSE OCR.NZEB_IND_OCR
	END AS NZEB_IND
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE.EPC_ISSUING_DATE_ADENE   
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR.EPC_ISSUING_DATE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE.EPC_ISSUING_DATE_ADENE 
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE.EPC_ISSUING_DATE_ADENE 
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE.EPC_ISSUING_DATE_ADENE 
		ELSE OCR.EPC_ISSUING_DATE_OCR
	END AS EPC_ISSUING_DATE
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE.GPS_LATITUDE_OCR   
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR.GPS_LATITUDE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE.GPS_LATITUDE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE.GPS_LATITUDE_OCR 
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE.GPS_LATITUDE_OCR
		ELSE OCR.GPS_LATITUDE_OCR
	END AS GPS_LATITUDE
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE.GPS_LONGITUDE_OCR 
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR.GPS_LONGITUDE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE.GPS_LONGITUDE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE.GPS_LONGITUDE_OCR 
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE.GPS_LONGITUDE_OCR
		ELSE OCR.GPS_LONGITUDE_OCR
	END AS GPS_LONGITUDE
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE.DISTRICT_MUNICIP_PARISH_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR.DISTRICT_MUNICIP_PARISH_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE.DISTRICT_MUNICIP_PARISH_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE.DISTRICT_MUNICIP_PARISH_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE.DISTRICT_MUNICIP_PARISH_CODE_OCR
		ELSE OCR.DISTRICT_MUNICIP_PARISH_CODE_OCR
	END AS DISTRICT_MUNICIP_PARISH_CODE
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE.FLOOR_NUMBER_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR.FLOOR_NUMBER_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE.FLOOR_NUMBER_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE.FLOOR_NUMBER_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE.FLOOR_NUMBER_OCR
		ELSE OCR.FLOOR_NUMBER_OCR
	END AS FLOOR_NUMBER
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE.ADDRESS_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR.ADDRESS_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE.ADDRESS_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE.ADDRESS_CODE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE.ADDRESS_CODE_OCR
		ELSE OCR.ADDRESS_CODE_OCR
	END AS ADDRESS_CODE
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE_SUM.SUM_PRIMARY_ENERGY_REQ_VALUE_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR_SUM.SUM_PRIMARY_ENERGY_REQ_VALUE_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE_SUM.SUM_PRIMARY_ENERGY_REQ_VALUE_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE_SUM.SUM_PRIMARY_ENERGY_REQ_VALUE_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE_SUM.SUM_PRIMARY_ENERGY_REQ_VALUE_ADENE
		ELSE OCR_SUM.SUM_PRIMARY_ENERGY_REQ_VALUE_OCR
	END AS PRIMARY_ENERGY_REQ_VALUE
	,CASE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)<>'' AND (OCR.EPC_EXPIRATION_DATE_OCR IS NULL OR TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='') THEN ADENE_SUM.SUM_ENERGY_CONSUMPTION_VALUE_YEAR_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)<>'' THEN OCR_SUM.SUM_ENERGY_CONSUMPTION_VALUE_YEAR_OCR
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND OCR.EPC_EXPIRATION_DATE_OCR IS NULL THEN ADENE_SUM.SUM_ENERGY_CONSUMPTION_VALUE_YEAR_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND TRIM(ADENE.EPC_EXPIRATION_DATE_ADENE)='' AND TRIM(OCR.EPC_EXPIRATION_DATE_OCR)='' THEN ADENE_SUM.SUM_ENERGY_CONSUMPTION_VALUE_YEAR_ADENE
		WHEN ADENE.COLLATERALASSETID_ADENE IS NOT NULL AND ADENE.EPC_EXPIRATION_DATE_ADENE>=OCR.EPC_EXPIRATION_DATE_OCR THEN ADENE_SUM.SUM_ENERGY_CONSUMPTION_VALUE_YEAR_ADENE
		ELSE OCR_SUM.SUM_ENERGY_CONSUMPTION_VALUE_YEAR_OCR
	END AS ENERGY_CONSUMPTION_VALUE_YEAR
	
FROM
	(
	SELECT DISTINCT TRIM(COLLATERALASSETID) AS CHAVE_BEM   
	FROM CURATED_INTERNAL_GESTAOIMOVEIS.PROPERTYCERTIFICATE
	WHERE TRIM(UPPER(ENERGYEFFICIENCYRATING)) NOT IN ('+','-','S','N','J','')
		AND DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM CURATED_INTERNAL_GESTAOIMOVEIS.PROPERTYCERTIFICATE WHERE DATA_DATE_PART <= '${ref_date}')
	)BASE 
LEFT JOIN 
	(
	SELECT *
	FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_OCR_STEP2_DEZ24
	)OCR ON BASE.CHAVE_BEM=OCR.COLLATERALASSETID_OCR
LEFT JOIN 
	(
	SELECT COLLATERALASSETID_OCR,SUM_NET_FLOOR_AREA_OCR,SUM_CARBON_EMISSION_VALUE_YEAR_OCR,SUM_ENERGY_CONSUMPTION_VALUE_YEAR_OCR,SUM_PRIMARY_ENERGY_REQ_VALUE_OCR
		,SUM(POND_REN_ENERGY_PRODUCED_VALUE) AS SUM_POND_REN_ENERGY_PRODUCED_VALUE
	FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_OCR_STEP3_DEZ24
	GROUP BY 1,2,3,4,5
	)OCR_SUM ON BASE.CHAVE_BEM=OCR_SUM.COLLATERALASSETID_OCR
LEFT JOIN 
	(
	SELECT *
	FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_STEP2_DEZ24
	)ADENE ON BASE.CHAVE_BEM=ADENE.COLLATERALASSETID_ADENE
LEFT JOIN 
	(
	SELECT COLLATERALASSETID_ADENE,SUM_NET_FLOOR_AREA_ADENE,SUM_CARBON_EMISSION_VALUE_YEAR_ADENE,SUM_ENERGY_CONSUMPTION_VALUE_YEAR_ADENE,SUM_PRIMARY_ENERGY_REQ_VALUE_ADENE
		,SUM(POND_REN_ENERGY_PRODUCED_VALUE) AS SUM_POND_REN_ENERGY_PRODUCED_VALUE
	FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_ADENE_STEP3_DEZ24
	GROUP BY 1,2,3,4,5
	)ADENE_SUM ON BASE.CHAVE_BEM=ADENE_SUM.COLLATERALASSETID_ADENE
;

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 3. Criação de uma Tabela Auxiliar com o tratamento de informação da ADENE do Modelo de Gestão de Empreendimentos
--------------------------------------------------------------------------------------------------------------------------------------------------	

-- DEZ24 | Inserted 274.743 row(s)

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.CD_IMV_DEZ_CERTIF_MBI_DEZ24;
CREATE TABLE BU_CAPTOOLS_WORK.CD_IMV_DEZ_CERTIF_MBI_DEZ24_V2 AS

SELECT 
	UNIV.PROPERTY_BANK_ID
	,UNIV.PROPERTY_BRANCH_CODE
	,UNIV.PROPERTY_CONTRACT_ID
	,UNIV.PROPERTY_REFERENCE_CODE
	,GEST_EMPR.LAND_REGISTRY_OFFICE_CODE
	,GEST_EMPR.PROPERTY_IDENTIFICATION_CODE
	,GEST_EMPR.ENERGY_CERTIFICATION_SYSTEM_CODE
	,CASE WHEN GEST_EMPR.CHAVE_BEM IS NOT NULL THEN GEST_EMPR.EPC_ISSUING_DATE ELSE GPT_31.DSISAEMI_31 END AS EPC_ISSUING_DATE
	,GEST_EMPR.epc_expiration_date
	,CASE WHEN GEST_EMPR.CHAVE_BEM IS NOT NULL THEN GEST_EMPR.EPC WHEN GPT_31.CHAVE_BEM_18 IS NOT NULL THEN GPT_31.IENERG_31 WHEN GLOVAL.CHAVE_BEM IS NOT NULL THEN GLOVAL.EPC END AS EPC
	,0 AS ENERGY_CONSUMPTION_TYPE_S_IND
	,0 AS ENERGY_CONSUMPTION_TYPE_T_IND
	,0 AS ENERGY_EFFICIENCY_IND
	,0 AS REN_ENERGY_EFFICIENCY_IND
	,GEST_EMPR.NZEB_IND
	,CASE WHEN GEST_EMPR.CHAVE_BEM IS NOT NULL THEN '1-REAL' WHEN GPT_31.CHAVE_BEM_18 IS NOT NULL THEN '1-REAL' WHEN GLOVAL.CHAVE_BEM IS NOT NULL THEN GLOVAL.ACTUAL_VALUE_IND END AS QUALITY_SCORE
	,CASE 
		WHEN GEST_EMPR.CHAVE_BEM IS NOT NULL AND GEST_EMPR.PRIMARY_ENERGY_REQ_VALUE IS NOT NULL THEN GEST_EMPR.PRIMARY_ENERGY_REQ_VALUE
		WHEN GLOVAL.CHAVE_BEM IS NOT NULL THEN GLOVAL.ENERGY_CONSUMPTION_VALUE_YEAR 
	END AS EP_SCORE
	,CONCAT
		(
			CASE 
				WHEN GEST_EMPR.CHAVE_BEM IS NOT NULL THEN GEST_EMPR.SOURCE_CODE 
				WHEN GPT_31.CHAVE_BEM_18 IS NOT NULL THEN 'GPT31' 
				WHEN GLOVAL.CHAVE_BEM IS NOT NULL THEN 'GLOVAL'
				ELSE 'MISS'
			END 
		,';',
			CASE 
				WHEN GEST_EMPR.CHAVE_BEM IS NOT NULL AND GEST_EMPR.PRIMARY_ENERGY_REQ_VALUE IS NOT NULL THEN GEST_EMPR.SOURCE_CODE
				WHEN GLOVAL.ENERGY_CONSUMPTION_VALUE_YEAR  IS NOT NULL THEN 'GLOVAL'
				ELSE 'MISS'
			END 
		,';',
			CASE 
				WHEN GEST_EMPR.CHAVE_BEM IS NOT NULL AND GEST_EMPR.CARBON_EMISSION_VALUE_YEAR IS NOT NULL THEN GEST_EMPR.SOURCE_CODE 
				WHEN GLOVAL.CARBON_EMISSION_VALUE_YEAR IS NOT NULL THEN 'GLOVAL'
				ELSE 'MISS'
			END 
		,';',
			CASE 
				WHEN GEST_EMPR.CHAVE_BEM IS NOT NULL AND GEST_EMPR.PRIMARY_ENERGY_REQ_VALUE IS NOT NULL THEN GEST_EMPR.SOURCE_CODE 
				WHEN GLOVAL.ENERGY_CONSUMPTION_VALUE_YEAR IS NOT NULL THEN 'GLOVAL'
				ELSE 'MISS'
			END  
		)
	AS SOURCE_CODE
	,'${ref_date}' AS DATA_DATE_PART
	,GEST_EMPR.CERTIFICATE_TYPE
	,0 AS BUILDING_DOMEST_HOTWATER_VALUE
	,0 AS RENEWABLE_DOMEST_HOTWATER_VALUE
	,0 AS DOMEST_HOTWATER_REF_VALUE
	,0 AS HEIGHT
	,0 AS BUILDING_SPACE_HEATING_VALUE
	,0 AS SPACE_HEATING_REF_VALUE
	,0 AS RENEWABLE_SPACE_HEATING_VALUE
	,0 AS BUILDING_SPACE_COOLING_VALUE
	,0 AS RENEWABLE_SPACE_COOLING_VALUE
	,0 AS SPACE_COOLING_REF_VALUE
	,0 AS USEFUL_ENERGY_HEATING_REQ_VALUE
	,'' AS THERMAL_BEHAVIOUR_ROOF
	,'' AS THERMAL_BEHAVIOUR_WINDOWS
	,'' AS THERMAL_BEHAVIOUR_WALL
	,'' AS THERMAL_BEHAVIOUR_FLOORS
	,'' AS THERMAL_BEHAVIOUR_TECH_SYS_VENT
	,0 AS TOTAL_INVSTMNT_ESTMTD_VALUE
	,0 AS DURATION_SUMMER
	,0 AS DURATION_WINTER
	,CASE 
		WHEN GEST_EMPR.CHAVE_BEM IS NOT NULL AND GEST_EMPR.CARBON_EMISSION_VALUE_YEAR IS NOT NULL THEN GEST_EMPR.CARBON_EMISSION_VALUE_YEAR 
		WHEN GLOVAL.CHAVE_BEM IS NOT NULL THEN GLOVAL.CARBON_EMISSION_VALUE_YEAR 
	END AS CARBON_EMISSION_VALUE_YEAR
	,0 AS CARBON_EMISSION_VALUE
	,0 AS USEFUL_ENERGY_FANS_REQ_VALUE
	,0 AS REN_ENERGY_PRODUCED_OTHER_VALUE
	,0 AS REN_ENERGY_PRODUCED_REG_VALUE
	,GEST_EMPR.REN_ENERGY_PRODUCED_VALUE
	,0 AS USEFUL_ENERGY_DOM_HOTWATER_VALUE
	,0 AS USEFUL_ENERGY_COOLING_VALUE
	,0 AS TEMPERATURE_DAY_VALUE
	,CASE 
		WHEN GEST_EMPR.CHAVE_BEM IS NOT NULL AND GEST_EMPR.PRIMARY_ENERGY_REQ_VALUE IS NOT NULL THEN GEST_EMPR.PRIMARY_ENERGY_REQ_VALUE 
		WHEN GLOVAL.CHAVE_BEM IS NOT NULL THEN GLOVAL.ENERGY_CONSUMPTION_VALUE_YEAR 
	END AS PRIMARY_ENERGY_REQ_VALUE
	,GEST_EMPR.ENERGY_CONSUMPTION_VALUE_YEAR 
	,'' AS PNL_WINTER_WALLS_DOORS_VALUE
	,'' AS PNL_WINTER_FLOORS_VALUE
	,'' AS PNL_WINTER_ROOF_VALUE
	,'' AS PNL_WINTER_WINDOWS_VALUE
	,'' AS PNL_WINTER_REF_VALUE
	,'' AS PNL_WINTER_FANS_VALUE
	,'' AS PNL_SUMMER_ROOF_VALUE
	,'' AS PNL_SUMMER_WINDOWS_VALUE
	,'' AS PNL_SUMMER_WALLS_DOORS_VALUE
	,'' AS PNL_SUMMER_REF_VALUE
	,0 AS INVOICE_RED_ANNUAL_ESTMTD_VALUE
	,0 AS TEMPERATURE_OUTDOOR_AVG_VALUE
	,'' AS CLIMATE_ZONE_WINTER
	,'' AS CLIMATE_ZONE_SUMMER
	,GEST_EMPR.GPS_LATITUDE
	,GEST_EMPR.GPS_LONGITUDE
	,ROUND(GEST_EMPR.NET_FLOOR_AREA,2) AS NET_FLOOR_AREA
	,GEST_EMPR.CADASTRAL_REGISTER_CODE
	,GEST_EMPR.DISTRICT_MUNICIP_PARISH_CODE
	,GEST_EMPR.PROPERTY_PURPOSE_CODE
	,GEST_EMPR.ADDRESS_CODE
	,GEST_EMPR.FLOOR_NUMBER
	,GEST_EMPR.LOCALITY
	,0 AS ENERGY_CLASS_AFTER_MEASUREMENT
	,GEST_EMPR.CURRENT_ENERGY_RATING_PERCENTAGE

FROM 
	-- 1º Cruzamento: Obter todo o universo de bens do MBI 
	--> JUN24 274.958 bens
	(
	SELECT DISTINCT PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE
		,CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE
		,CONCAT(PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID) AS CHAVE_S
    FROM BU_ESG_WORK.PROPERTY
    WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BU_ESG_WORK.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
	)UNIV

LEFT JOIN 
	-- 2º Cruzamento: Obter informação do Modelo de Gestão de Empreendimentos 
	--> JUN24 XXX registos
	(
	SELECT * 
	FROM BU_CAPTOOLS_WORK.INPUT_GESTEMPR_DEZ24
	)GEST_EMPR ON UNIV.CHAVE_S=GEST_EMPR.CHAVE_BEM

LEFT JOIN 
 
	-- 3º Cruzamento: Obter informação do Modelo de Gestão de Empreendimentos 
	--> JUN24 XXX registos
	--> Nota importante: Para o universo em questão não é ncessário realizar mais tratamento, no entanto, se for necessário, considerar O registo com: 1) dt_proc mais recente 2)zversão_31 maior 3) Pior EPC 
	(
	SELECT DISTINCT CHAVE_BEM_18,IENERG_31,DSISAEMI_31
	FROM    
		(
		SELECT *
			,RANK() OVER (PARTITION BY CHAVE_BEM_18 ORDER BY DTPROC ASC) AS RANK_TRAT_1
		FROM
			(
			SELECT *
				,COUNT(*) OVER (PARTITION BY GPT31.CHAVE_31) AS NUM_PROC_BEM
			FROM
				(
				SELECT *
				from
					(
					SELECT DISTINCT CHAVE_21,ZVERSAO_21,ZSEQVER_21
					FROM
						(
						SELECT CONCAT(CKBALCAO,CKNUMCTA) AS CHAVE_21,ZVERSAO AS ZVERSAO_21,ZSEQVER AS ZSEQVER_21
							,RANK() OVER (PARTITION BY CONCAT(CKBALCAO,CKNUMCTA) ORDER BY ZSEQVER DESC) AS RANK_TRAT_1
						FROM CD_EMPRESTIMOS.GPT21_PROCESSOS
						WHERE DATA_DATE_PART='2024-12-31'
							AND CODEST='FOR'
							--AND CONCAT(CKBALCAO,CKNUMCTA)='513000495313800'
						)AUX WHERE RANK_TRAT_1=1
					)F1
				LEFT JOIN 
					(
					SELECT DISTINCT CHAVE_21_DT,dtproc
					FROM
						(
						SELECT *
							,RANK() OVER (PARTITION BY CHAVE_21_DT ORDER BY dtproc ASC) AS RANK_TRAT_2B
							FROM
							(
							SELECT CONCAT(CKBALCAO,CKNUMCTA) AS CHAVE_21_DT,dtproc
								,RANK() OVER (PARTITION BY CONCAT(CKBALCAO,CKNUMCTA) ORDER BY ZSEQVER ASC) AS RANK_TRAT_2A
							FROM CD_EMPRESTIMOS.GPT21_PROCESSOS
							WHERE DATA_DATE_PART='2024-12-31'
								AND CODEST='FOR'
								--AND CONCAT(CEMPRESA,CKBALCAO,CKNUMCTA)='31003000496412630'
							)AUX_1 WHERE RANK_TRAT_2A=1
						)AUX_2 WHERE RANK_TRAT_2B=1  
					)F2 ON F1.CHAVE_21=F2.CHAVE_21_DT
				)GPT21 
			LEFT JOIN
				(
				SELECT DISTINCT CONCAT(CKBALBEM,CKCTABEM) AS CHAVE_BEM_18,CONCAT(CKBALCAO,CKNUMCTA) AS CHAVE_18,zversao AS zversao_18
				FROM CD_EMPRESTIMOS.GPT18_BENS
				WHERE DATA_DATE_PART='2024-12-31'
					--AND CONCAT(CKBALBEM,CKCTABEM)='004000497764250'
				)GTP18 ON GPT21.CHAVE_21=GTP18.CHAVE_18 AND GPT21.ZSEQVER_21=GTP18.ZVERSAO_18
			LEFT JOIN 
				(
				SELECT DISTINCT CHAVE_31,zversao_31,IENERG_31,DSISAEMI_31
				FROM
					(
					SELECT concat(ckbalcao,cknumcta) AS CHAVE_31,zversao AS zversao_31,TRIM(IENERG) AS IENERG_31,DSISAEMI AS DSISAEMI_31
						,RANK() OVER (PARTITION BY CONCAT(CKBALCAO,CKNUMCTA) ORDER BY zversao DESC) AS RANK_TRAT_31
					FROM CD_EMPRESTIMOS.GPT31_CONTRATO
					WHERE DATA_DATE_PART IN (SELECT MAX(DATA_DATE_PART) FROM CD_EMPRESTIMOS.GPT31_CONTRATO)
						AND TRIM(IENERG) NOT IN ('+','-','S','N','J','')
					)AUX_TRAT WHERE RANK_TRAT_31=1
				)GPT31 ON GTP18.CHAVE_18=GPT31.CHAVE_31 
				WHERE GPT31.CHAVE_31 IS NOT NULL
			)TRAT_1 WHERE NUM_PROC_BEM=1
		)TRAT_2 WHERE RANK_TRAT_1=1
	)GPT_31 ON UNIV.CHAVE_S=GPT_31.CHAVE_BEM_18 AND GEST_EMPR.CHAVE_BEM IS NULL 

LEFT JOIN 
 
	-- 4º Cruzamento: Obter informação do Modelo de Gestão de Empreendimentos 
	--> JUN24 XXX registos
	(
	SELECT CONCAT(Q1.property_bank_id,Q1.property_branch_code,Q1.property_contract_id,Q1.property_reference_code) AS CHAVE_BEM
	    ,CASE WHEN TRIM(Q2.FIABILIDAD)='SANTANDER' THEN '1-REAL' ELSE Q2.FIABILIDAD END AS ACTUAL_VALUE_IND
	    ,Q2.classe_energetica AS EPC
	    ,Q2.EMISSIONES AS CARBON_EMISSION_VALUE_YEAR
	    ,Q2.CONSUMOS AS ENERGY_CONSUMPTION_VALUE_YEAR
	FROM 
		(
		SELECT *
		FROM 
			(
			SELECT data_envio,property_bank_id,property_branch_code,property_contract_id,property_reference_code,chave_gloval,
				RANK() OVER (PARTITION BY CONCAT(NVL(property_bank_id,''),NVL(property_branch_code,''),NVL(property_contract_id,''),NVL(property_reference_code,'')) ORDER BY DATA_ENVIO DESC) AS RANK_1
			FROM (SELECT DISTINCT data_envio,property_bank_id,property_branch_code,property_contract_id,property_reference_code,chave_gloval FROM cd_esg.energy_certificate_est_input)X
			WHERE 1=1 --TRIM(classe_energetica) NOT IN ('+','-','S','N','J','')
				AND TRIM(data_envio)<>''
			)AUX WHERE RANK_1=1 
		)Q1
	LEFT JOIN 
		(
		SELECT *
		FROM
			(
			SELECT *
				,RANK() OVER (PARTITION BY CHAVE_GLOVAL ORDER BY FLAG_ORDEM_EPC DESC, FLAG_ORDEM_FIABI DESC, AVG_VALUES DESC ) AS RANK_TRAT_2
			FROM 
				(
				SELECT chave_gloval,ref_date,FIABILIDAD,classe_energetica,EMISSIONES,CONSUMOS
					,RANK() OVER (PARTITION BY CHAVE_GLOVAL ORDER BY REF_DATE DESC) AS RANK_TRAT
					,CASE 
						WHEN TRIM(classe_energetica)='A+' THEN 1
						WHEN TRIM(classe_energetica)='A' THEN 2
						WHEN TRIM(classe_energetica)='A-' THEN 3
						WHEN TRIM(classe_energetica)='B+' THEN 4
						WHEN TRIM(classe_energetica)='B' THEN 5
						WHEN TRIM(classe_energetica)='B-' THEN 6
						WHEN TRIM(classe_energetica)='C' THEN 7
						WHEN TRIM(classe_energetica)='D' THEN 8
						WHEN TRIM(classe_energetica)='E' THEN 9
						WHEN TRIM(classe_energetica)='F' THEN 10
						WHEN TRIM(classe_energetica)='G' THEN 11
						WHEN TRIM(classe_energetica)='' THEN 12
					END AS FLAG_ORDEM_EPC 
					,CASE
						WHEN TRIM(FIABILIDAD) IN ('SANTANDER','1-REAL') THEN 1
						WHEN TRIM(FIABILIDAD) ='2-MUY ALTA' THEN 2
						WHEN TRIM(FIABILIDAD)='3-ALTA' THEN 3
						WHEN TRIM(FIABILIDAD) ='4-MEDIA' THEN 4
						WHEN TRIM(FIABILIDAD) ='5-MEDIA BAJA' THEN 5
						WHEN TRIM(FIABILIDAD) ='6-BAJA' THEN 6
						WHEN TRIM(FIABILIDAD) ='7-SIN DATO' THEN 7
						WHEN TRIM(FIABILIDAD) ='' THEN 8
					END AS FLAG_ORDEM_FIABI
					,0.5*(NVL(EMISSIONES,0)+NVL(CONSUMOS,0)) AS AVG_VALUES
				FROM (SELECT DISTINCT chave_gloval,ref_date,FIABILIDAD,classe_energetica,EMISSIONES,CONSUMOS FROM cd_esg.energy_certificate_est_input)Y
				WHERE 1=1--TRIM(classe_energetica) NOT IN ('+','-','S','N','J','')'
				)AUX WHERE RANK_TRAT=1 
			)AUX_2 WHERE RANK_TRAT_2=1
		)Q2 ON Q1.chave_gloval=Q2.CHAVE_GLOVAL
	)GLOVAL ON UNIV.CHAVE=GLOVAL.CHAVE_BEM --AND GEST_EMPR.CHAVE_BEM IS NULL AND GPT_31.CHAVE_BEM_18 IS NULL 
;


--------------------------------------------------------------------------------------------------------------------------------------------------
-- 4. VALIDAÇÕES CALCULADORA 
--------------------------------------------------------------------------------------------------------------------------------------------------	

		-- VALIDAÇÃO 1 
SELECT *
FROM 
    (
    SELECT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE,EPC,SOURCE_CODE,QUALITY_SCORE
    FROM BUSINESS_ASSETS.PROPERTY_ENERGY_CERTIFICATE
    WHERE DATA_DATE_PART='2024-12-31'
    )F1 
FULL JOIN 
    (
    SELECT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE,EPC,SOURCE_CODE,QUALITY_SCORE 
    FROM BU_CAPTOOLS_WORK.CD_IMV_DEZ_CERTIF_MBI_DEZ24_V2
    )F2 ON F1.CHAVE=F2.CHAVE
WHERE F1.EPC<>F2.EPC OR (F1.EPC IS NULL AND F2.EPC IS NOT NULL) OR (F1.EPC IS NOT NULL AND F2.EPC IS NULL)