
/*===================================================================================================================================================
                                                      
											SIMULAÇÃO MODESG_OUT_BENS_IMOVEIS - MODELO VERDE
										                    NEYOND 2024 - V1.0 
															    
 ===================================================================================================================================================*/
 

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 1. Criação da tabela - ORIGINAL  
--------------------------------------------------------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.BENS_IMOVEIS_MV_DEZ24;
CREATE TABLE BU_CAPTOOLS_WORK.BENS_IMOVEIS_MV_DEZ24 AS

SELECT 
	BASE.*
	,EPC.EPC
	,EPC.QUALITY_SCORE
	,FIN_BEM.TIPO_FINALIDADE_BEM
	,FIN_BEM.VALOR_ORIGINAL
	,FIN_BEM.TIPO_FINALIDADE_BEM_2
	,CASE
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN 'Nao Aplicavel' 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS3_2A'
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B' -- HF: E-mail da Corp no dia 14/Nov com a indicação que caso o EPC não se encontre no input (exemplo EPC G para Residential total ('31003014433390000000000000000000')) deve ser considerado a linha do input sem EPC 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP1_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP1_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		ELSE 'MISS'
	END AS ORIGEM_SCP1_EMSS
	,CASE 
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN 'Nao Aplicavel' 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS3_2A'
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP2_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP2_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		ELSE 'MISS'
	END AS ORIGEM_SCP2_EMSS
	,CASE WHEN TRIM(BASE.CHAVE_BEM)='' THEN '1'END AS ORIGEM_SCP3_EMSS
	,CASE  
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN NULL 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP1_FTR_EMSS IS NOT NULL THEN EMISS_3.SCP1_FTR_EMSS
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP1_FTR_EMSS IS NOT NULL THEN EMISS_4.SCP1_FTR_EMSS
		ELSE NULL
	END AS SCP1_EMSS
	,CASE  
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN NULL 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP2_FTR_EMSS IS NOT NULL THEN EMISS_3.SCP2_FTR_EMSS
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP2_FTR_EMSS IS NOT NULL THEN EMISS_4.SCP2_FTR_EMSS
		ELSE NULL
	END AS SCP2_EMSS
	
FROM 

	-- 1º Cruzamento: Obter o Universo Base 
	--> SET24 275.266 Registos 
	(
	SELECT DISTINCT PROPERTY_BANK_ID AS CEMPBEM
	
		,PROPERTY_BRANCH_CODE AS CKBALBEM
		,PROPERTY_CONTRACT_ID AS CKCTABEM
		,PROPERTY_REFERENCE_CODE AS CKREFBEM
		,CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,NET_FLOOR_AREA
	FROM BUSINESS_ASSETS.PROPERTY
    WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BUSINESS_ASSETS.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
	)BASE 

LEFT JOIN 

	-- 2º Cruzamento: Obter o EPC 
	--> SET24 275.266 Registos
	(
	SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,TRIM(UPPER(EPC)) AS EPC,TRIM(QUALITY_SCORE) AS QUALITY_SCORE
	FROM BUSINESS_ASSETS.PROPERTY_ENERGY_CERTIFICATE
    WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BUSINESS_ASSETS.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
		AND TRIM(QUALITY_SCORE) IN ('1-REAL', 'SANTANDER')
	)EPC ON BASE.CHAVE_BEM = EPC.CHAVE_BEM 

LEFT JOIN

	-- 3º Cruzamento: Obter a Finalidade do Bem de acordo com a parametrização 
	--> SET24 275.266 Registos
	(
	SELECT *
		,TRIM(UPPER(CASE
			WHEN VALOR_ORIGINAL ='1_01' THEN 'Residential Total'
			WHEN VALOR_ORIGINAL ='1_03' THEN 'Office'
			WHEN VALOR_ORIGINAL ='1_05' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_02' THEN 'Retail - high street'
			WHEN VALOR_ORIGINAL ='1_04' THEN 'Retail - warehouse'
			WHEN VALOR_ORIGINAL ='1_08' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_'   THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_07' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='1_06' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='1_11' THEN 'Healthcare'
			WHEN VALOR_ORIGINAL ='1_09' THEN 'Hotel'
			WHEN VALOR_ORIGINAL ='1_12' THEN 'Leisure/Lodging'
			WHEN VALOR_ORIGINAL ='1_14' THEN 'Retail - shopping center'
			WHEN VALOR_ORIGINAL ='1_10' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_13' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='0_01' THEN 'Residential Total'
			WHEN VALOR_ORIGINAL ='0_03' THEN 'Office'
			WHEN VALOR_ORIGINAL ='0_05' THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_02' THEN 'Retail High-street'
			WHEN VALOR_ORIGINAL ='0_04' THEN 'Retail Warehouse'
			WHEN VALOR_ORIGINAL ='0_08' THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_'   THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_07' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='0_06' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='0_11' THEN 'Healthcare'
			WHEN VALOR_ORIGINAL ='0_09' THEN 'Hotel'
			WHEN VALOR_ORIGINAL ='0_12' THEN 'Lodge/Leisure'
			WHEN VALOR_ORIGINAL ='0_14' THEN 'Shopping Center'
			WHEN VALOR_ORIGINAL ='0_10' THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_13' THEN 'Non-residential buildings'
		ELSE 'SEM PARAMET'
		END)) AS TIPO_FINALIDADE_BEM
		,'NON-RESIDENTIAL BUILDINGS' AS TIPO_FINALIDADE_BEM_2
	FROM
		(
		SELECT 
			F1.*
			,CASE 
				WHEN F2.CHAVE_BEM IS NOT NULL THEN concat_ws('_','1',TRIM(F1.PROPERTY_PURPOSE_CODE))
				ELSE concat_ws('_','0',TRIM(F1.PROPERTY_PURPOSE_CODE))
			END AS VALOR_ORIGINAL
		FROM 
			(
			SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,PROPERTY_PURPOSE_CODE
			FROM BUSINESS_ASSETS.PROPERTY
			WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BUSINESS_ASSETS.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
			)F1 
		LEFT JOIN 
			(
			SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,EPC,TRIM(QUALITY_SCORE)
			FROM BUSINESS_ASSETS.PROPERTY_ENERGY_CERTIFICATE
			WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BUSINESS_ASSETS.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
				AND TRIM(QUALITY_SCORE) IN ('1-REAL', 'SANTANDER')
			)F2 ON F1.CHAVE_BEM = F2.CHAVE_BEM
		)AUX_1
	)FIN_BEM ON BASE.CHAVE_BEM = FIN_BEM.CHAVE_BEM 

LEFT JOIN

	-- 4º Cruzamento: Obter as métricas para o universo com EPC e Área útil  
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='FLOOR AREA'
		)AUX WHERE ROW_1=1
	)EMISS_1 ON EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.EPC_AUX=EPC.EPC AND EMISS_1.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN

	-- 5º Cruzamento: Obter as métricas para o universo com EPC e Área útil mas o EPC não consta na tabela de input (exemplo EPC G para Residential total)
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='FLOOR AREA'
			AND (TRIM(EPC)='' OR EPC IS NULL)
		)AUX WHERE ROW_1=1
	)EMISS_1B ON EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN 
	-- 6º Cruzamento: Obter as métricas para o universo sem EPC mas com Área útil
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='FLOOR AREA'
			AND (TRIM(EPC)='' OR EPC IS NULL)
		)AUX WHERE ROW_1=1
	)EMISS_2 ON EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN 
	-- 7º Cruzamento: Obter as métricas para o universo sem Área útil 
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='DWELLING'
			AND (TRIM(EPC)='' OR EPC IS NULL)
		)AUX WHERE ROW_1=1
	)EMISS_3 ON BASE.NET_FLOOR_AREA=0  AND EMISS_3.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN 
	-- 8º Cruzamento: Obter as métricas para o universo sem Área útil que não foi possivel obter no 7º cruzamento (nestes casos é assumido a seguinte finalidade: NON-RESIDENTIAL BUILDINGS)
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='DWELLING'
			AND (TRIM(EPC)='' OR EPC IS NULL)
		)AUX WHERE ROW_1=1
	)EMISS_4 ON BASE.NET_FLOOR_AREA=0  AND EMISS_4.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM_2

;

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 2. Criação da tabela - CENÁRIO 1 // Considerar todos os EPC's Reais 
--------------------------------------------------------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.BENS_IMOVEIS_MV_DEZ24_OP1;
CREATE TABLE BU_CAPTOOLS_WORK.BENS_IMOVEIS_MV_DEZ24_OP1 AS

SELECT 
	BASE.*
	,EPC.EPC
	,EPC.QUALITY_SCORE
	,FIN_BEM.TIPO_FINALIDADE_BEM
	,FIN_BEM.VALOR_ORIGINAL
	,FIN_BEM.TIPO_FINALIDADE_BEM_2
	,CASE
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN 'Nao Aplicavel' 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS3_2A'
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B' -- HF: E-mail da Corp no dia 14/Nov com a indicação que caso o EPC não se encontre no input (exemplo EPC G para Residential total ('31003014433390000000000000000000')) deve ser considerado a linha do input sem EPC 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP1_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP1_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		ELSE 'MISS'
	END AS ORIGEM_SCP1_EMSS
	,CASE 
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN 'Nao Aplicavel' 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS3_2A'
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP2_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP2_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		ELSE 'MISS'
	END AS ORIGEM_SCP2_EMSS
	,CASE WHEN TRIM(BASE.CHAVE_BEM)='' THEN '1'END AS ORIGEM_SCP3_EMSS
	,CASE  
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN NULL 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP1_FTR_EMSS IS NOT NULL THEN EMISS_3.SCP1_FTR_EMSS
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP1_FTR_EMSS IS NOT NULL THEN EMISS_4.SCP1_FTR_EMSS
		ELSE NULL
	END AS SCP1_EMSS
	,CASE  
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN NULL 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP2_FTR_EMSS IS NOT NULL THEN EMISS_3.SCP2_FTR_EMSS
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP2_FTR_EMSS IS NOT NULL THEN EMISS_4.SCP2_FTR_EMSS
		ELSE NULL
	END AS SCP2_EMSS
	
FROM 

	-- 1º Cruzamento: Obter o Universo Base 
	--> SET24 275.266 Registos 
	(
	SELECT DISTINCT PROPERTY_BANK_ID AS CEMPBEM
	
		,PROPERTY_BRANCH_CODE AS CKBALBEM
		,PROPERTY_CONTRACT_ID AS CKCTABEM
		,PROPERTY_REFERENCE_CODE AS CKREFBEM
		,CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,NET_FLOOR_AREA
	FROM BUSINESS_ASSETS.PROPERTY
    WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BUSINESS_ASSETS.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
	)BASE 

LEFT JOIN 

	-- 2º Cruzamento: Obter o EPC 
	--> SET24 275.266 Registos
	(
	SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,TRIM(UPPER(EPC)) AS EPC,TRIM(QUALITY_SCORE) AS QUALITY_SCORE
	FROM BUSINESS_ASSETS.PROPERTY_ENERGY_CERTIFICATE
    WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BUSINESS_ASSETS.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
	--	AND TRIM(QUALITY_SCORE) IN ('1-REAL', 'SANTANDER')
		AND EPC IS NOT NULL 
	)EPC ON BASE.CHAVE_BEM = EPC.CHAVE_BEM 

LEFT JOIN

	-- 3º Cruzamento: Obter a Finalidade do Bem de acordo com a parametrização 
	--> SET24 275.266 Registos
	(
	SELECT *
		,TRIM(UPPER(CASE
			WHEN VALOR_ORIGINAL ='1_01' THEN 'Residential Total'
			WHEN VALOR_ORIGINAL ='1_03' THEN 'Office'
			WHEN VALOR_ORIGINAL ='1_05' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_02' THEN 'Retail - high street'
			WHEN VALOR_ORIGINAL ='1_04' THEN 'Retail - warehouse'
			WHEN VALOR_ORIGINAL ='1_08' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_'   THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_07' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='1_06' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='1_11' THEN 'Healthcare'
			WHEN VALOR_ORIGINAL ='1_09' THEN 'Hotel'
			WHEN VALOR_ORIGINAL ='1_12' THEN 'Leisure/Lodging'
			WHEN VALOR_ORIGINAL ='1_14' THEN 'Retail - shopping center'
			WHEN VALOR_ORIGINAL ='1_10' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_13' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='0_01' THEN 'Residential Total'
			WHEN VALOR_ORIGINAL ='0_03' THEN 'Office'
			WHEN VALOR_ORIGINAL ='0_05' THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_02' THEN 'Retail High-street'
			WHEN VALOR_ORIGINAL ='0_04' THEN 'Retail Warehouse'
			WHEN VALOR_ORIGINAL ='0_08' THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_'   THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_07' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='0_06' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='0_11' THEN 'Healthcare'
			WHEN VALOR_ORIGINAL ='0_09' THEN 'Hotel'
			WHEN VALOR_ORIGINAL ='0_12' THEN 'Lodge/Leisure'
			WHEN VALOR_ORIGINAL ='0_14' THEN 'Shopping Center'
			WHEN VALOR_ORIGINAL ='0_10' THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_13' THEN 'Non-residential buildings'
		ELSE 'SEM PARAMET'
		END)) AS TIPO_FINALIDADE_BEM
		,'NON-RESIDENTIAL BUILDINGS' AS TIPO_FINALIDADE_BEM_2
	FROM
		(
		SELECT 
			F1.*
			,CASE 
				WHEN F2.CHAVE_BEM IS NOT NULL THEN concat_ws('_','1',TRIM(F1.PROPERTY_PURPOSE_CODE))
				ELSE concat_ws('_','0',TRIM(F1.PROPERTY_PURPOSE_CODE))
			END AS VALOR_ORIGINAL
		FROM 
			(
			SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,PROPERTY_PURPOSE_CODE
			FROM BUSINESS_ASSETS.PROPERTY
			WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BUSINESS_ASSETS.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
			)F1 
		LEFT JOIN 
			(
			SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,EPC,TRIM(QUALITY_SCORE)
			FROM BUSINESS_ASSETS.PROPERTY_ENERGY_CERTIFICATE
			WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BUSINESS_ASSETS.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
				--AND TRIM(QUALITY_SCORE) IN ('1-REAL', 'SANTANDER')
				AND EPC IS NOT NULL
			)F2 ON F1.CHAVE_BEM = F2.CHAVE_BEM
		)AUX_1
	)FIN_BEM ON BASE.CHAVE_BEM = FIN_BEM.CHAVE_BEM 

LEFT JOIN

	-- 4º Cruzamento: Obter as métricas para o universo com EPC e Área útil  
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='FLOOR AREA'
		)AUX WHERE ROW_1=1
	)EMISS_1 ON EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.EPC_AUX=EPC.EPC AND EMISS_1.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN

	-- 5º Cruzamento: Obter as métricas para o universo com EPC e Área útil mas o EPC não consta na tabela de input (exemplo EPC G para Residential total)
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='FLOOR AREA'
			AND (TRIM(EPC)='' OR EPC IS NULL)
		)AUX WHERE ROW_1=1
	)EMISS_1B ON EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN 
	-- 6º Cruzamento: Obter as métricas para o universo sem EPC mas com Área útil
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='FLOOR AREA'
			AND (TRIM(EPC)='' OR EPC IS NULL)
		)AUX WHERE ROW_1=1
	)EMISS_2 ON EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN 
	-- 7º Cruzamento: Obter as métricas para o universo sem Área útil 
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='DWELLING'
			AND (TRIM(EPC)='' OR EPC IS NULL)
		)AUX WHERE ROW_1=1
	)EMISS_3 ON BASE.NET_FLOOR_AREA=0  AND EMISS_3.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN 
	-- 8º Cruzamento: Obter as métricas para o universo sem Área útil que não foi possivel obter no 7º cruzamento (nestes casos é assumido a seguinte finalidade: NON-RESIDENTIAL BUILDINGS)
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='DWELLING'
			AND (TRIM(EPC)='' OR EPC IS NULL)
		)AUX WHERE ROW_1=1
	)EMISS_4 ON BASE.NET_FLOOR_AREA=0  AND EMISS_4.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM_2

;

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 3. Criação da tabela - CENÁRIO 2 // Alterar finalidade do Bem 
--------------------------------------------------------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.BENS_IMOVEIS_MV_DEZ24_OP2;
CREATE TABLE BU_CAPTOOLS_WORK.BENS_IMOVEIS_MV_DEZ24_OP2 AS

SELECT 
	BASE.*
	,EPC.EPC
	,EPC.QUALITY_SCORE
	,FIN_BEM.TIPO_FINALIDADE_BEM
	,FIN_BEM.VALOR_ORIGINAL
	,FIN_BEM.TIPO_FINALIDADE_BEM_2
	,CASE
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN 'Nao Aplicavel' 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS3_2A'
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B' -- HF: E-mail da Corp no dia 14/Nov com a indicação que caso o EPC não se encontre no input (exemplo EPC G para Residential total ('31003014433390000000000000000000')) deve ser considerado a linha do input sem EPC 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP1_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP1_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		ELSE 'MISS'
	END AS ORIGEM_SCP1_EMSS
	,CASE 
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN 'Nao Aplicavel' 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS3_2A'
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP2_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP2_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		ELSE 'MISS'
	END AS ORIGEM_SCP2_EMSS
	,CASE WHEN TRIM(BASE.CHAVE_BEM)='' THEN '1'END AS ORIGEM_SCP3_EMSS
	,CASE  
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN NULL 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP1_FTR_EMSS IS NOT NULL THEN EMISS_3.SCP1_FTR_EMSS
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP1_FTR_EMSS IS NOT NULL THEN EMISS_4.SCP1_FTR_EMSS
		ELSE NULL
	END AS SCP1_EMSS
	,CASE  
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN NULL 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP2_FTR_EMSS IS NOT NULL THEN EMISS_3.SCP2_FTR_EMSS
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP2_FTR_EMSS IS NOT NULL THEN EMISS_4.SCP2_FTR_EMSS
		ELSE NULL
	END AS SCP2_EMSS
	
FROM 

	-- 1º Cruzamento: Obter o Universo Base 
	--> SET24 275.266 Registos 
	(
	SELECT DISTINCT PROPERTY_BANK_ID AS CEMPBEM
	
		,PROPERTY_BRANCH_CODE AS CKBALBEM
		,PROPERTY_CONTRACT_ID AS CKCTABEM
		,PROPERTY_REFERENCE_CODE AS CKREFBEM
		,CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,NET_FLOOR_AREA
	FROM BUSINESS_ASSETS.PROPERTY
    WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BUSINESS_ASSETS.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
	)BASE 

LEFT JOIN 

	-- 2º Cruzamento: Obter o EPC 
	--> SET24 275.266 Registos
	(
	SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,TRIM(UPPER(EPC)) AS EPC,TRIM(QUALITY_SCORE) AS QUALITY_SCORE
	FROM BUSINESS_ASSETS.PROPERTY_ENERGY_CERTIFICATE
    WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BUSINESS_ASSETS.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
		AND TRIM(QUALITY_SCORE) IN ('1-REAL', 'SANTANDER')
	)EPC ON BASE.CHAVE_BEM = EPC.CHAVE_BEM 

LEFT JOIN

	-- 3º Cruzamento: Obter a Finalidade do Bem de acordo com a parametrização 
	--> SET24 275.266 Registos
	(
	SELECT *
		,TRIM(UPPER(CASE
			WHEN VALOR_ORIGINAL ='1_01' THEN 'Residential Total'
			WHEN VALOR_ORIGINAL ='1_03' THEN 'Office'
			WHEN VALOR_ORIGINAL ='1_05' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_02' THEN 'Retail - high street'
			WHEN VALOR_ORIGINAL ='1_04' THEN 'Retail - warehouse'
			WHEN VALOR_ORIGINAL ='1_08' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_'   THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_07' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='1_06' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='1_11' THEN 'Healthcare'
			WHEN VALOR_ORIGINAL ='1_09' THEN 'Hotel'
			WHEN VALOR_ORIGINAL ='1_12' THEN 'Leisure/Lodging'
			WHEN VALOR_ORIGINAL ='1_14' THEN 'Retail - shopping center'
			WHEN VALOR_ORIGINAL ='1_10' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_13' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='0_01' THEN 'Residential Total'
			WHEN VALOR_ORIGINAL ='0_03' THEN 'Office'
			WHEN VALOR_ORIGINAL ='0_05' THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_02' THEN 'Retail High-street'
			WHEN VALOR_ORIGINAL ='0_04' THEN 'Retail Warehouse'
			WHEN VALOR_ORIGINAL ='0_08' THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_'   THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_07' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='0_06' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='0_11' THEN 'Healthcare'
			WHEN VALOR_ORIGINAL ='0_09' THEN 'Hotel'
			WHEN VALOR_ORIGINAL ='0_12' THEN 'Lodge/Leisure'
			WHEN VALOR_ORIGINAL ='0_14' THEN 'Shopping Center'
			WHEN VALOR_ORIGINAL ='0_10' THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_13' THEN 'Non-residential buildings'
		ELSE 'SEM PARAMET'
		END)) AS TIPO_FINALIDADE_BEM
		,'NON-RESIDENTIAL BUILDINGS' AS TIPO_FINALIDADE_BEM_2
	FROM
		(
		SELECT 
			F1.*
			,CASE 
				WHEN F2.CHAVE_BEM IS NOT NULL THEN concat_ws('_','1',TRIM(F1.PROPERTY_PURPOSE_CODE_MOD))
				ELSE concat_ws('_','0',TRIM(F1.PROPERTY_PURPOSE_CODE_MOD))
			END AS VALOR_ORIGINAL
		FROM 
			(
			SELECT DISTINCT CHAVE_BEM,PROPERTY_PURPOSE_CODE,
				CASE 
					WHEN TRIM(PROPERTY_PURPOSE_CODE)<>'08' THEN TRIM(PROPERTY_PURPOSE_CODE)
					WHEN TRIM(PROPERTY_PURPOSE_CODE)='08' AND TRIM(CGARANT_BEM) IN ('5101','5102') THEN '01'
					WHEN TRIM(PROPERTY_PURPOSE_CODE)='08' AND TRIM(CGARANT_BEM) IN ('5201','5202') THEN '02'
					WHEN TRIM(PROPERTY_PURPOSE_CODE)='08' AND TRIM(CGARANT_BEM) IN ('5213') THEN '10'
					WHEN TRIM(PROPERTY_PURPOSE_CODE)='08' AND TRIM(CGARANT_BEM) IN ('5215') THEN '11'
					ELSE '08'
				END AS PROPERTY_PURPOSE_CODE_MOD
			FROM 
				(
				SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,PROPERTY_PURPOSE_CODE
				FROM BUSINESS_ASSETS.PROPERTY
				WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BUSINESS_ASSETS.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
				)T1
			LEFT JOIN  
				(
					SELECT DISTINCT CONCAT(CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) AS CHAVE,CGARANT_BEM
					FROM CD_GARANTIAS.GT018_RATEIO_AVAL
					WHERE REF_DATE='${ref_date}' AND TIPOLOGIA='IMO'
				) T2 ON T1.CHAVE_BEM=T2.CHAVE 
			)F1 
		LEFT JOIN 
			(
			SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,EPC,TRIM(QUALITY_SCORE)
			FROM BUSINESS_ASSETS.PROPERTY_ENERGY_CERTIFICATE
			WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BUSINESS_ASSETS.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
				AND TRIM(QUALITY_SCORE) IN ('1-REAL', 'SANTANDER')
			)F2 ON F1.CHAVE_BEM = F2.CHAVE_BEM
		)AUX_1
	)FIN_BEM ON BASE.CHAVE_BEM = FIN_BEM.CHAVE_BEM 

LEFT JOIN

	-- 4º Cruzamento: Obter as métricas para o universo com EPC e Área útil  
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='FLOOR AREA'
		)AUX WHERE ROW_1=1
	)EMISS_1 ON EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.EPC_AUX=EPC.EPC AND EMISS_1.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN

	-- 5º Cruzamento: Obter as métricas para o universo com EPC e Área útil mas o EPC não consta na tabela de input (exemplo EPC G para Residential total)
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='FLOOR AREA'
			AND (TRIM(EPC)='' OR EPC IS NULL)
		)AUX WHERE ROW_1=1
	)EMISS_1B ON EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN 
	-- 6º Cruzamento: Obter as métricas para o universo sem EPC mas com Área útil
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='FLOOR AREA'
			AND (TRIM(EPC)='' OR EPC IS NULL)
		)AUX WHERE ROW_1=1
	)EMISS_2 ON EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN 
	-- 7º Cruzamento: Obter as métricas para o universo sem Área útil 
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='DWELLING'
			AND (TRIM(EPC)='' OR EPC IS NULL)
		)AUX WHERE ROW_1=1
	)EMISS_3 ON BASE.NET_FLOOR_AREA=0  AND EMISS_3.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN 
	-- 8º Cruzamento: Obter as métricas para o universo sem Área útil que não foi possivel obter no 7º cruzamento (nestes casos é assumido a seguinte finalidade: NON-RESIDENTIAL BUILDINGS)
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='DWELLING'
			AND (TRIM(EPC)='' OR EPC IS NULL)
		)AUX WHERE ROW_1=1
	)EMISS_4 ON BASE.NET_FLOOR_AREA=0  AND EMISS_4.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM_2

;

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 4. Criação da tabela - CENÁRIO 3 // EPC's mais recentes  
--------------------------------------------------------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.BENS_IMOVEIS_MV_DEZ24_OP3;
CREATE TABLE BU_CAPTOOLS_WORK.BENS_IMOVEIS_MV_DEZ24_OP3 AS

SELECT 
	BASE.*
	,EPC.EPC
	,EPC.QUALITY_SCORE
	,EPC.SOURCE_CODE
	,EPC.EPC_ISSUING_DATE
	,EPC.EPC_EXPIRATION_DATE
	,EPC.DATA_DATE_PART
	,EPC_ORI.*
	,FIN_BEM.TIPO_FINALIDADE_BEM
	,FIN_BEM.VALOR_ORIGINAL
	,FIN_BEM.TIPO_FINALIDADE_BEM_2
	,CASE
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN 'Nao Aplicavel' 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS3_2A'
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B' -- HF: E-mail da Corp no dia 14/Nov com a indicação que caso o EPC não se encontre no input (exemplo EPC G para Residential total ('31003014433390000000000000000000')) deve ser considerado a linha do input sem EPC 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP1_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP1_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		ELSE 'MISS'
	END AS ORIGEM_SCP1_EMSS
	,CASE 
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN 'Nao Aplicavel' 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS3_2A'
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP2_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP2_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		ELSE 'MISS'
	END AS ORIGEM_SCP2_EMSS
	,CASE WHEN TRIM(BASE.CHAVE_BEM)='' THEN '1'END AS ORIGEM_SCP3_EMSS
	,CASE  
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN NULL 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP1_FTR_EMSS IS NOT NULL THEN EMISS_3.SCP1_FTR_EMSS
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP1_FTR_EMSS IS NOT NULL THEN EMISS_4.SCP1_FTR_EMSS
		ELSE NULL
	END AS SCP1_EMSS
	,CASE  
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN NULL 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP2_FTR_EMSS IS NOT NULL THEN EMISS_3.SCP2_FTR_EMSS
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP2_FTR_EMSS IS NOT NULL THEN EMISS_4.SCP2_FTR_EMSS
		ELSE NULL
	END AS SCP2_EMSS
	
FROM 

	-- 1º Cruzamento: Obter o Universo Base 
	--> SET24 275.266 Registos 
	(
	SELECT DISTINCT PROPERTY_BANK_ID AS CEMPBEM
	
		,PROPERTY_BRANCH_CODE AS CKBALBEM
		,PROPERTY_CONTRACT_ID AS CKCTABEM
		,PROPERTY_REFERENCE_CODE AS CKREFBEM
		,CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,NET_FLOOR_AREA
	FROM BUSINESS_ASSETS.PROPERTY
    WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BUSINESS_ASSETS.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
	)BASE 

LEFT JOIN 

	-- 2º Cruzamento: Obter o EPC 
	--> SET24 275.266 Registos
	(
    SELECT *
    FROM 
        (
        SELECT RANK() OVER (PARTITION BY CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) ORDER BY DATA_DATE_PART DESC) AS RANK_TRAT,
            CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,
			TRIM(UPPER(EPC)) AS EPC,
			TRIM(QUALITY_SCORE) AS QUALITY_SCORE,SOURCE_CODE,EPC_ISSUING_DATE,EPC_EXPIRATION_DATE,DATA_DATE_PART
        FROM BUSINESS_ASSETS.PROPERTY_ENERGY_CERTIFICATE
        WHERE EPC IS NOT NULL AND TRIM(EPC)<>''
        )AUX WHERE RANK_TRAT=1 AND QUALITY_SCORE IN ('1-REAL', 'SANTANDER')
	)EPC ON BASE.CHAVE_BEM = EPC.CHAVE_BEM 
LEFT JOIN 

	-- 2º Cruzamento: Obter o EPC 
	--> SET24 275.266 Registos
	(
	SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM_ORI,TRIM(UPPER(EPC)) AS EPC_ORI,TRIM(QUALITY_SCORE) AS QUALITY_SCORE_ORI
		,SOURCE_CODE as SOURCE_CODE_ori
	FROM BUSINESS_ASSETS.PROPERTY_ENERGY_CERTIFICATE
    WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BUSINESS_ASSETS.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
	)EPC_ORI ON BASE.CHAVE_BEM = EPC_ORI.CHAVE_BEM_ori 

LEFT JOIN

	-- 3º Cruzamento: Obter a Finalidade do Bem de acordo com a parametrização 
	--> SET24 275.266 Registos
	(
	SELECT *
		,TRIM(UPPER(CASE
			WHEN VALOR_ORIGINAL ='1_01' THEN 'Residential Total'
			WHEN VALOR_ORIGINAL ='1_03' THEN 'Office'
			WHEN VALOR_ORIGINAL ='1_05' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_02' THEN 'Retail - high street'
			WHEN VALOR_ORIGINAL ='1_04' THEN 'Retail - warehouse'
			WHEN VALOR_ORIGINAL ='1_08' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_'   THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_07' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='1_06' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='1_11' THEN 'Healthcare'
			WHEN VALOR_ORIGINAL ='1_09' THEN 'Hotel'
			WHEN VALOR_ORIGINAL ='1_12' THEN 'Leisure/Lodging'
			WHEN VALOR_ORIGINAL ='1_14' THEN 'Retail - shopping center'
			WHEN VALOR_ORIGINAL ='1_10' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_13' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='0_01' THEN 'Residential Total'
			WHEN VALOR_ORIGINAL ='0_03' THEN 'Office'
			WHEN VALOR_ORIGINAL ='0_05' THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_02' THEN 'Retail High-street'
			WHEN VALOR_ORIGINAL ='0_04' THEN 'Retail Warehouse'
			WHEN VALOR_ORIGINAL ='0_08' THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_'   THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_07' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='0_06' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='0_11' THEN 'Healthcare'
			WHEN VALOR_ORIGINAL ='0_09' THEN 'Hotel'
			WHEN VALOR_ORIGINAL ='0_12' THEN 'Lodge/Leisure'
			WHEN VALOR_ORIGINAL ='0_14' THEN 'Shopping Center'
			WHEN VALOR_ORIGINAL ='0_10' THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_13' THEN 'Non-residential buildings'
		ELSE 'SEM PARAMET'
		END)) AS TIPO_FINALIDADE_BEM
		,'NON-RESIDENTIAL BUILDINGS' AS TIPO_FINALIDADE_BEM_2
	FROM
		(
		SELECT 
			F1.*
			,CASE 
				WHEN F2.CHAVE_BEM IS NOT NULL THEN concat_ws('_','1',TRIM(F1.PROPERTY_PURPOSE_CODE))
				ELSE concat_ws('_','0',TRIM(F1.PROPERTY_PURPOSE_CODE))
			END AS VALOR_ORIGINAL
		FROM 
			(
			SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,PROPERTY_PURPOSE_CODE
			FROM BUSINESS_ASSETS.PROPERTY
			WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BUSINESS_ASSETS.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
			)F1 
		LEFT JOIN 
			(
			SELECT *
			FROM 
				(
				SELECT RANK() OVER (PARTITION BY CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) ORDER BY DATA_DATE_PART DESC) AS RANK_TRAT,
					CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,
					TRIM(UPPER(EPC)) AS EPC,
					TRIM(QUALITY_SCORE) AS QUALITY_SCORE,SOURCE_CODE,EPC_ISSUING_DATE,EPC_EXPIRATION_DATE,DATA_DATE_PART
				FROM BUSINESS_ASSETS.PROPERTY_ENERGY_CERTIFICATE
				WHERE EPC IS NOT NULL AND TRIM(EPC)<>''
				)AUX WHERE RANK_TRAT=1 AND QUALITY_SCORE IN ('1-REAL', 'SANTANDER')
			)F2 ON F1.CHAVE_BEM = F2.CHAVE_BEM
		)AUX_1
	)FIN_BEM ON BASE.CHAVE_BEM = FIN_BEM.CHAVE_BEM 

LEFT JOIN

	-- 4º Cruzamento: Obter as métricas para o universo com EPC e Área útil  
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='FLOOR AREA'
		)AUX WHERE ROW_1=1
	)EMISS_1 ON EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.EPC_AUX=EPC.EPC AND EMISS_1.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN

	-- 5º Cruzamento: Obter as métricas para o universo com EPC e Área útil mas o EPC não consta na tabela de input (exemplo EPC G para Residential total)
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='FLOOR AREA'
			AND (TRIM(EPC)='' OR EPC IS NULL)
		)AUX WHERE ROW_1=1
	)EMISS_1B ON EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN 
	-- 6º Cruzamento: Obter as métricas para o universo sem EPC mas com Área útil
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='FLOOR AREA'
			AND (TRIM(EPC)='' OR EPC IS NULL)
		)AUX WHERE ROW_1=1
	)EMISS_2 ON EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN 
	-- 7º Cruzamento: Obter as métricas para o universo sem Área útil 
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='DWELLING'
			AND (TRIM(EPC)='' OR EPC IS NULL)
		)AUX WHERE ROW_1=1
	)EMISS_3 ON BASE.NET_FLOOR_AREA=0  AND EMISS_3.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN 
	-- 8º Cruzamento: Obter as métricas para o universo sem Área útil que não foi possivel obter no 7º cruzamento (nestes casos é assumido a seguinte finalidade: NON-RESIDENTIAL BUILDINGS)
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='DWELLING'
			AND (TRIM(EPC)='' OR EPC IS NULL)
		)AUX WHERE ROW_1=1
	)EMISS_4 ON BASE.NET_FLOOR_AREA=0  AND EMISS_4.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM_2
;


--------------------------------------------------------------------------------------------------------------------------------------------------
-- 5. Criação da tabela - CENÁRIO 2 // Alterar finalidade do Bem + Considerar Input Espanha 
--------------------------------------------------------------------------------------------------------------------------------------------------

-- DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.BENS_IMOVEIS_MV_DEZ24_OP4;
CREATE TABLE BU_CAPTOOLS_WORK.BENS_IMOVEIS_MV_DEZ24_OP4 AS

SELECT 
	BASE.*
	,EPC.EPC
	,EPC.QUALITY_SCORE
	,FIN_BEM.TIPO_FINALIDADE_BEM
	,FIN_BEM.VALOR_ORIGINAL
	,FIN_BEM.TIPO_FINALIDADE_BEM_2
	,CASE
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN 'Nao Aplicavel' 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS3_2A'
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B' -- HF: E-mail da Corp no dia 14/Nov com a indicação que caso o EPC não se encontre no input (exemplo EPC G para Residential total ('31003014433390000000000000000000')) deve ser considerado a linha do input sem EPC 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP1_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP1_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		ELSE 'MISS'
	END AS ORIGEM_SCP1_EMSS
	,CASE 
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN 'Nao Aplicavel' 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS3_2A'
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP2_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP2_FTR_EMSS IS NOT NULL THEN 'RE_DQS5_3'
		ELSE 'MISS'
	END AS ORIGEM_SCP2_EMSS
	,CASE WHEN TRIM(BASE.CHAVE_BEM)='' THEN '1'END AS ORIGEM_SCP3_EMSS
	,CASE  
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN NULL 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP1_FTR_EMSS IS NOT NULL THEN EMISS_3.SCP1_FTR_EMSS
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP1_FTR_EMSS IS NOT NULL THEN EMISS_4.SCP1_FTR_EMSS
		ELSE NULL
	END AS SCP1_EMSS
	,CASE  
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN NULL 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP2_FTR_EMSS IS NOT NULL THEN EMISS_3.SCP2_FTR_EMSS
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP2_FTR_EMSS IS NOT NULL THEN EMISS_4.SCP2_FTR_EMSS
		ELSE NULL
	END AS SCP2_EMSS
	
FROM 

	-- 1º Cruzamento: Obter o Universo Base 
	--> SET24 275.266 Registos 
	(
	SELECT DISTINCT PROPERTY_BANK_ID AS CEMPBEM
	
		,PROPERTY_BRANCH_CODE AS CKBALBEM
		,PROPERTY_CONTRACT_ID AS CKCTABEM
		,PROPERTY_REFERENCE_CODE AS CKREFBEM
		,CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,NET_FLOOR_AREA
	FROM BUSINESS_ASSETS.PROPERTY
    WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BUSINESS_ASSETS.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
	)BASE 

LEFT JOIN 

	-- 2º Cruzamento: Obter o EPC 
	--> SET24 275.266 Registos
	(
	SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,TRIM(UPPER(EPC)) AS EPC,TRIM(QUALITY_SCORE) AS QUALITY_SCORE
	FROM BUSINESS_ASSETS.PROPERTY_ENERGY_CERTIFICATE
    WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BUSINESS_ASSETS.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
		AND TRIM(QUALITY_SCORE) IN ('1-REAL', 'SANTANDER')
	)EPC ON BASE.CHAVE_BEM = EPC.CHAVE_BEM 

LEFT JOIN

	-- 3º Cruzamento: Obter a Finalidade do Bem de acordo com a parametrização 
	--> SET24 275.266 Registos
	(
	SELECT *
		,TRIM(UPPER(CASE
			WHEN VALOR_ORIGINAL ='1_01' THEN 'Residential Total'
			WHEN VALOR_ORIGINAL ='1_03' THEN 'Office'
			WHEN VALOR_ORIGINAL ='1_05' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_02' THEN 'Retail - high street'
			WHEN VALOR_ORIGINAL ='1_04' THEN 'Retail - warehouse'
			WHEN VALOR_ORIGINAL ='1_08' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_'   THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_07' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='1_06' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='1_11' THEN 'Healthcare'
			WHEN VALOR_ORIGINAL ='1_09' THEN 'Hotel'
			WHEN VALOR_ORIGINAL ='1_12' THEN 'Leisure/Lodging'
			WHEN VALOR_ORIGINAL ='1_14' THEN 'Retail - shopping center'
			WHEN VALOR_ORIGINAL ='1_10' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_13' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='0_01' THEN 'Residential Total'
			WHEN VALOR_ORIGINAL ='0_03' THEN 'Office'
			WHEN VALOR_ORIGINAL ='0_05' THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_02' THEN 'Retail High-street'
			WHEN VALOR_ORIGINAL ='0_04' THEN 'Retail Warehouse'
			WHEN VALOR_ORIGINAL ='0_08' THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_'   THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_07' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='0_06' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='0_11' THEN 'Healthcare'
			WHEN VALOR_ORIGINAL ='0_09' THEN 'Hotel'
			WHEN VALOR_ORIGINAL ='0_12' THEN 'Lodge/Leisure'
			WHEN VALOR_ORIGINAL ='0_14' THEN 'Shopping Center'
			WHEN VALOR_ORIGINAL ='0_10' THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_13' THEN 'Non-residential buildings'
		ELSE 'SEM PARAMET'
		END)) AS TIPO_FINALIDADE_BEM
		,'NON-RESIDENTIAL BUILDINGS' AS TIPO_FINALIDADE_BEM_2
	FROM
		(
		SELECT 
			F1.*
			,CASE 
				WHEN F2.CHAVE_BEM IS NOT NULL THEN concat_ws('_','1',TRIM(F1.PROPERTY_PURPOSE_CODE_MOD))
				ELSE concat_ws('_','0',TRIM(F1.PROPERTY_PURPOSE_CODE_MOD))
			END AS VALOR_ORIGINAL
		FROM 
			(
			SELECT DISTINCT CHAVE_BEM,PROPERTY_PURPOSE_CODE,
				CASE 
					WHEN TRIM(PROPERTY_PURPOSE_CODE)<>'08' THEN TRIM(PROPERTY_PURPOSE_CODE)
					WHEN TRIM(PROPERTY_PURPOSE_CODE)='08' AND TRIM(CGARANT_BEM) IN ('5101','5102') THEN '01'
					WHEN TRIM(PROPERTY_PURPOSE_CODE)='08' AND TRIM(CGARANT_BEM) IN ('5201','5202') THEN '02'
					WHEN TRIM(PROPERTY_PURPOSE_CODE)='08' AND TRIM(CGARANT_BEM) IN ('5213') THEN '10'
					WHEN TRIM(PROPERTY_PURPOSE_CODE)='08' AND TRIM(CGARANT_BEM) IN ('5215') THEN '11'
					ELSE '08'
				END AS PROPERTY_PURPOSE_CODE_MOD
			FROM 
				(
				SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,PROPERTY_PURPOSE_CODE
				FROM BUSINESS_ASSETS.PROPERTY
				WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BUSINESS_ASSETS.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
				)T1
			LEFT JOIN  
				(
					SELECT DISTINCT CONCAT(CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) AS CHAVE,CGARANT_BEM
					FROM CD_GARANTIAS.GT018_RATEIO_AVAL
					WHERE REF_DATE='${ref_date}' AND TIPOLOGIA='IMO'
				) T2 ON T1.CHAVE_BEM=T2.CHAVE 
			)F1 
		LEFT JOIN 
			(
			SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,EPC,TRIM(QUALITY_SCORE)
			FROM BUSINESS_ASSETS.PROPERTY_ENERGY_CERTIFICATE
			WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BUSINESS_ASSETS.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
				AND TRIM(QUALITY_SCORE) IN ('1-REAL', 'SANTANDER')
			)F2 ON F1.CHAVE_BEM = F2.CHAVE_BEM
		)AUX_1
	)FIN_BEM ON BASE.CHAVE_BEM = FIN_BEM.CHAVE_BEM 

LEFT JOIN

	-- 4º Cruzamento: Obter as métricas para o universo com EPC e Área útil  
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='SPAIN'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='FLOOR AREA'
		)AUX WHERE ROW_1=1
	)EMISS_1 ON EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.EPC_AUX=EPC.EPC AND EMISS_1.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN

	-- 5º Cruzamento: Obter as métricas para o universo com EPC e Área útil mas o EPC não consta na tabela de input (exemplo EPC G para Residential total)
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,CASE WHEN TRIM(TIPO_FINALIDADE_BEM)='Retail - high street' THEN 'RETAIL HIGH-STREET' ELSE TRIM(UPPER(TIPO_FINALIDADE_BEM)) END AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='SPAIN'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='FLOOR AREA'
			AND (TRIM(EPC)='' OR EPC IS NULL)
		)AUX WHERE ROW_1=1
	)EMISS_1B ON EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN 
	-- 6º Cruzamento: Obter as métricas para o universo sem EPC mas com Área útil
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,CASE WHEN TRIM(TIPO_FINALIDADE_BEM)='Retail - high street' THEN 'RETAIL HIGH-STREET' ELSE TRIM(UPPER(TIPO_FINALIDADE_BEM)) END AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='SPAIN'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='FLOOR AREA'
			AND (TRIM(EPC)='' OR EPC IS NULL)
		)AUX WHERE ROW_1=1
	)EMISS_2 ON EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN 
	-- 7º Cruzamento: Obter as métricas para o universo sem Área útil 
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='SPAIN'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='DWELLING'
			AND (TRIM(EPC)='' OR EPC IS NULL)
		)AUX WHERE ROW_1=1
	)EMISS_3 ON BASE.NET_FLOOR_AREA=0  AND EMISS_3.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN 
	-- 8º Cruzamento: Obter as métricas para o universo sem Área útil que não foi possivel obter no 7º cruzamento (nestes casos é assumido a seguinte finalidade: NON-RESIDENTIAL BUILDINGS)
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM BUSINESS_ESG.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='SPAIN'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='DWELLING'
			AND (TRIM(EPC)='' OR EPC IS NULL)
		)AUX WHERE ROW_1=1
	)EMISS_4 ON BASE.NET_FLOOR_AREA=0  AND EMISS_4.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM_2

	
--------------------------------------------------------------------------------------------------------------------------------------------------
-- 2. Validação da Tabela
--------------------------------------------------------------------------------------------------------------------------------------------------

		-- VALIDAÇÃO #1 

SELECT 
    CASE 
        WHEN F2.CHAVE_BEM IS NOT NULL AND F1.CHAVE_BEM IS NOT NULL THEN 'UNIVERSO COMUM'
        WHEN F2.CHAVE_BEM IS NULL AND F1.CHAVE_BEM IS NOT NULL THEN 'EXCLUSIVO IT'
        WHEN F2.CHAVE_BEM IS NOT NULL AND F1.CHAVE_BEM IS NULL THEN 'EXCLUSIVO SIMULAÇÃO'
    END AS VALID_UNIV
    ,CASE
        WHEN F1.ORIGEM_SCP1_EMSS IS NULL AND F2.ORIGEM_SCP1_EMSS IN ('MISS','NAO APLICAVEL') THEN 'NOK NULL - MISS OU N/A'
        WHEN F1.ORIGEM_SCP1_EMSS IS NULL THEN 'NOK NULL'
        WHEN F1.ORIGEM_SCP1_EMSS=F2.ORIGEM_SCP1_EMSS THEN 'OK'
        ELSE 'NOK' 
    END AS VALID_ORIGEM_SCP1
    ,CASE
        WHEN F1.ORIGEM_SCP2_EMSS IS NULL AND F2.ORIGEM_SCP2_EMSS IN ('MISS','NAO APLICAVEL') THEN 'NOK NULL - MISS OU N/A'
        WHEN F1.ORIGEM_SCP2_EMSS IS NULL THEN 'NOK NULL'
        WHEN F1.ORIGEM_SCP2_EMSS=F2.ORIGEM_SCP2_EMSS THEN 'OK'
        ELSE 'NOK' 
    END AS VALID_ORIGEM_SCP2
    ,CASE 
        WHEN F1.SCP1_EMSS IS NULL AND F2.SCP1_EMSS IS NULL THEN 'OK - AMBOS NULL'
        WHEN F1.SCP1_EMSS IS NULL AND F2.SCP1_EMSS IS NOT NULL THEN 'NOK - IT NULL'
        WHEN F1.SCP1_EMSS IS NOT NULL AND F2.SCP1_EMSS IS NULL THEN 'NOK - SIMUL NULL'
        WHEN ABS(F1.SCP1_EMSS-F2.SCP1_EMSS)<0.2 THEN 'OK'
        ELSE 'NOK'
    END AS VALID_SCP1
    ,COUNT(*) AS NUM_REG
FROM 
    (
    SELECT CONCAT(CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) AS CHAVE_BEM,*
    FROM BUSINESS_ESG.MODESG_OUT_BENS_IMOVEIS
    WHERE REF_DATE='2024-12-31'
    )F1 
FULL JOIN 
    (
    SELECT * 
    FROM BU_CAPTOOLS_WORK.BENS_IMOVEIS_MV_DEZ24
    )F2 ON F1.CHAVE_BEM=F2.CHAVE_BEM
GROUP BY 1,2,3,4
;

SELECT 
    CASE 
        WHEN F2.CHAVE_BEM IS NOT NULL AND F1.CHAVE_BEM IS NOT NULL THEN 'UNIVERSO COMUM'
        WHEN F2.CHAVE_BEM IS NULL AND F1.CHAVE_BEM IS NOT NULL THEN 'EXCLUSIVO IT'
        WHEN F2.CHAVE_BEM IS NOT NULL AND F1.CHAVE_BEM IS NULL THEN 'EXCLUSIVO SIMULAÇÃO'
    END AS VALID_UNIV
    ,CASE
        WHEN F1.ORIGEM_SCP1_EMSS IS NULL AND F2.ORIGEM_SCP1_EMSS IN ('MISS','NAO APLICAVEL') THEN 'NOK NULL - MISS OU N/A'
        WHEN F1.ORIGEM_SCP1_EMSS IS NULL THEN 'NOK NULL'
        WHEN F1.ORIGEM_SCP1_EMSS=F2.ORIGEM_SCP1_EMSS THEN 'OK'
        ELSE 'NOK' 
    END AS VALID_ORIGEM_SCP1
    ,CASE
        WHEN F1.ORIGEM_SCP2_EMSS IS NULL AND F2.ORIGEM_SCP2_EMSS IN ('MISS','NAO APLICAVEL') THEN 'NOK NULL - MISS OU N/A'
        WHEN F1.ORIGEM_SCP2_EMSS IS NULL THEN 'NOK NULL'
        WHEN F1.ORIGEM_SCP2_EMSS=F2.ORIGEM_SCP2_EMSS THEN 'OK'
        ELSE 'NOK' 
    END AS VALID_ORIGEM_SCP2
    ,CASE 
        WHEN F1.SCP1_EMSS IS NULL AND F2.SCP1_EMSS IS NULL THEN 'OK - AMBOS NULL'
        WHEN F1.SCP1_EMSS IS NULL AND F2.SCP1_EMSS IS NOT NULL THEN 'NOK - IT NULL'
        WHEN F1.SCP1_EMSS IS NOT NULL AND F2.SCP1_EMSS IS NULL THEN 'NOK - SIMUL NULL'
        WHEN ABS(F1.SCP1_EMSS-F2.SCP1_EMSS)<0.2 THEN 'OK'
        ELSE 'NOK'
    END AS VALID_SCP1,*
    -- ,COUNT(*) AS NUM_REG
FROM 
    (
    SELECT CONCAT(CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) AS CHAVE_BEM,*
    FROM BUSINESS_ESG.MODESG_OUT_BENS_IMOVEIS
    WHERE REF_DATE='2024-12-31'
    )F1 
FULL JOIN 
    (
    SELECT * 
    FROM BU_CAPTOOLS_WORK.BENS_IMOVEIS_MV_DEZ24
    )F2 ON F1.CHAVE_BEM=F2.CHAVE_BEM
    
HAVING VALID_UNIV='UNIVERSO COMUM' AND VALID_ORIGEM_SCP1='OK' AND VALID_SCP1='NOK'


