
/*===================================================================================================================================================
                                                      
											    SIMULAÇÃO MODESG_OUT_EMSS_VCLS - MODELO VERDE
										                    NEYOND 2024 - V0.01 
															    
 ===================================================================================================================================================*/
 
 --------------------------------------------------------------------------------------------------------------------------------------------------
-- 0. Tabela Auxiliar (correr em HIVE) para veiculos com uma marca similar (com nivel de aceitação > 75%)
--------------------------------------------------------------------------------------------------------------------------------------------------

INVALIDATE METADATA BU_CAPTOOLS_WORK.VEICU_LEVENSH_AUX; -- HF: Depois de criar a tabela em HIVE, correr isto em impala

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.VEICU_LEVENSH_AUX;
CREATE TABLE BU_CAPTOOLS_WORK.VEICU_LEVENSH_AUX AS

SELECT
	*
	,RANK() OVER (PARTITION BY CHAVE_BEM_LEVENSH ORDER BY MODELO_FINAL_TRATADO DESC) AS RANK_LEVENSH
FROM
	(
	SELECT 
		*
		,LEVENSHTEIN (UNI.MODELO_LEVENSH,AUX.MODELO_AUX2_1B)
		,(1- (LEVENSHTEIN (UNI.MODELO_LEVENSH,AUX.MODELO_AUX2_1B)/LENGTH(AUX.MODELO_AUX2_1B)))*100 AS MODELO_TRATADO_CORP
		,(1- (LEVENSHTEIN (UNI.MODELO_LEVENSH,AUX.MODELO_AUX2_1B)/LENGTH(UNI.MODELO_LEVENSH)))*100 AS MODELO_TRATADO_GT013
		,CASE 
			WHEN (1- (LEVENSHTEIN (UNI.MODELO_LEVENSH,AUX.MODELO_AUX2_1B)/LENGTH(AUX.MODELO_AUX2_1B)))*100 > (1-(LEVENSHTEIN (UNI.MODELO_LEVENSH,AUX.MODELO_AUX2_1B)/LENGTH(UNI.MODELO_LEVENSH)))*100 THEN (1- (LEVENSHTEIN (UNI.MODELO_LEVENSH,AUX.MODELO_AUX2_1B)/LENGTH(AUX.MODELO_AUX2_1B)))*100
			ELSE (1- (LEVENSHTEIN (UNI.MODELO_LEVENSH,AUX.MODELO_AUX2_1B)/LENGTH(UNI.MODELO_LEVENSH)))*100 
		END AS MODELO_FINAL_TRATADO
		FROM
			(
			SELECT 
				CONCAT(CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) AS CHAVE_BEM_LEVENSH
				,REGEXP_REPLACE(TRIM(UPPER(MARCA)),'[^a-zA-Z0-9]','') AS MARCA_LEVENSH
				,REGEXP_REPLACE(TRIM(UPPER(MODELO)),'[^a-zA-Z0-9]','') AS MODELO_LEVENSH
				,TRIM(UPPER(CASE
					WHEN TRIM(TIPO_COMBUST) ='2' THEN 'DIESEL'
					WHEN TRIM(TIPO_COMBUST) ='7' THEN 'DIESEL/ELECTRIC'
					WHEN TRIM(TIPO_COMBUST) ='5' THEN 'DIESEL'
					WHEN TRIM(TIPO_COMBUST) ='4' THEN 'ELECTRIC'
					WHEN TRIM(TIPO_COMBUST) ='3' THEN 'LPG'
					WHEN TRIM(TIPO_COMBUST) ='1' THEN 'PETROL'
					WHEN TRIM(TIPO_COMBUST) ='6' THEN 'PETROL/ELECTRIC'
					WHEN TRIM(TIPO_COMBUST) ='' THEN 'Average'
				END)) AS TIPO_MOTOR_LEVENSH
				,TRIM(UPPER(CASE
						WHEN TRIM(CGARANT_BEM) ='7101' THEN 'Passenger car'
						WHEN TRIM(CGARANT_BEM) ='7102' THEN 'Van'
						WHEN TRIM(CGARANT_BEM) ='7103' THEN 'Heavy Vehicle'
						WHEN TRIM(CGARANT_BEM) ='7104' THEN 'Heavy Vehicle'
						WHEN TRIM(CGARANT_BEM) ='7105' THEN 'Passenger car'
						WHEN TRIM(CGARANT_BEM) ='7100' THEN 'NOT APPLICABLE'
						WHEN TRIM(CGARANT_BEM) ='7106' THEN 'Heavy Vehicle'
						WHEN TRIM(CGARANT_BEM) ='7107' THEN 'Heavy Vehicle'
						WHEN TRIM(CGARANT_BEM) ='7108' THEN 'NOT APPLICABLE'
						WHEN TRIM(CGARANT_BEM) ='7109' THEN 'NOT APPLICABLE'
						WHEN TRIM(CGARANT_BEM) ='7110' THEN 'Passenger car'
						WHEN TRIM(CGARANT_BEM) ='7111' THEN 'NOT APPLICABLE'
				END)) AS TIPO_VEICULO_LEVENSH
			FROM cd_garantias.GT013_BENS_MOB
			WHERE REF_DATE='${ref_date}'
				AND CGARANT_BEM LIKE '71%'
			)UNI	
		LEFT JOIN 
			(
			SELECT 
				*
			FROM    
				(
				SELECT 
					SCP1_FTR_EMSS 
					,SCP2_FTR_EMSS 
					,SCP3_FTR_EMSS 
					,CAST(SCP1_FTR_EMSS AS DECIMAL(32,10)) AS SCP1_FTR_EMSS_1B
					,CAST(SCP2_FTR_EMSS AS DECIMAL(32,10)) AS SCP2_FTR_EMSS_1B
					,TRIM(UPPER(MODELO)) AS MODELO_AUX_1B
					,TRIM(UPPER(MARCA)) AS MARCA_AUX_1B
					,REGEXP_REPLACE(TRIM(UPPER(MARCA)),'[^a-zA-Z0-9]','') AS MARCA_AUX2_1B --HF: É necessário adicionar o tratamento do ' ' na especificação 
					,REGEXP_REPLACE(TRIM(UPPER(MODELO)),'[^a-zA-Z0-9]','') AS MODELO_AUX2_1B
					,TRIM(UPPER(TIPO_VEICULO)) AS TIPO_VEICULO_AUX_1B
					,TRIM(UPPER(TIPO_MOTOR))AS TIPO_MOTOR_AUX_1B
					,RANK () OVER (PARTITION BY CONCAT(REGEXP_REPLACE(TRIM(UPPER(MARCA)),'[^a-zA-Z0-9]',''),REGEXP_REPLACE(TRIM(UPPER(MODELO)),'[^a-zA-Z0-9]',''),TRIM(UPPER(TIPO_VEICULO)),TRIM(UPPER(TIPO_MOTOR))) ORDER BY (NVL(CAST(SCP1_FTR_EMSS AS DECIMAL(32,10)),0)+NVL(CAST(SCP2_FTR_EMSS AS DECIMAL(32,10)),0))/2 DESC) AS RANK_1
				FROM BU_ESG_WORK.MODESG_INP_EMSS_VCLS
				WHERE REF_DATE='${ref_date}'
					AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
					AND TRIM(UPPER(TIPO_MOTOR))<>'AVERAGE'
				)TRAT WHERE RANK_1=1 --HF 03/12 : Tratamento e-mail SB --> BS | Testes ESG Pilar III - Tabela Veículos - Proposta de escolha de 1 registo do input de veículos  
			)AUX ON AUX.MARCA_AUX2_1B = UNI.MARCA_LEVENSH AND AUX.TIPO_VEICULO_AUX_1B = UNI.TIPO_VEICULO_LEVENSH AND AUX.TIPO_MOTOR_AUX_1B = UNI.TIPO_MOTOR_LEVENSH
	)AUX_TRAT

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 1. Criação da tabela 
--------------------------------------------------------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.MODESG_OUT_EMSS_VCLS_MV_DEZ24;
CREATE TABLE BU_CAPTOOLS_WORK.MODESG_OUT_EMSS_VCLS_MV_DEZ24 AS

SELECT 
    BASE.CHAVE_BEM
    ,CAST(BASE.CO2 AS DECIMAL(32,10)) AS CNSM_CO2
	,CASE
		WHEN TIPO_VEICULO_GT013='NOT APPLICABLE' THEN 'MISS'
		WHEN EMISS_1B.CHAVE_BEM_LEVENSH IS NOT NULL AND KM_1.TIPO_VEICULO_KM_1 IS NOT NULL THEN 'MVL_DQS3_2B'
		WHEN EMISS_2.TIPO_VEICULO_EMI_2 IS NOT NULL AND KM_2.TIPO_VEICULO_KM_2 IS NOT NULL THEN 'MVL_DQS4_3A'
		WHEN EMISS_3.TIPO_VEICULO_EMI_3 IS NOT NULL AND KM_3.TIPO_VEICULO_KM_3 IS NOT NULL THEN 'MVL_DQS5_3B'
		ELSE 'MISS'
	END AS ORIGEM_SCP1_EMSS_AUX
	,CASE
		WHEN TIPO_VEICULO_GT013='NOT APPLICABLE' THEN 'MISS'
		WHEN EMISS_1B.CHAVE_BEM_LEVENSH IS NOT NULL AND KM_1.TIPO_VEICULO_KM_1 IS NOT NULL THEN 'MVL_DQS3_2B'
		WHEN EMISS_2.TIPO_VEICULO_EMI_2 IS NOT NULL AND KM_2.TIPO_VEICULO_KM_2 IS NOT NULL THEN 'MVL_DQS4_3A'
		WHEN EMISS_3.TIPO_VEICULO_EMI_3 IS NOT NULL AND KM_3.TIPO_VEICULO_KM_3 IS NOT NULL THEN 'MVL_DQS5_3B'
		ELSE 'MISS'
	END AS ORIGEM_SCP2_EMSS_AUX
	,'Nao Aplicavel' AS ORIGEM_SCP3_EMSS
	,CASE
		WHEN TIPO_VEICULO_GT013='NOT APPLICABLE' THEN NULL
		WHEN EMISS_1B.CHAVE_BEM_LEVENSH IS NOT NULL AND KM_1.TIPO_VEICULO_KM_1 IS NOT NULL THEN EMISS_1B.SCP1_FTR_EMSS_1B*KM_1.MEDIA_KM_1
		WHEN EMISS_2.TIPO_VEICULO_EMI_2 IS NOT NULL AND KM_2.TIPO_VEICULO_KM_2 IS NOT NULL THEN EMISS_2.SCP1_FTR_EMSS_2*KM_2.MEDIA_KM_2
		WHEN EMISS_3.TIPO_VEICULO_EMI_3 IS NOT NULL AND KM_3.TIPO_VEICULO_KM_3 IS NOT NULL THEN EMISS_3.SCP1_FTR_EMSS_3*KM_3.MEDIA_KM_3
	END AS SCP1_EMSS
	,CASE
		WHEN TIPO_VEICULO_GT013='NOT APPLICABLE' THEN NULL
		WHEN EMISS_1B.CHAVE_BEM_LEVENSH IS NOT NULL AND KM_1.TIPO_VEICULO_KM_1 IS NOT NULL THEN EMISS_1B.SCP2_FTR_EMSS_1B*KM_1.MEDIA_KM_1
		WHEN EMISS_2.TIPO_VEICULO_EMI_2 IS NOT NULL AND KM_2.TIPO_VEICULO_KM_2 IS NOT NULL THEN EMISS_2.SCP2_FTR_EMSS_2*KM_2.MEDIA_KM_2
		WHEN EMISS_3.TIPO_VEICULO_EMI_3 IS NOT NULL AND KM_3.TIPO_VEICULO_KM_3 IS NOT NULL THEN EMISS_3.SCP2_FTR_EMSS_3*KM_3.MEDIA_KM_3
	END AS SCP2_EMSS
	,CASE WHEN TRIM(BASE.CHAVE_BEM)='' THEN '1'END AS SCP3_EMSS
FROM
	-- 1º Cruzamento: Obter o Universo Base, CNSM_CO2, TIPO_MOTOR E TIPO_VEICULO  
	--> OUT24 20.643 Registos 

	(
	SELECT  
		CONCAT(CEMPBEM,CKBALBEM,CKCTABEM,CKREFBEM) AS CHAVE_BEM
		,CO2 
		,MARCA
		,MODELO
		,TIPO_COMBUST
		,CGARANT_BEM
		,REGEXP_REPLACE(TRIM(UPPER(MARCA)),'[^a-zA-Z0-9]','') AS MARCA_GT013
		,REGEXP_REPLACE(TRIM(UPPER(MODELO)),'[^a-zA-Z0-9]','') AS MODELO_GT013
		,TRIM(UPPER(CASE
				WHEN TRIM(TIPO_COMBUST) ='2' THEN 'DIESEL'
				WHEN TRIM(TIPO_COMBUST) ='7' THEN 'DIESEL/ELECTRIC'
				WHEN TRIM(TIPO_COMBUST) ='5' THEN 'DIESEL'
				WHEN TRIM(TIPO_COMBUST) ='4' THEN 'ELECTRIC'
				WHEN TRIM(TIPO_COMBUST) ='3' THEN 'LPG'
				WHEN TRIM(TIPO_COMBUST) ='1' THEN 'PETROL'
				WHEN TRIM(TIPO_COMBUST) ='6' THEN 'PETROL/ELECTRIC'
				WHEN TRIM(TIPO_COMBUST) ='' THEN 'Average'
			END)) AS TIPO_MOTOR_GT013
		,TRIM(UPPER(CASE
				WHEN TRIM(CGARANT_BEM) ='7101' THEN 'Passenger car'
				WHEN TRIM(CGARANT_BEM) ='7102' THEN 'Van'
				WHEN TRIM(CGARANT_BEM) ='7103' THEN 'Heavy Vehicle'
				WHEN TRIM(CGARANT_BEM) ='7104' THEN 'Heavy Vehicle'
				WHEN TRIM(CGARANT_BEM) ='7105' THEN 'Passenger car'
				WHEN TRIM(CGARANT_BEM) ='7100' THEN 'NOT APPLICABLE'
				WHEN TRIM(CGARANT_BEM) ='7106' THEN 'Heavy Vehicle'
				WHEN TRIM(CGARANT_BEM) ='7107' THEN 'Heavy Vehicle'
				WHEN TRIM(CGARANT_BEM) ='7108' THEN 'NOT APPLICABLE'
				WHEN TRIM(CGARANT_BEM) ='7109' THEN 'NOT APPLICABLE'
				WHEN TRIM(CGARANT_BEM) ='7110' THEN 'Passenger car'
				WHEN TRIM(CGARANT_BEM) ='7111' THEN 'NOT APPLICABLE'
			END)) AS TIPO_VEICULO_GT013	
	FROM cd_garantias.GT013_BENS_MOB
    WHERE ref_date = '${ref_date}'
        AND CGARANT_BEM LIKE '71%'
	)BASE

LEFT JOIN 

	-- 2Aº Cruzamento: Obtenção Scope 1ª Metodologia 
	--> OUT24 20.643 Registos
	(
	SELECT 
		*
	FROM
		(
		SELECT
			*
			,RANK () OVER (PARTITION BY CHAVE_BEM_LEVENSH ORDER BY MODELO_AUX2_1B) AS RANK_LEVENSH_3 --HF 04/12 - Este rank serve para casos onde empatam na média das scopes mas tem modelos diferentes. Dado que as scopes são iguais não é relevante o modelo a escolher no tratamento do levenshtein (Verificamos 2 casos para esta casuística em Out: ('89000000005110422000000000000001','89000000000248335000000000000001'))
		FROM
			(
			SELECT
				*
				,RANK () OVER (PARTITION BY CONCAT(CHAVE_BEM_LEVENSH,MARCA_LEVENSH,MODELO_LEVENSH,TIPO_MOTOR_LEVENSH,TIPO_VEICULO_LEVENSH)  ORDER BY (NVL(CAST(SCP1_FTR_EMSS_1B AS DECIMAL(32,10)),0)+NVL(CAST(SCP2_FTR_EMSS_1B AS DECIMAL(32,10)),0))/2 DESC) AS RANK_LEVENSH_2
			FROM
				(
				SELECT
					*
				FROM BU_CAPTOOLS_WORK.VEICU_LEVENSH_AUX
				)AUX_TRAT_1 WHERE RANK_LEVENSH = 1 AND MODELO_FINAL_TRATADO > 75
			)AUX_TRAT_2 WHERE RANK_LEVENSH_2=1
		)FINAL_TRAT WHERE RANK_LEVENSH_3=1
	)EMISS_1B ON BASE.MARCA_GT013 IS NOT NULL AND BASE.MODELO_GT013 IS NOT NULL AND BASE.TIPO_MOTOR_GT013 IS NOT NULL AND BASE.TIPO_VEICULO_GT013 IS NOT NULL  
				AND EMISS_1B.MARCA_LEVENSH=BASE.MARCA_GT013 
				AND EMISS_1B.TIPO_VEICULO_LEVENSH=BASE.TIPO_VEICULO_GT013 
				AND EMISS_1B.TIPO_MOTOR_LEVENSH=BASE.TIPO_MOTOR_GT013
				AND EMISS_1B.CHAVE_BEM_LEVENSH=BASE.CHAVE_BEM
	
LEFT JOIN 

	-- 2Bº Cruzamento: Obtenção KM Médios 1ª Metodologia 
	--> OUT24 20.643 Registos
	(
	SELECT 
		 MEDIA_KM
		 ,CAST(MEDIA_KM AS DECIMAL(32,10)) AS MEDIA_KM_1
		,TRIM(UPPER(TIPO_VCL)) AS TIPO_VEICULO_KM_1
		,TRIM(UPPER(TIPO_MOTOR))AS TIPO_MOTOR_KM_1
	FROM BU_ESG_WORK.MODESG_INP_KM_MEDIOS_EMSS_VCLS
	WHERE REF_DATE='${ref_date}'
		AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
		AND TRIM(UPPER(SUBGRUPO))='AVERAGE'
	)KM_1 ON BASE.TIPO_MOTOR_GT013 IS NOT NULL AND BASE.TIPO_VEICULO_GT013 IS NOT NULL
				AND KM_1.TIPO_VEICULO_KM_1=BASE.TIPO_VEICULO_GT013 
				AND KM_1.TIPO_MOTOR_KM_1=BASE.TIPO_MOTOR_GT013

LEFT JOIN

	-- 3Aº Cruzamento: Obtenção Scope 2ª Metodologia 
	--> OUT24 20.643 Registos
	(
	SELECT 
	     SCP1_FTR_EMSS 
	    ,SCP2_FTR_EMSS 
	    ,SCP3_FTR_EMSS
		,CAST(SCP1_FTR_EMSS AS DECIMAL(32,10)) AS SCP1_FTR_EMSS_2
	    ,CAST(SCP2_FTR_EMSS AS DECIMAL(32,10)) AS SCP2_FTR_EMSS_2		
		,TRIM(UPPER(TIPO_VEICULO)) AS TIPO_VEICULO_EMI_2
		,TRIM(UPPER(TIPO_MOTOR))AS TIPO_MOTOR_EMI_2
	FROM BU_ESG_WORK.MODESG_INP_EMSS_VCLS
	WHERE REF_DATE='${ref_date}'
		AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
		AND TRIM(UPPER(SUBGRUPO))='AVERAGE'
	)EMISS_2 ON BASE.TIPO_MOTOR_GT013 IS NOT NULL AND BASE.TIPO_VEICULO_GT013 IS NOT NULL AND BASE.TIPO_MOTOR_GT013<>'AVERAGE'
				AND EMISS_2.TIPO_VEICULO_EMI_2=BASE.TIPO_VEICULO_GT013 
				AND EMISS_2.TIPO_MOTOR_EMI_2=BASE.TIPO_MOTOR_GT013

LEFT JOIN

	-- 3Bº Cruzamento: Obtenção KMs Médios 2ª Metodologia 
	--> OUT24 20.643 Registos
	(
	SELECT 
		 MEDIA_KM 
		,CAST(MEDIA_KM AS DECIMAL(32,10)) AS MEDIA_KM_2
		,TRIM(UPPER(TIPO_VCL)) AS TIPO_VEICULO_KM_2
		,TRIM(UPPER(TIPO_MOTOR))AS TIPO_MOTOR_KM_2
	FROM BU_ESG_WORK.MODESG_INP_KM_MEDIOS_EMSS_VCLS
	WHERE REF_DATE='${ref_date}'
		AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
		AND TRIM(UPPER(SUBGRUPO))='AVERAGE'
	)KM_2 ON BASE.TIPO_MOTOR_GT013 IS NOT NULL AND BASE.TIPO_VEICULO_GT013 IS NOT NULL AND BASE.TIPO_MOTOR_GT013<>'AVERAGE'
				AND KM_2.TIPO_VEICULO_KM_2=BASE.TIPO_VEICULO_GT013 
				AND KM_2.TIPO_MOTOR_KM_2=BASE.TIPO_MOTOR_GT013

LEFT JOIN
	
	-- 4Aº Cruzamento: Obtenção Scope 3ª Metodologia 
	--> OUT24 20.643 Registos
	(
	SELECT 
	     SCP1_FTR_EMSS
	    ,SCP2_FTR_EMSS
	    ,SCP3_FTR_EMSS
		,CAST(SCP1_FTR_EMSS AS DECIMAL(32,10)) AS SCP1_FTR_EMSS_3
	    ,CAST(SCP2_FTR_EMSS AS DECIMAL(32,10)) AS SCP2_FTR_EMSS_3
	    ,TRIM(UPPER(TIPO_MOTOR))AS TIPO_MOTOR_EMI_3
		,TRIM(UPPER(TIPO_VEICULO)) AS TIPO_VEICULO_EMI_3
	FROM BU_ESG_WORK.MODESG_INP_EMSS_VCLS
	WHERE REF_DATE='${ref_date}'
		AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
		AND TRIM(UPPER(SUBGRUPO))='AVERAGE'
		AND TRIM(UPPER(TIPO_MOTOR))='AVERAGE'
	)EMISS_3 ON BASE.TIPO_VEICULO_GT013 IS NOT NULL 
				AND EMISS_3.TIPO_VEICULO_EMI_3=BASE.TIPO_VEICULO_GT013 

LEFT JOIN

    -- 4Bº Cruzamento: Obtenção KMs Médios 3ª Metodologia 
	--> OUT24 20.643 Registos
	(
	SELECT 
		 MEDIA_KM
		,CAST(MEDIA_KM AS DECIMAL(32,10)) AS MEDIA_KM_3
		,TRIM(UPPER(TIPO_VCL)) AS TIPO_VEICULO_KM_3
		,TRIM(UPPER(TIPO_MOTOR))AS TIPO_MOTOR_KM_3
	FROM BU_ESG_WORK.MODESG_INP_KM_MEDIOS_EMSS_VCLS
	WHERE REF_DATE='${ref_date}'
		AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
		AND TRIM(UPPER(SUBGRUPO))='AVERAGE'
		AND TRIM(UPPER(TIPO_MOTOR))='AVERAGE'
	)KM_3 ON BASE.TIPO_VEICULO_GT013 IS NOT NULL 
				AND KM_3.TIPO_VEICULO_KM_3=BASE.TIPO_VEICULO_GT013 
;
				
--------------------------------------------------------------------------------------------------------------------------------------------------
-- 2. Criação da tabela 
--------------------------------------------------------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.MODESG_OUT_EMSS_VCLS_MV_V2_DEZ24;
CREATE TABLE BU_CAPTOOLS_WORK.MODESG_OUT_EMSS_VCLS_MV_V2_DEZ24 AS

SELECT *
	,CASE
		WHEN SCP1_EMSS IS NULL AND SCP2_EMSS IS NOT NULL THEN 'Nao Aplicavel'
		WHEN ORIGEM_SCP1_EMSS_AUX IS NOT NULL THEN ORIGEM_SCP1_EMSS_AUX
		ELSE 'MISS'
	END AS ORIGEM_SCP1_EMSS
	,CASE
		WHEN SCP2_EMSS IS NULL AND SCP1_EMSS IS NOT NULL THEN 'Nao Aplicavel'
		WHEN ORIGEM_SCP2_EMSS_AUX IS NOT NULL THEN ORIGEM_SCP2_EMSS_AUX
		ELSE 'MISS'
	END AS ORIGEM_SCP2_EMSS
	,CASE
		WHEN SCP1_EMSS IS NULL THEN NULL 
		ELSE 'kgCO2/km'
	END AS UNIDADE_FUNCIONAL_SCP1_EMSS
	,CASE
		WHEN SCP2_EMSS IS NULL THEN NULL 
		ELSE 'kgCO2/km'
	END AS UNIDADE_FUNCIONAL_SCP2_EMSS
	,CASE
		WHEN SCP3_EMSS IS NULL THEN NULL 
		ELSE 'kgCO2/km'
	END AS UNIDADE_FUNCIONAL_SCP3_EMSS

FROM BU_CAPTOOLS_WORK.MODESG_OUT_EMSS_VCLS_MV_DEZ24
