
/*===================================================================================================================================================
                                                      
											SIMULAÇÃO MODESG_OUT_BENS_IMOVEIS - MODELO VERDE
										                    NEYOND 2024 - V0.01 
															    
 ===================================================================================================================================================*/
 

--------------------------------------------------------------------------------------------------------------------------------------------------
-- 1. Criação da tabela 
--------------------------------------------------------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS BU_CAPTOOLS_WORK.MODESG_OUT_BENS_IMOVEIS_MV_DEZ24;
CREATE TABLE BU_CAPTOOLS_WORK.MODESG_OUT_BENS_IMOVEIS_MV_DEZ24 AS
SELECT 
	BASE.CHAVE_BEM
	,CASE
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN NULL 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS3_2A'
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B' -- HF: E-mail da Corp no dia 14/Nov com a indicação que caso o EPC não se encontre no input (exemplo EPC G para Residential total ('31003014433390000000000000000000')) deve ser considerado a linha do input sem EPC 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP1_FTR_EMSS*BENS.NUM_BENS IS NOT NULL THEN 'RE_DQS5_3'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP1_FTR_EMSS*BENS.NUM_BENS IS NOT NULL THEN 'RE_DQS5_3'
		ELSE NULL
	END AS ORIGEM_SCP1_EMSS
	,CASE 
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN NULL 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS3_2A'
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'RE_DQS4_2B'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP2_FTR_EMSS*BENS.NUM_BENS IS NOT NULL THEN 'RE_DQS5_3'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP2_FTR_EMSS*BENS.NUM_BENS IS NOT NULL THEN 'RE_DQS5_3'
		ELSE NULL
	END AS ORIGEM_SCP2_EMSS
	,CASE WHEN TRIM(BASE.CHAVE_BEM)='' THEN '1'END AS ORIGEM_SCP3_EMSS
	,CASE  
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN NULL 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP1_FTR_EMSS*BENS.NUM_BENS IS NOT NULL THEN EMISS_3.SCP1_FTR_EMSS*BENS.NUM_BENS
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP1_FTR_EMSS*BENS.NUM_BENS IS NOT NULL THEN EMISS_4.SCP1_FTR_EMSS*BENS.NUM_BENS
		ELSE NULL
	END AS SCP1_EMSS
	,CASE  
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN NULL 
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP2_FTR_EMSS*BENS.NUM_BENS IS NOT NULL THEN EMISS_3.SCP2_FTR_EMSS*BENS.NUM_BENS
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP2_FTR_EMSS*BENS.NUM_BENS IS NOT NULL THEN EMISS_4.SCP2_FTR_EMSS*BENS.NUM_BENS
		ELSE NULL
	END AS SCP2_EMSS
	,CASE
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN NULL
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'tCO2e/m2'
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'tCO2e/m2' 
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP1_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'tCO2e/m2'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP1_FTR_EMSS*BENS.NUM_BENS IS NOT NULL THEN 'tCO2e/m2'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP1_FTR_EMSS*BENS.NUM_BENS IS NOT NULL THEN 'tCO2e/m2'
		ELSE NULL	
	END AS UNIDADE_FUNCIONAL_SCP1_EMSS
	,CASE
		WHEN FIN_BEM.TIPO_FINALIDADE_BEM='NOT APPLICABLE' THEN NULL
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'tCO2e/m2'
		WHEN EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'tCO2e/m2'
		WHEN EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.SCP2_FTR_EMSS*BASE.NET_FLOOR_AREA IS NOT NULL THEN 'tCO2e/m2'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_3.SCP2_FTR_EMSS*BENS.NUM_BENS IS NOT NULL THEN 'tCO2e/m2'
		WHEN BASE.NET_FLOOR_AREA=0 AND EMISS_4.SCP2_FTR_EMSS*BENS.NUM_BENS IS NOT NULL THEN 'tCO2e/m2'
		ELSE NULL
	END AS UNIDADE_FUNCIONAL_SCP2_EMSS
	,CASE WHEN TRIM(BASE.CHAVE_BEM)='' THEN '1'END AS UNIDADE_FUNCIONAL_SCP3_EMSS
	,FLG_RSC_FSC_AGD_SIMUL AS FLG_RSC_FSC_AGD 
	,FLG_RSC_FSC_CRNC_SIMUL AS FLG_RSC_FSC_CRNC
	,ORIGEM_FLG_RSC_FSC_CRNC_SIMUL AS ORIGEM_FLG_RSC_FSC_CRNC
	,ORIGEM_FLG_RSC_FSC_AGD_SIMUL AS ORIGEM_FLG_RSC_FSC_AGD

	
	--,FLG_RSC_FSC_AGD --Comentário HF: Em WIP, data Pr. de Correção: 25/11/2024
	--,FLG_RSC_FSC_CRNC --Comentário HF: Em WIP, data Pr. de Correção: 25/11/2024
	--,ORIGEM_FLG_RSC_FSC_AGD --Comentário HF: Em WIP, data Pr. de Correção: 25/11/2024
	--,ORIGEM_FLG_RSC_FSC_CRNC --Comentário HF: Em WIP, data Pr. de Correção: 25/11/2024

FROM 

	-- 1º Cruzamento: Obter o Universo Base 
	--> SET24 275.266 Registos 
	(
	SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,NET_FLOOR_AREA
	FROM BU_ESG_WORK.PROPERTY
    WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BU_ESG_WORK.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
	)BASE 

LEFT JOIN 

	-- 2º Cruzamento: Obter o EPC 
	--> SET24 275.266 Registos
	(
	SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,TRIM(UPPER(EPC)) AS EPC,TRIM(QUALITY_SCORE)
	FROM BU_ESG_WORK.PROPERTY_ENERGY_CERTIFICATE
    WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BU_ESG_WORK.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
		AND TRIM(QUALITY_SCORE) IN ('1-REAL', 'SANTANDER')
	)EPC ON BASE.CHAVE_BEM = EPC.CHAVE_BEM 

LEFT JOIN

	-- 3º Cruzamento: Obter a Finalidade do Bem de acordo com a parametrização 
	--> SET24 275.266 Registos
	(
	SELECT *
		,TRIM(UPPER(CASE
			WHEN VALOR_ORIGINAL ='1_01' THEN 'Residential Total'
			WHEN VALOR_ORIGINAL ='1_03' THEN 'Office'
			WHEN VALOR_ORIGINAL ='1_05' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_02' THEN 'Retail - high street'
			WHEN VALOR_ORIGINAL ='1_04' THEN 'Retail - warehouse'
			WHEN VALOR_ORIGINAL ='1_08' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_'   THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_07' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='1_06' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='1_11' THEN 'Healthcare'
			WHEN VALOR_ORIGINAL ='1_09' THEN 'Hotel'
			WHEN VALOR_ORIGINAL ='1_12' THEN 'Leisure/Lodging'
			WHEN VALOR_ORIGINAL ='1_14' THEN 'Retail - shopping center'
			WHEN VALOR_ORIGINAL ='1_10' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='1_13' THEN 'Non-residential total'
			WHEN VALOR_ORIGINAL ='0_01' THEN 'Residential Total'
			WHEN VALOR_ORIGINAL ='0_03' THEN 'Office'
			WHEN VALOR_ORIGINAL ='0_05' THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_02' THEN 'Retail High-street'
			WHEN VALOR_ORIGINAL ='0_04' THEN 'Retail Warehouse'
			WHEN VALOR_ORIGINAL ='0_08' THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_'   THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_07' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='0_06' THEN 'Not applicable'
			WHEN VALOR_ORIGINAL ='0_11' THEN 'Healthcare'
			WHEN VALOR_ORIGINAL ='0_09' THEN 'Hotel'
			WHEN VALOR_ORIGINAL ='0_12' THEN 'Lodge/Leisure'
			WHEN VALOR_ORIGINAL ='0_14' THEN 'Shopping Center'
			WHEN VALOR_ORIGINAL ='0_10' THEN 'Non-residential buildings'
			WHEN VALOR_ORIGINAL ='0_13' THEN 'Non-residential buildings'
		ELSE 'SEM PARAMET'
		END)) AS TIPO_FINALIDADE_BEM
		,'NON-RESIDENTIAL BUILDINGS' AS TIPO_FINALIDADE_BEM_2
	FROM
		(
		SELECT 
			F1.*
			,CASE 
				WHEN F2.CHAVE_BEM IS NOT NULL THEN concat_ws('_','1',TRIM(F1.PROPERTY_PURPOSE_CODE))
				ELSE concat_ws('_','0',TRIM(F1.PROPERTY_PURPOSE_CODE))
			END AS VALOR_ORIGINAL
		FROM 
			(
			SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,PROPERTY_PURPOSE_CODE
			FROM BU_ESG_WORK.PROPERTY
			WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BU_ESG_WORK.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
			)F1 
		LEFT JOIN 
			(
			SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,EPC,TRIM(QUALITY_SCORE)
			FROM BU_ESG_WORK.PROPERTY_ENERGY_CERTIFICATE
			WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BU_ESG_WORK.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
				AND TRIM(QUALITY_SCORE) IN ('1-REAL', 'SANTANDER')
			)F2 ON F1.CHAVE_BEM = F2.CHAVE_BEM
		)AUX_1
	)FIN_BEM ON BASE.CHAVE_BEM = FIN_BEM.CHAVE_BEM 

LEFT JOIN

	-- 4º Cruzamento: Obter as métricas para o universo com EPC e Área útil  
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM bu_esg_work.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='FLOOR AREA'
		)AUX WHERE ROW_1=1
	)EMISS_1 ON EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1.EPC_AUX=EPC.EPC AND EMISS_1.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN

	-- 5º Cruzamento: Obter as métricas para o universo com EPC e Área útil mas o EPC não consta na tabela de input (exemplo EPC G para Residential total)
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM bu_esg_work.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='FLOOR AREA'
			AND TRIM(EPC)=''
		)AUX WHERE ROW_1=1
	)EMISS_1B ON EPC.CHAVE_BEM IS NOT NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_1B.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN 
	-- 6º Cruzamento: Obter as métricas para o universo sem EPC mas com Área útil
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM bu_esg_work.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='FLOOR AREA'
			AND TRIM(EPC)=''
		)AUX WHERE ROW_1=1
	)EMISS_2 ON EPC.CHAVE_BEM IS NULL AND BASE.NET_FLOOR_AREA<>0 AND EMISS_2.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN 
	-- 7º Cruzamento: Obter as métricas para o universo sem Área útil 
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM bu_esg_work.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='DWELLING'
			AND TRIM(EPC)=''
		)AUX WHERE ROW_1=1
	)EMISS_3 ON BASE.NET_FLOOR_AREA=0  AND EMISS_3.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM

LEFT JOIN 
	-- 8º Cruzamento: Obter as métricas para o universo sem Área útil que não foi possivel obter no 7º cruzamento (nestes casos é assumido a seguinte finalidade: NON-RESIDENTIAL BUILDINGS)
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM
		(
		SELECT *
			,TRIM(UPPER(EPC)) AS EPC_AUX
			,TRIM(UPPER(TIPO_FINALIDADE_BEM)) AS TIPO_FINALIDADE_BEM_AUX
			,ROW_NUMBER() OVER (PARTITION BY EPC,TIPO_FINALIDADE_BEM ORDER BY ANO_FATOR_EMISSAO DESC) AS ROW_1
		FROM bu_esg_work.modesg_inp_emss_bens_imoveis
		WHERE REF_DATE='${ref_date}'
			AND TRIM(UPPER(NOME_PAIS))='PORTUGAL'
			AND TRIM(UPPER(NOME_UNIDADE_FUNCIONAL))='DWELLING'
			AND TRIM(EPC)=''
		)AUX WHERE ROW_1=1
	)EMISS_4 ON BASE.NET_FLOOR_AREA=0  AND EMISS_4.TIPO_FINALIDADE_BEM_AUX=FIN_BEM.TIPO_FINALIDADE_BEM_2

	LEFT JOIN 
	-- 9º Cruzamento: Obter o número de bens de suporte à metodologia 3 (ou seja o universo do 7º e 8º cruzamento) 
	--> SET24 275.266 Registos
	(
	SELECT *
	FROM 
		(
		SELECT X.*, Y.NUM_BENS,ROW_NUMBER() OVER (PARTITION BY X.CHAVE_BEM ORDER BY Y.NUM_BENS DESC) AS ROW_1
		FROM 
			(
			SELECT DISTINCT F1.CHAVE_BEM,F2.CHAVE_RESPONS 
			FROM 
				(
				SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,
				CONCAT(PROCESS_BANK_ID,PROCESS_BRANCH_CODE,PROCESS_ACCOUNT_ID,PROCESS_REFERENCE_CODE) AS CHAVE_PROCESSO
				FROM BU_ESG_WORK.PROCESS_PROPERTY_REL
				WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BU_ESG_WORK.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
				)F1
			FULL JOIN 
				(
				SELECT DISTINCT CONCAT(PROCESS_BANK_ID,PROCESS_BRANCH_CODE,PROCESS_ACCOUNT_ID,PROCESS_REFERENCE_CODE) AS CHAVE_PROCESSO
				,CONCAT(BANK_ID,BRANCH_CODE,CONTRACT_ID,REFERENCE_CODE) AS CHAVE_RESPONS
				FROM BU_ESG_WORK.RESPONSIBILITY_PROCESS_REL
				WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BU_ESG_WORK.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
				)F2 ON F1.CHAVE_PROCESSO=F2.CHAVE_PROCESSO
			)X
		LEFT JOIN
			
			(
			SELECT F2.CHAVE_RESPONS,COUNT(DISTINCT F1.CHAVE_BEM) AS NUM_BENS
			FROM 
				(
				SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,
				CONCAT(PROCESS_BANK_ID,PROCESS_BRANCH_CODE,PROCESS_ACCOUNT_ID,PROCESS_REFERENCE_CODE) AS CHAVE_PROCESSO
				FROM BU_ESG_WORK.PROCESS_PROPERTY_REL
				WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BU_ESG_WORK.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
				)F1
			FULL JOIN 
				(
				SELECT DISTINCT CONCAT(PROCESS_BANK_ID,PROCESS_BRANCH_CODE,PROCESS_ACCOUNT_ID,PROCESS_REFERENCE_CODE) AS CHAVE_PROCESSO
				,CONCAT(BANK_ID,BRANCH_CODE,CONTRACT_ID,REFERENCE_CODE) AS CHAVE_RESPONS
				FROM BU_ESG_WORK.RESPONSIBILITY_PROCESS_REL
				WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BU_ESG_WORK.PROPERTY WHERE DATA_DATE_PART <= '${ref_date}') 
				)F2 ON F1.CHAVE_PROCESSO=F2.CHAVE_PROCESSO
			GROUP BY 1 
			)Y ON X.CHAVE_RESPONS=Y.CHAVE_RESPONS
		)AUX WHERE ROW_1=1
	)BENS ON BASE.CHAVE_BEM=BENS.CHAVE_BEM

LEFT JOIN 

	-- 10º Cruzamento: Obter a marcação de risco físico
	(
	SELECT DISTINCT CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM,FLG_RSC_FSC_AGD_SIMUL, FLG_RSC_FSC_CRNC_SIMUL, ORIGEM_FLG_RSC_FSC_AGD_SIMUL, ORIGEM_FLG_RSC_FSC_CRNC_SIMUL
	FROM BU_ESG_WORK.ANL_RISCO_FISICO_COL_DEZ24
	)RISCO_FISICO 
ON BASE.CHAVE_BEM = RISCO_FISICO.CHAVE_BEM 



--------------------------------------------------------------------------------------------------------------------------------------------------
-- 2. Marcação de Riscos Físicos -- COLATERAL
--------------------------------------------------------------------------------------------------------------------------------------------------

DROP TABLE BU_ESG_WORK.ANL_RISCO_FISICO_COL_JAN25;
CREATE TABLE BU_ESG_WORK.ANL_RISCO_FISICO_COL_JAN25 AS 
SELECT DISTINCT
   BASE.*
        ,CASE 
            WHEN PR_CP.LOCALIZACAO IS NOT NULL AND PR_CP.FLG_RSC_FSC_AGD = 'Yes' THEN 1
            WHEN PR_CP.LOCALIZACAO IS NULL AND NUT.COD_NUTIII IS NOT NULL AND NUT.FLG_RSC_FSC_AGD = 'Yes' THEN 1
            WHEN PR_CP.LOCALIZACAO IS NULL AND NUT.COD_NUTIII IS NULL AND PROXY.COD_PAIS IS NOT NULL AND PROXY.FLG_RSC_FSC_AGD = 'Yes' THEN 1 
        ELSE 0 END AS FLG_RSC_FSC_AGD_SIMUL
        ,CASE 
            WHEN PR_CP.LOCALIZACAO IS NOT NULL AND PR_CP.FLG_RSC_FSC_CRNC = 'Yes' THEN 1
            WHEN PR_CP.LOCALIZACAO IS NULL AND NUT.COD_NUTIII IS NOT NULL AND NUT.FLG_RSC_FSC_CRNC = 'Yes' THEN 1
            WHEN PR_CP.LOCALIZACAO IS NULL AND NUT.COD_NUTIII IS NULL AND PROXY.COD_PAIS IS NOT NULL AND PROXY.FLG_RSC_FSC_CRNC = 'Yes' THEN 1
        ELSE 0 END AS FLG_RSC_FSC_CRNC_SIMUL
        ,CASE 
            WHEN PR_CP.LOCALIZACAO IS NOT NULL THEN 'Corporação - ZipCode'
            WHEN PR_CP.LOCALIZACAO IS NULL AND NUT.COD_NUTIII IS NOT NULL THEN 'Corporação - Nuts'
            WHEN PR_CP.LOCALIZACAO IS NULL AND NUT.COD_NUTIII IS NULL AND PROXY.COD_PAIS IS NOT NULL THEN 'Corporação - Proxy'
        ELSE '' END AS ORIGEM_FLG_RSC_FSC_AGD_SIMUL
        ,CASE 
            WHEN PR_CP.LOCALIZACAO IS NOT NULL THEN 'Corporação - ZipCode'
            WHEN PR_CP.LOCALIZACAO IS NULL AND NUT.COD_NUTIII IS NOT NULL THEN 'Corporação - Nuts'
            WHEN PR_CP.LOCALIZACAO IS NULL AND NUT.COD_NUTIII IS NULL AND PROXY.COD_PAIS IS NOT NULL THEN 'Corporação - Proxy'
        ELSE '' END AS ORIGEM_FLG_RSC_FSC_CRNC_SIMUL   
        
        
FROM
(
    SELECT  BASE.*
           ,CONCAT('PRT_',SUBSTR(BASE.POSTAL_CODE,1,4)) AS CPOSTAL
           ,TAYD91C0_NELEMC05 AS NUTS
    FROM 
    -- CRUZAMENTO: OBTER O UNIVERSO BASE 
    --> DEZ24 274.743 REGISTOS 
    (
        SELECT *, CONCAT(PROPERTY_BANK_ID,PROPERTY_BRANCH_CODE,PROPERTY_CONTRACT_ID,PROPERTY_REFERENCE_CODE) AS CHAVE_BEM
        FROM BU_ESG_WORK.PROPERTY
        WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM BU_ESG_WORK.PROPERTY WHERE DATA_DATE_PART <= '${REF_DATE}')
    )BASE 
    
    -- CRUZAMENTO: OBTER INFORMAÇÃO SOBRE NUTS
    LEFT JOIN
    (
        SELECT DISTINCT TAYD91C0_CELEMTAB,TAYD91C0_NELEMC05
        FROM CD_ESTRUTURAIS.TAT91_TABELAS
        WHERE DATA_DATE_PART IN (SELECT MAX (DATA_DATE_PART) FROM CD_ESTRUTURAIS.TAT91_TABELAS WHERE DATA_DATE_PART <= '${REF_DATE}') AND TAYD91C0_CTABELA='J48'
    ) TAT2
    ON BASE.district_municip_parish_code = TAT2.TAYD91C0_CELEMTAB
) BASE
LEFT JOIN
-- A) CRUZAMENTO: OBTER MARCAÇÃO DE RISCO FÍSICO POR ZIP_CODE
(
    SELECT *
    FROM BU_ESG_WORK.MODESG_INP_RISCO_FISICO_ZIPCODE
    WHERE REF_DATE='2025-01-31' AND COD_PAIS='PT' AND cod_nace_esg='Secured'
) PR_CP
ON BASE.CPOSTAL = PR_CP.LOCALIZACAO
    
LEFT JOIN
-- B) CRUZAMENTO: OBTER MARCAÇÃO DE RISCO FÍSICO POR NUT
(
    SELECT *
    FROM BU_ESG_WORK.MODESG_INP_RISCO_FISICO
    WHERE REF_DATE='2025-01-31' AND COD_PAIS='PT' AND cod_nace_esg='Secured'
) NUT
ON BASE.NUTS = NUT.COD_NUTIII
    
LEFT JOIN
-- C) CRUZAMENTO: OBTER MARCAÇÃO DE RISCO FÍSICO POR PROXY
(
    SELECT *
    FROM BU_ESG_WORK.MODESG_INP_RISCO_FISICO
    WHERE REF_DATE='2025-01-31' AND COD_PAIS='PT' AND cod_nace_esg='Secured' AND TRIM(COD_NUTIII) = ''
) PROXY
ON PROXY.COD_PAIS = 'PT'
